### ISSUE TITLE
IO test bug

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [looly/hutool#102]
in Unit Test  ```cn.hutool.core.io.FileUtilTest```:
- subPathTest()
- getPathEle()

Unit tests are failed.
JDK env: 1.8

**Comment by looly** [comment]
我使用1.8.0_152测试单元测试没问题。如果可以请提供下报错堆栈。

**Comment by ZhengshuaiPENG** [comment]
ENV: MacOS JDK 1.8.0_162

```FileUtilTest.subPathTest()```:

```
org.junit.ComparisonFailure: 
Expected :eee
Actual   :ddd
 <Click to see difference>


	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at cn.hutool.core.io.FileUtilTest.subPathTest(FileUtilTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255

```

**Comment by ZhengshuaiPENG** [comment]
Update:

Linux Env, JDK:

```
➜  ~ /usr/lib/jvm/java-8-jdk/bin/java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

The error trace of Unit test is the same as on MacOS

**Comment by looly** [comment]
可以先忽略此unit。很奇怪哎。尝试使用v4-dev分支的试下。

**Comment by ZhengshuaiPENG** [comment]
我给你还原一下debug  的 trace:

方法 ```FileUtil#subPath(Path, int fromIndex, int toIndex)```
传入参数: 

- path: "d:/aaa/bbb/ccc/ddd/eee/fff"
- fromIndex: 5
- toIndex: 4

执行到 Line 1531, ```len: 7, path: "d:/aaa/bbb/ccc/ddd/eee/fff"```
Line 1533-1549, if 条件不符合,跳过

执行Line 1551 - 1555, 交换 fromIndex 和 toIndex,``` fromIndex:4, toIndex:5```
Line 1557-1559, if 条件不符合,跳过

执行 ```path.subpath(4, 5)```, 得到结果是 ```ddd```.

根据 ```path.subPath()```的 doc 描述: beginIndex 和 endIndex 应该是左闭右开

```
 @param   beginIndex
     *          the index of the first element, inclusive
     * @param   endIndex
     *          the index of the last element, exclusive
```
我认为 ```ddd``` 应该是 expected value
