### ISSUE TITLE
executeBatch 批量插入问题

### ISSUE THREAD

**Issue by jackwei** [looly/hutool#1053]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
 List<Object[]> insertList = new ArrayList<>();
.......
......
 Db.use().executeBatch(sql,insertList.toArray());

2. 堆栈信息
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of [Ljava.lang.Object;. Use setObject() with an explicit Types value to specify the type to use.
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:972)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java)
	at cn.hutool.db.StatementUtil.setParam(StatementUtil.java:350)
	at cn.hutool.db.StatementUtil.fillParams(StatementUtil.java:72)
	at cn.hutool.db.StatementUtil.fillParams(StatementUtil.java:51)
	at cn.hutool.db.StatementUtil.fillParams(StatementUtil.java:38)
	at cn.hutool.db.StatementUtil.prepareStatementForBatch(StatementUtil.java:167)
	at cn.hutool.db.sql.SqlExecutor.executeBatch(SqlExecutor.java:176)
	at cn.hutool.db.sql.SqlExecutor.executeBatch(SqlExecutor.java:159)
	at cn.hutool.db.AbstractDb.executeBatch(AbstractDb.java:245)
	at com.ykkj.sdp.provider.service.MqttTemperatureDataHandleTest.TestBatchData(MqttTemperatureDataHandleTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by jackwei** [comment]
找到问题了,AbstractDb 不支持SqlExecutor的 public static int[] executeBatch(Connection conn, String sql, Iterable<Object[]> paramsBatch) 方法, 建议在AbstractDb 中也支持该方法,谢谢

**Comment by looly** [comment]
5.4.2增加方法，感谢意见。
