### ISSUE TITLE
获得指定地址信息中的MAC地址空指针异常

### ISSUE THREAD

**Issue by yeternallove** [looly/hutool#1057]
### 版本情况

JDK版本：    jdk1.82
hutool版本： 5.3.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
NetUtil.getLocalMacAddress();
```

2. 堆栈信息
java.lang.NullPointerException: null
	at cn.hutool.core.net.NetUtil.getMacAddress(NetUtil.java:534)
	at cn.hutool.core.net.NetUtil.getMacAddress(NetUtil.java:517)
	at cn.hutool.core.net.NetUtil.getLocalMacAddress(NetUtil.java:507)

NetworkInterface.getByInetAddress(inetAddress)执行返回为null
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
应该是没有获取到你的网卡。

5.4.2会返回null
