### ISSUE TITLE
SpringBoot打包后 ClassScanner.scanPackageByAnnotation 报数组越界

### ISSUE THREAD

**Issue by lzpeng723** [looly/hutool#1074]
### 版本情况

JDK版本：    Oracle jdk1.8.0_71
hutool版本： 5.4.2

### 问题描述
开发环境正常,Spring Boot打包后报错。
从[Spring Initializr](https://start.spring.io)下载SpringBoot工程,将main函数改为
```java
        Set<Class<?>> classes = ClassScanner.scanPackageByAnnotation("", SpringBootApplication.class);
        for (Class<?> aClass : classes) {
            System.out.println(aClass);
        }
```
开发环境可正常输出 class com.test.demo.DemoApplication
![开发环境](https://user-images.githubusercontent.com/25931187/92849056-72794300-f41d-11ea-935f-6589bf14674c.png)
Spring Boot打包后报错
![打包后](https://user-images.githubusercontent.com/25931187/92849046-70af7f80-f41d-11ea-917f-94c0922c2543.png)
测试项目源码在这里
[testDemo.zip](https://github.com/looly/hutool/files/5205679/testDemo.zip)

1. 复现代码
```java
package com.test.demo;

import cn.hutool.core.lang.ClassScanner;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Set;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        Set<Class<?>> classes = ClassScanner.scanPackageByAnnotation("", SpringBootApplication.class);
        for (Class<?> aClass : classes) {
            System.out.println(aClass);
        }
    }

}
```

2. 堆栈信息
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
        at java.lang.Class.createAnnotationData(Class.java:3521)
        at java.lang.Class.annotationData(Class.java:3510)
        at java.lang.Class.getAnnotation(Class.java:3415)
        at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
        at java.lang.Class.isAnnotationPresent(Class.java:3425)
        at cn.hutool.core.lang.ClassScanner.lambda$scanPackageByAnnotation$0(ClassScanner.java:76)
        at cn.hutool.core.lang.ClassScanner.addIfAccept(ClassScanner.java:335)
        at cn.hutool.core.lang.ClassScanner.scanJar(ClassScanner.java:270)
        at cn.hutool.core.lang.ClassScanner.scan(ClassScanner.java:177)
        at cn.hutool.core.lang.ClassScanner.scanPackage(ClassScanner.java:119)
        at cn.hutool.core.lang.ClassScanner.scanPackageByAnnotation(ClassScanner.java:76)
        at com.test.demo.DemoApplication.main(DemoApplication.java:13)
        ... 8 more

**Comment by looly** [comment]
isAnnotationPresent导致的。考虑包冲突或者版本冲突。
