### ISSUE TITLE
生成验证码图片时抛出InternalError异常

### ISSUE THREAD

**Issue by zuminX** [looly/hutool#1078]
### 版本情况

JDK版本：    oracle_14.0.2
hutool版本： 5.3.7（抛出异常的代码在新版本中与此版本相同）
系统： CentOS 7.3.1611

### 问题描述（包括截图）

1. 复现代码

```java
    LineCaptcha captcha = CaptchaUtil.createLineCaptcha(width, height);
    String uuid = UUID.fastUUID().toString();
    redisUtils.setObject(getCaptchaKey(uuid), captcha.getCode(), expireTime, TimeUnit.MINUTES);
```

2. 堆栈信息
```
Caused by: java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:249)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:261)
	at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:856)
	at cn.hutool.core.img.GraphicsUtil.getCenterY(GraphicsUtil.java:59)
	at cn.hutool.core.img.GraphicsUtil.drawString(GraphicsUtil.java:108)
	at cn.hutool.core.img.GraphicsUtil.drawStringColourful(GraphicsUtil.java:84)
	at cn.hutool.captcha.LineCaptcha.drawString(LineCaptcha.java:75)
	at cn.hutool.captcha.LineCaptcha.createImage(LineCaptcha.java:58)
	at cn.hutool.captcha.AbstractCaptcha.createCode(AbstractCaptcha.java:102)
	at cn.hutool.captcha.AbstractCaptcha.getCode(AbstractCaptcha.java:126)
	at com.sudoku.security.service.impl.CaptchaServiceImpl.generateCaptcha(CaptchaServiceImpl.java:55)
	at com.sudoku.security.controller.CaptchaController.getCaptcha(CaptchaController.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
```

3. 抛出异常的方法
```java
public static int getCenterY(Graphics g, int backgroundHeight) {
  // 获取允许文字最小高度
  FontMetrics metrics = null;
  try {
    //执行该方法时抛出InternalError异常
    metrics = g.getFontMetrics();
  } catch (Exception e) {
    // 此处报告bug某些情况下会抛出IndexOutOfBoundsException，在此做容错处理
  }
  int y;
  if (null != metrics) {
    y = (backgroundHeight - metrics.getHeight()) / 2 + metrics.getAscent();
  } else {
    y = backgroundHeight / 3;
  }
  return y;
}
```

**Comment by zuminX** [comment]
解决了，是因为服务器没有安装字体库的原因
