### ISSUE TITLE
时间文本 转 LocalDateTime对象 在 格式为 DatePattern.PURE_DATETIME_MS_PATTERN(yyyyMMddHHmmssSSS) 时 失败

### ISSUE THREAD

**Issue by Cyan-Stone** [looly/hutool#1082]
### 版本情况

JDK版本：    openjdk_8_172
hutool版本： 5.4.2

### 问题描述
0. 简述
调用LocalDateTimeUtil.parse(CharSequence text, String format)方法
且format参数为DatePattern.PURE_DATETIME_MS_PATTERN(yyyyMMddHHmmssSSS) 时
转换失败

1. 复现代码
```
@Test
public void testEnum() {
	String timeStr = "19940121183604682";
	DateUtil.parseLocalDateTime(timeStr, DatePattern.PURE_DATETIME_MS_PATTERN);
}
```

2. 堆栈信息
java.time.format.DateTimeParseException: Text '19940121183604682' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
	at cn.hutool.core.date.LocalDateTimeUtil.parse(LocalDateTimeUtil.java:234)
	at cn.hutool.core.date.LocalDateTimeUtil.parse(LocalDateTimeUtil.java:248)
	at cn.hutool.core.date.DateUtil.parseLocalDateTime(DateUtil.java:664)
	at com.fmsh.demo.test.tool.HuToolTest.testEnum(HuToolTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

3. 问题成因分析
java8中直接使用DateTimeFormatter无法将**yyyyMMddHHmmssSSS**格式的数据转换为LocalDateTime
此为JDK的BUG，详见：[https://bugs.openjdk.java.net/browse/JDK-8031085](url)

4. 解决方案
为
LocalDateTimeUtil.parse(CharSequence text, String format)
方法添加逻辑分支，方法改为如下所示

```
public static LocalDateTime parse(CharSequence text, String format) {
	if (null == text) {
		return null;
	}
	if (DatePattern.PURE_DATETIME_MS_PATTERN.equals(format)) {
		return parse(text, new DateTimeFormatterBuilder().appendPattern(DatePattern.PURE_DATETIME_PATTERN).appendValue(ChronoField.MILLI_OF_SECOND, 3).toFormatter());
	}
	return parse(text, DateTimeFormatter.ofPattern(format));
}
```

**Comment by looly** [comment]
嗯，感谢意见，确认bug。

hutool做了更好的兼容，可以兼容yyyyMMddHHmmssS、yyyyMMddHHmmssSS、yyyyMMddHHmmssSSS

```java
if(StrUtil.startWithIgnoreEquals(format, DatePattern.PURE_DATETIME_PATTERN)){
	final String fraction = StrUtil.removePrefix(format, DatePattern.PURE_DATETIME_PATTERN);
	if(ReUtil.isMatch("[S]{1,2}", fraction)){
		//将yyyyMMddHHmmssS、yyyyMMddHHmmssSS的日期统一替换为yyyyMMddHHmmssSSS格式，用0补
		text += StrUtil.repeat('0', 3-fraction.length());
	}
	formatter = new DateTimeFormatterBuilder()
			.appendPattern(DatePattern.PURE_DATETIME_PATTERN)
			.appendValue(ChronoField.MILLI_OF_SECOND, 3)
			.toFormatter();
}

5.4.3修复此问题。
```
