### ISSUE TITLE
二维码工具类使用异常

### ISSUE THREAD

**Issue by shangx335** [looly/hutool#1088]
### 版本情况

JDK版本：   jkd1.8
hutool版本： 5.4.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
完全使用官网提供的教程：
引入hutool和zxing
 <dependency>
	<groupId>cn.hutool</groupId>
	<artifactId>hutool-all</artifactId>
	<version>5.4.2</version>
</dependency>
<dependency>
    <groupId>com.google.zxing</groupId>
    <artifactId>core</artifactId>
    <version>3.3.3</version>
</dependency>

测试main方法
public static void main(String[] args) {
// 生成指定url对应的二维码到文件，宽和高都是300像素
QrCodeUtil.generate("https://hutool.cn/", 300, 300, FileUtil.file("d:/qrcode.jpg"));
}

堆栈信息：
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.zxing.qrcode.decoder.Version.getVersionForNumber(Version.java:105)
	at com.google.zxing.qrcode.encoder.Encoder.encode(Encoder.java:112)
	at com.google.zxing.qrcode.QRCodeWriter.encode(QRCodeWriter.java:78)
	at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
	at cn.hutool.extra.qrcode.QrCodeUtil.encode(QrCodeUtil.java:312)
	at cn.hutool.extra.qrcode.QrCodeUtil.generate(QrCodeUtil.java:229)
	at cn.hutool.extra.qrcode.QrCodeUtil.generate(QrCodeUtil.java:215)
	at cn.hutool.extra.qrcode.QrCodeUtil.generate(QrCodeUtil.java:190)
	at cn.hutool.extra.qrcode.QrCodeUtil.generate(QrCodeUtil.java:133)
	at com.solan.test.hutool.TestQr.main(TestQr.java:12)

大概看了一下源码
zxing的Version.java类里有getVersionForNumber方法：
    public static Version getVersionForNumber(int versionNumber) {
        if (versionNumber > 0 && versionNumber <= 40) {
            return VERSIONS[versionNumber - 1];
        } else {
            throw new IllegalArgumentException();
        }
    }
使用工具类传入的versionNumber值是0，所以抛出异常。
看到请回复一下

**Comment by looly** [comment]
新版本的zxing确实有这个问题。

旧版中QrConfig.qrVersion可以为0，表示默认，新版本不允许了。

5.4.3修复此问题，你可以暂时：

```
QrConfig config = new QrConfig();
config.setQrVersion(null);
QrCodeUtil.generate("https://hutool.cn/", config, FileUtil.file("d:/qrcodeCustom.png"));
```
