### ISSUE TITLE
VersionComparator类重载的equals方法会导致递归调用，从而栈溢出

### ISSUE THREAD

**Issue by silent-field** [looly/hutool#1093]
### 版本情况

JDK版本：    jdk_8_261
hutool版本： 最新v5-master分支，SHA-1: 1b8e921ab2c515b8b47d0660f45a3107435e1b55

### 问题描述（包括截图）
VersionComparator类重载的equals方法会导致递归调用，从而栈溢出

cn.hutool.core.comparator.VersionComparator#equals
![image](https://user-images.githubusercontent.com/13652530/93436109-ea071080-f8fc-11ea-957e-2a6a9b8f4ef9.png)

1. 复现代码

```java
	public static void main(String[] args) {
		VersionComparator first = new VersionComparator();
		VersionComparator other = new VersionComparator();
		System.out.println(first.equals(other));
	}
```

2. 堆栈信息
Exception in thread "main" java.lang.StackOverflowError
	at cn.hutool.core.comparator.VersionComparator.equals(VersionComparator.java:97)
	at cn.hutool.core.comparator.VersionComparator.equals(VersionComparator.java:99)
	at cn.hutool.core.comparator.VersionComparator.equals(VersionComparator.java:99)
	at cn.hutool.core.comparator.VersionComparator.equals(VersionComparator.java:99)

**Comment by looly** [comment]
确认bug。

5.4.3解决此问题，会删除重载的equals方法，没啥意义。

感谢。
