### ISSUE TITLE
ExcelUtil  报错POI 版本不兼容，请帮看看，谢谢

### ISSUE THREAD

**Issue by suxg001** [looly/hutool#1098]
### 版本情况

JDK版本：    java version "1.8.0_144"
hutool版本： 5.4.3

### 问题描述（包括截图）

1. 复现代码

String file = "/Users/wjj/Downloads/beanToExecl.xlsx";

		Persion p = new Persion();

		p.setAge(18);
		p.setName("张三");
		p.setSorecs("100");

		Persion p1 = new Persion();

		p1.setAge(28);
		p1.setName("李四");
		p1.setSorecs("80");
		List<Persion> rows = CollUtil.newArrayList(p, p1);	
		
		
		// 通过工具类创建writer
		ExcelWriter writer = ExcelUtil.getWriter(file);
		// 合并单元格后的标题行，使用默认标题样式
		writer.merge(3, "一班成绩单");
		// 一次性写出内容，使用默认样式，强制输出标题
		writer.write(rows, true);
		// 关闭writer，释放内存
		writer.close();

 2、报错信息如下

Exception in thread "main" cn.hutool.core.exceptions.DependencyException: You need to add dependency of 'poi-ooxml' to your project, and version >= 4.1.2
	at cn.hutool.poi.excel.ExcelUtil.getWriter(ExcelUtil.java:395)
	at hutu.test.ExecUtilDemo.beanTOExecl(ExecUtilDemo.java:37)
	at hutu.test.ExecUtilDemo.main(ExecUtilDemo.java:12)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.HeaderFooter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cn.hutool.poi.excel.ExcelUtil.getWriter(ExcelUtil.java:393)
	... 2 more

**Comment by looly** [comment]
看下cause by。

一般是
1、你的poi版本太旧
2、多个poi版本冲突了
3、poi依赖包没有引入。

**Comment by suxg001** [comment]
这poi 不是hutool集成的吗？要我看什么？

**Comment by looly** [comment]
> 这poi 不是hutool集成的吗？要我看什么？

并不是，hutool不会关联引入poi，请见文档。
