### ISSUE TITLE
使用BeanUtil.copyProperties方法报错：No Converter for type [java.util.TreeSet]

### ISSUE THREAD

**Issue by Li-Jing** [looly/hutool#1101]
### 版本情况

JDK版本：    jdk_1.8.0_251
hutool版本： 5.4.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
实体中包含java.util.TreeSet类型时，BeanUtil.copyProperties方法报错：No Converter for type [java.util.TreeSet]
1. 复现代码

```java
public static TreeNodeDto toTreeNodeDto(TreeNode info) {
        TreeNodeDto dto = new TreeNodeDto();
        BeanUtil.copyProperties(info, dto, true);
        return dto;
    }

@Data
public class TreeNodeDto {
    private String id;
    private String parentId;
    private int sort;
    private String nodeName;
    private int type;
    private Boolean status;
    private String treeNodeId;
    private TreeSet<TreeNodeDto> children = new TreeSet();
}

@Data
public class TreeNode implements Comparable<TreeNode> {
    private String id;
    private String parentId;
    private int sort;
    private String nodeName;
    private int type;
    private Boolean status;
    private String treeNodeId;
    private TreeSet<TreeNode> children = new TreeSet();
}

```

2. 堆栈信息
cn.hutool.core.convert.ConvertException: No Converter for type [java.util.TreeSet]
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:272)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:287)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:729)
	at cn.hutool.core.bean.PropDesc.getValue(PropDesc.java:184)
	at cn.hutool.core.bean.copier.provider.BeanValueProvider.value(BeanValueProvider.java:41)
	at cn.hutool.core.bean.copier.provider.BeanValueProvider.value(BeanValueProvider.java:16)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$valueProviderToBean$1(BeanCopier.java:242)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.valueProviderToBean(BeanCopier.java:220)
	at cn.hutool.core.bean.copier.BeanCopier.beanToBean(BeanCopier.java:122)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:108)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:674)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

调用toTreeNodeDto(TreeNode info) 时的参数info(转为json格式后的数据)
```json
{
	"children": [{
		"children": [],
		"id": "52c95b83-2083-4138-99fb-e6e21f0c1277",
		"nodeName": "admin",
		"parentId": "00010001",
		"sort": 0,
		"status": true,
		"treeNodeId": "00010001_52c95b83-2083-4138-99fb-e6e21f0c1277",
		"type": 10
	}, {
		"children": [],
		"id": "97054a82-f8ff-46a1-b76c-cbacf6d18045",
		"nodeName": "test",
		"parentId": "00010001",
		"sort": 0,
		"status": true,
		"treeNodeId": "00010001_97054a82-f8ff-46a1-b76c-cbacf6d18045",
		"type": 10
	}],
	"id": "00010001",
	"nodeName": "测试",
	"parentId": "0001",
	"sort": 0,
	"status": true,
	"treeNodeId": "00010001",
	"type": 0
}
```

**Comment by Li-Jing** [comment]
hutool版本为4.6.4时可以正常解析，升级到5.4.3时解析出错（5.4.2也是一样出错）

**Comment by looly** [comment]
终于找到问题了，是因为TreeSet新建没有给默认的比较器导致的错误。

5.4.4解决此问题。
