### ISSUE TITLE
布隆过滤器数组越界

### ISSUE THREAD

**Issue by xianjinyao** [looly/hutool#1115]
### 版本情况

JDK版本：    openjdk_8_191
hutool版本： 5.4.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
BloomFilter filter = new JSFilter(50);
filter.contains("");
```

2. 堆栈信息
java.lang.ArrayIndexOutOfBoundsException: 1
	at cn.hutool.bloomfilter.bitMap.IntMap.contains(IntMap.java:43)
	at cn.hutool.bloomfilter.filter.AbstractFilter.contains(AbstractFilter.java:62)

3. 问题
布隆过滤器的*Map#contains没有判断是否有元素

**Comment by xianjinyao** [comment]
用法错误。maxValue初始化有误
