### ISSUE TITLE
关于PATCH请求的问题 在windows开发环境下可以正常请求，linux生产和测试均报错

### ISSUE THREAD

**Issue by KXiaoOu** [looly/hutool#1171]
### 版本情况

JDK版本：    jdk1.8.1_131
hutool版本：5.2.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
cn.hutool.http.HttpException: Invalid HTTP method: PATCH
	at cn.hutool.http.HttpConnection.setMethod(HttpConnection.java:133)
	at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:986)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:934)
	at com.thinkgem.jeesite.modules.oa.util.WPSYunDocUtil.rename(WPSYunDocUtil.java:268)

1. 复现代码
HttpRequest request = HttpRequest.patch(url)
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + getWPSAccessToken());
        // 执行
        HttpResponse response = request.execute();

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
尝试升级到5.4.5，中间魔改JDK支持了PATCH方法。
