### ISSUE TITLE
升级5.4.5包版本后Linux环境下部署测试，'sun.net.www.protocol.file.FileURLConnection' is not a http connection, make sure URL is format for http.

### ISSUE THREAD

**Issue by KXiaoOu** [looly/hutool#1174]
### 版本情况

JDK版本：    jdk1.8.0_131
hutool版本： 5.4.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
cn.hutool.http.HttpException: 'sun.net.www.protocol.file.FileURLConnection' is not a http connection, make sure URL is format for http.
        at cn.hutool.http.HttpConnection.openHttp(HttpConnection.java:534)
        at cn.hutool.http.HttpConnection.initConn(HttpConnection.java:88)
        at cn.hutool.http.HttpConnection.<init>(HttpConnection.java:75)
        at cn.hutool.http.HttpConnection.create(HttpConnection.java:59)
        at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1028)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:968)
        at com.thinkgem.jeesite.modules.oa.util.WPSYunDocUtil.getWPSAccessToken(WPSYunDocUtil.java:1232)

在本机开发环境可以正常访问，是否与linux下jdk版本(jdk1.8.0-201)相关？

1. 复现代码

String url = "http://xtbgyy.digitalgd.com.cn/ebus/../../.."
HttpRequest request = HttpRequest.post(url)
                .header("Content-Type", "application/x-www-form-urlencoded")
                .header("Authorization", "Basic " + authorizationBase64)
                .form("grant_type", "client_credentials")
                .form("scope", "App.Files.ReadWrite App.Files.Read App.Webhook");
        setDigitalgdAuthHeader(request);
        HttpResponse response = request.execute(true);

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
我这边没有测试出啥问题来，目测你的URL不是http://xxxxxxx，是不是`../../`导致的?
