### ISSUE TITLE
cn.hutool.http.HttpException: Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by ZhouQQQ** [looly/hutool#1183]
### 版本情况

JDK版本：    openjdk1.8
hutool版本： 5.3.10

### 问题描述（包括截图）

1. 复现代码

```java
HttpRequest.patch(findFileUrl).header(HttpHeaders.CONTENT_TYPE, "application/json").body(jsonStr).execute().body();
```

2. 堆栈信息
```bash
cn.hutool.http.HttpException: Invalid HTTP method: PATCH
	at cn.hutool.http.HttpConnection.setMethod(HttpConnection.java:133) ~[hutool-all-5.3.10.jar!/:na]
	at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1001) ~[hutool-all-5.3.10.jar!/:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:940) ~[hutool-all-5.3.10.jar!/:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:913) ~[hutool-all-5.3.10.jar!/:na]

```

**Comment by looly** [comment]
请升级到5.4.5，支持了patch。

**Comment by qiaolb** [comment]
我们使用的5.4.5也发现有这个问题 @looly 
![image](https://user-images.githubusercontent.com/8615816/143992852-c940bcee-8203-46c0-8dae-3b50c0871b14.png)

**Comment by looly** [comment]
@qiaolb 考虑是否版本冲突，升级5.7.16试下。

**Comment by amosnothing** [comment]
> @qiaolb 考虑是否版本冲突，升级5.7.16试下。

5.7.16  依然有问题

**Comment by deeplhub** [comment]
hutool-all：5.7.18
偶发性出现：cn.hutool.http.HttpException: Invalid HTTP method: PATCH 这时什么问题？

**Comment by looly** [comment]
@deeplhub 奇怪的问题，HttpGlobalConfig.allowPatch();已经执行了啊。

考虑是否有热部署的情况？

**Comment by bertondeng** [comment]
还是没解决吗？
