### ISSUE TITLE
The maximum length of cell contents (text) is 32,767 characters

### ISSUE THREAD

**Issue by fcjker** [looly/hutool#1195]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.6

导出excel字段过长报错，改成xlsx，还是不行，换成Bigwriter,依然报错

1. 复现代码
java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32,767 characters
	at org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:437)
	at org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:418)
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:227)
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:182)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:909)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:878)
	at cn.hutool.poi.excel.ExcelWriter.write(ExcelWriter.java:771)

**Comment by looly** [comment]
这个是POI限制，我这边没办法。
