### ISSUE TITLE
ClassConverter无法在不提供默认值的情况下进行类型转化

### ISSUE THREAD

**Issue by ForteScarlet** [looly/hutool#1207]
### 版本情况

JDK版本：    1.8.0_171
hutool版本： 5.4.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

我想要通过类的全路径字符串构建一个 `Class` 实例，但是如果 `convert(...)` 不提供默认值则无法正常转化。

1. 复现代码

```java
public class Test1 {
    public static void main(String[] args) {

        ConverterRegistry registry = ConverterRegistry.getInstance();
        String c = "love.forte.test.lis.Test1";
        // 虽然此处提供一个默认值可以执行，但是按理说不提供默认值也应该是正常的。
        Class<?> clazz = registry.convert(Class.class, c);
        System.out.println(clazz);
    }
}
```

2. 错误日志
```
Exception in thread "main" java.lang.NullPointerException: [type] and [defaultValue] are both null for Converter [cn.hutool.core.convert.impl.ClassConverter], we can not know what type to convert !
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:43)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:251)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:292)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:305)
	at love.forte.test.lis.Test1.main(Test1.java:36)

Process finished with exit code 1
```

**Comment by looly** [comment]
ClassUtil.getTypeArgument方法在判断泛型时导致的问题。

5.5.0修复此问题，感谢。
