### ISSUE TITLE
JSONUtil 工具类解析json字符串不允许有重复key

### ISSUE THREAD

**Issue by wcfeng9527** [looly/hutool#1212]
使用JSONUtil 解析一个json，字符串，如果字符串中有重复的key，会报错
```
String s = "{ \"key\": \"va\",\"key\":\"vb\"}";
final JSONObject json = JSONUtil.parseObj(s);
```
报错信息
```
Exception in thread "main" cn.hutool.json.JSONException: Duplicate key "key"
	at cn.hutool.json.JSONObject.putOnce(JSONObject.java:393)
	at cn.hutool.json.JSONObject.init(JSONObject.java:732)
	at cn.hutool.json.JSONObject.init(JSONObject.java:699)
	at cn.hutool.json.JSONObject.init(JSONObject.java:659)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:202)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:112)
```
我这里有可能存在多个相关的key的情况，怎么处理

**Comment by looly** [comment]
hutool的json设计的时候就不允许重复key。

这个没办法，要么处理json，要么考虑其它库试试看。
