### ISSUE TITLE
cn.hutool.core.math.Calculator.conversion("1") raises "java.lang.ArrayIndexOutOfBoundsException: 1"

### ISSUE THREAD

**Issue by asdf913** [looly/hutool#1222]
### 版本情况

JDK版本：    jdk1.8.0_271
hutool版本：
```
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-core</artifactId>
    <version>5.5.1</version>
</dependency>
```

### 问题描述（包括截图）

1. 复现代码

```
import cn.hutool.core.math.Calculator;

public class CalculatorTest {

	public static void main(final String[] args) {
		//
		// Output "12.0"
		//
		System.out.println(Calculator.conversion("12"));
		//
		// Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
		//
		System.out.println(Calculator.conversion("1"));
		//
	}

}
```

2. 堆栈信息
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at cn.hutool.core.math.Calculator.transform(Calculator.java:56)
	at cn.hutool.core.math.Calculator.conversion(Calculator.java:30)
```

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
判断数组问题，5.5.2修复此问题，感谢。
