### ISSUE TITLE
ExcelUtil.readBySax 无法流解析文件

### ISSUE THREAD

**Issue by lijinghui** [looly/hutool#1225]
### 版本情况

JDK版本：    jdk 1.80_203
hutool版本： 5.5.0（请确保最新尝试是否还有问题）
poi-ooxml版本： 4.1.2
### 问题描述（包括截图）
上传文件使用 ExcelUtil.readBySax 无法解析，使用new Excel07SaxReader 正常解析

1. 复现代码

ExcelUtil.readBySax(inputStream,0,createRowHandler());

2. 堆栈信息
Caused by: org.apache.poi.openxml4j.exceptions.NotOfficeXmlFileException: No valid entries or contents found, this is not a valid OOXML (Office Open XML) file
	at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.getNextEntry(ZipArchiveThresholdInputStream.java:145) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at org.apache.poi.openxml4j.util.ZipInputStreamZipEntrySource.<init>(ZipInputStreamZipEntrySource.java:49) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:106) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:307) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at cn.hutool.poi.excel.sax.Excel07SaxReader.read(Excel07SaxReader.java:123) ~[hutool-all-5.5.0.jar:na]
	at cn.hutool.poi.excel.sax.Excel07SaxReader.read(Excel07SaxReader.java:118) ~[hutool-all-5.5.0.jar:na]
	at cn.hutool.poi.excel.sax.Excel07SaxReader.read(Excel07SaxReader.java:36) ~[hutool-all-5.5.0.jar:na]
	at cn.hutool.poi.excel.ExcelUtil.readBySax(ExcelUtil.java:88) ~[hutool-all-5.5.0.jar:na]
	at com.shores.fuad.controller.FileController.encodeBigFile(FileController.java:170) ~[classes/:na]
	at com.shores.fuad.controller.FileController.uploadFiles(FileController.java:101) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 60 common frames omitted
Caused by: java.util.zip.ZipException: Unexpected record signature: 0X936BC9E9
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:260) ~[commons-compress-1.19.jar:1.19]
	at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.getNextEntry(ZipArchiveThresholdInputStream.java:141) ~[poi-ooxml-4.1.2.jar:4.1.2]
	... 82 common frames omitted

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/13672644/99355173-c5bab680-28e2-11eb-9414-a959e343260f.png)

**Comment by looly** [comment]
5.5.2修复问题。

你也可以使用如下方法解决此问题：
```java
ExcelUtil.readBySax(IoUtil.toMarkSupportStream(inputStream),0,createRowHandler());
```
