### ISSUE TITLE
JSONUtil.parseObj对\字符转换报错

### ISSUE THREAD

**Issue by lipeng260** [looly/hutool#1248]
### 版本情况

JDK版本：    openjdk_8_222
hutool版本： 5.5.1

### 问题描述（包括截图）

1. 复现代码
"\"这个字符转义后是\\。
```java
final JSONObject jsonObject = JSONUtil.parseObj("{\n" +
                "    \"test\": \"\\地库地库\",\n" +
                "}");
```

2. 堆栈信息
cn.hutool.json.JSONException: Illegal escape. at 17 [character 15 line 2]

	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
	at cn.hutool.json.JSONTokener.nextString(JSONTokener.java:262)
	at cn.hutool.json.JSONTokener.nextValue(JSONTokener.java:329)
	at cn.hutool.json.JSONObject.init(JSONObject.java:747)
	at cn.hutool.json.JSONObject.init(JSONObject.java:714)
	at cn.hutool.json.JSONObject.init(JSONObject.java:670)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:179)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:161)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:144)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:88)
	at com.yuqiinfo.yzb.common.util.MapToInsUtilTest.createMapToIns(MapToInsUtilTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Comment by looly** [comment]
你应该使用`\\\\`：

```java
final JSONObject jsonObject = JSONUtil.parseObj("{\n" +
				"    \"test\": \"\\\\地库地库\",\n" +
				"}");
```

**Comment by lipeng260** [comment]
前端提交的"\地库地库"，后端String接收到的是"\\\地库地库"，不会是\\\\\\

**Comment by lipeng260** [comment]
```
import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;

import java.util.Scanner;

/**
 * @Author: lipeng
 * @Date: 2020/11/27 上午9:16
 */
public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("请输入你的姓名：");
        String name = sc.nextLine();
        System.out.println(name);
        final JSONObject jsonObject = JSONUtil.parseObj("{\n" +
                "    \"test\": \""+name+"\",\n" +
                "}");
        System.out.println(jsonObject);
    }
}
```
![image](https://user-images.githubusercontent.com/15009707/100400593-0a3c1400-3092-11eb-8fa2-f6971f1aba95.png)
