### ISSUE TITLE
JSONUtil.parseObj对\字符转换报错

### ISSUE THREAD

**Issue by lipeng260** [looly/hutool#1254]
### 版本情况

JDK版本：    openjdk_8_222
hutool版本： 5.5.1

### 问题描述（包括截图）

1. 复现代码

```java
import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;

import java.util.Scanner;

/**
 * @Author: lipeng
 * @Date: 2020/11/27 上午9:16
 */
public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("请输入你的姓名：");
        String name = sc.nextLine();
        System.out.println(name);
        final JSONObject jsonObject = JSONUtil.parseObj("{\n" +
                "    \"test\": \""+name+"\",\n" +
                "}");
        System.out.println(jsonObject);
    }
}

```

2. 堆栈信息
请输入你的姓名：
\张三
\张三
Exception in thread "main" cn.hutool.json.JSONException: Illegal escape. at 17 [character 15 line 2]
	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
	at cn.hutool.json.JSONTokener.nextString(JSONTokener.java:262)
	at cn.hutool.json.JSONTokener.nextValue(JSONTokener.java:329)
	at cn.hutool.json.JSONObject.init(JSONObject.java:747)
	at cn.hutool.json.JSONObject.init(JSONObject.java:714)
	at cn.hutool.json.JSONObject.init(JSONObject.java:670)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:179)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:161)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:144)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:88)
	at App.main(App.java:16)

Process finished with exit code 1

**Comment by looly** [comment]
用\\

**Comment by lipeng260** [comment]
\会自动再String中保存的是\\\，测试代码我都贴上去了，还要我怎么样？

**Comment by looly** [comment]
你应该输入`\\张三`。

你这里用的字符串拼接，因此JSON字符串中的特殊字符必须是转义后的，所以用两个`\`。

**Comment by lipeng260** [comment]
@looly 客户录入系统就是\，不可能让客户录入系统输入\\\。
asc码\是92，客户录入的信息里就是这个92，
![image](https://user-images.githubusercontent.com/15009707/100418291-7d0eb480-30bd-11eb-852c-14038995a7e9.png)

**Comment by lipeng260** [comment]
![image](https://user-images.githubusercontent.com/15009707/100418558-f0b0c180-30bd-11eb-81cb-f098a5bbded3.png)
外层的case已经是\b,\t,\n,\r,\\转义字符了，\\\代表的就是字符\，内层的case就不需要了，取后面的字符就是是\张三中的张了！所以报错了！\\\不是转义，是字符92，就是\

**Comment by looly** [comment]
那你就不应该使用拼接字符串的方式，使用JSONUtil.createObj().set()即可自动转义。

**Comment by lipeng260** [comment]
我只能呵呵了

**Comment by looly** [comment]
我想你对转义符理解有误。

用户输入`\`确实表示斜杠本身，但是在json字符串中，`\`字符本身表示转义符。所以你可以：

```java
Scanner sc = new Scanner(System.in);
System.out.println("请输入你的姓名：");
String name = sc.nextLine();
System.out.println(name);
final JSONObject jsonObject = JSONUtil.createObj().set("test", name);
System.out.println(jsonObject);
```

输出：

```
\张三
\张三
{"test":"\\张三"}
```

在JSON字符串中，`\\`就是表示`\`。

**Comment by looly** [comment]
如果还是不能解决你的疑问，考虑换FastJSON等库试下，是一样的。

**Comment by lipeng260** [comment]
理解了，谢谢。
