### ISSUE TITLE
DateUtil.parse("2020-12-23", DatePattern.PURE_DATE_PATTERN);结果为：2019-11-02 00:00:00

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1332]
### 版本情况

JDK版本： jdk_8_201
hutool版本： 5.4.0

### 问题描述（包括截图）

1. 复现代码

```java
DateUtil.parse("2020-12-23", DatePattern.PURE_DATE_PATTERN);
结果为：2019-11-02 00:00:00
```

**Comment by joey-happy** [comment]
同样的代码 apache工具类提示错误如下：
Date date = DateUtils.parseDate("2020-12-23", DatePattern.PURE_DATE_PATTERN);
Exception in thread "main" java.text.ParseException: Unable to parse the date: 2020-12-23
	at org.apache.commons.lang3.time.DateUtils.parseDateWithLeniency(DateUtils.java:388)
	at org.apache.commons.lang3.time.DateUtils.parseDate(DateUtils.java:302)
	at org.apache.commons.lang3.time.DateUtils.parseDate(DateUtils.java:279)
	at com.zhou.techstack.foundation.Test.main(Test.java:41)

**Comment by joey-happy** [comment]
同样的代码 joda报错如下：
        DateTimeFormatter format = DateTimeFormat.forPattern(DatePattern.PURE_DATE_PATTERN);
        DateTime dateTime = format.parseDateTime("2020-12-23");
        System.out.println(dateTime);

Exception in thread "main" java.lang.IllegalArgumentException: Invalid format: "2020-12-23" is malformed at "-12-23"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
	at com.zhou.techstack.foundation.Test.main(Test.java:42)

**Comment by looly** [comment]
这源于`SimpleDateFormat`的处理问题。你传字符串默认使用此对象来处理。

你可以：
```java
DateUtil.parse("2020-12-23", DatePattern.PURE_DATE_FORMAT);
```

这样是返回报错的。

5.5.5我会修改这个规则以应对此类情况，算是`SimpleDateFormat`一个坑，需要调用`setLenient`设置为严格模式。
