### ISSUE TITLE
【bug】BCRYPT加密算法的问题

### ISSUE THREAD

**Issue by CodingOX** [looly/hutool#1377]
### 版本情况

JDK版本：    openjdk_8_201 Or  openjdk version "11.0.9.1" 
hutool版本： 5.5.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
// 其中第二参数是通过 BCrypt.hashpw(oriPwd) 生成的
cn.hutool.crypto.digest.BCrypt.checkpw("xxx","$2a$2a$10$e4lBTlZ019KhuAFyqAlgB.Jxc6cM66GwkSR/5/xXNQuHUItPLyhzy");
```

2. 堆栈信息
```
java.lang.NumberFormatException: For input string: "2a"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at cn.hutool.crypto.digest.BCrypt.hashpw(BCrypt.java:435)
	at cn.hutool.crypto.digest.BCrypt.checkpw(BCrypt.java:514)
	at com.uewell.ubirth.tool.util.CheckTest.testPwd(CheckTest.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```
根据调用栈是在类`Bcrypt`地方报错：
```
		if (salt.charAt(off + 2) > '$')
			throw new IllegalArgumentException("Missing salt rounds");
		rounds = Integer.parseInt(salt.substring(off, off + 2));
```
上文：` Integer.parseInt`抛出错误。

# 建议
这个工具方法是否考虑只返回 true/false ，报错的情况，也算校验失败？
`https://github.com/patrickfav/bcrypt` 使用这个项目只返回了 false.

**Comment by CodeLunatic** [comment]
为什么你的hashpw的长度是63？

**Comment by CodingOX** [comment]
> 为什么你的hashpw的长度是63？

这个不清楚，从数据库里面拷贝出来的，理论上都是通过`BCrypt.hashpw()`生成并插入的。

**Comment by looly** [comment]
5.5.8修复此问题。此处确实应该返回false，而不是报错。
