### ISSUE TITLE
关于BigDecimal add = NumberUtil.add("123", "", "");  报错的问题

### ISSUE THREAD

**Issue by victorgkang** [looly/hutool#1389]
### 版本情况

JDK版本：    openjdk_8_211
hutool版本： 5.5.7（

### 问题描述（包括截图）

1. 复现代码

```java
BigDecimal add = NumberUtil.add("123", "", "");
        Console.log(add);     //报错了
```

2. 堆栈信息
Exception in thread "main" java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:599)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:809)
	at cn.hutool.core.util.NumberUtil.add(NumberUtil.java:165)
	at com.victor.utils.TestJSON.test7(TestJSON.java:162)
	at com.victor.utils.TestJSON.main(TestJSON.java:36)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
see: https://gitee.com/loolly/hutool/issues/I2MAS8?from=project-issue
