### ISSUE TITLE
JSON包在将Exception类转化为JSON字符串时，会产生堆栈溢出错误(java.lang.StackOverflowError)

### ISSUE THREAD

**Issue by tanloo** [looly/hutool#1399]
### 版本情况

JDK版本：    oracle jdk1.8.0_271
hutool版本： 5.5.8

### 问题描述（包括截图）
 在使用mybatis-plus查询数据库，只要是数据库语句错误，将异常类(Exception)放置入JSONObject中，再转化为字符串就会产生这个堆栈溢出的问题。
1. 复现代码

```java
        JSONObject jsonObject = new JSONObject();
        jsonObject.set("msg", 500);
        try {
            List<Long> userIds = new ArrayList<>();
            // 执行语句为：SELECT id,name,password FROM user WHERE (id IN ())
            List<User> userList = userMapper.selectList(Wrappers.<User>lambdaQuery().in(User::getId, userIds));
        } catch (Exception e) {
            jsonObject.set("exception", e);
        }
        System.out.println(jsonObject.toString());
```

2. 堆栈信息
java.lang.StackOverflowError
	at cn.hutool.core.util.ClassUtil.isBasicType(ClassUtil.java:737)
	at cn.hutool.core.util.ObjectUtil.isBasicType(ObjectUtil.java:506)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:719)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:740)
	at cn.hutool.json.JSONArray.add(JSONArray.java:382)
	at cn.hutool.json.JSONArray.init(JSONArray.java:609)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:189)
        ........

**Comment by looly** [comment]
目测循环引用了，请检查Exception到底具体是哪个对象，看是否实现了什么特使接口，比如Iterator

**Comment by tanloo** [comment]
> 目测循环引用了，请检查Exception到底具体是哪个对象，看是否实现了什么特使接口，比如Iterator

图片是打印的堆栈信息：
![Exception_detail](https://user-images.githubusercontent.com/43210590/106693526-a3972180-6611-11eb-8a22-1b03947d3e3a.png)

查看进去，因该是这个异常`SQLException`实现了`Iterable<Throwable>`导致的，在官方包`java.sql`下。
如果可以，麻烦请解决一下这个问题呢。现在我是额外引用了fastjson，可以将该异常进行json字符串转换了

**Comment by looly** [comment]
5.5.9解决此问题，感谢

**Comment by looly** [comment]
暂时的解决办法是：

```
 jsonObject.set("exception", e.toString());
```
