### ISSUE TITLE
oracle 批量插入，指定id的值为 sequence 的时候 会报错。

### ISSUE THREAD

**Issue by jicg** [looly/hutool#1483]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.6.0

### 问题描述
oracle 批量插入，指定id的值为 sequence 的时候 会报错。
代码
```sql
create table EB_JST_PURCHASEIN(
       IO_ID NUMBER(10)   ,
       IO_DATE VARCHAR2(500)   ,
      id number(10, 0) not null
);
```
```java
    @Data
    @TableName("eb_jst_purchasein")
    public static class PurchaseInPullT {
        //region 属性
        private Integer id;
        //入库单号
        private Integer io_id;
        //单据日期
        private String io_date;
    }
    @Test
    void insertDb2() throws SQLException {
        String table = "eb_jst_purchasein";
        List<PurchaseInPullT> ds = new ArrayList<PurchaseInPullT>();
        for (int i = 0; i < 100; i++) {
            PurchaseInPullT d = new PurchaseInPullT();
            d.setIo_date("setIo_date" + i);
            d.setIo_id(i);
            ds.add(d);
        }
        long time = System.currentTimeMillis();
        try {
            List<Entity> entities = ds.stream().map((s) -> Entity.parse(s)
                    .setTableName(table)
                    .set("id", "seq_" + table + ".nextval")).collect(Collectors.toList());
            Db.use().insert(entities);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        System.out.println("---end---" + ((System.currentTimeMillis() - time) / 1000));
    }
```
错误
```log
java.sql.SQLException: 无效的列索引
	at oracle.jdbc.driver.OraclePreparedStatement.setNullCritical(OraclePreparedStatement.java:4204)
	at oracle.jdbc.driver.OraclePreparedStatement.setNull(OraclePreparedStatement.java:4192)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setNull(OraclePreparedStatementWrapper.java:1010)
	at cn.hutool.db.StatementUtil.setParam(StatementUtil.java:338)
	at cn.hutool.db.StatementUtil.fillParams(StatementUtil.java:84)
	at cn.hutool.db.StatementUtil.prepareStatementForBatch(StatementUtil.java:206)
	at cn.hutool.db.dialect.impl.AnsiSqlDialect.psForInsertBatch(AnsiSqlDialect.java:56)
	at cn.hutool.db.DialectRunner.insert(DialectRunner.java:82)
	at cn.hutool.db.SqlConnRunner.insert(SqlConnRunner.java:117)
	at cn.hutool.db.AbstractDb.insert(AbstractDb.java:360)

```

比如报错的Excel文件，有问题的图片等。

**Comment by jicg** [comment]
如果方便，可否添加个 下面的方式。就是 字段的值是来自数据库。
```java
entity.setSql("id", "通过自定义sql获取id")
          .setSql("update", "sysdate")
          .setSql("type", "get_type('"+参数+"')");
```

**Comment by looly** [comment]
看下生成的SQL，你的索引`"seq_" + table`是不不存在？一般是

```java
.set("id", "id.nextval"))
```
