### ISSUE TITLE
SFTP工具断线重连报错

### ISSUE THREAD

**Issue by bluelychee** [looly/hutool#1524]
### 版本情况

JDK版本：    jdk_1.8
hutool版本： 5.6.3

### 问题描述（包括截图）
1、正常连接sftp服务器
2、断开sftp服务器的网络，使用reconnectIfTimeout重新连接
3、连接sftp服务器的网络，使用reconnectIfTimeout重新连接报错了，跟踪代码发现使用了连接池，连接池中session使用的是之前的连接，从缓存中取出session后应该要检测一下连接是否断开，连接断开后要重新创建session，不然会报错。
![image](https://user-images.githubusercontent.com/19816631/115173425-da051880-a0f9-11eb-9805-430a99d6e375.png)

1. 复现代码

```java
public static Sftp getSftp() {
        String ip = "192.168.2.15";
        //String ip = "172.27.155.12";
        FtpConfig config = FtpConfig.create().setHost(ip).setPort(22).setUser("root").setPassword("lizhihui123").setCharset(Charset.forName("Utf-8")).setSoTimeout(timeOut).setConnectionTimeout(timeOut);
        if (sftp == null) {
            sftp = new Sftp(config);
        } else {
            sftp = sftp.reconnectIfTimeout();
        }
        return sftp;
    }
```

2. 堆栈信息
Caused by: cn.hutool.extra.ssh.JschRuntimeException: JSchException: Packet corrupt
	at cn.hutool.extra.ssh.JschUtil.createChannel(JschUtil.java:392)
	at cn.hutool.extra.ssh.JschUtil.openChannel(JschUtil.java:367)
	at cn.hutool.extra.ssh.JschUtil.openSftp(JschUtil.java:306)
	at cn.hutool.extra.ssh.Sftp.init(Sftp.java:153)
	at cn.hutool.extra.ssh.Sftp.init(Sftp.java:123)
	at cn.hutool.extra.ssh.Sftp.init(Sftp.java:142)
	at cn.hutool.extra.ssh.Sftp.reconnectIfTimeout(Sftp.java:175)
	at com.smp.api.dx.service.SftpInstance.getSftp(SftpInstance.java:23)
	at com.smp.api.dx.service.SftpPipeline.run(SftpPipeline.java:54)
	at com.smp.quartz.task.DxSftpTask.doTask(DxSftpTask.java:27)
	... 9 more
Caused by: com.jcraft.jsch.JSchException: Packet corrupt
	at com.jcraft.jsch.Session.start_discard(Session.java:1067)
	at com.jcraft.jsch.Session.read(Session.java:937)
	at com.jcraft.jsch.Session.connect(Session.java:309)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at cn.hutool.extra.ssh.JschUtil.createChannel(JschUtil.java:388)
	... 18 more

**Comment by bluelychee** [comment]
![image](https://user-images.githubusercontent.com/19816631/115176004-bbede700-a0fe-11eb-84f8-7ea948790420.png)

目前只能用这种蠢办法来兼容了，盼尽快解决。

**Comment by looly** [comment]
问题出在reconnectIfTimeout方法的逻辑判断上，cd命令执行失败会抛出异常，而非返回false。
