### ISSUE TITLE
QQ邮箱发送邮件失败

### ISSUE THREAD

**Issue by ghost** [looly/hutool#1529]
### 版本情况

JDK版本：    1.8
hutool版本： 5.6.3

### 问题描述（包括截图）

1. 复现代码

```java
MailAccount mailAccount = new MailAccount();
mailAccount.setFrom("braycep@foxmail.com");
mailAccount.setPass("xxxx");

mailAccount.setHost("smtp.qq.com");
mailAccount.setAuth(true);

mailAccount.setSslEnable(true);

Mail mail = Mail.create(mailAccount).setTos(to);
mail.setTitle("邮箱验证");
mail.setContent("您的验证码是：<h3>" + code.toUpperCase() + "</h3>");
mail.setHtml(true);

try {
    mail.send();
} catch (Exception e) {
    e.printStackTrace();
    return false;
}

return true;
```

2. 堆栈信息
```java
cn.hutool.extra.mail.MailException: MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465
	at cn.hutool.extra.mail.Mail.send(Mail.java:383)
	at top.braycep.springbootdemo.service.EmailService.sendVerifyEmail(EmailService.java:26)
	at top.braycep.springbootdemo.service.EmailService.main(EmailService.java:46)
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at cn.hutool.extra.mail.Mail.doSend(Mail.java:397)
	at cn.hutool.extra.mail.Mail.send(Mail.java:375)
	... 2 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:549)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:354)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:211)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1927)
	... 10 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 21 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 27 more
```

3. 临时的解决办法
```java
// 修改socketFactoryClass类
mailAccount.setSocketFactoryClass(TrustedMailSSLSocketFactory.class.getName());

// TrustedMailSSLSocketFactory
public class TrustedMailSSLSocketFactory {
    public static SSLSocketFactory getDefault() throws NoSuchAlgorithmException {
        SSLSocketFactory sslSocketFactory = null;
        try {
            sslSocketFactory = new MailSSLSocketFactory();
            ((MailSSLSocketFactory) sslSocketFactory).setTrustAllHosts(true);
        } catch (GeneralSecurityException e) {
            sslSocketFactory = SSLContext.getDefault().getSocketFactory();
        }

        return sslSocketFactory;
    }
}
```

请问有别的解决办法没

**Comment by looly** [comment]
QQ邮箱我这边测试正常，没有遇见过此类问题啊。

你mail包使用最新版本么？

```xml
<dependency>
	<groupId>com.sun.mail</groupId>
	<artifactId>javax.mail</artifactId>
	<version>1.6.2</version>
</dependency>
```

**Comment by ghost** [comment]
```xml
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.6.3</version>
        </dependency>

        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.6.2</version>
        </dependency>
```

**Comment by looly** [comment]
近期会接受你的pr：https://gitee.com/dromara/hutool/pulls/317
