### ISSUE TITLE
用hutool的downloadBytes，400问题

### ISSUE THREAD

**Issue by Stefbing** [looly/hutool#1537]
### 版本情况

JDK版本：    1.8.0_231
hutool版本： 5.4.0

### 需求是网图url下载为base64，我用hutool的downloadBytes，但是400了
这个url在postman或者另一个转base64方法里是可以正常获取图片的

1. 复现代码

```java
public static void main(String[] args) {
        byte[] bytes = HttpUtil.downloadBytes("https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic.jj20.com%2Fup%2Fallimg%2F1114%2F0H320120Z3%2F200H3120Z3-6-1200.jpg&refer=http%3A%2F%2Fpic.jj20.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1621996490&t=8c384c2823ea453da15a1b9cd5183eea");
        Console.log(Base64.encode(bytes));
    }

Exception in thread "main" cn.hutool.http.HttpException: Server response error with status code: [400]
	at cn.hutool.http.HttpUtil.downloadBytes(HttpUtil.java:381)
	at cn.yitu.app.utility.ImageUtils.main(ImageUtils.java:128)
```

**Comment by redbirdztc** [comment]
HttpUtil.downloadBytes在解析url时构造UrlBuilder。url被decode导致目标服务器不能正常解析url。可以对解析路径上的多个方法重载使得解析时不decode。

decode后的url：
```
https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic.jj20.com%2Fup%2Fallimg%2F1114%2F0H320120Z3%2F200H3120Z3-6-1200.jpg&refer=http%3A%2F%2Fpic.jj20.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1621996490&t=8c384c2823ea453da15a1b9cd5183eea
```

**Comment by redbirdztc** [comment]
HttpUtil.downloadBytes(String url)会对url做urlcode解码。而解码后的url不能正常访问资源。

decode后的url：
```
https://gimg2.baidu.com/image_search/src=http://pic.jj20.com/up/allimg/1114/0H320120Z3/200H3120Z3-6-1200.jpg&refer=http://pic.jj20.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1621996490&t=8c384c2823ea453da15a1b9cd5183eea
```

**Comment by daidai21** [comment]
![image](https://user-images.githubusercontent.com/36124626/116257359-91f38f00-a7a6-11eb-8d24-3b0822265697.png)
最后一个参数的url有问题

**Comment by looly** [comment]
问题出在对URL的编码问题上：

":"和"/"都没有纳入编码的字符范围导致的问题，百度这个URL很是奇怪。

5.6.5修复此问题，感谢。
