### ISSUE TITLE
boolmfilter javaDefaultHash 得到的hash值大于int范围出现负数，然后还把负数作为数组角标

### ISSUE THREAD

**Issue by zhang-shoukang** [looly/hutool#154]
public static int javaDefaultHash(String str) {
        int h = 0;
        int off = 0;
        int len = str.length();
        for (int i = 0; i < len; i++) {
            h = 31 * h + str.charAt(off++);
        }
        return h;
    }

public boolean contains(long i) {
		int r = (int) (i / BitMap.MACHINE64);
		long c = i % BitMap.MACHINE64;
		if (((longs[r] >>> c) & 1) == 1) {
			return true;
		}
		return false;
	}

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -196386
	at cn.hutool.bloomfilter.bitMap.IntMap.contains(IntMap.java:31)
	at cn.hutool.bloomfilter.filter.AbstractFilter.contains(AbstractFilter.java:44)
	at cn.hutool.bloomfilter.BitMapBloomFilter.contains(BitMapBloomFilter.java:70)
	at BloomFilterTest.main(BloomFilterTest.java:26)

**Comment by looly** [comment]
4.1.9修复此问题，感谢。
