### ISSUE TITLE
JSONUtil解析抽象类，反序列化出现NPE

### ISSUE THREAD

**Issue by wuuJiawei** [looly/hutool#1550]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

- 报错代码贴在二楼
- 尝试解决的代码贴在三楼

2. 堆栈信息

```
java.lang.NullPointerException
	at cn.hutool.core.bean.copier.BeanCopier.valueProviderToBean(BeanCopier.java:214)
	at cn.hutool.core.bean.copier.BeanCopier.mapToBean(BeanCopier.java:133)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:102)
	at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:78)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:273)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:292)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:729)
	at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:80)
	at cn.hutool.json.JSON.toBean(JSON.java:185)
	at cn.hutool.json.JSON.toBean(JSON.java:172)
	at cn.hutool.json.JSON.toBean(JSON.java:148)
	at MessageParseTest.parseTest(MessageParseTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by wuuJiawei** [comment]
> 报错的代码

```
import cn.hutool.json.JSON;
import cn.hutool.json.JSONUtil;
import cn.hutool.json.serialize.JSONDeserializer;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.junit.Test;

public class MessageParseTest {
    
    CustomMessage customMessage = new CustomMessage(999);
    
    @Test
    public void parseTest(){
        Message messageObj = new Message(customMessage);
        String messageJSON = JSONUtil.toJsonStr(messageObj);
        System.out.println(messageJSON);
    
        Message parseMessageObj = JSONUtil.parse(messageJSON).toBean(Message.class);
        System.out.println(parseMessageObj.getContent());
    }
    
    @Data
    public static class Message {
        
        /**
         * 消息类型
         */
        private String objectName;
        
        /**
         * 发送消息内容
         */
        private AbstractMessage content;
        
        public Message(AbstractMessage content) {
            this.objectName = content.getType();
            this.content = content;
        }
       
    }
    
    public static abstract class AbstractMessage {
        public String type;
        @Getter
        @Setter
        private String other;
        
        public abstract String toString();
        public abstract String getType();
    }
    
    @AllArgsConstructor
    public static class CustomMessage extends AbstractMessage {
    
        @Getter
        @Setter
        private int count;
        
        @Override
        public String toString() {
            return JSONUtil.toJsonStr(this);
        }
    
        @Override
        public String getType() {
            super.type = "CustomMessage";
            return super.type;
        }
        
    }
}

```

**Comment by wuuJiawei** [comment]
看了下源码，找到了`putDeserializer()`方法，通过自定义反序列化方法，手动转换为抽象类的子类。
**不知道有没有更好的方法？烦请赐教！**

> 尝试解决的代码

```
    @Test
    public void customDeserializerTest(){
        JSONUtil.putDeserializer(Message.class, new JSONDeserializer<Object>() {
            @Override
            public Message deserialize(JSON json) {
                String text = json.toString();
                System.out.println(text);
    
                // {"content":{"count":999,"type":"CustomMessage"},"objectName":"CustomMessage"}
                
                String objectName = json.getByPath("objectName", String.class);
                System.out.println(objectName);
                
                Object contentObj = json.getByPath("content");
                AbstractMessage abstractMessage = null;
    
                switch (objectName) {
                    case "CustomMessage":
                        abstractMessage = JSONUtil.parse(contentObj).toBean(CustomMessage.class);
                    default:
                        // do nothing
                }
                
                return new Message(abstractMessage);
            }
        });
        
        Message messageObj = new Message(customMessage);
        String messageJSON = JSONUtil.toJsonStr(messageObj);
        System.out.println(messageJSON);
        
        Message parseMessageObj = JSONUtil.parse(messageJSON).toBean(Message.class, true);
        System.out.println(parseMessageObj.getContent());
    }
    
```

**Comment by looly** [comment]
抽象类没有好的方法，只能自定义实现了。Hutool没法创建匿名对象。
