### ISSUE TITLE
sftp工具类多次连接报错

### ISSUE THREAD

**Issue by zzb980881** [looly/hutool#1551]
### 版本情况

JDK版本：   jdk11
hutool版本： 5.6.0（请确保最新尝试是否还有问题）

### 问题描述： sftp工具类使用时，多次创建连接，如果第一次连接关闭，后面的连接操作会报错
![QQ截图20210430162206](https://user-images.githubusercontent.com/1118228/116669006-a1562080-a9d0-11eb-927c-e28a7cc6a9a9.png)

1. 复现代码
#
```java
               Session session = JschUtil.getSession("xxxxxx", 22, "xxx", "xx");
		Sftp sftp = JschUtil.createSftp(session);
		List<String> ls=sftp.ls("data");
		sftp.close();
		sftp= new Sftp(session);
		ls=sftp.ls("data");
		Console.log(ls);
```

2. 堆栈信息
cn.hutool.extra.ssh.JschRuntimeException: JSchException: Packet corrupt

	at cn.hutool.extra.ssh.JschUtil.createChannel(JschUtil.java:392)
	at cn.hutool.extra.ssh.JschUtil.openChannel(JschUtil.java:367)
	at cn.hutool.extra.ssh.JschUtil.openSftp(JschUtil.java:306)
	at cn.hutool.extra.ssh.Sftp.init(Sftp.java:154)
	at cn.hutool.extra.ssh.Sftp.<init>(Sftp.java:99)
	at cn.hutool.extra.ssh.Sftp.<init>(Sftp.java:87)
	at cn.hutool.extra.ssh.JschUtilTest.sftpTest1(JschUtilTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: com.jcraft.jsch.JSchException: Packet corrupt
	at com.jcraft.jsch.Session.start_discard(Session.java:1067)
	at com.jcraft.jsch.Session.read(Session.java:937)
	at com.jcraft.jsch.Session.connect(Session.java:309)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at cn.hutool.extra.ssh.JschUtil.createChannel(JschUtil.java:388)
	... 31 more

**Comment by looly** [comment]
这是Session复用导致的，如果复用Session，请不要关闭Channel。

**Comment by zzb980881** [comment]
> 
> 
> 这是Session复用导致的，如果复用Session，请不要关闭Channel。

重新创建连接也不行吗，我这是测试生产的问题，因为生产上长时间没有上传问题，再上传文件系统会报错。

**Comment by looly** [comment]
尝试使用JSchUtil.createSession试下。
