### ISSUE TITLE
hutool封装的redis连接池时

### ISSUE THREAD

**Issue by ywacko** [looly/hutool#1570]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在使用hutool封装的redis连接池时，在预料之外的时间点报错Could not get a resource from the pool
1. 复现代码
```java

    @Override
    public String getAll(String key) {
        LOGGER.info("正在redis中查询表内容");
        try (Jedis jedis = RedisDS.create(ConfigConstant.ENVIRONMENT).getJedis()) {
            String valueList = jedis.hget(key, ConfigConstant.VERSION);
            LOGGER.info("关键字：" + key + " 查询结束");
            return valueList;
        } catch (Exception e) {
            LOGGER.error("获取redis失败", e);
            return NOT_FOUND;
        }
    }

```

2. 堆栈信息
```java

来了老弟? 2021-05-10 13:54:26.026 INFO  --- [io-8800-exec-10]  c.p.cms.configcenter.controller.QueryController    : 正在查询表：t-elc-xf-pm-tsgjwz中的配置文件
来了老弟? 2021-05-10 13:54:26.026 INFO  --- [io-8800-exec-10]  c.p.c.c.service.redis.impl.RedisServiceImpl        : 关键字：t-elc-xf-pm-tsgjwz 查询结束
来了老弟? 2021-05-10 13:54:26.026 INFO  --- [io-8800-exec-10]  c.p.c.c.service.business.impl.QueryServiceImpl     : 在redis中查询表：t-elc-xf-pm-tsgjwz 版本：0.2 结束
来了老弟? 2021-05-10 13:54:26.026 INFO  --- [nio-8800-exec-2]  c.p.cms.configcenter.controller.QueryController    : 正在查询表：t-elc-xf-gjk中的配置文件
来了老弟? 2021-05-10 13:54:26.026 INFO  --- [nio-8800-exec-2]  c.p.c.c.service.redis.impl.RedisServiceImpl        : 关键字：t-elc-xf-gjk 查询结束
来了老弟? 2021-05-10 13:54:26.026 INFO  --- [nio-8800-exec-2]  c.p.c.c.service.business.impl.QueryServiceImpl     : 在redis中查询表：t-elc-xf-gjk 版本：0.2 结束
来了老弟? 2021-05-10 13:54:31.031 INFO  --- [nio-8800-exec-4]  c.p.cms.configcenter.controller.QueryController    : 正在查询表：t-elc-xf-pm-tsgjwz中的配置文件
来了老弟? 2021-05-10 13:54:31.031 INFO  --- [nio-8800-exec-4]  c.p.c.c.service.redis.impl.RedisServiceImpl        : 关键字：t-elc-xf-pm-tsgjwz 查询结束
来了老弟? 2021-05-10 13:54:31.031 INFO  --- [nio-8800-exec-4]  c.p.c.c.service.business.impl.QueryServiceImpl     : 在redis中查询表：t-elc-xf-pm-tsgjwz 版本：0.2 结束
来了老弟? 2021-05-10 13:54:31.031 INFO  --- [nio-8800-exec-6]  c.p.cms.configcenter.controller.QueryController    : 正在查询表：t-elc-xf-gjk中的配置文件
来了老弟? 2021-05-10 13:54:32.032 INFO  --- [nio-8800-exec-6]  c.p.c.c.service.redis.impl.RedisServiceImpl        : 关键字：t-elc-xf-gjk 查询结束
来了老弟? 2021-05-10 13:54:32.032 INFO  --- [nio-8800-exec-6]  c.p.c.c.service.business.impl.QueryServiceImpl     : 在redis中查询表：t-elc-xf-gjk 版本：0.2 结束
来了老弟? 2021-05-10 13:54:52.052 INFO  --- [nio-8800-exec-8]  c.p.cms.configcenter.controller.QueryController    : 正在查询表：t-elc-xf-pm-tsgjwz中的配置文件
来了老弟? 2021-05-10 13:54:54.054 ERROR --- [nio-8800-exec-8]  c.p.c.c.service.redis.impl.RedisServiceImpl        : 获取redis失败
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
	at cn.hutool.db.nosql.redis.RedisDS.getJedis(RedisDS.java:135)
	at com.pinlan.cms.configcenter.service.redis.impl.RedisServiceImpl.getAll(RedisServiceImpl.java:27)
	at com.pinlan.cms.configcenter.service.business.impl.QueryServiceImpl.getConfigByTableName(QueryServiceImpl.java:36)
	at com.pinlan.cms.configcenter.controller.QueryController.queryAll(QueryController.java:37)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.pinlan.cms.core.config.CrossOriginConfig.doFilter(CrossOriginConfig.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to ai-zht-dev.pinlandata.com:6379
	at redis.clients.jedis.Connection.connect(Connection.java:165)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:109)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1904)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:130)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:918)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:431)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:356)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 63 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:53)
	at redis.clients.jedis.Connection.connect(Connection.java:158)
	... 70 common frames omitted

```
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
提示很明确啊：

```
Failed connecting to ai-zht-dev.pinlandata.com:6379
connect timed out
```

服务器连不上。
