### ISSUE TITLE
excel操作工具类的包同时引用commons-collections4包会报错

### ISSUE THREAD

**Issue by zzb980881** [looly/hutool#1571]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.6.0（请确保最新尝试是否还有问题）

### 问题描述  excel工具类的包hutool-poi，添加commons-collections4的包后会报错

![图片](https://user-images.githubusercontent.com/1118228/117752672-c9a01380-b249-11eb-9ca8-dee9ea6721bf.png)

1. 复现代码

pom文件添加以下内容

```java
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-collections4</artifactId>
	<version>4.0</version>
 </dependency>
```
2. 堆栈信息
cn.hutool.core.exceptions.DependencyException: You need to add dependency of 'poi-ooxml' to your project, and version >= 4.1.2

	at cn.hutool.poi.excel.ExcelUtil.getWriter(ExcelUtil.java:433)
	at cn.hutool.poi.excel.ExcelWriteTest.writeTest2(ExcelWriteTest.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.ListValuedMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:156)
	at cn.hutool.poi.excel.WorkbookUtil.createBookForWriter(WorkbookUtil.java:72)
	at cn.hutool.poi.excel.ExcelWriter.<init>(ExcelWriter.java:160)
	at cn.hutool.poi.excel.ExcelWriter.<init>(ExcelWriter.java:141)
	at cn.hutool.poi.excel.ExcelWriter.<init>(ExcelWriter.java:118)
	at cn.hutool.poi.excel.ExcelUtil.getWriter(ExcelUtil.java:431)
	... 26 more

**Comment by zzb980881** [comment]
问题找到了，collections4版本的问题，poi4.1.2用的collections是4.4版本，改成一致就可以了
