### ISSUE TITLE
Android  NoClassDefFoundError: java.beans.Transient

### ISSUE THREAD

**Issue by zxavier94** [looly/hutool#1580]
### 版本情况

JDK版本：    jdk1.8.0_281
hutool版本： hutool-all-5.6.5

### 问题描述
develop Android App，when convert json string to java bean,the app will crash.

app  build.gradle
plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {

        applicationId "cn.xxx.yy"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.github.bumptech.glide:glide:3.7.0'

    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation('com.google.android.libraries.places:places:1.0.0') {
        exclude module: 'glide'
    }

    implementation 'com.balysv:material-ripple:1.0.2'

    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'

    // https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit
    implementation group: 'com.squareup.retrofit2', name: 'retrofit', version: '2.9.0'

    // https://mvnrepository.com/artifact/cn.hutool/hutool-all
    implementation group: 'cn.hutool', name: 'hutool-all', version: '5.6.5'

    compileOnly 'org.projectlombok:lombok:1.18.16'
    annotationProcessor 'org.projectlombok:lombok:1.18.16'

    testCompileOnly 'org.projectlombok:lombok:1.18.16'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.16'

}

1. 复现代码

```java
import org.apache.commons.lang3.StringUtils;

import cn.hutool.json.JSONUtil;
import lombok.Data;

@Data
public class RespData {

    private String code;

    private String action;

    private String msg;

    private String data;

//    private T dataBean;

    public static RespData getFromJson(String json) {
        if(StringUtils.isBlank(json)) {
            return null;
        }
        return JSONUtil.toBean(json, RespData.class);  // happen error 
    }
}
```

2. 堆栈信息
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: cn.xxx.yy, PID: 7181
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Transient;
        at cn.hutool.core.bean.PropDesc.isTransientForSet(PropDesc.java:375)
        at cn.hutool.core.bean.PropDesc.isWritable(PropDesc.java:205)
        at cn.hutool.core.bean.copier.BeanCopier.lambda$valueProviderToBean$1$BeanCopier(BeanCopier.java:229)
        at cn.hutool.core.bean.copier.-$$Lambda$BeanCopier$yl6h0A9kRR_luuWldipHcU61VaI.accept(Unknown Source:13)
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:643)
        at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:181)
        at cn.hutool.core.bean.copier.BeanCopier.valueProviderToBean(BeanCopier.java:228)
        at cn.hutool.core.bean.copier.BeanCopier.mapToBean(BeanCopier.java:133)
        at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:102)
        at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:78)
        at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
        at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:273)
        at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:292)
        at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:730)
        at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:80)
        at cn.hutool.json.JSON.toBean(JSON.java:185)
        at cn.hutool.json.JSON.toBean(JSON.java:172)
        at cn.hutool.json.JSON.toBean(JSON.java:148)
        at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:435)
        at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:423)
        at cn.xxx.yy.model.resp.RespData.getFromJson(RespData.java:25)
        at cn.xxx.yy.activity.login.LoginActivity$1.run(LoginActivity.java:70)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.beans.Transient" on path: DexPathList[[zip file "/data/app/cn.xxx.yy-yik0hdI3gtvh0f1RgF6Tag==/base.apk"],nativeLibraryDirectories=[/data/app/cn.xxx.yy-yik0hdI3gtvh0f1RgF6Tag==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at cn.hutool.core.bean.PropDesc.isTransientForSet(PropDesc.java:375) 
        at cn.hutool.core.bean.PropDesc.isWritable(PropDesc.java:205) 
        at cn.hutool.core.bean.copier.BeanCopier.lambda$valueProviderToBean$1$BeanCopier(BeanCopier.java:229) 
        at cn.hutool.core.bean.copier.-$$Lambda$BeanCopier$yl6h0A9kRR_luuWldipHcU61VaI.accept(Unknown Source:13) 
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:643) 
        at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:181) 
        at cn.hutool.core.bean.copier.BeanCopier.valueProviderToBean(BeanCopier.java:228) 
        at cn.hutool.core.bean.copier.BeanCopier.mapToBean(BeanCopier.java:133) 
        at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:102) 
        at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:78) 
        at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58) 
        at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:273) 
        at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:292) 
        at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:730) 
        at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:80) 
        at cn.hutool.json.JSON.toBean(JSON.java:185) 
        at cn.hutool.json.JSON.toBean(JSON.java:172) 
        at cn.hutool.json.JSON.toBean(JSON.java:148) 
        at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:435) 
        at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:423) 
        at cn.xxx.yy.model.resp.RespData.getFromJson(RespData.java:25) 
        at cn.xxx.yy.activity.login.LoginActivity$1.run(LoginActivity.java:70) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by zxavier94** [comment]
请大佬指示一二

**Comment by looly** [comment]
安卓没有测试过，是不是你Android的版本太低导致的？缺的类是jdk本身的类。
