### ISSUE TITLE
POI 模块是否需要用户自己添加依赖？

### ISSUE THREAD

**Issue by ReachKing** [looly/hutool#160]
ExcelReader reader = ExcelUtil.getReader(path, 0);

`Exception in thread "main" cn.hutool.core.exceptions.DependencyException: NoClassDefFoundError: org/apache/poi/ss/usermodel/WorkbookFactory
	at cn.hutool.poi.PoiChecker.transError(PoiChecker.java:36)
	at cn.hutool.poi.excel.ExcelUtil.getReader(ExcelUtil.java:211)
	at com.tech.util.POIUtils.readExcel(POIUtils.java:17)
	at com.TestAll.main(TestAll.java:34)`

**Comment by looly** [comment]
是滴，请看文档：

[http://hutool.mydoc.io/#text_319507](http://hutool.mydoc.io/#text_319507)
