### ISSUE TITLE
 ZipUtil 不同目录下存在同名文件时异常

### ISSUE THREAD

**Issue by JackNo2018** [looly/hutool#1616]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.6

### 问题描述（包括截图）

当我使用 ZipUtil 时遇到一个问题 , **不同目录下存在同名文件时**会抛出异常

test 目录结构
.
├── zip1
│   ├── t1
│   │   └── a.txt
│   └── t2
│       └── a.txt
├── zip2
│   └── t1
│       └── a.txt
└── zipxx

1. 复现代码

```java

File file1 = new File("D:\\test\\zip1\\t1");
File file2 = new File("D:\\test\\zip2\\t1");
File zipFile = new File("D:\\test\\t.zip");
ZipUtil.zip(zipFile, true, file1,file2);

```

2. 堆栈信息
```java

Exception in thread "main" cn.hutool.core.io.IORuntimeException: ZipException: duplicate entry: t1/a.txt
	at cn.hutool.core.util.ZipUtil.add(ZipUtil.java:1114)
	at cn.hutool.core.util.ZipUtil.add(ZipUtil.java:1095)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:1081)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:1077)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:262)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:235)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:215)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:196)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:182)
Caused by: java.util.zip.ZipException: duplicate entry: t1/a.txt
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
	at cn.hutool.core.util.ZipUtil.add(ZipUtil.java:1111)

```

**Comment by looly** [comment]
逻辑是这样的，当第二个参数为true的时候，会保留被打包目录的目录为路径，但是只会获取上一级目录，所以：

`D:\\test\\zip1\\t1`会变成`t1/****`
`D:\\test\\zip2\\t1`也会变成`t1/****`

就重复了。

你可以使用` zip(File zipFile, Charset charset, boolean withSrcDir, FileFilter filter, File... srcFiles)`自定义过滤器过滤自己需要的
