### ISSUE TITLE
XmlUtil.xmlToBean转换失败

### ISSUE THREAD

**Issue by anaer** [looly/hutool#1663]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.1

### 问题描述（包括截图）

1. 复现代码

```java

import java.util.List;
import java.util.Map;

import com.alibaba.fastjson.JSON;

import org.w3c.dom.Document;

import cn.hutool.core.bean.BeanUtil;
import cn.hutool.core.util.XmlUtil;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class XmlUtilTest {

    public static void main(String[] args) {
        String xmlStr = "<?xml version=\"1.0\" encoding=\"gbk\" ?><response><code>02</code></response>";
        // String xmlStr = "<?xml version=\"1.0\" encoding=\"gbk\" ?><response><code>02</code><message></message></response>";

        Document doc = XmlUtil.parseXml(xmlStr);

        Map<String, Object> map = XmlUtil.xmlToMap(doc.getFirstChild());
        SmsRes res = new SmsRes();
        BeanUtil.fillBeanWithMap(map, res, true);

        SmsRes res1 = XmlUtil.xmlToBean(doc.getFirstChild(), SmsRes.class);

        log.info("预期: {}", JSON.toJSONString(res, true));
        log.info("实际: {}", JSON.toJSONString(res1, true));
    }

}

@Data
class SmsRes {
    /**
     * 状态码.
     */
    private String code;

    /**
    * 消息列表.
    */
    private List<Message> message;
}

@Data
class Message {
    /**
     * 手机号.
     */
    private String desmobile;
    /**
    * 消息id.
    */
    private String msgid;
}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/4637100/122512298-3f628080-d03b-11eb-9dc8-6269572d83e1.png)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
问题出在这句话：

```java
if (null != map && map.size() == 1) {
	return BeanUtil.toBean(map.get(bean.getSimpleName()), bean);
}
```

当map中只有一个节点的时候，会被当成单一对象。

这个逻辑有问题，5.7.2修复此问题，感谢。

**Comment by Rain-Chen** [comment]
对BUG进行修改，修改两个模型为以下模型：
```
@Data
class SmsRes {
    /**
     * 状态码.
     */
    private String code;

    /**
    * 消息.
    */
    private Message message;
}

@Data
class Message {
    
	/**
     * 消息项.
     */
	private List<MessageItem> item = new ArrayList<>();
}

@Data
class MessageItem {

	/**
     * 手机号.
     */
    private String desmobile;
    /**
     * 消息id.
     */
    private String msgid;
}
```
使用相同测试用例
1、```String xmlStr = "<?xml version=\"1.0\" encoding=\"gbk\" ?><response><code>02</code></response>";``` 测试通过
2、```String xmlStr = "<?xml version=\"1.0\" encoding=\"gbk\" ?><response><code>02</code><message></message></response>"; ```异常
异常栈：
```
Exception in thread "main" cn.hutool.core.convert.ConvertException: Unsupported source type: class java.lang.String
	at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:84)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:228)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:247)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:753)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:92)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:349)
	at cn.hutool.core.bean.copier.MapToBeanCopier.lambda$copy$0(MapToBeanCopier.java:91)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at cn.hutool.core.bean.copier.MapToBeanCopier.copy(MapToBeanCopier.java:60)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:771)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:567)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:549)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:505)
	at cn.hutool.core.util.XmlUtil.xmlToBean(XmlUtil.java:991)
```
使用5.8.19版本
