### ISSUE TITLE
ExcelUtil.getBigWriter加载大数据excel会爆内存

### ISSUE THREAD

**Issue by kiddkyd2** [looly/hutool#1675]
### 版本情况

JDK版本：    openjdk_11+28
hutool版本： 5.6.5

### 问题描述（包括截图）

这是一个90w行，大小是50m的excel。已经配置了Xmx3g，依然挤爆jvm。看了ExcelUtil.getBigWriter的new过程，大致是先createXSS，然后再转SXSS。但是在createXSS的时候就已经爆内存了，根本去不到toSXSS的逻辑。

1. 复现代码

```java
BigExcelWriter writer= ExcelUtil.getBigWriter("e:/xxx.xlsx");
```

2. 堆栈信息
`cn.hutool.poi.exceptions.POIException: IOException: Java heap space
        at cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:86)
        at cn.hutool.poi.excel.WorkbookUtil.createSXSSFBook(WorkbookUtil.java:194)
        at cn.hutool.poi.excel.WorkbookUtil.createSXSSFBook(WorkbookUtil.java:182)`
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
SXSSFWorkbook的性质决定了最好不要读取已有的文件，就算成功读取，也有可能写出报错。

这个暂时没法规避，欢迎提供思路。
