### ISSUE TITLE
Java 11运行下报java.lang.NoClassDefFoundError: Could not initialize class cn.hutool.http.HttpConnection

### ISSUE THREAD

**Issue by EarnestLee** [looly/hutool#169]
java.lang.NoClassDefFoundError: Could not initialize class cn.hutool.http.HttpConnection
	at cn.hutool.http.HttpRequest.initConnecton(HttpRequest.java:685) ~[hutool-all-4.0.12.jar!/:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:648) ~[hutool-all-4.0.12.jar!/:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:625) ~[hutool-all-4.0.12.jar!/:na]

原因使用了sun/reflect/Reflection这个类，11版本已废弃
java.lang.NoClassDefFoundError: sun/reflect/Reflection
	at cn.hutool.core.lang.Caller$ReflectionCaller.getCallerCaller(Caller.java:184) ~[hutool-all-4.0.12.jar!/:na]
	at cn.hutool.core.lang.Caller.getCallerCaller(Caller.java:32) ~[hutool-all-4.0.12.jar!/:na]
	at cn.hutool.log.LogFactory.get(LogFactory.java:164) ~[hutool-all-4.0.12.jar!/:na]
	at cn.hutool.http.HttpConnection.<clinit>(HttpConnection.java:40) ~[hutool-all-4.0.12.jar!/:na]
	at cn.hutool.http.HttpRequest.initConnecton(HttpRequest.java:685) ~[hutool-all-4.0.12.jar!/:na]

**Comment by looly** [comment]
请升级到4.1.14，新版解决了此类问题。

**Comment by EarnestLee** [comment]
升了还是不行，麻烦再确定下

**Comment by CodinngLee** [comment]
java.lang.NoClassDefFoundError: sun/reflect/Reflection
	at cn.hutool.core.lang.caller.ReflectionCaller.getCallerCaller(ReflectionCaller.java:22) ~[hutool-all-4.1.15.jar!/:na]
	at cn.hutool.core.lang.caller.CallerUtil.getCallerCaller(CallerUtil.java:30) ~[hutool-all-4.1.15.jar!/:na]
	at cn.hutool.log.LogFactory.get(LogFactory.java:164) ~[hutool-all-4.1.15.jar!/:na]
	at cn.hutool.http.HttpConnection.<clinit>(HttpConnection.java:40) ~[hutool-all-4.1.15.jar!/:na]
	at cn.hutool.http.HttpRequest.initConnecton(HttpRequest.java:837) ~[hutool-all-4.1.15.jar!/:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:800) ~[hutool-all-4.1.15.jar!/:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:777) ~[hutool-all-4.1.15.jar!/:na]
