### ISSUE TITLE
ftp工具类中的exist方法不能判断目录是否存在

### ISSUE THREAD

**Issue by caoyuzheng** [looly/hutool#1716]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
extra包下面的ftp工具类中，cn.hutool.extra.ftp.AbstractFtp#exist 这个方法只可以判断文件是否存在，不能判断目录是否存在
当目录已存在，并且有文件后缀时，该方法会返回false

1. 复现代码
``` java
String ftpPath = "/dev/test/";
try {
    if (!ftp.exist(ftpPath)) {
        ftp.mkdir(ftpPath);
    }
} catch (Exception e) {
    e.printStackTrace();
}
```
2. 堆栈信息
``` java
cn.hutool.extra.ssh.JschRuntimeException: SftpException: Failure
	at cn.hutool.extra.ssh.Sftp.mkdir(Sftp.java:324)
        ... ...
        ... ...
	at java.lang.Thread.run(Thread.java:748)
Caused by: 4: Failure
	at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2873)
	at com.jcraft.jsch.ChannelSftp.mkdir(ChannelSftp.java:2182)
	at cn.hutool.extra.ssh.Sftp.mkdir(Sftp.java:321)
	... 7 more
```

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by caoyuzheng** [comment]
建议在创建目录方法中cn.hutool.extra.ftp.AbstractFtp#mkdir，判断该目录如果存在，直接返回

**Comment by looly** [comment]
按理说这个逻辑没有问题，这个还需要具体测试。

逻辑是找到上级目录，然后执行ls命令，遍历之再查找是否有最后一个名字。

暂时的解决是在`mkdir`方法前加isDir方法判断下：

```java
final SftpATTRS sftpATTRS;
try {
	sftpATTRS = this.channel.stat(dir);
} catch (SftpException e) {
	throw new FtpException(e);
}
return sftpATTRS.isDir();
```
