### ISSUE TITLE
读取excel数据，返回实体类列表，当excel中date类型列为空时报错

### ISSUE THREAD

**Issue by justfeizai** [looly/hutool#1729]
### 版本情况

JDK版本：    jdk1.8.0_291
[UserProjectDO.xlsx](https://github.com/dromara/hutool/files/6882569/UserProjectDO.xlsx)

hutool版本： 5.7.5

### 问题描述（包括截图）
ExcelReader.read(int headerRowIndex, int startRowIndex, Class<T> beanType)   
将excel数据读取成一个对象数据，当excel中的date类型列为空时，会报错（应该读出来null就行）
![image](https://user-images.githubusercontent.com/51252438/127092774-df660185-6d93-443c-a647-5c189e815b59.png)
![image](https://user-images.githubusercontent.com/51252438/127092822-a350153e-19b7-4ca3-8d19-a36071fa71a5.png)

 堆栈信息
 java.lang.UnsupportedOperationException: Unsupport Date type: java.sql.Date
	at cn.hutool.core.convert.impl.DateConverter.convertInternal(DateConverter.java:82)
	at cn.hutool.core.convert.impl.DateConverter.convertInternal(DateConverter.java:18)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:254)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:295)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:745)
	at cn.hutool.core.bean.copier.provider.MapValueProvider.value(MapValueProvider.java:66)
	at cn.hutool.core.bean.copier.provider.MapValueProvider.value(MapValueProvider.java:24)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$valueProviderToBean$1(BeanCopier.java:255)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:181)
	at cn.hutool.core.bean.copier.BeanCopier.valueProviderToBean(BeanCopier.java:228)
	at cn.hutool.core.bean.copier.BeanCopier.mapToBean(BeanCopier.java:133)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:102)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:712)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:552)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:504)
	at cn.hutool.poi.excel.reader.BeanSheetReader.read(BeanSheetReader.java:45)
	at cn.hutool.poi.excel.reader.BeanSheetReader.read(BeanSheetReader.java:17)
	at cn.hutool.poi.excel.ExcelReader.read(ExcelReader.java:373)
	at cn.hutool.poi.excel.ExcelReader.read(ExcelReader.java:360)
	at cn.hutool.poi.excel.ExcelReader.read(ExcelReader.java:342)

**Comment by justfeizai** [comment]
还有一个问题，读取excle会返回cn.hutool.core.date.DateTime，这个set实体类的Date属性（java.sql.Date）也是会报错的，这个要怎么处理比较好。谢谢

**Comment by looly** [comment]
确认bug。

5.7.6修复此问题，感谢。

bug原因如下：
1. 单元格读取出的空数据为""而非null，导致转换出错，bug修复方式为忽略错误赋值为null。
2. 读取Excel类型为java.sql.Date是类型读取错误导致转换错误导致的，这是另一个bug。

再次感谢一个issue修复两个bug~~

**Comment by justfeizai** [comment]
@looly 非常感谢
