### ISSUE TITLE
停止Web服务时，hutool-db的DSFactory执行destroy异常

### ISSUE THREAD

**Issue by luo201227** [looly/hutool#173]
`log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.XmlWebApplicationContext).
log4j:WARN Please initialize the log4j system properly.
06-Oct-2018 09:23:38.290 警告 [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
06-Oct-2018 09:23:38.290 警告 [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
06-Oct-2018 09:23:38.309 信息 [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
06-Oct-2018 09:23:38.394 信息 [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-8009"]
06-Oct-2018 09:23:38.396 信息 [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
06-Oct-2018 09:23:38.398 信息 [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-8009"]
Exception in thread "Thread-13" java.lang.NoClassDefFoundError: cn/hutool/core/collection/CollectionUtil
	at cn.hutool.db.ds.druid.DruidDSFactory.destroy(DruidDSFactory.java:75)
	at cn.hutool.db.ds.GlobalDSFactory$1.run(GlobalDSFactory.java:27)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [cn.hutool.core.collection.CollectionUtil]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1343)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1206)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
	... 2 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [cn.hutool.core.collection.CollectionUtil]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1353)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1341)
	... 4 more`

**Comment by luo201227** [comment]
![qq 20181006093146](https://user-images.githubusercontent.com/16028168/46566071-b7032680-c94a-11e8-9b82-da1632ee0928.png)
[ex.log](https://github.com/looly/hutool/files/2452635/ex.log)

**Comment by looly** [comment]
服务（JVM）已停止，不必单独停止Factory了。
