### ISSUE TITLE
HttpUtil 响应头：Content-encoding:deflate

### ISSUE THREAD

**Issue by Mr-SYGao** [looly/hutool#1732]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.5

### 问题描述（包括截图）

使用HttpUtil.get()，通过postman测试，响应头Content-encoding:deflate

堆栈信息
```java
cn.hutool.http.HttpException: ZipException: invalid stored block lengths
	at cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:502) ~[hutool-all-5.7.5.jar:na]
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:451) ~[hutool-all-5.7.5.jar:na]
	at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:396) ~[hutool-all-5.7.5.jar:na]
	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:76) ~[hutool-all-5.7.5.jar:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:966) ~[hutool-all-5.7.5.jar:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:930) ~[hutool-all-5.7.5.jar:na]
```

**Comment by Mr-SYGao** [comment]
> ### 版本情况
> JDK版本： openjdk_8_201
> hutool版本： 5.7.5
> 
> ### 问题描述（包括截图）
> 使用HttpUtil.get(请求地址)报错，通过postman测试，响应头Content-encoding:deflate
> 
> 堆栈信息
> 
> ```java
> cn.hutool.http.HttpException: ZipException: invalid stored block lengths
> 	at cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:502) ~[hutool-all-5.7.5.jar:na]
> 	at cn.hutool.http.HttpResponse.init(HttpResponse.java:451) ~[hutool-all-5.7.5.jar:na]
> 	at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:396) ~[hutool-all-5.7.5.jar:na]
> 	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:76) ~[hutool-all-5.7.5.jar:na]
> 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:966) ~[hutool-all-5.7.5.jar:na]
> 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:930) ~[hutool-all-5.7.5.jar:na]
> ```
