### ISSUE TITLE
4.1.15版本在Java 11运行下仍然报java.lang.NoClassDefFoundError: Could not initialize class cn.hutool.http.HttpConnection question

### ISSUE THREAD

**Issue by EarnestLee** [looly/hutool#174]
java.lang.NoClassDefFoundError: sun/reflect/Reflection
at cn.hutool.core.lang.caller.ReflectionCaller.getCallerCaller(ReflectionCaller.java:22) ~[hutool-all-4.1.15.jar!/:na]
at cn.hutool.core.lang.caller.CallerUtil.getCallerCaller(CallerUtil.java:30) ~[hutool-all-4.1.15.jar!/:na]
at cn.hutool.log.LogFactory.get(LogFactory.java:164) ~[hutool-all-4.1.15.jar!/:na]
at cn.hutool.http.HttpConnection.(HttpConnection.java:40) ~[hutool-all-4.1.15.jar!/:na]
at cn.hutool.http.HttpRequest.initConnecton(HttpRequest.java:837) ~[hutool-all-4.1.15.jar!/:na]
at cn.hutool.http.HttpRequest.execute(HttpRequest.java:800) ~[hutool-all-4.1.15.jar!/:na]
at cn.hutool.http.HttpRequest.execute(HttpRequest.java:777) ~[hutool-all-4.1.15.jar!/:na]

**Comment by looly** [comment]
4.1.16修复此问题，十分感谢。

**Comment by CodinngLee** [comment]
> 4.1.16修复此问题，十分感谢。

 @这周赶得出不？准备在11上生产了

**Comment by looly** [comment]
今晚发布新版

**Comment by EarnestLee** [comment]
> 今晚发布新版

你太6了

**Comment by EarnestLee** [comment]
> 今晚发布新版

4.1.16还是没解决呀
