### ISSUE TITLE
偶现patch不支持

### ISSUE THREAD

**Issue by mengxzh** [looly/hutool#1742]
### 版本情况

JDK版本：   openjdk8 "1.8.0_161"
hutool版本： hutool-all-5.7.5

### 问题描述（包括截图）

1. 复现代码
偶现

2. 堆栈信息
hutool部分堆栈信息如下: 
```java
 java.net.ProtocolException: Invalid HTTP method: PATCH
        at java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:440)
        at sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLConnection.java:552)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestMethod(HttpsURLConnectionImpl.java:383)
        at cn.hutool.http.HttpConnection.setMethod(HttpConnection.java:129)
        at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1059)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:957)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:930)
```

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
如果是偶尔出现，考虑是不是引入多版本冲突导致的？

**Comment by mengxzh** [comment]
@looly 是什么的多版本呢...hutool的版本就只用了5.7.5的

**Comment by looly** [comment]
因为这里之前的版本存在patch不支持的bug，很有可能你项目里有多个版本的hutool，导致有时候用的旧包，有时候用的新包。

麻烦日志下报错的URL，然后单独test试下。

**Comment by amosnothing** [comment]
> 因为这里之前的版本存在patch不支持的bug，很有可能你项目里有多个版本的hutool，导致有时候用的旧包，有时候用的新包。
> 
> 麻烦日志下报错的URL，然后单独test试下。

hello 我在新版本也出现了 5.7.16 确定只引入了一个 hutool
