### ISSUE TITLE
JSONUtil序列化枚举类型报错

### ISSUE THREAD

**Issue by JiangGuangxing** [looly/hutool#1753]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.7

### 问题描述（包括截图）

1. 复现代码

```java
        System.out.println(JSONUtil.toJsonStr(CaseStatusEnum.INIT));
```

2. 堆栈信息
Exception in thread "main" cn.hutool.json.JSONException: Unsupported type [class com.leya.sytpa.enums.CaseStatusEnum] to JSONObject!
	at cn.hutool.json.JSONObject.init(JSONObject.java:631)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:200)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:233)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:204)
	at cn.hutool.json.JSONUtil.toJsonStr(JSONUtil.java:358)
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
CaseStatusEnum的class可否贴一下。应该是转换错误导致的。

可以考虑实现JSONString接口即可。
