### ISSUE TITLE
Hutool的Http客户端获取body内容错误

### ISSUE THREAD

**Issue by PlayerYao** [looly/hutool#1766]
### 版本情况

JDK版本：    openjdk_11.0.12
hutool版本： 5.7.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
用hutool请求第三方api`https://api.acplay.net/api/v2/bangumi/9541`时返回的body字符串丢失了一部分导致json格式化出错

1. 复现代码
调用方法
```java
@Test
    void testGetBangumi() {
        Bangumi bangumi = BangumiApi.getBangumi(9541);
        System.out.println(JSONUtil.toJsonStr(bangumi));
    }
```
方法详情
```java
public static Bangumi getBangumi(int animeId) {
        String body = HttpUtil.get("https://api.acplay.net/api/v2/bangumi/" + animeId);
        if (StrUtil.isBlankIfStr(body)) {
            throw new RuntimeException("请求番剧详情接口失败");
        }
        System.out.println(body);
        Anime anime = JSONUtil.toBean(body, Anime.class);
        if (!Boolean.TRUE.equals(anime.getSuccess())) {
            throw new RuntimeException("请求番剧详情接口失败,错误信息" + anime);
        }
        return anime.getBangumi();
    }
```
在将字符串反序列换为java Bean时出错,即`Anime anime = JSONUtil.toBean(body, Anime.class);`
2. 堆栈信息
```bash
cn.hutool.json.JSONException: Unterminated string at 3478 [character 3479 line 1]

	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
	at cn.hutool.json.JSONTokener.nextString(JSONTokener.java:233)
	at cn.hutool.json.JSONTokener.nextValue(JSONTokener.java:329)
	at cn.hutool.json.JSONObject.init(JSONObject.java:696)
	at cn.hutool.json.JSONObject.init(JSONObject.java:622)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:200)
	at cn.hutool.json.JSONTokener.nextValue(JSONTokener.java:332)
	at cn.hutool.json.JSONObject.init(JSONObject.java:696)
	at cn.hutool.json.JSONObject.init(JSONObject.java:663)
	at cn.hutool.json.JSONObject.init(JSONObject.java:619)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:200)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:176)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:158)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:141)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:88)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:407)
	at tk.justyao.animedatacapture.ddplay.api.BangumiApi.getBangumi(BangumiApi.java:28)
	at tk.justyao.animedatacapture.AnimeDataCaptureApplicationTests.testGetBangumi(AnimeDataCaptureApplicationTests.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

```

3. 测试涉及到的文件（注意脱密）
`Anime.java`这个类我就不传了,跟套娃一样很多层,这是错误的body字符串
```text
{"bangumi":{"type":"tvseries","typeDescription":"TV动画","episodes":[{"episodeId":95410001,"episodeTitle":"第1话 二千年後の君へ シガンシナ陥落①","episodeNumber":"1","lastWatched":null,"airDate":"2013-04-07T00:00:00"},{"episodeId":95410002,"episodeTitle":"第2话 その日 シガンシナ陥落②","episodeNumber":"2","lastWatched":null,"airDate":"2013-04-14T00:00:00"},{"episodeId":95410003,"episodeTitle":"第3话 絶望の中で鈍く光る 人類の再起①","episodeNumber":"3","lastWatched":null,"airDate":"2013-04-21T00:00:00"},{"episodeId":95410004,"episodeTitle":"第4话 解散式の夜 人類の再起②","episodeNumber":"4","lastWatched":null,"airDate":"2013-04-28T00:00:00"},{"episodeId":95410005,"episodeTitle":"第5话 初陣 トロスト区攻防戦①","episodeNumber":"5","lastWatched":null,"airDate":"2013-05-05T00:00:00"},{"episodeId":95410006,"episodeTitle":"第6话 少女が見た世界 トロスト区攻防戦②","episodeNumber":"6","lastWatched":null,"airDate":"2013-05-12T00:00:00"},{"episodeId":95410007,"episodeTitle":"第7话 小さな刃 トロスト区攻防戦③","episodeNumber":"7","lastWatched":null,"airDate":"2013-05-19T00:00:00"},{"episodeId":95410008,"episodeTitle":"第8话 心臓の鼓動が聞こえる トロスト区攻防戦④","episodeNumber":"8","lastWatched":null,"airDate":"2013-05-26T00:00:00"},{"episodeId":95410009,"episodeTitle":"第9话 左腕の行方 トロスト区攻防戦⑤","episodeNumber":"9","lastWatched":null,"airDate":"2013-06-02T00:00:00"},{"episodeId":95410010,"episodeTitle":"第10话 応える トロスト区攻防戦⑥","episodeNumber":"10","lastWatched":null,"airDate":"2013-06-09T00:00:00"},{"episodeId":95410011,"episodeTitle":"第11话 偶像 トロスト区攻防戦⑦","episodeNumber":"11","lastWatched":null,"airDate":"2013-06-16T00:00:00"},{"episodeId":95410012,"episodeTitle":"第12话 傷 トロスト区攻防戦⑧","episodeNumber":"12","lastWatched":null,"airDate":"2013-06-23T00:00:00"},{"episodeId":95410013,"episodeTitle":"第13话 原初的欲求 トロスト区攻防戦⑨","episodeNumber":"13","lastWatched":null,"airDate":"2013-06-30T00:00:00"},{"episodeId":95410014,"episodeTitle":"第14话 まだ目を見れない 反撃前夜①","episodeNumber":"14","lastWatched":null,"airDate":"2013-07-14T00:00:00"},{"episodeId":95410015,"episodeTitle":"第15话 特別作戦班 反撃前夜②","episodeNumber":"15","lastWatched":null,"airDate":"2013-07-21T00:00:00"},{"episodeId":95410016,"episodeTitle":"第16话 今, 何をすべきか 反撃前夜③","episodeNumber":"16","lastWatched":null,"airDate":"2013-07-28T00:00:00"},{"episodeId":95410017,"episodeTitle":"第17话 女型の巨人 第57回壁外調査①","episodeNumber":"17","lastWatched":null,"airDate":"2013-08-04T00:00:00"},{"episodeId":95410018,"episodeTitle":"第18话 巨大樹の森 第57回壁外調査②","episodeNumber":"18","lastWatched":null,"airDate":"2013-08-11T00:00:00"},{"episodeId":95410019,"episodeTitle":"第19话 噛みつく 第57回壁外調査③","episodeNumber":"19","lastWatched":null,"airDate":"2013-08-18T00:00:00"},{"episodeId":95410020,"episodeTitle":"第20话 エルヴィン・スミス 第57回壁外調査④","episodeNumber":"20","lastWatched":null,"airDate":"2013-08-25T00:00:00"},{"episodeId":95410021,"episodeTitle":"第21话 鉄槌 第57回壁外調査⑤","episodeNumber":"21","lastWatched":null,"airDate":"2013-09-01T00:00:00"},{"episodeId":95410022,"episodeTitle":"第22话 敗者達 第57回壁外調査⑥","episodeNumber":"22","lastWatched":null,"airDate":"2013-09-08T00:00:00"},{"episodeId":95410023,"episodeTitle":"第23话 微笑み ストヘス区急襲①","episodeNumber":"23","lastWatched":null,"airDate":"2013-09-15T00:00:00"},{"episodeId":95410024,"episodeTitle":"第24话 慈悲 ストヘス区急襲②","episodeNumber":"24","lastWatched":null,"airDate":"2013-09-22T00:00:00"},{"episodeId":95410025,"episodeTitle":"第25话 壁 ストヘス区急襲③","episodeNumber":"25","lastWatched":null,"airDate":"2013-09-28T00:00:00"}],"summary":"悠长的历史之中,人类曾一度因被巨人捕食而崩溃。幸存下来的人们建造了一面巨大的墙壁,防止了巨人的入侵。不过,作为“和平”的代价,人类失去了到墙壁的外面去这一“自由”。主人公艾伦·耶格尔对还没见过的外面的世界抱有兴趣。在他正做着到墙壁的外面去�
```
正确的应该是这样(postman请求结果)
```json
{
    "bangumi": {
        "type": "tvseries",
        "typeDescription": "TV动画",
        "episodes": [
            {
                "episodeId": 95410001,
                "episodeTitle": "第1话 二千年後の君へ シガンシナ陥落①",
                "episodeNumber": "1",
                "lastWatched": null,
                "airDate": "2013-04-07T00:00:00"
            },
            {
                "episodeId": 95410002,
                "episodeTitle": "第2话 その日 シガンシナ陥落②",
                "episodeNumber": "2",
                "lastWatched": null,
                "airDate": "2013-04-14T00:00:00"
            },
            {
                "episodeId": 95410003,
                "episodeTitle": "第3话 絶望の中で鈍く光る 人類の再起①",
                "episodeNumber": "3",
                "lastWatched": null,
                "airDate": "2013-04-21T00:00:00"
            },
            {
                "episodeId": 95410004,
                "episodeTitle": "第4话 解散式の夜 人類の再起②",
                "episodeNumber": "4",
                "lastWatched": null,
                "airDate": "2013-04-28T00:00:00"
            },
            {
                "episodeId": 95410005,
                "episodeTitle": "第5话 初陣 トロスト区攻防戦①",
                "episodeNumber": "5",
                "lastWatched": null,
                "airDate": "2013-05-05T00:00:00"
            },
            {
                "episodeId": 95410006,
                "episodeTitle": "第6话 少女が見た世界 トロスト区攻防戦②",
                "episodeNumber": "6",
                "lastWatched": null,
                "airDate": "2013-05-12T00:00:00"
            },
            {
                "episodeId": 95410007,
                "episodeTitle": "第7话 小さな刃 トロスト区攻防戦③",
                "episodeNumber": "7",
                "lastWatched": null,
                "airDate": "2013-05-19T00:00:00"
            },
            {
                "episodeId": 95410008,
                "episodeTitle": "第8话 心臓の鼓動が聞こえる トロスト区攻防戦④",
                "episodeNumber": "8",
                "lastWatched": null,
                "airDate": "2013-05-26T00:00:00"
            },
            {
                "episodeId": 95410009,
                "episodeTitle": "第9话 左腕の行方 トロスト区攻防戦⑤",
                "episodeNumber": "9",
                "lastWatched": null,
                "airDate": "2013-06-02T00:00:00"
            },
            {
                "episodeId": 95410010,
                "episodeTitle": "第10话 応える トロスト区攻防戦⑥",
                "episodeNumber": "10",
                "lastWatched": null,
                "airDate": "2013-06-09T00:00:00"
            },
            {
                "episodeId": 95410011,
                "episodeTitle": "第11话 偶像 トロスト区攻防戦⑦",
                "episodeNumber": "11",
                "lastWatched": null,
                "airDate": "2013-06-16T00:00:00"
            },
            {
                "episodeId": 95410012,
                "episodeTitle": "第12话 傷 トロスト区攻防戦⑧",
                "episodeNumber": "12",
                "lastWatched": null,
                "airDate": "2013-06-23T00:00:00"
            },
            {
                "episodeId": 95410013,
                "episodeTitle": "第13话 原初的欲求 トロスト区攻防戦⑨",
                "episodeNumber": "13",
                "lastWatched": null,
                "airDate": "2013-06-30T00:00:00"
            },
            {
                "episodeId": 95410014,
                "episodeTitle": "第14话 まだ目を見れない 反撃前夜①",
                "episodeNumber": "14",
                "lastWatched": null,
                "airDate": "2013-07-14T00:00:00"
            },
            {
                "episodeId": 95410015,
                "episodeTitle": "第15话 特別作戦班 反撃前夜②",
                "episodeNumber": "15",
                "lastWatched": null,
                "airDate": "2013-07-21T00:00:00"
            },
            {
                "episodeId": 95410016,
                "episodeTitle": "第16话 今, 何をすべきか 反撃前夜③",
                "episodeNumber": "16",
                "lastWatched": null,
                "airDate": "2013-07-28T00:00:00"
            },
            {
                "episodeId": 95410017,
                "episodeTitle": "第17话 女型の巨人 第57回壁外調査①",
                "episodeNumber": "17",
                "lastWatched": null,
                "airDate": "2013-08-04T00:00:00"
            },
            {
                "episodeId": 95410018,
                "episodeTitle": "第18话 巨大樹の森 第57回壁外調査②",
                "episodeNumber": "18",
                "lastWatched": null,
                "airDate": "2013-08-11T00:00:00"
            },
            {
                "episodeId": 95410019,
                "episodeTitle": "第19话 噛みつく 第57回壁外調査③",
                "episodeNumber": "19",
                "lastWatched": null,
                "airDate": "2013-08-18T00:00:00"
            },
            {
                "episodeId": 95410020,
                "episodeTitle": "第20话 エルヴィン・スミス 第57回壁外調査④",
                "episodeNumber": "20",
                "lastWatched": null,
                "airDate": "2013-08-25T00:00:00"
            },
            {
                "episodeId": 95410021,
                "episodeTitle": "第21话 鉄槌 第57回壁外調査⑤",
                "episodeNumber": "21",
                "lastWatched": null,
                "airDate": "2013-09-01T00:00:00"
            },
            {
                "episodeId": 95410022,
                "episodeTitle": "第22话 敗者達 第57回壁外調査⑥",
                "episodeNumber": "22",
                "lastWatched": null,
                "airDate": "2013-09-08T00:00:00"
            },
            {
                "episodeId": 95410023,
                "episodeTitle": "第23话 微笑み ストヘス区急襲①",
                "episodeNumber": "23",
                "lastWatched": null,
                "airDate": "2013-09-15T00:00:00"
            },
            {
                "episodeId": 95410024,
                "episodeTitle": "第24话 慈悲 ストヘス区急襲②",
                "episodeNumber": "24",
                "lastWatched": null,
                "airDate": "2013-09-22T00:00:00"
            },
            {
                "episodeId": 95410025,
                "episodeTitle": "第25话 壁 ストヘス区急襲③",
                "episodeNumber": "25",
                "lastWatched": null,
                "airDate": "2013-09-28T00:00:00"
            }
        ],
        "summary": "悠长的历史之中,人类曾一度因被巨人捕食而崩溃。幸存下来的人们建造了一面巨大的墙壁,防止了巨人的入侵。不过,作为“和平”的代价,人类失去了到墙壁的外面去这一“自由”。主人公艾伦·耶格尔对还没见过的外面的世界抱有兴趣。在他正做着到墙壁的外面去这个梦的时候,毁坏墙壁的大巨人出现了！",
        "metadata": [
            "中文名: 进击的巨人",
            "话数: 25",
            "放送开始: 2013年4月6日",
            "放送星期: 星期六",
            "原作: 諫山創",
            "导演: 荒木哲郎",
            "脚本: 小林靖子、瀬古浩司、高木登",
            "分镜: 徳土大介、横山彰利、別所誠人、大原実、荒木哲郎、江崎慎平、若林信、山本秀世、田中洋之、肥塚正史、立川譲、笹嶋啓一、平田智浩、宮地昌幸、小松田大全",
            "演出: 若林信、藤原佳幸、田中洋之、荒木哲郎、肥塚正史、池田智美、徳土大介、山田弘和、室谷靖、別所誠人、江崎慎平、いとがしんたろー、福本潔、大西景介、立川譲、横山彰利、南川達馬、菊池聡延",
            "音乐: 澤野弘之",
            "人物设定: 浅野恭司、門脇聡",
            "系列构成: 小林靖子",
            "美术监督: 吉原俊一郎",
            "色彩设计: 橋本賢",
            "总作画监督: 千葉崇明、門脇聡、浅野恭司",
            "作画监督: 佐藤陽子、富田恵美、野崎真一、長谷川ひとみ、佐藤道雄、山崎輝彦、竹内昭、小野陽子、酒井智史、Kim Dae Hoon、西尾智恵、三宅雄一郎、山田歩、小泉初栄、村上龍一、田中春香、石井ゆみこ、藤田正幸、門脇聡、佐藤利幸、世良コータ、斉藤大輔、田中美穂、野村雅史、舘崎大、菊池聡延、山本祐子、工藤晃子、関口亮輔、浅野恭司、宮崎里美、河井淳、北田勝彦、手塚響平、宮井加奈、胡拓磨、星野玲香、服部一郎、柴田健児、長谷川亨雄、サトウミチオ、山村俊了、千葉崇明、清水勝祐、杉崎由佳",
            "摄影监督: 山田和弘",
            "道具设计: 肥塚正史",
            "原画: 北田勝彦、田中宏紀、梁博雅、藤井俊郎、胡拓磨、朱暁、徳土大介、なかじまちゅうじ、荒木裕、今井有文、小坂倫洋、越智信次、若林信、髙部光章、遠藤大輔、碇谷敦、三輪和宏、古俣拓磨、濱口明、千葉崇明、小柳達也、瀬口泉、森山洋、横山彰利、江原康之、孙猛、吉田健一、後藤雅巳、門脇聡、小林直樹、世良悠子、佐々木啓悟、塩谷直義、石浜真史、中川英樹、佐藤利幸、浅野恭司、中嶋敦子",
            "第二原画: 若林信、江原康之",
            "背景美术: 美峰",
            "剪辑: 肥田文",
            "主题歌编曲: Revo / 根岸貴幸、cinema staff・亀田誠治",
            "主题歌作曲: Revo / 石塚玲依、cinema staff",
            "主题歌作词: Revo / マイクスギヤマ、三島想平",
            "主题歌演出: Linked Horizon(Revo) / 日笠陽子、cinema staff",
            "企画: 丸山博雄",
            "录音: アオイスタジオ",
            "设定: 三輪清宗",
            "音响监督: 三間雅文",
            "音响: テクノサウンド",
            "音效: 倉橋静男、山谷尚人",
            "特效: 入佐芽詠美",
            "补间动画: 若林信",
            "制片人: 丸山博雄、前田俊博",
            "制作助手: 童夢、Production I.G",
            "制作: 「進撃の巨人」製作委員会(ポニーキャニオン / 講談社 / Production I.G / 電通 / ポニーキャニオンエンタープライズ)",
            "音乐制作: ポニーキャニオン",
            "动画制作: WIT STUDIO",
            "CG 导演: 籔田修平",
            "美术设计: 谷内優穂",
            "副导演: 肥塚正史、田中洋之",
            "OP・ED 分镜: 荒木哲郎、山本沙代、立川譲、石浜真史",
            "动作作画监督: 今井有文、佐藤誠之、江原康之、世良悠子",
            "别名: 自由之翼",
            "别名: 進擊的巨人",
            "别名: Attack on Titan",
            "别名: Shingeki no Kyojin",
            "官方网站: http://shingeki.tv",
            "播放电视台: MBS",
            "其他电视台: TOKYO MX / FBS / TOS / 北海道テレビ / テレビ愛知 / BS11",
            "播放结束: 2013年9月28日",
            "Copyright: ©諫山創・講談社／「進撃の巨人」製作委員会",
            "巨人设计: 千葉崇明",
            "ビジュアルコンセプト: 森山洋",
            "主动画师: 手塚響平・山田歩"
        ],
        "bangumiUrl": "http://bgm.tv/subject/55770",
        "loushaoUrl": "http://www.loushao.net/show_comic_1298.html",
        "userRating": 0,
        "favoriteStatus": null,
        "comment": null,
        "ratingDetails": {
            "弹弹play连载中评分": 0.00,
            "弹弹play完结后评分": 9.56,
            "Bangumi评分": 7.90,
            "Anidb连载中评分": 8.16,
            "Anidb完结后评分": 8.20,
            "Anidb评论员评分": 6.78
        },
        "relateds": [
            {
                "animeId": 9826,
                "animeTitle": "进击的巨人 OAD",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/9826.jpg",
                "searchKeyword": "进击的巨人 OAD",
                "isOnAir": false,
                "airDay": 1,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 7.30
            },
            {
                "animeId": 10583,
                "animeTitle": "进击的巨人 剧场版",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/10583.jpg",
                "searchKeyword": "进击的巨人 剧场版",
                "isOnAir": false,
                "airDay": 5,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 6.60
            },
            {
                "animeId": 10944,
                "animeTitle": "进击的巨人 第二季",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/10944.jpg",
                "searchKeyword": "进击的巨人 第二季",
                "isOnAir": false,
                "airDay": 6,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 8.20
            },
            {
                "animeId": 11468,
                "animeTitle": "进击！巨人中学校",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/11468.jpg",
                "searchKeyword": "进击！巨人中学校",
                "isOnAir": false,
                "airDay": 0,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 5.60
            },
            {
                "animeId": 15582,
                "animeTitle": "進撃の巨人 ~CHRONICLE~",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/15582.jpg",
                "searchKeyword": "進撃の巨人 ~CHRONICLE~",
                "isOnAir": false,
                "airDay": 5,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 6.40
            }
        ],
        "similars": [
            {
                "animeId": 4892,
                "animeTitle": "大剑",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/4892.jpg",
                "searchKeyword": "大剑",
                "isOnAir": false,
                "airDay": 3,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 7.60
            },
            {
                "animeId": 10951,
                "animeTitle": "甲铁城的卡巴内瑞",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/10951.jpg",
                "searchKeyword": "甲铁城的卡巴内瑞",
                "isOnAir": false,
                "airDay": 5,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 6.00
            },
            {
                "animeId": 10813,
                "animeTitle": "终结的炽天使",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/10813.jpg",
                "searchKeyword": "终结的炽天使",
                "isOnAir": false,
                "airDay": 6,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 5.90
            },
            {
                "animeId": 10842,
                "animeTitle": "噬神者",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/10842.jpg",
                "searchKeyword": "噬神者",
                "isOnAir": false,
                "airDay": 0,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 6.20
            },
            {
                "animeId": 10713,
                "animeTitle": "希德尼娅的骑士 第二季",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/10713.jpg",
                "searchKeyword": "希德尼娅的骑士 第二季",
                "isOnAir": false,
                "airDay": 0,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 7.40
            },
            {
                "animeId": 10439,
                "animeTitle": "火星异种",
                "imageUrl": "https://ddcdn-img.acplay.net/anime/10439.jpg",
                "searchKeyword": "火星异种",
                "isOnAir": false,
                "airDay": 6,
                "isFavorited": false,
                "isRestricted": false,
                "rating": 5.50
            }
        ],
        "tags": [
            {
                "id": 1,
                "name": "进击的巨人",
                "count": 2837
            },
            {
                "id": 2,
                "name": "热血",
                "count": 2033
            },
            {
                "id": 3,
                "name": "2013年4月",
                "count": 1608
            },
            {
                "id": 4,
                "name": "泽野弘之",
                "count": 1567
            },
            {
                "id": 5,
                "name": "漫画改",
                "count": 1241
            },
            {
                "id": 6,
                "name": "Production.I.G",
                "count": 1150
            },
            {
                "id": 7,
                "name": "WITSTUDIO",
                "count": 961
            },
            {
                "id": 8,
                "name": "TV",
                "count": 923
            },
            {
                "id": 9,
                "name": "梶裕贵",
                "count": 570
            },
            {
                "id": 10,
                "name": "2013",
                "count": 512
            },
            {
                "id": 11,
                "name": "荒木哲郎",
                "count": 452
            },
            {
                "id": 12,
                "name": "漫改",
                "count": 337
            },
            {
                "id": 13,
                "name": "神谷浩史",
                "count": 262
            },
            {
                "id": 14,
                "name": "战斗",
                "count": 259
            },
            {
                "id": 15,
                "name": "ProductionI.G",
                "count": 134
            },
            {
                "id": 16,
                "name": "奇幻",
                "count": 76
            },
            {
                "id": 17,
                "name": "孝哥",
                "count": 71
            },
            {
                "id": 18,
                "name": "神作",
                "count": 61
            },
            {
                "id": 19,
                "name": "燃",
                "count": 50
            },
            {
                "id": 20,
                "name": "2013春",
                "count": 49
            },
            {
                "id": 21,
                "name": "猎奇",
                "count": 45
            },
            {
                "id": 22,
                "name": "兵长",
                "count": 35
            },
            {
                "id": 23,
                "name": "井上麻里奈",
                "count": 34
            },
            {
                "id": 24,
                "name": "小林靖子",
                "count": 33
            },
            {
                "id": 25,
                "name": "2013年",
                "count": 32
            },
            {
                "id": 26,
                "name": "WIT_STUDIO",
                "count": 30
            },
            {
                "id": 27,
                "name": "剧情",
                "count": 28
            },
            {
                "id": 28,
                "name": "日本",
                "count": 27
            },
            {
                "id": 29,
                "name": "谏山创",
                "count": 26
            },
            {
                "id": 30,
                "name": "澤野弘之",
                "count": 24
            }
        ],
        "animeId": 9541,
        "animeTitle": "进击的巨人",
        "imageUrl": "https://ddcdn-img.acplay.net/anime/9541.jpg",
        "searchKeyword": "进击的巨人",
        "isOnAir": false,
        "airDay": 6,
        "isFavorited": false,
        "isRestricted": false,
        "rating": 8.20
    },
    "errorCode": 0,
    "success": true,
    "errorMessage": ""
}
```

**Comment by looly** [comment]
这是服务端响应的Content-Length为压缩后的长度导致Hutool错误导致的，此bug5.7.9修复，请暂时退回5.7.7
