### ISSUE TITLE
HttpUtil 出现Connection reset问题

### ISSUE THREAD

**Issue by iceco1a** [looly/hutool#1776]
### 版本情况

JDK版本：    
> java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

hutool版本： 5.7.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
``` java
      HashMap<String, String> headers = new HashMap<>();
        String accessToken = CacheManager.getCacheManagerInstance().getCachedDceToken("XXXX");
        headers.put("accessToken", accessToken);
        HttpResponse response = HttpRequest.post(packedFileUrl)
                .header("accessToken", accessToken)
                .body(JSON.toJSONString(queryPackedFile))
                .execute();
        String body = response.body();
        if (response.isOk()) {
            String header = response.header("Content-Type");
            if (header.equals("application/json;charset=UTF-8")) {
                Map map = JSONUtil.toBean(body, Map.class);
                String code = (String) map.get("code");
                String message = (String) map.get("message");
                if (map.get("code") != "200") {
                    throw new ServiceException(code, message);
                }
                throw new ServiceException("400", "download file faild");
            } else if(header.equals("application/x-zip-compressed;charset=UTF-8")){
                String md5 = response.header("md5");
                String content = response.header("Content-Disposition");
                String fileName = content.substring(content.lastIndexOf("=") + 1);
                InputStream inputStream = response.bodyStream();
                log.info("download Files success ! Filename:{},Md5:{}", fileName, md5);
            }
        }
```

2. 堆栈信息
```
cn.hutool.http.HttpException: SSLException: java.net.SocketException: Connection reset
	at cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:497)
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:472)
	at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:417)
	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:76)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:962)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:926)
	at com.cffex.apiproxy.service.dce.PackedFilesService.packedFile(PackedFilesService.java:50)
	at com.cffex.apiproxy.service.dce.PackedFilesService$$FastClassBySpringCGLIB$$8eee38cc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:100)
	at com.cffex.wukong.aspect.SessionAttributeAspect.setSessionAttribute(SessionAttributeAspect.java:56)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.cffex.apiproxy.service.dce.PackedFilesService$$EnhancerBySpringCGLIB$$8e422c02.packedFile(<generated>)
	at com.cffex.apiproxy.service.dce.DceClientService.packedFile(DceClientService.java:43)
	at com.cffex.apiproxy.service.dce.DceClientService$$FastClassBySpringCGLIB$$cfe4efba.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.cffex.wukong.log.LogAspect.serviceLogAround(LogAspect.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:100)
	at com.cffex.wukong.aspect.SessionAttributeAspect.setSessionAttribute(SessionAttributeAspect.java:56)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.cffex.apiproxy.service.dce.DceClientService$$EnhancerBySpringCGLIB$$21a7dae6.packedFile(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cffex.wukong.handler.DownloadHandler.handleDownload(DownloadHandler.java:66)
	at com.cffex.wukong.controller.InternalServiceController.doInternalDownload(InternalServiceController.java:104)
	at com.cffex.wukong.controller.InternalServiceController$$FastClassBySpringCGLIB$$ca430a50.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.cffex.wukong.log.LogAspect.controlLogAround(LogAspect.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.cffex.wukong.controller.InternalServiceController$$EnhancerBySpringCGLIB$$b7db30e.doInternalDownload(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:873)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.cffex.wukong.span.SpanFilter.doFilter(SpanFilter.java:63)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: cn.hutool.core.io.IORuntimeException: SSLException: java.net.SocketException: Connection reset
	at cn.hutool.core.io.copy.StreamCopier.copy(StreamCopier.java:71)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:161)
	at cn.hutool.http.HttpResponse.copyBody(HttpResponse.java:543)
	at cn.hutool.http.HttpResponse.readBody(HttpResponse.java:521)
	at cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:491)
	... 134 common frames omitted
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:141)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1293)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1260)
	at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:75)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:926)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3454)
	at cn.hutool.http.HttpInputStream.read(HttpInputStream.java:41)
	at cn.hutool.core.io.copy.StreamCopier.doCopy(StreamCopier.java:97)
	at cn.hutool.core.io.copy.StreamCopier.copy(StreamCopier.java:68)
	... 138 common frames omitted
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:83)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:401)
		... 153 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
	at sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:458)
	at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:242)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:180)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 150 common frames omitted
```

-- -Djavax.net.debug=ssl
```
javax.net.ssl|FINE|3E|Keep-Alive-Timer|2021-08-20 16:26:15.421 CST|SSLSocketImpl.java:479|duplex close of SSLSocket
javax.net.ssl|FINE|3E|Keep-Alive-Timer|2021-08-20 16:26:15.422 CST|SSLSocketImpl.java:1510|close the underlying socket
javax.net.ssl|FINE|3E|Keep-Alive-Timer|2021-08-20 16:26:15.422 CST|SSLSocketImpl.java:1529|close the SSL connection (initiative)
javax.net.ssl|FINE|3E|Keep-Alive-Timer|2021-08-20 16:26:15.422 CST|SSLSocketImpl.java:737|close inbound of SSLSocket
javax.net.ssl|WARNING|3E|Keep-Alive-Timer|2021-08-20 16:26:15.423 CST|SSLSocketImpl.java:497|SSLSocket duplex close failed (
"throwable" : {
  java.net.SocketException: Socket is closed
  	at java.net.Socket.shutdownInput(Socket.java:1538)
  	at sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:216)
  	at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:753)
  	at sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(SSLSocketImpl.java:702)
  	at sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:562)
  	at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:486)
  	at sun.net.www.http.HttpClient.closeServer(HttpClient.java:1053)
  	at sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:199)
  	at java.lang.Thread.run(Thread.java:748)}

)


3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
尝试代码改为：

```java
HashMap<String, String> headers = new HashMap<>();
String accessToken = CacheManager.getCacheManagerInstance().getCachedDceToken("XXXX");
headers.put("accessToken", accessToken);
HttpResponse response = HttpRequest.post(packedFileUrl)
        .header("accessToken", accessToken)
        .body(JSON.toJSONString(queryPackedFile))
        .executeAsync();
if (response.isOk()) {
    String header = response.header("Content-Type");
    if (header.equals("application/json;charset=UTF-8")) {
        Map map = JSONUtil.toBean(response.body(), Map.class);
        String code = (String) map.get("code");
        String message = (String) map.get("message");
        if (map.get("code") != "200") {
            throw new ServiceException(code, message);
        }
        throw new ServiceException("400", "download file faild");
    } else if(header.equals("application/x-zip-compressed;charset=UTF-8")){
        String md5 = response.header("md5");
        String content = response.header("Content-Disposition");
        String fileName = content.substring(content.lastIndexOf("=") + 1);
        InputStream inputStream = response.bodyStream();
        log.info("download Files success ! Filename:{},Md5:{}", fileName, md5);
    }
}
```

目测报错在读取响应流的时候发生，可能是服务端在某些情况下不返回任何内容，直接关闭了流导致的。

改动两处：

1. 是`execute()`改为`executeAsync()`，这样不会直接读取响应流。

2. `response.body()`方法放在分支判断中了，这样只有到了这个分支才会触发读取响应流。
