### ISSUE TITLE
从5.4.2升级到5.7.9后读取 excel报错

### ISSUE THREAD

**Issue by yanpeipan** [looly/hutool#1781]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
从5.4.2升级到5.7.9后读取 excel报错

1. 复现代码

```java
header = header(excelReader.readRow(rowIndex++), sheetIndex);
```

2. 堆栈信息
Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellType()Lorg/apache/poi/ss/usermodel/CellType;
	at cn.hutool.poi.excel.cell.CellUtil.getCellValue(CellUtil.java:103)
	at cn.hutool.poi.excel.cell.CellUtil.getCellValue(CellUtil.java:71)
	at cn.hutool.poi.excel.RowUtil.readRow(RowUtil.java:76)
	at cn.hutool.poi.excel.RowUtil.readRow(RowUtil.java:50)
	at cn.hutool.poi.excel.ExcelReader.readRow(ExcelReader.java:441)
	at cn.hutool.poi.excel.ExcelReader.readRow(ExcelReader.java:406)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
请升级你的POI到4.1.2以上，5.6.x之后不再支持3.x的POI。
