### ISSUE TITLE
日期解析，若月和天为个位数但前面不补0时会报错，希望能够兼容

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#1800]
### 版本情况

JDK版本：    1.8
hutool版本： 5.7.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
    public static void main(String[] args) {
        System.out.println(LocalDateTimeUtil.parseDate("2021-01-01"));
        System.out.println(LocalDateTimeUtil.parseDate("2021-1-1"));
    }
```

2. 堆栈信息
```
2021-01-01
Exception in thread "main" java.time.format.DateTimeParseException: Text '2021-1-1' could not be parsed at index 5
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDate.parse(LocalDate.java:400)
	at java.time.LocalDate.parse(LocalDate.java:385)
	at cn.hutool.core.date.LocalDateTimeUtil.parseDate(LocalDateTimeUtil.java:309)
	at cn.hutool.core.date.LocalDateTimeUtil.parseDate(LocalDateTimeUtil.java:293)
	at com.huixian.saasemployeemanage.biz.process.person.manage.PersonFlowImportBizProcessTest.main(PersonFlowImportBizProcessTest.java:64)
```

问题：日期解析，若月和天为个位数但前面不补0时会报错，希望能够兼容

**Comment by looly** [comment]
可以使用:

```java
DateUtil.parse("2021-1-1");
```

你也可以指定自定格式：

```java
LocalDateTimeUtil.parseDate("2020-1-1", "yyyy-M-d");
```
