### ISSUE TITLE
Convert类报错

### ISSUE THREAD

**Issue by n-kong** [looly/hutool#1817]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
String str = Convert.toStr(12);
byte[] bytes = str.getBytes();
System.out.println(Convert.bytesToInt(bytes));
```

2. 堆栈信息
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at cn.hutool.core.util.ByteUtil.bytesToInt(ByteUtil.java:126)
	at cn.hutool.core.util.ByteUtil.bytesToInt(ByteUtil.java:113)
	at cn.hutool.core.convert.Convert.bytesToInt(Convert.java:1081)
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个理解有误：

str是字符串`12`，和数字12不是一个东西，你可以：

```java
final String s = Convert.toStr(12);
final int integer = Convert.toInt(s);
```

如果是数字int和bytes转换，则使用：

```java
final byte[] bytes = Convert.intToBytes(12);
final int i = Convert.bytesToInt(bytes);
```
