### ISSUE TITLE
Width (-1) and height (-1) cannot be <= 0

### ISSUE THREAD

**Issue by Taogang00** [looly/hutool#1821]
### 版本情况

JDK版本：    jdk8
hutool版本： 最新版本

### 问题描述（包括截图）
我想获取网络图片的base64编码，使用ImgUtil工具时发现报错，main方法执行会报错。如果放到controller 接口，第一次调用报同样的错误，再次调用正常。谢谢~

1. 复现代码 (完整):

```java
    public static void main(String[] args) {
        try {
            Image image = ImgUtil.getImage(new URL("https://img2.baidu.com/it/u=4111104008,2106708700&fm=26&fmt=auto&gp=0.jpg"));
            String s = ImgUtil.toBase64(image, ImgUtil.IMAGE_TYPE_JPG);
            System.out.println(s);
        }catch (Exception e){
            throw new RuntimeException(e);
        }
    }
```

2. 堆栈信息

```java
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
	at xxxxxxxxxxxx.main(VehicleV2Controller.java:267)
Caused by: java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at cn.hutool.core.img.ImgUtil.copyImage(ImgUtil.java:1250)
	at cn.hutool.core.img.ImgUtil.copyImage(ImgUtil.java:1224)
	at cn.hutool.core.img.ImgUtil.toBufferedImage(ImgUtil.java:1198)
	at cn.hutool.core.img.ImgUtil.toBufferedImage(ImgUtil.java:1178)
	at cn.hutool.core.img.ImgUtil.write(ImgUtil.java:1539)
	at cn.hutool.core.img.ImgUtil.write(ImgUtil.java:1520)
	at cn.hutool.core.img.ImgUtil.write(ImgUtil.java:1505)
	at cn.hutool.core.img.ImgUtil.toBytes(ImgUtil.java:1328)
	at cn.hutool.core.img.ImgUtil.toBase64(ImgUtil.java:1315)
	at xxxxxxxxxxxx.main(xxxxxx.java:264)
```

**Comment by Taogang00** [comment]
ImgUtil.toBase64DataUri 存在同样的错误

**Comment by looly** [comment]
你可以：

```java
final URL url = new URL("https://img2.baidu.com/it/u=4111104008,2106708700&fm=26&fmt=auto&gp=0.jpg");
final Image read = ImgUtil.read(url);
String s = ImgUtil.toBase64(read, ImgUtil.IMAGE_TYPE_JPG);
```

**Comment by looly** [comment]
原因是使用`ImgUtil.getImage`调用`Toolkit.getDefaultToolkit().getImage()`方法，这是个异步方法，在没有读完的时候就直接读取肯定报错。你可以：

```java
Image image = ImgUtil.getImage(new URL("https://img2.baidu.com/it/u=4111104008,2106708700&fm=26&fmt=auto&gp=0.jpg"));

// ensures that all the pixels loaded
img = new ImageIcon(img).getImage();

String s = ImgUtil.toBase64(image, ImgUtil.IMAGE_TYPE_JPG);
```

**Comment by looly** [comment]
参考：https://www.oschina.net/question/1092_23668?sort=default&p=1

**Comment by looly** [comment]
5.7.13会自动加上这句，感谢。

**Comment by Taogang00** [comment]
好的，谢谢
