### ISSUE TITLE
JWTUtil.createToken error 

### ISSUE THREAD

**Issue by war1644** [looly/hutool#1837]
### 版本情况

JDK版本：    openjdk_8_302
hutool版本： 5.7.13（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用JWTUtil.createToken报错
报错堆栈如下

1. 复现代码

```java
byte[] key = "1234".getBytes();
Map<String, Object> map = new HashMap<String, Object>() {
	private static final long serialVersionUID = 1L;
	{
		put("uid", Integer.parseInt(uid));
		put("expire_time", System.currentTimeMillis() + 1000 * 60 * 60 * 24 * 15);
		
	}
};

return JWTUtil.createToken(map, key);
```

2. 堆栈信息
严重: 在路径为/app的上下文中，Servlet[springmvcWeb]的Servlet.service（）引发了具有根本原因的异常Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: SHA256withRSA_PSS
java.lang.NoSuchFieldError: SHA256withRSA_PSS
	at cn.hutool.jwt.signers.AlgorithmUtil.<clinit>(AlgorithmUtil.java:34)
	at cn.hutool.jwt.signers.JWTSignerUtil.createSigner(JWTSignerUtil.java:136)
	at cn.hutool.jwt.signers.JWTSignerUtil.hs256(JWTSignerUtil.java:36)
	at cn.hutool.jwt.JWT.setKey(JWT.java:120)
	at cn.hutool.jwt.JWTUtil.createToken(JWTUtil.java:35)
	at cn.hutool.jwt.JWTUtil.createToken(JWTUtil.java:20)
	at com.bl.service.impl.LoginServiceImpl.genToken(LoginServiceImpl.java:106)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
我本地测试没有问题，请检查是否引入多个hutool版本导致版本冲突了。

**Comment by war1644** [comment]
感谢，清理了lib的hutool，只保留最新的。正常了
