### ISSUE TITLE
JWT（Hutool-jwt）验证非法token异常

### ISSUE THREAD

**Issue by Aii2BNice** [looly/hutool#1852]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.7.13

### 问题描述（包括截图）
JWT（Hutool-jwt）验证非法token异常
例如： 123123123
            123.123.123
1. 复现代码

```java
JWTUtil.verify(token, key)
```

2. 堆栈信息

 123123123的时候:
cn.hutool.jwt.JWTException: The token was expected 3 parts, but got 1.
	at cn.hutool.jwt.JWT.splitToken(JWT.java:392)
	at cn.hutool.jwt.JWT.parse(JWT.java:95)
	at cn.hutool.jwt.JWT.<init>(JWT.java:85)
	at cn.hutool.jwt.JWT.of(JWT.java:66)
	at cn.hutool.jwt.JWTUtil.verify(JWTUtil.java:84)
123.123.123的时候：
cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
	at cn.hutool.json.JSONObject.init(JSONObject.java:676)
	at cn.hutool.json.JSONObject.init(JSONObject.java:663)
	at cn.hutool.json.JSONObject.init(JSONObject.java:619)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:200)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:120)
	at cn.hutool.jwt.Claims.parse(Claims.java:84)
	at cn.hutool.jwt.JWT.parse(JWT.java:97)
	at cn.hutool.jwt.JWT.<init>(JWT.java:85)
	at cn.hutool.jwt.JWT.of(JWT.java:66)
	at cn.hutool.jwt.JWTUtil.verify(JWTUtil.java:84)
3. 建议：不合法的token验证直接返回false，就不用在外面try...catch...了

**Comment by looly** [comment]
这个概念不同：

verify只是验证是否被篡改，因为格式问题而导致的解析异常，理应抛出异常。
