### ISSUE TITLE
excelwriter官方例子报错

### ISSUE THREAD

**Issue by n-kong** [looly/hutool#1865]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.13

### 问题描述（包括截图）

1. 复现代码

```java
Map<String, Object> row1 = new LinkedHashMap<>();
        row1.put("姓名", "张三");
        row1.put("年龄", 23);
        row1.put("成绩", 88.32);
        row1.put("是否合格", true);
        row1.put("考试日期", DateUtil.date());

        Map<String, Object> row2 = new LinkedHashMap<>();
        row2.put("姓名", "李四");
        row2.put("年龄", 33);
        row2.put("成绩", 59.50);
        row2.put("是否合格", false);
        row2.put("考试日期", DateUtil.date());

        ArrayList<Map<String, Object>> rows = CollUtil.newArrayList(row1, row2);

        // 通过工具类创建writer
        ExcelWriter writer = ExcelUtil.getWriter("D:\\resource.xlsx");

// 合并单元格后的标题行，使用默认标题样式
//        writer.merge(row1.size() - 1, "一班成绩单");
// 一次性写出内容，使用默认样式，强制输出标题
        writer.write(rows, true);
// 关闭writer，释放内存
        writer.close();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

官网例子报错：
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellType()Lorg/apache/poi/ss/usermodel/CellType;
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:221)
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:182)
	at cn.hutool.poi.excel.ExcelWriter.writeHeadRow(ExcelWriter.java:880)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:986)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:965)
	at cn.hutool.poi.excel.ExcelWriter.write(ExcelWriter.java:819)

**Comment by looly** [comment]
检查你的：

1. POI版本是否确实是4.1.2
2. 检查是否引入旧版本的POI，导致包冲突了。
