### ISSUE TITLE
符合调用规范使用DateUtil.parse() 解析会出现异常;

### ISSUE THREAD

**Issue by tanzf0818** [looly/hutool#1891]
### 版本情况

JDK版本：    1.8.0_162
hutool版本： 5.7.14

### 问题描述（包括截图） 
使用DateUtil进行符合使用要求的情况下,会出现以下异常信息;  
如果入参日期字符串加上时分秒,且将DatePattern改为NORM_DATETIME_FORMATTER则能正常;  
如果是不允许该操作,是否有编码上的提醒或直接异常禁止;

1. 复现代码

```java
	@Test
	public void parseTest(){
		Assert.assertThrows(DateTimeException.class, () -> DateUtil.parse("2021-01-01", DatePattern.NORM_DATE_FORMATTER));
	}
```

2. 堆栈信息  
``` 
java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor: {},ISO,Asia/Shanghai resolved to 2021-01-01 of type java.time.format.Parsed

	at java.time.Instant.from(Instant.java:378)
	at cn.hutool.core.date.DateTime.<init>(DateTime.java:279)
	at cn.hutool.core.date.DateUtil.parse(DateUtil.java:708)
	at cn.hutool.core.date.DateUtilTest.parseTest(DateUtilTest.java:992)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds
	at java.time.format.Parsed.getLong(Parsed.java:203)
	at java.time.Instant.from(Instant.java:373)
	... 28 more 
```

3. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
这是个bug。

问题出在`Instant.from`不能转换`java.time.format.Parsed`，这个算是JDK的一个坑……

5.7.15修复此问题。

你暂时可以：

```java
DateUtil.parse("2021-01-01", DatePattern.NORM_DATE_FORMAT);
```
