### ISSUE TITLE
SM2解密时无效的密文invalid cipher text

### ISSUE THREAD

**Issue by trxrjgc** [looly/hutool#1892]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.14（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
            byte[] d = SmUtil.sm2().getD();
            byte[] q = SmUtil.sm2().getQ(false);
            String privateKey = HexUtil.encodeHexStr(d);
            String publicKey = HexUtil.encodeHexStr(q);
            System.out.println("私钥：" + privateKey);
            System.out.println("公钥：" + publicKey);
            SM2 sm2 = SmUtil.sm2(privateKey, publicKey);
            String cipher = sm2.encryptHex("111111", KeyType.PublicKey);
            String plaintext = sm2.decryptStr(cipher, KeyType.PrivateKey);
            System.out.println(plaintext);
```

2. 堆栈信息
cn.hutool.crypto.CryptoException: InvalidCipherTextException: invalid cipher text

	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:298)
	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:279)
	at cn.hutool.crypto.asymmetric.AsymmetricDecryptor.decrypt(AsymmetricDecryptor.java:58)
	at cn.hutool.crypto.asymmetric.AsymmetricDecryptor.decryptStr(AsymmetricDecryptor.java:71)
	at cn.hutool.crypto.asymmetric.AsymmetricDecryptor.decryptStr(AsymmetricDecryptor.java:83)
	at Demo.test1(Demo.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: invalid cipher text
	at org.bouncycastle.crypto.engines.SM2Engine.decrypt(Unknown Source)
	at org.bouncycastle.crypto.engines.SM2Engine.processBlock(Unknown Source)
	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:296)
	... 36 more
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个问题已经回答过了：https://github.com/dromara/hutool/issues/1890
