### ISSUE TITLE
native-image将程序打包为exe后hutool的http工具无法正常使用

### ISSUE THREAD

**Issue by Anivie** [looly/hutool#1897]
### 版本情况

JDK版本：    Graalvm 21 with Java 16
hutool版本： 5.7.14

### 问题描述（包括截图）
当我使用Graalvm的native-image将程序打包为exe后hutool的http工具就发生了错误：他无法正确的发出请求，错误信息显示它将程运行目录拼接进了请求地址中从而无法发出请求。
这段代码在正常的jvm环境下运行正常，只有在native-image打包后会发生错误

1. 复现代码

```
        //JavaFx应用，button是Button类，title是TextFiled类
        button.setOnAction(actionEvent -> {
            HttpResponse response = HttpRequest.post("http://localhost:7070/home")
                    .form("action","tables1")
                    .timeout(5000)
                    .execute();
            response.close();
            title.setText(response.body());
        });
```

2. 堆栈信息
`
Exception in thread "JavaFX Application Thread" cn.hutool.http.HttpException: 'sun.net.www.protocol.file.FileURLConnection' of URL [file:/D%3A/IDEA%20Projects/GVMTest/out/artifacts/test_jar/http%3A/localhost%3A7070/home] is not a http connection, make sure URL is format for http.
        at cn.hutool.http.HttpConnection.openHttp(HttpConnection.java:532)
        at cn.hutool.http.HttpConnection.initConn(HttpConnection.java:86)
        at cn.hutool.http.HttpConnection.<init>(HttpConnection.java:73)
        at cn.hutool.http.HttpConnection.create(HttpConnection.java:57)
        at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1067)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:955)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:928)
        at iBuilder.UI.lambda$start$0(UI.java:43)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8792)
        at javafx.scene.control.Button.fire(Button.java:203)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1878)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.security.AccessController.doPrivileged(AccessController.java:105)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
        at com.sun.glass.ui.View.notifyMouse(View.java:943)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Lcom_sun_glass_ui_View_2_0002enotifyMouse_00028IIIIIIIZZ_00029V(JNIJavaCallWrappers.java:0)
        at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.lang.Thread.run(Thread.java:831)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
`
3. 测试涉及到的文件（注意脱密）
测试链接是我自己搭建的，实际上开谁都一样

**Comment by CherryRum** [comment]
确实没有在建造者模式找到中获取本地路径进行拼接uri，难道Graalvm编译本地时候进行了修改，挺离谱的

**Comment by looly** [comment]
非常奇怪的问题，Http路径为何直接变成了本地路径。

尝试自行使用`HttpUrlConnection`完成请求会不会有该问题。

麻烦通过`UrlBuilder.ofHttp(url).toURL()`尝试是否这个路径变更了。

有问题再打开此issue即可。

**Comment by hjldev** [comment]
> 非常奇怪的问题，Http路径为何直接变成了本地路径。
> 
> 尝试自行使用`HttpUrlConnection`完成请求会不会有该问题。
> 
> 麻烦通过`UrlBuilder.ofHttp(url).toURL()`尝试是否这个路径变更了。
> 
> 有问题再打开此issue即可。

通过这种方式还是报错， @Anivie 请问您是如何解决的

**Comment by Anivie** [comment]
> > 非常奇怪的问题，Http路径为何直接变成了本地路径。
> > 尝试自行使用`HttpUrlConnection`完成请求会不会有该问题。
> > 麻烦通过`UrlBuilder.ofHttp(url).toURL()`尝试是否这个路径变更了。
> > 有问题再打开此issue即可。
> 
> 通过这种方式还是报错， @Anivie 请问您是如何解决的

换其他工具

**Comment by CV-Devlau** [comment]
也遇到这个问题找到原因了
原生打包需要手动开启http协议。

[https://docs.oracle.com/en/graalvm/enterprise/22/docs/reference-manual/native-image/dynamic-features/URLProtocols/#url-protocols-in-native-image](https://gitee.com/link?target=https%3A%2F%2Fdocs.oracle.com%2Fen%2Fgraalvm%2Fenterprise%2F22%2Fdocs%2Freference-manual%2Fnative-image%2Fdynamic-features%2FURLProtocols%2F%23url-protocols-in-native-image)

添加参数开启http协议

```
<buildArgs>
	--no-fallback
	--enable-url-protocols=http
	--enable-url-protocols=https
</buildArgs>
```

**Comment by looly** [comment]
感谢@CV-Devlau 答疑解惑，学习了。

相关修复见：https://gitee.com/dromara/hutool/issues/I8PY3Y
