### ISSUE TITLE
连接mysql8.0.26.0出现Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by guomz** [looly/hutool#1913]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```
List<Entity> result = Db.use().findAll("city");
		System.out.println(result);
```

2. 堆栈信息
** BEGIN NESTED EXCEPTION ** 

com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException
MESSAGE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

STACKTRACE:

com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:921)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:885)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3421)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1247)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2924)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:149)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:143)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1512)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1575)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2450)

** END NESTED EXCEPTION **

3. 测试涉及到的文件（注意脱密）
## db.setting文件

url = jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
user = root
pass = 123

showSql = true

formatSql = true

showParams = true

sqlLevel = debug

比如报错的Excel文件，有问题的图片等。

**Comment by guomz** [comment]
我额外使用了新版本的mysql-connector-java解决了这个问题。
