### ISSUE TITLE
ZipUtil的 child directory 判断存在错误

### ISSUE THREAD

**Issue by ghost** [looly/hutool#1938]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：![image](https://user-images.githubusercontent.com/19369884/140678310-b35d9848-32f0-4159-b333-5ec785420381.png)

### 问题描述（包括截图）

1. 复现代码

```java
long timestamp = System.currentTimeMillis();
String excelExportDirPath = System.getProperty("user.dir") + File.separator + "tsos_temp_export"
                        + File.separator + reportId + "_" + timestamp;
Files.createDirectories(Paths.get(excelExportDirPath));
String excelExportZipDirPath = excelExportDirPath + "_zip";
Files.createDirectories(Paths.get(excelExportZipDirPath));
// 打包目录
String destFileName = report.getName() + ".zip", destFilePath = excelExportZipDirPath + "/" + destFileName;
// 报错
ZipUtil.zip(excelExportDirPath, destFilePath);
```

2. 堆栈信息
```shell
2021/11/08 11:07:06.964 ERROR [http-nio-10040-exec-1] c.x.tsos.handler.GlobalExceptionHandler : 发生系统异常: cn.hutool.core.exceptions.UtilException: Zip file path [E:\workspace\tsos-server\tsos_temp_export\4_1636340825763_zip\test.zip] must not be the child directory of [E:\workspace\tsos-server\tsos_temp_export\4_1636340825763] !
	at cn.hutool.core.util.ZipUtil.validateFiles(ZipUtil.java:1031)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:179)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:163)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:134)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:118)
	at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:105)
```

**Comment by refeccd** [comment]
感觉可以升到最新版本再试试，最新版本已经到 5.7.16 了

**Comment by refeccd** [comment]
找到了这个 commit 994a7a49bffec80400264065ed7e3f265a7d9dc9，希望对你有用

**Comment by ghost** [comment]
> 找到了这个 commit [994a7a4](https://github.com/dromara/hutool/commit/994a7a49bffec80400264065ed7e3f265a7d9dc9)，希望对你有用

谢谢啦

**Comment by looly** [comment]
@liaozan Good job ! 感谢。
