### ISSUE TITLE
Bug  数值转换字符串报错

### ISSUE THREAD

**Issue by lin-code-world** [looly/hutool#1949]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.7.16

### 问题描述（包括截图）

1. 复现代码

```java
JSONObject jsonObject = new JSONObject();
jsonObject.set("code", 101);
log.info(jsonObject.toString());
```

2. 堆栈信息
java.lang.NoSuchMethodError: cn.hutool.core.util.NumberUtil.toStr(Ljava/lang/Number;Z)Ljava/lang/String;

	at cn.hutool.json.serialize.JSONWriter.writeNumberValue(JSONWriter.java:257)
	at cn.hutool.json.serialize.JSONWriter.writeObjValue(JSONWriter.java:231)
	at cn.hutool.json.serialize.JSONWriter.writeValueDirect(JSONWriter.java:211)
	at cn.hutool.json.serialize.JSONWriter.writeField(JSONWriter.java:171)
	at cn.hutool.json.JSONObject.lambda$write$0(JSONObject.java:597)
	at java.base/java.util.Map.forEach(Map.java:661)
	at cn.hutool.json.JSONObject.write(JSONObject.java:594)
	at cn.hutool.json.JSONObject.write(JSONObject.java:576)
	at cn.hutool.json.JSON.toJSONString(JSON.java:112)
	at cn.hutool.json.JSONObject.toString(JSONObject.java:555)

**Comment by lin-code-world** [comment]
找到原因了，是依赖包版本有冲突的关系。依赖包里也引用了hutool的包，版本不一致导致的。
