### ISSUE TITLE
5.2.5 升级到 5.7.16后  ZipUtil.zip()报错

### ISSUE THREAD

**Issue by JackNo2018** [looly/hutool#1961]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.5 升级到 5.7.16

### 问题描述
版本升级带来的bug , 此处应当可以兼容原来的处理逻辑 , 使升级更顺利

1. 复现代码

```java
        File target = new File("temp.zip");
        ZipUtil.zip(target, true, new File("D:\\test\\20210607"));
```

2. 堆栈信息
```java
java.lang.IllegalArgumentException: [Assertion failed] - this argument is required; it must not be null
        at cn.hutool.core.lang.Assert.lambda$notNull$3(Assert.java:216)
        at cn.hutool.core.lang.Assert.notNull(Assert.java:196)
        at cn.hutool.core.lang.Assert.notNull(Assert.java:216)
        at cn.hutool.core.lang.Assert.notNull(Assert.java:232)
        at cn.hutool.core.io.FileUtil.isSub(FileUtil.java:3345)
        at cn.hutool.core.util.ZipUtil.validateFiles(ZipUtil.java:1006)
        at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:248)
        at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:232)
        at cn.hutool.core.util.ZipUtil.zip(ZipUtil.java:218)

```
3.导致异常的代码
[[https://github.com/dromara/hutool/blob/a70d50736e622500955dc1072b91aa8ee5fc3243/hutool-core/src/main/java/cn/hutool/core/util/ZipUtil.java#L1006]](https://github.com/dromara/hutool/blob/a70d50736e622500955dc1072b91aa8ee5fc3243/hutool-core/src/main/java/cn/hutool/core/util/ZipUtil.java#L1006)
**bug已在下方代码注释中表明**
```java
	/**
	 * 判断压缩文件保存的路径是否为源文件路径的子文件夹，如果是，则抛出异常（防止无限递归压缩的发生）
	 *
	 * @param zipFile  压缩后的产生的文件路径
	 * @param srcFiles 被压缩的文件或目录
	 */
	private static void validateFiles(File zipFile, File... srcFiles) throws UtilException {
		if (zipFile.isDirectory()) {
			throw new UtilException("Zip file [{}] must not be a directory !", zipFile.getAbsoluteFile());
		}

		for (File srcFile : srcFiles) {
			if (null == srcFile) {
				continue;
			}
			if (false == srcFile.exists()) {
				throw new UtilException(StrUtil.format("File [{}] not exist!", srcFile.getAbsolutePath()));
			}

			// 压缩文件不能位于被压缩的目录内
                        // bug::  zipFile.getParentFile()
                        // 当 zipFile =  new File("temp.zip") 时, zipFile.getParentFile() == null
                        // 建议优化为 zipFile.getCanonicalFile().getParentFile()
			if (srcFile.isDirectory() && FileUtil.isSub(srcFile, zipFile.getParentFile())) {
				throw new UtilException("Zip file path [{}] must not be the child directory of [{}] !", zipFile.getPath(), srcFile.getPath());
			}
		}
	}
```

**Comment by looly** [comment]
这块忽略了！确认bug，5.7.17修复此问题~~
