### ISSUE TITLE
log工具空指针异常

### ISSUE THREAD

**Issue by wanbing881209** [looly/hutool#198]
System.err: java.lang.NullPointerException: Attempt to get length of null array
        at cn.hutool.core.lang.caller.SecurityManagerCaller.getCallerCaller(SecurityManagerCaller.java:24)
        at cn.hutool.core.lang.caller.CallerUtil.getCallerCaller(CallerUtil.java:30)

**Comment by wanbing881209** [comment]
private static Caller tryCreateCaller() {
		try {
			return new SecurityManagerCaller();
		} catch (Throwable e) {
		}
		return new StackTraceCaller();
	}
其中SecurityManager不能通过这个方法简单地new吧

**Comment by looly** [comment]
请问有使用环境么，还有如何调用的代码？我这边测试没有触发出问题。
