### ISSUE TITLE
Calculator.conversion EmptyStackException

### ISSUE THREAD

**Issue by jerhe** [looly/hutool#1984]
### 版本情况

JDK版本：    window jdk 1.8.0_291
hutool版本：5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
public static void main(String[] args) {
        System.out.println(Calculator.conversion("((1/1) / (1/1)  -1) *100"));
    }

```java
Exception in thread "main" java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at cn.hutool.core.math.Calculator.prepare(Calculator.java:114)
	at cn.hutool.core.math.Calculator.calculate(Calculator.java:72)
	at cn.hutool.core.math.Calculator.conversion(Calculator.java:31)
	at net.jerhe.mydemo.hutool.HutoolDemo.main(HutoolDemo.java:12)

Process finished with exit code 1
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可能是个bug，稍后处理。

**Comment by looly** [comment]
gitee上有人提供了一种解决方法的私聊，我先关闭这个issue，保留那个解决方案的issue，稍后处理：https://gitee.com/dromara/hutool/issues/I4KONB
