### ISSUE TITLE
socket客户端AioClient在服务端AioServer异常断开时报错

### ISSUE THREAD

**Issue by tanhq1024** [looly/hutool#1987]
版本情况
JDK版本： jdk8
hutool版本： 5.7.16

问题描述（包括截图）
socket客户端AioClient在服务端AioServer异常断开时报错

```java
Exception in thread "Huool-socket-11" cn.hutool.socket.SocketRuntimeException: IOException: 远程主机强迫关闭了一个现有的连接。
	at cn.hutool.socket.aio.ReadHandler.failed(ReadHandler.java:22)
	at cn.hutool.socket.aio.ReadHandler.failed(ReadHandler.java:13)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:353)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.read0(Native Method)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.access$700(WindowsAsynchronousSocketChannelImpl.java:43)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.run(WindowsAsynchronousSocketChannelImpl.java:511)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.implRead(WindowsAsynchronousSocketChannelImpl.java:657)
	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276)
	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297)
	at cn.hutool.socket.aio.AioSession.read(AioSession.java:117)
	at cn.hutool.socket.aio.AioSession.read(AioSession.java:105)
	at com.thq.socket.job.Job.readMessage(Job.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more
```

复现代码

客户端代码(两个类)

```java
@Component
@Slf4j
public class AIOClient implements ApplicationRunner {

    public static ConcurrentHashMap<String,AioSession> aioSessionMap = new ConcurrentHashMap<>();

    @Override
    public void run(ApplicationArguments args){
        AioClient client = new AioClient(new InetSocketAddress("localhost", 2000), new SimpleIoAction() {
            /**
             * 会话建立事件处理
             *
             * @param session 会话
             */
            @Override
            public void accept(AioSession session) {
                Console.log("【监听地址】：{} 。", session.getRemoteAddress());
                aioSessionMap.put("AioSession", session);
            }

            /**
             * 执行数据处理（消息读取）
             *
             * @param session Socket Session会话
             * @param data    解码后的数据
             */
            @Override
            public void doAction(AioSession session, ByteBuffer data) {
                if (data.hasRemaining()) {
                    Map<String, Object> stringObjectMap = XmlUtil.xmlToMap(StrUtil.utf8Str(data));
                    String s = JSON.toJSONString(stringObjectMap);
                    Console.log("收到服务端消息:" + s);
                } else {
                    Console.log("收到的是空消息");
                }
            }
        });
    }
}
```

```java
@Component
@Slf4j
public class Job {
    @Scheduled(cron = "* * * * * ?")
    public void readMessage() {
        AioSession session = aioSessionMap.get("AioSession");
        if (ObjectUtil.isNotEmpty(session) && session.isOpen()) {
            try {
                session.read();
            } catch (ReadPendingException e) {
            }
        } else {
            //TODO 重连
        }
    }
}
```

**Comment by looly** [comment]
session.read有个重载方法，可以自定义`CompletionHandler`，对于异常信息，走到`failed`方法后，你可以捕获异常只打印日志。

**Comment by tanhq1024** [comment]
已按该方法解决
