### ISSUE TITLE
write excel no Suchmethod error

### ISSUE THREAD

**Issue by derekzhan** [looly/hutool#1996]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
ExcelWriter writer = ExcelUtil.getBigWriter();
			writer.addHeaderAlias("deviceName", "名称");
			writer.addHeaderAlias("companyName", "企业");
			writer.addHeaderAlias("areaDeptName", "辖区");
			writer.write(dataList);
			response.setContentType("application/vnd.ms-excel;charset=utf-8");
			response.setHeader("Content-Disposition", "attachment;filename=exportOffLine.xls");
			out = response.getOutputStream();
			writer.flush(out);
			writer.close();
```

2. 堆栈信息
Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellType()Lorg/apache/poi/ss/usermodel/CellType;
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:190)
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:151)
	at cn.hutool.poi.excel.ExcelWriter.writeHeadRow(ExcelWriter.java:878)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:984)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:963)
	at cn.hutool.poi.excel.ExcelWriter.write(ExcelWriter.java:817)
	at cn.hutool.poi.excel.ExcelWriter.write(ExcelWriter.java:791)
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
![image](https://user-images.githubusercontent.com/2375460/144564767-10937eec-6bed-4e4f-b40f-b9f9b4837a88.png)

**Comment by looly** [comment]
请检查你的POI版本是否4.1.2及其以上，或者是否存在多个版本POI的情况。
