### ISSUE TITLE
SM4加密使用192位秘钥报错

### ISSUE THREAD

**Issue by micuncang** [looly/hutool#2031]
### 版本情况

JDK版本：    1.8.0_292
hutool版本： 5.7.17（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

```
代码中注释写到支持秘钥长度192位，实际使用报错

	/**
	 * 构造
	 *
	 * @param mode    模式{@link Mode}
	 * @param padding {@link Padding}补码方式
	 * @param key     密钥，支持三种密钥长度：128、192、256位
	 */
	public SM4(Mode mode, Padding padding, byte[] key) {
		this(mode, padding, key, null);
	}
```

1. 复现代码

```java
byte[] key = "123456781234567812345678".getBytes(StandardCharsets.UTF_8);
SM4 sm4 = new SM4(Mode.ECB, Padding.PKCS5Padding, key);
byte[] en = sm4.encrypt("中国文化");
System.out.println(Base64Utils.encodeToString(en));
```

2. 报错信息
```
Exception in thread "main" cn.hutool.crypto.CryptoException: InvalidKeyException: SM4 requires a 128 bit key
	at cn.hutool.crypto.symmetric.SymmetricCrypto.encrypt(SymmetricCrypto.java:277)
	at cn.hutool.crypto.symmetric.SymmetricEncryptor.encrypt(SymmetricEncryptor.java:139)
	at com.elens.data.definition.controller.ToolController.main(ToolController.java:77)
Caused by: java.security.InvalidKeyException: SM4 requires a 128 bit key
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1189)
	at cn.hutool.crypto.CipherWrapper.initMode(CipherWrapper.java:116)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.initMode(SymmetricCrypto.java:415)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.encrypt(SymmetricCrypto.java:274)
	... 2 more
```

**Comment by CherryRum** [comment]
@looly 老哥你这个参考的国标是哪个?
我记得sm4密钥不就`128bit`吗
`http://www.gmbz.org.cn/main/viewfile/20180108015408199368.html`
`http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=7803DE42D3BC5E80B0C3E5D8E873D56A`

**Comment by micuncang** [comment]
> @looly 老哥你这个参考的国标是哪个? 我记得sm4密钥不就`128bit`吗 `http://www.gmbz.org.cn/main/viewfile/20180108015408199368.html` `http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=7803DE42D3BC5E80B0C3E5D8E873D56A`

我看咱们的代码注释中提到支持三种密钥长度：128、192、256位，所以这个注释是不是需要调整下

**Comment by CherryRum** [comment]
您稍等我问下,下个版本应该会把注释改掉,非常感谢

**Comment by looly** [comment]
已合并PR~~
