### ISSUE TITLE
cn.hutool.http.HttpException: Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by amosnothing** [looly/hutool#2033]
### 版本情况

JDK版本：    1.8.0_161
hutool版本：5.7.16（正式环境出现，新的版本没有确认，偶现的问题）

### 问题描述（包括截图）

1. 复现代码
无，这个问题是一定概率出现的
2. 堆栈信息
2021-12-21 11:56:10.877---[ERROR]---[157a2a6025ff7811fc9c2d482f930f06]---[async-scene-service-4]---[c.s.e.p.s.i.DebugServiceImpl]:发起请求出现未知异常
cn.hutool.http.HttpException: Invalid HTTP method: PATCH
        at cn.hutool.http.HttpConnection.setMethod(HttpConnection.java:131)
        at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1102)
        at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1074)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:967)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:943)
        at com.xxxx.yyy.zzz(项目代码省略)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
        at io.opentracing.contrib.spring.cloud.async.TraceAsyncAspect.traceBackgroundThread(TraceAsyncAspect.java:56)
        at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
3. 测试涉及到的文件（注意脱密）
无

**Comment by amosnothing** [comment]
已经确定当前项目只引入了一个 hutool-all

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/147209543-e1ed4b30-3670-4683-ab1e-fd72d9b4ec5f.png)

怀疑是这句没执行成功。

尝试手动执行下：`HttpGlobalConfig.allowPatch()`看报错不。

**Comment by amosnothing** [comment]
OK，因为需要修改正式环境下的代码， 可能需要等到下一次迭代的时候才可以看到结果，这个问题在测试环境又比较难重现。

**Comment by sheldon-lu** [comment]
> OK，因为需要修改正式环境下的代码， 可能需要等到下一次迭代的时候才可以看到结果，这个问题在测试环境又比较难重现。

最后咋解决的？

**Comment by amosnothing** [comment]
> > OK，因为需要修改正式环境下的代码， 可能需要等到下一次迭代的时候才可以看到结果，这个问题在测试环境又比较难重现。
> 
> 最后咋解决的？

在全局设置 enable patch
