### ISSUE TITLE
使用javamail发送网易邮箱附件变成bin

### ISSUE THREAD

**Issue by qintao0203** [looly/hutool#2050]
### 版本情况

JDK版本：    1.8.0_231
hutool版本： 5.7.14（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用javamail发送至网易邮箱，在添加附件文件时，如果附件文件名中含有中文，并且名称过长就会出现附件文件变成ATT00001.bin的问题，英文名称测试50个字符没问题，设置附件名使用英文很长之后也是会出现附件名被篡改.发送至qq邮箱以及发送到公司邮箱也是没有问题。
![image](https://user-images.githubusercontent.com/29176158/147624769-903d5b09-efad-4abe-a222-9c5689e2a420.png)

1. 复现代码

```java
        String send = MailUtil.send(“” : email, "测试", "aaa", false, new File(“”));

```

2. 测试涉及到的文件（注意脱密）

[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.xlsx](https://github.com/dromara/hutool/files/7787188/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.xlsx)

**Comment by looly** [comment]
尝试编码附件的文件名，使用UrlUtil.encodeAll

**Comment by qintao0203** [comment]
> 尝试编码附件的文件名，使用UrlUtil.encodeAll

您好，UrlUtil.encodeAll这个方法不存在，尝试使用URLEncodeUtil.encodeAll进行编码就会报文件找不到
```
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: /home/weblogic/files/%E6%95%B0%E6%8D%AE%E6%B8%85%E5%8D%95%E8%A1%A8_20211224145459_test_user6.xlsx (No such file or directory)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1365)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at cn.hutool.extra.mail.Mail.doSend(Mail.java:407)
	at cn.hutool.extra.mail.Mail.send(Mail.java:385)
	... 76 more
Caused by: java.io.FileNotFoundException: /home/weblogic/files/%E6%95%B0%E6%8D%AE%E6%B8%85%E5%8D%95%E8%A1%A8_20211224145459_test_user6.xlsx (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1694)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:996)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:561)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:84)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1694)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1913)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1315)
	... 80 more

```

**Comment by looly** [comment]
看下这个：https://www.cnblogs.com/apache-x/p/5436714.html

**Comment by qintao0203** [comment]
> 看下这个：https://www.cnblogs.com/apache-x/p/5436714.html

看了一下hutool中添加文件时候的实现，也是使用同样的方式实现的，我试了一下还是不行
```
public Mail setAttachments(DataSource... attachments) {
		if (ArrayUtil.isNotEmpty(attachments)) {
			final Charset charset = this.mailAccount.getCharset();
			MimeBodyPart bodyPart;
			String nameEncoded;
			try {
				for (DataSource attachment : attachments) {
					bodyPart = new MimeBodyPart();
					bodyPart.setDataHandler(new DataHandler(attachment));
					nameEncoded = InternalMailUtil.encodeText(attachment.getName(), charset);
					// 普通附件文件名
					bodyPart.setFileName(nameEncoded);
					if (StrUtil.startWith(attachment.getContentType(), "image/")) {
						// 图片附件，用于正文中引用图片
						bodyPart.setContentID(nameEncoded);
					}
					this.multipart.addBodyPart(bodyPart);
				}
			} catch (MessagingException e) {
				throw new MailException(e);
			}
		}
		return this;
	}
```

**Comment by looly** [comment]
那你只能看有什么办法了对于长附件名。欢迎提供思路，我这边没办法了。

**Comment by qintao0203** [comment]
设置了一下这个系统参数解决问题了
```
System.setProperty("mail.mime.splitlongparameters", "false");
```

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/149435929-5b1f67ef-c763-48c2-933b-10d46575f9a1.png)

这个Hutool就是默认的啊。

你升级到5.7.19试下。

**Comment by qintao0203** [comment]
> ![image](https://user-images.githubusercontent.com/1432613/149435929-5b1f67ef-c763-48c2-933b-10d46575f9a1.png)
> 
> 这个Hutool就是默认的啊。
> 
> 你升级到5.7.19试下。

升级到最新版本试了一下也还是不行，我两个版本打断点确实在getSmtpProps()方法中是设置了这个系统属性的，不明白为什么没有生效，调用之前手动设置一下是好使的

**Comment by xlgo** [comment]
@looly    
ParameterList.splitLongParameters  这家伙是一个private static final boolean，他的初始化在你设置之前了，所以你再 MailAccount.getSmtpProps 设置没有作用了

**Comment by pivotbbq** [comment]
attachment.setFileName(MimeUtility.encodeText(fileName));中文的话filename encode一下
