### ISSUE TITLE
Cache抛出ConcurrentModificationException异常

### ISSUE THREAD

**Issue by NoErla** [looly/hutool#2093]
### 版本情况

JDK版本：    1.8
hutool版本： 5.7.19
### 问题描述（包括截图）

应该是缓存底层是hashmap导致的问题吧。使用ConcurrentHashMap就不会引起这个问题，或者把keySet()的内容放到新对象中也能解决

1. 复现代码

```java
TimedCache<String, String> cache = CacheUtil.newTimedCache(1000 * 3600);
//final ConcurrentHashMap<String, String> cache = new ConcurrentHashMap<>();
cache.put("1", "1");
cache.put("2", "1");
cache.put("3", "1");
final Set<String> keys = cache.keySet();
for (String key : keys) {
      System.out.println(key);
      cache.remove(key);
}
```

2. 堆栈信息

Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1584)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1607)

**Comment by CherryRum** [comment]
对于`hashmap`包括(hashset)等不要使用一边遍历一边删除
应该使用 Iterator 迭代器遍历,删除.
`ConcurrentHashMap`,会自己检查删除操作,所以不会报错

**Comment by CherryRum** [comment]
您可以尝试,
``` java
System.out.println(cache.size());
cache.remove(key);
System.out.println(cache.size());
```

**Comment by NoErla** [comment]
谢谢回复。其实我主要是担心cache底层是hashmap的话，多线程下会不会出现问题。

**Comment by NoErla** [comment]
尝试使用迭代器进行删除的结果如下
```java
TimedCache<String, String> cache = CacheUtil.newTimedCache(1000 * 3600);
cache.put("1", "1");
cache.put("2", "1");
cache.put("3", "1");
final Iterator<String> it = cache.iterator();
while (it.hasNext()){
      final String next = it.next();
      if ("1".equals(next)){
            it.remove();
      }
}
```
会报错
Exception in thread "main" java.lang.UnsupportedOperationException: Cache values Iterator is not support to modify.
at cn.hutool.cache.impl.CacheObjIterator.remove(CacheObjIterator.java:58)
at cn.hutool.cache.impl.CacheValuesIterator.remove(CacheValuesIterator.java:46)

是否是我使用方式有错误，或者有更好的迭代删除方式呢。

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/149283575-c5f76139-67ee-49b0-8aca-ba74782b9448.png)
作者意思是不让通过迭代器删除了,那可能需要重新开辟一个空间再删除

**Comment by CherryRum** [comment]
> 谢谢回复。其实我主要是担心cache底层是hashmap的话，多线程下会不会出现问题。

这个貌似我看了,加过锁了

**Comment by CherryRum** [comment]
不知道您是不是这个意思
```java
public static void main(String[] args) {
		TimedCache<String, String> cache = CacheUtil.newTimedCache(1000 * 3600);
		cache.put("1", "1");
		cache.put("2", "1");
		cache.put("3", "1");
		Set<String> sets  = cache.keySet();
		List<String> lists = new LinkedList<>(sets);

		for(String list:lists){
			if(list.equals("2")) {
				cache.remove(list);
			}
		}

		for (String entry : sets) {
			System.out.println("key=" + entry + "," + "value=" + cache.get(entry));
		}
	}
```

**Comment by NoErla** [comment]
是的，我现在就是这么遍历删除的，但是总感觉怪怪的。谢谢了。

**Comment by CherryRum** [comment]
> 是的，我现在就是这么遍历删除的，但是总感觉怪怪的。谢谢了。

大概看了下,你的迭代器删除是不是意思错了

```java
public static void main(String[] args) {
		TimedCache<String, String> cache = CacheUtil.newTimedCache(1000 * 3600);
		cache.put("1", "1");
		cache.put("2", "1");
		cache.put("3", "1");

		
		for(Iterator<String> iterator = cache.keySet().iterator();iterator.hasNext();){
			String key = iterator.next();
			if ("1".equals(key)){
				iterator.remove();
			}
		}


		for (String entry : cache.keySet()) {
			System.out.println("key=" + entry + "," + "value=" + cache.get(entry));
		}
	}
```

可以优化成`jdk8的方法引用`
```java
public static void main(String[] args) {
		TimedCache<String, String> cache = CacheUtil.newTimedCache(1000 * 3600);
		cache.put("1", "1");
		cache.put("2", "1");
		cache.put("3", "1");
		cache.keySet().removeIf("1"::equals);

		for (String entry : cache.keySet()) {
			System.out.println("key=" + entry + "," + "value=" + cache.get(entry));
		}
	}
```

**Comment by NoErla** [comment]
漂亮的写法
学到了，谢谢。

**Comment by CherryRum** [comment]
能帮助你就行,可以有多个条件呀,麻烦关闭下`issue`
```java
cache.keySet().removeIf(
				x->x.equals("1")||x.equals("2")
		);
```

**Comment by looly** [comment]
@CherryRum 厉害了老铁。
