### ISSUE TITLE
字符串分割类，好像当匹配的结果在字符串最后的时候，会报错

### ISSUE THREAD

**Issue by nianqinianyi** [looly/hutool#2099]
### 版本情况

JDK版本：    oracle jdk1.8.0_291
hutool版本： 5.7.18/5.7.19 （5.7.20 暂时在 mvnrepository.com 还没看到）

### 问题描述（包括截图）

字符串分割类，好像当匹配的结果在字符串最后的时候，会报错。使用java自带的split不会出问题。

1. 复现代码

```java
package cn.sixlab.minesoft.test;

import cn.hutool.core.text.StrSplitter;
import cn.hutool.json.JSONUtil;

public class Test {
    public static void main(String[] args) {
        String text = "01  821   34567890182345617821";
        // 正常
        System.out.println(JSONUtil.toJsonStr(text.split("82")));
        System.out.println(JSONUtil.toJsonStr(text.split("21")));
        System.out.println(JSONUtil.toJsonStr(text.split("[123]")));
        System.out.println(JSONUtil.toJsonStr(StrSplitter.splitByRegex(text, "82", 0, false, true)));

        // 报错
        try {
            System.out.println(JSONUtil.toJsonStr(StrSplitter.splitByRegex(text, "21", 0, false, true)));
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            System.out.println(JSONUtil.toJsonStr(StrSplitter.splitByRegex(text, "[123]", 0, false, true)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

2. 堆栈信息
```text
["01  ","1   345678901","345617","1"]
["01  8","   345678901823456178"]
["0","  8","","   ","4567890","8","","456","78"]
["01  ","1   345678901","345617","1"]
java.lang.IndexOutOfBoundsException: Illegal start index
	at java.util.regex.Matcher.find(Matcher.java:662)
	at cn.hutool.core.text.finder.PatternFinder.start(PatternFinder.java:51)
	at cn.hutool.core.text.split.SplitIter.computeNext(SplitIter.java:74)
	at cn.hutool.core.text.split.SplitIter.computeNext(SplitIter.java:21)
	at cn.hutool.core.collection.ComputeIter.hasNext(ComputeIter.java:42)
	at cn.hutool.core.text.split.SplitIter.toList(SplitIter.java:141)
	at cn.hutool.core.text.split.SplitIter.toList(SplitIter.java:129)
	at cn.hutool.core.text.StrSplitter.split(StrSplitter.java:402)
	at cn.hutool.core.text.StrSplitter.splitByRegex(StrSplitter.java:382)
	at cn.sixlab.minesoft.test.Test.main(Test.java:17)
java.lang.IndexOutOfBoundsException: Illegal start index
	at java.util.regex.Matcher.find(Matcher.java:662)
	at cn.hutool.core.text.finder.PatternFinder.start(PatternFinder.java:51)
	at cn.hutool.core.text.split.SplitIter.computeNext(SplitIter.java:74)
	at cn.hutool.core.text.split.SplitIter.computeNext(SplitIter.java:96)
	at cn.hutool.core.text.split.SplitIter.computeNext(SplitIter.java:21)
	at cn.hutool.core.collection.ComputeIter.hasNext(ComputeIter.java:42)
	at cn.hutool.core.text.split.SplitIter.toList(SplitIter.java:141)
	at cn.hutool.core.text.split.SplitIter.toList(SplitIter.java:129)
	at cn.hutool.core.text.StrSplitter.split(StrSplitter.java:402)
	at cn.hutool.core.text.StrSplitter.splitByRegex(StrSplitter.java:382)
	at cn.sixlab.minesoft.test.Test.main(Test.java:22)

Process finished with exit code 0
```

3. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
PatternFinder的end边界判断有问题。

5.7.20修复此问题，感谢。
