### ISSUE TITLE
`IdUtil.getDataCenterId(Long.MAX_VALUE)` 偶尔会出现小于等于1的 `dataCenterId`

### ISSUE THREAD

**Issue by wangliang181230** [looly/hutool#2101]
测试不通过日志：
```java
[INFO] Running cn.hutool.core.util.IdUtilTest
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 0.088 s <<< FAILURE! - in cn.hutool.core.util.IdUtilTest
Error:  getDataCenterIdTest  Time elapsed: 0.012 s  <<< FAILURE!
java.lang.AssertionError
	at cn.hutool.core.util.IdUtilTest.getDataCenterIdTest(IdUtilTest.java:141)
```

`IdUtilTest` 测试用例源码:
```java
@Test
public void getDataCenterIdTest(){
	final long dataCenterId = IdUtil.getDataCenterId(Long.MAX_VALUE);
	Assert.assertTrue(dataCenterId > 1);
}
```

**Comment by CherryRum** [comment]
麻烦您看下您的ip地址获取正确吗？
我这边测试`100`次也没有出现异常

**Comment by wangliang181230** [comment]
> 麻烦您看下您的ip地址获取正确吗？ 我这边测试`100`次也没有出现异常

@CherryRum 
我这边运行过几百多次，也是第一次出现。
我这边暂时改了一下测试用例的代码，等复现后，我再把相关原因发出来吧。

**Comment by CherryRum** [comment]
好的 这玩意获取的mac地址，所以每个人的都不太好测试

**Comment by wangliang181230** [comment]
我也是扔到 `github/actions` 上在自动测的，所以也不是我的本地环境。
我重新运行了一次 对应的测试任务，结果又成功的。
等我多试几次看看再说吧。

**Comment by CherryRum** [comment]
我猜测是 容器的问题

**Comment by CherryRum** [comment]
我大概看了下算法 确实和我之前背的有一点点偏差

**Comment by wangliang181230** [comment]
```java
[INFO] Running cn.hutool.core.util.IdUtilTest
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 0.026 s <<< FAILURE! - in cn.hutool.core.util.IdUtilTest
Error:  getDataCenterIdTest  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: 校验 'dataCenterId > 1' 不通过：dataCenterId = 1, host = /172.17.0.1, mac = [2,66,87,25,123,0]
	at cn.hutool.core.util.IdUtilTest.getDataCenterIdTest(IdUtilTest.java:156)
```

调整后的测试用例源码：
```java
@Test
public void getDataCenterIdTest(){
	//final long dataCenterId = IdUtil.getDataCenterId(Long.MAX_VALUE);
	//Assert.assertTrue(dataCenterId > 1);

	long dataCenterId = 1L;
	InetAddress host = NetUtil.getLocalhost();
	final byte[] mac = NetUtil.getHardwareAddress(host);
	if (null != mac) {
		dataCenterId = ((0x000000FF & (long) mac[mac.length - 2])
				| (0x0000FF00 & (((long) mac[mac.length - 1]) << 8))) >> 6;
		dataCenterId = dataCenterId % (Long.MAX_VALUE + 1);
	}

	System.out.println("dataCenterId = " + dataCenterId + ", host = " + host + ", mac = " + toString(mac));

	Assert.assertTrue("校验 'dataCenterId > 1' 不通过：dataCenterId = " + dataCenterId + ", host = " + host + ", mac = " + toString(mac), dataCenterId > 1);
}
```

**Comment by wangliang181230** [comment]
> 我大概看了下算法 确实和我之前背的有一点点偏差

又复现出来了。
我是直接把方法里面的代码拿出来了。主要是想看下mac是不是为null。
结果，dataCenterId是0，mac不为null。

**Comment by CherryRum** [comment]
您试试这个
```java
 id = ((0x000000FF & (long) mac[mac.length - 1])
                        | (0x0000FF00 & (((long) mac[mac.length - 2]) << 8))) >> 6;
```

**Comment by wangliang181230** [comment]
> 您试试这个
> 
> ```java
>  id = ((0x000000FF & (long) mac[mac.length - 1])
>                         | (0x0000FF00 & (((long) mac[mac.length - 2]) << 8))) >> 6;
> ```

不行，返回0了。

**Comment by wangliang181230** [comment]
> > 您试试这个
> > ```java
> >  id = ((0x000000FF & (long) mac[mac.length - 1])
> >        | (0x0000FF00 & (((long) mac[mac.length - 2]) << 8))) >> 6;
> > ```
> 
> 不行，返回0了。

**Comment by CherryRum** [comment]
我大概知道了，看了下 代码确实有点问题，下个版本应该会有修正

**Comment by wangliang181230** [comment]
> 我大概知道了，看了下 代码确实有点问题，下个版本应该会有修正

好的。

**Comment by looly** [comment]
5.7.20做一些修改，允许返回0。

见：https://github.com/dromara/hutool/pull/2105
