### ISSUE TITLE
使用c3p0；Connection connection = Db.use().getConnection()；丢失用户名密码

### ISSUE THREAD

**Issue by polarxy** [looly/hutool#2134]
DataSource dataSource = new C3p0DSFactory(new Setting("db.setting", true)).getDataSource();
Connection connection = Db.use().getConnection();
System.out.println(connection);
connection.close();

Exception in thread "main" java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at cn.hutool.db.ds.DataSourceWrapper.getConnection(DataSourceWrapper.java:105)
	at cn.hutool.db.ThreadLocalConnection$GroupedConnection.get(ThreadLocalConnection.java:75)
	at cn.hutool.db.ThreadLocalConnection.get(ThreadLocalConnection.java:35)
	at cn.hutool.db.Db.getConnection(Db.java:129)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
Caused by: java.sql.SQLException: Access denied for user ''@'localhost' (using password: NO)

由于 cn.hutool.db.ds.c3p0.C3p0DSFactory createDataSource方法中有如下代码，导致报错
// remarks等特殊配置，since 5.3.8
final Props connProps = new Props();
String connValue;
for (String key : KEY_CONN_PROPS) {
	connValue = poolSetting.getAndRemoveStr(key);
	if(StrUtil.isNotBlank(connValue)){
		connProps.setProperty(key, connValue);
	}
}
ds.setProperties(connProps);

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I4T7XZ
