### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by jimmyshealisa** [looly/hutool#2137]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/48204246/153534173-92f28abf-8cc1-4d33-b53d-2d1549a112fc.png">

1. 复现代码

```java
 String taskDetailStr = HttpRequest.get("https://xxxxxx)
                            .header("Authorization", "x'x'x'x'x").timeout(1000 * 60 * 30)
                            .setChunkedStreamingMode(0)
                            .execute.body();
```

2. 堆栈信息
java.lang.OutOfMemoryError: Java heap space
        at cn.hutool.core.io.FastByteBuffer.toArray(FastByteBuffer.java:213)
        at cn.hutool.core.io.FastByteArrayOutputStream.toByteArray(FastByteArrayOutputStream.java:96)
        at cn.hutool.http.HttpResponse.readBody(HttpResponse.java:567)
        at cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:536)
        at cn.hutool.http.HttpResponse.init(HttpResponse.java:517)
        at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:462)
        at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:75)
        at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1113)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:997)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:973)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by xyz327** [comment]
看起来像是 http返回值太大了。Jvm Xmx 太小导致 OOM了

**Comment by jimmyshealisa** [comment]
> 

除了调整Xmx，其他还有什么办法吗

**Comment by 818000** [comment]
Thank you. Your email is received and will be handled  as soon as possible.

**Comment by xyz327** [comment]
> > 
> 
> 除了调整Xmx，其他还有什么办法吗

jvm 剩余对空间存不下 返回值。不能改xmx 那就看你对返回值要做什么处理咯。 把返回值的流 写入到文件。再处理文件？
