### ISSUE TITLE
LRUCache并发写报错

### ISSUE THREAD

**Issue by DavidCalls** [looly/hutool#2140]
### 版本情况

JDK版本：   
 java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

hutool版本：  
<dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.7.21</version>
 </dependency>

### 问题描述（包括截图）

LRUCache并发写报错，一般出现在修改相同的key，异常堆栈以及测试代码如下

`Exception in thread "Thread-9" java.util.ConcurrentModificationException
 at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
 at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
 at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
 at java.util.AbstractMap.toString(AbstractMap.java:554)
 at cn.hutool.cache.impl.AbstractCache.toString(AbstractCache.java:191)
 at java.lang.String.valueOf(String.java:2994)
 at java.io.PrintStream.println(PrintStream.java:821)
 at com.TestLRUCache.lambda$main$0(TestLRUCache.java:17)
 at java.lang.Thread.run(Thread.java:748)`

1. 复现代码

```java
package com;


import cn.hutool.cache.CacheUtil;
import cn.hutool.cache.impl.LRUCache;

/**
 * @author jianwei.long
 */
public class TestLRUCache {
    public static void main(String[] args) {
        LRUCache<String, Object> tagCache = CacheUtil.newLRUCache(20000, 1000 * 60 * 60 * 6);

        for (int i = 0; i < 1000; i++) {
            int finalI = i;
            new Thread(() -> {
                System.out.println(tagCache);
                //tagCache.put("" + i1, map.get("" + i1));
                tagCache.put(String.valueOf(finalI %5), new Object());
            }).start();

        }
        try {
            Thread.sleep(1000000000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

```

2. 堆栈信息
Exception in thread "Thread-9" java.util.ConcurrentModificationException
 at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
 at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
 at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
 at java.util.AbstractMap.toString(AbstractMap.java:554)
 at cn.hutool.cache.impl.AbstractCache.toString(AbstractCache.java:191)
 at java.lang.String.valueOf(String.java:2994)
 at java.io.PrintStream.println(PrintStream.java:821)
 at com.TestLRUCache.lambda$main$0(TestLRUCache.java:17)
 at java.lang.Thread.run(Thread.java:748)
3. 截图
![image](https://user-images.githubusercontent.com/26464954/153861734-5df3b4a1-033e-4a84-bfc1-6eb9a7a24d2b.png)

**Comment by xyz327** [comment]
` System.out.println(tagCache);`
 这行导致的异常。删掉就好了

**Comment by DavidCalls** [comment]
如果需要打印缓存的话，确实有问题的

**Comment by DavidCalls** [comment]
> ` System.out.println(tagCache);` 这行导致的异常。删掉就好了

如果需要打印缓存的话，确实是有问题的

**Comment by xyz327** [comment]
> > ` System.out.println(tagCache);` 这行导致的异常。删掉就好了
> 
> 如果需要打印缓存的话，确实是有问题的

想不到什么场景下需要打印整个 cache 对象。如果要输出 cache 里面所有的值，可以用`tagCache.cacheObjIterator()`. 
`cache.toString()` 是直接打印内部的 map.  可以重写下 toString 变成线程安全的

**Comment by looly** [comment]
确实问题出在`toString`方法上，5.7.22修复这个方法也加锁。

感谢。

**Comment by CherryRum** [comment]
> 确实问题出在`toString`方法上，5.7.22修复这个方法也加锁。
> 
> 感谢。

刚准备说，哈哈，老哥太快了
