### ISSUE TITLE
mongodb客户端能支持4版本的么？

### ISSUE THREAD

**Issue by 905407220** [looly/hutool#2155]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.17（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
mongodb客户端能支持4版本的么？，目前代码里的只是3版本的
1. 复现代码

Setting setting = Setting.create();
        setting.set("connectionsPerHost","10");
        setting.set("maxWaitTime","120000");
        setting.set("connectTimeout","0");
        setting.set("socketTimeout","0");
        setting.set("socketKeepAlive","false");
        setting.set("threadsAllowedToBlockForConnectionMultiplier","10");
        MongoDS mongoDS = new MongoDS(setting,"192.168.1.43",29018);
        MongoDatabase oa = mongoDS.getDb("oa");
        System.out.println(oa.getName());

2. 堆栈信息
Exception in thread "main" java.lang.NoClassDefFoundError: com/mongodb/MongoClient
	at cn.hutool.db.nosql.mongo.MongoDS.initSingle(MongoDS.java:150)
	at cn.hutool.db.nosql.mongo.MongoDS.<init>(MongoDS.java:67)
	at com.glgsoft.oa.Test.main(Test.java:188)
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 3 more

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个确实没有，MongoDB客户端升级后API变化很大。

参考：https://docs.mongodb.com/drivers/java/sync/current/

**Comment by VampireAchao** [comment]
[简单写了点，试试？](https://gitee.com/dromara/hutool/pulls/568)

**Comment by looly** [comment]
见：https://gitee.com/dromara/hutool/pulls/568
