### ISSUE TITLE
JSONUtil已经支持解析xml, 但是后续重新解析json导致报错

### ISSUE THREAD

**Issue by LoveofRedMoon** [looly/hutool#2160]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

`JSONUtil.parse`的时候, 本质已经支持了`xml`的解析了, 例如下方代码中, 在`XML.toJSONObject`方法调用完后, 其实JSONObject已经解析完了, 但是后续的`init`方法判断了首个字符不为`{`导致了报错, 是否需要在`XML.toJSONObject(this, jsonStr, false);`直接`return`?

1. 复现代码

```java
        //  JSONObject.class:702
	/**
	 * 初始化，可以判断字符串为JSON或者XML
	 *
	 * @param source JSON字符串
	 */
	private void init(CharSequence source) {
		final String jsonStr = StrUtil.trim(source);
		if (StrUtil.startWith(jsonStr, '<')) {
			// 可能为XML
			XML.toJSONObject(this, jsonStr, false);
		}
		init(new JSONTokener(StrUtil.trim(source), this.config));
	}
```

2. 堆栈信息
```log
Exception in thread "main" cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
	at cn.hutool.json.JSONObject.init(JSONObject.java:717)
	at cn.hutool.json.JSONObject.init(JSONObject.java:704)
	at cn.hutool.json.JSONObject.init(JSONObject.java:660)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:120)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:232)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:206)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:465)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:451)
```
3. 测试涉及到的文件（注意脱密）
`
JSONUtil.parseObject("<sso></sso>")
`

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.7.22修复此问题，感谢。

**Comment by willsmithchen** [comment]
cn.hutool.json.JSONException: Mismatched hr and body at 164 [character 6 line 6]

**Comment by willsmithchen** [comment]
@looly
