### ISSUE TITLE
http模块不兼容部分android，里面有assert找不到

### ISSUE THREAD

**Issue by zhangweihust** [looly/hutool#2173]
implementation 'cn.hutool:hutool-core:5.7.21'
    implementation 'cn.hutool:hutool-http:5.7.21'

环境:  android模拟器

   
  Caused by: java.lang.NoClassDefFoundError: cn.hutool.core.lang.-$$Lambda$Assert$eSa13geDXfUFtcOuHoGzKFFBDCo
        at cn.hutool.core.lang.Assert.notNull(Assert.java:216)
        at cn.hutool.http.HttpDownloader.download(HttpDownloader.java:96)
        at cn.hutool.http.HttpDownloader.downloadString(HttpDownloader.java:29)
        at cn.hutool.http.HttpUtil.downloadString(HttpUtil.java:265)
        at cn.hutool.http.HttpUtil.downloadString(HttpUtil.java:253)
。。。

其实就是这里：
	/**
	 * 下载远程文件
	 *
	 * @param url            请求的url
	 * @param out            将下载内容写到输出流中 {@link OutputStream}
	 * @param isCloseOut     是否关闭输出流
	 * @param streamProgress 进度条
	 * @return 文件大小
	 */
	public static long download(String url, OutputStream out, boolean isCloseOut, StreamProgress streamProgress) {
		Assert.notNull(out, "[out] is null !");

		return requestDownload(url, -1).writeBody(out, isCloseOut, streamProgress);
	}

建议直接抛异常吧

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/156497938-342a590b-42a5-4698-8f1b-e7a876870281.png)

**Comment by looly** [comment]
看样子像是你的Android版本不支持lambda，检查你的运行环境针对JDK的兼容级别。
