### ISSUE TITLE
Illegal character in query at index...

### ISSUE THREAD

**Issue by fangdengfu** [looly/hutool#2233]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22+（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
HttpUtil.get(url)  

1. 复现代码

```java
public static void main(String[] args) {
        String url = "http://178.13.4.200:9000/api/getIpoRank?name=IPO排名&area={\"url\":\"/hello/proxy/es\",\"requestMethod\":\"get\",\"cType\":1}&industry=getIpoRank&t=098F6BCD4621D373CADE4E832627B4F6&u=645856";
        String res = HttpUtil.get(url);
        System.out.println(res);
    }
```

2. 堆栈信息
Exception in thread "main" cn.hutool.core.exceptions.UtilException: URISyntaxException: Illegal character in query at index 56: http://178.13.4.200:9000/api/getIpoRank?name=IPO排名&area={"url":"/hello/proxy/es","requestMethod":"get","cType":1}&industry=getIpoRank&t=098F6BCD4621D373CADE4E832627B4F6&u=645856
	at cn.hutool.core.util.URLUtil.toURI(URLUtil.java:476)
	at cn.hutool.core.util.URLUtil.toURI(URLUtil.java:446)
	at cn.hutool.core.util.URLUtil.toURI(URLUtil.java:429)
	at cn.hutool.http.cookie.GlobalCookieManager.getURI(GlobalCookieManager.java:106)
	at cn.hutool.http.cookie.GlobalCookieManager.add(GlobalCookieManager.java:72)
	at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1153)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1111)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1004)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:980)
	at cn.hutool.http.HttpUtil.get(HttpUtil.java:145)
	at cn.hutool.http.HttpUtil.get(HttpUtil.java:133)
	at cn.com.bdo.hutool.Test.main(Test.java:15)
Caused by: java.net.URISyntaxException: Illegal character in query at index 56: http://172.17.4.240:9000/api/getIpoRank?name=IPO排名&area={"url":"/hello/proxy/es","requestMethod":"get","cType":1}&industry=getIpoRank&t=098F6BCD4621D373CADE4E832627B4F6&u=645856
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at cn.hutool.core.util.URLUtil.toURI(URLUtil.java:474)
	... 11 more

Process finished with exit code 1

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个是编码默认关闭导致的问题。

见：https://gitee.com/dromara/hutool/issues/I50NHQ
