### ISSUE TITLE
使用SpringNative运行时发生错误

### ISSUE THREAD

**Issue by mrchar** [looly/hutool#2241]
### 版本情况

JDK版本：    graalvm-ce-java17-21.3.0
hutool版本： 5.7.22

### 问题描述

我的项目用到了spring nativa，使用JVM运行时没有问题，但是nativeCompile编译出来的exe执行时就会报错。  
如果不引入`org.bouncycastle:bcprov-jdk15to18:1.66`会报错`cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC`。  
如果引入`org.bouncycastle:bcprov-jdk15to18:1.66`会报错`java.lang.NoSuchMethodError: cn.hutool.crypto.ProviderFactory.createBouncyCastleProvider():`。

1. 复现代码

```java
Digester digester = new Digester(SHA256);
byte[] hashed = digester.digest("hello world");
```

2. 堆栈信息

java.lang.NoSuchMethodError: cn.hutool.crypto.ProviderFactory.createBouncyCastleProvider():
```
java.lang.NoSuchMethodError: cn.hutool.crypto.ProviderFactory.createBouncyCastleProvider()
        at cn.hutool.crypto.GlobalBouncyCastleProvider.<init>(GlobalBouncyCastleProvider.java:18) ~[na:na]
        at cn.hutool.crypto.GlobalBouncyCastleProvider.<clinit>(GlobalBouncyCastleProvider.java:11) ~[na:na]
        at cn.hutool.crypto.SecureUtil.createMessageDigest(SecureUtil.java:1031) ~[na:na]
        at cn.hutool.crypto.digest.Digester.init(Digester.java:92) ~[na:na]
        at cn.hutool.crypto.digest.Digester.<init>(Digester.java:78) ~[na:na]
        at cn.hutool.crypto.digest.Digester.<init>(Digester.java:56) ~[na:na]
        at cn.hutool.crypto.digest.Digester.<init>(Digester.java:47) ~[na:na]
        at cn.com.gobiz.model.AbstractModel.sign(AbstractModel.java:43) ~[endpoint.exe:na]
        at cn.com.gobiz.ClientImpl.doRequest(ClientImpl.java:47) ~[na:na]
        at cn.com.gobiz.ClientImpl.pushRfids(ClientImpl.java:90) ~[na:na]
        at com.gracechain.orientaleagle.endpoint.rfid.GobizHandler.handleEvent(GobizHandler.java:38) ~[endpoint.exe:na]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[na:na]
        at org.springframework.aop.framework.Interceptors$OptimizedReflectiveMethodInvocation.invokeJoinpoint(Interceptors.java:415) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[na:na]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.lang.Thread.run(Thread.java:833) ~[na:na]
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596) ~[na:na]
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138) ~[na:na]
```

cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC:

```
cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC
        at cn.hutool.crypto.SecureUtil.createMessageDigest(SecureUtil.java:1037) ~[na:na]
        at cn.hutool.crypto.digest.Digester.init(Digester.java:92) ~[na:na]
        at cn.hutool.crypto.digest.Digester.<init>(Digester.java:78) ~[na:na]
        at cn.hutool.crypto.digest.Digester.<init>(Digester.java:56) ~[na:na]
        at cn.hutool.crypto.digest.Digester.<init>(Digester.java:47) ~[na:na]
        at cn.com.gobiz.model.AbstractModel.sign(AbstractModel.java:43) ~[endpoint.exe:na]
        at cn.com.gobiz.ClientImpl.doRequest(ClientImpl.java:47) ~[na:na]
        at cn.com.gobiz.ClientImpl.pushRfids(ClientImpl.java:90) ~[na:na]
        at com.gracechain.orientaleagle.endpoint.rfid.GobizHandler.handleEvent(GobizHandler.java:38) ~[endpoint.exe:na]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[na:na]
        at org.springframework.aop.framework.Interceptors$OptimizedReflectiveMethodInvocation.invokeJoinpoint(Interceptors.java:415) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[na:na]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.lang.Thread.run(Thread.java:833) ~[na:na]
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596) ~[na:na]
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138) ~[na:na]
Caused by: java.security.NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC
        at sun.security.jca.GetInstance.getService(GetInstance.java:101) ~[na:na]
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:218) ~[na:na]
        at java.security.Security.getImpl(Security.java:730) ~[na:na]
        at java.security.MessageDigest.getInstance(MessageDigest.java:300) ~[na:na]
        at cn.hutool.crypto.SecureUtil.createMessageDigest(SecureUtil.java:1035) ~[na:na]
        ... 18 common frames omitted
```

**Comment by looly** [comment]
看样子像是包冲突。检查下Hutool是否多版本引入了？

**Comment by choubuzhaole** [comment]
> ### 版本情况
> JDK版本： graalvm-ce-java17-21.3.0 hutool版本： 5.7.22
> 
> ### 问题描述
> 我的项目用到了spring nativa，使用JVM运行时没有问题，但是nativeCompile编译出来的exe执行时就会报错。 如果不引入`org.bouncycastle:bcprov-jdk15to18:1.66`会报错`cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC`。 如果引入`org.bouncycastle:bcprov-jdk15to18:1.66`会报错`java.lang.NoSuchMethodError: cn.hutool.crypto.ProviderFactory.createBouncyCastleProvider():`。
> 
> 1. 复现代码
> 
> ```java
> Digester digester = new Digester(SHA256);
> byte[] hashed = digester.digest("hello world");
> ```
> 
> 2. 堆栈信息
> 
> java.lang.NoSuchMethodError: cn.hutool.crypto.ProviderFactory.createBouncyCastleProvider():
> 
> ```
> java.lang.NoSuchMethodError: cn.hutool.crypto.ProviderFactory.createBouncyCastleProvider()
>         at cn.hutool.crypto.GlobalBouncyCastleProvider.<init>(GlobalBouncyCastleProvider.java:18) ~[na:na]
>         at cn.hutool.crypto.GlobalBouncyCastleProvider.<clinit>(GlobalBouncyCastleProvider.java:11) ~[na:na]
>         at cn.hutool.crypto.SecureUtil.createMessageDigest(SecureUtil.java:1031) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.init(Digester.java:92) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.<init>(Digester.java:78) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.<init>(Digester.java:56) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.<init>(Digester.java:47) ~[na:na]
>         at cn.com.gobiz.model.AbstractModel.sign(AbstractModel.java:43) ~[endpoint.exe:na]
>         at cn.com.gobiz.ClientImpl.doRequest(ClientImpl.java:47) ~[na:na]
>         at cn.com.gobiz.ClientImpl.pushRfids(ClientImpl.java:90) ~[na:na]
>         at com.gracechain.orientaleagle.endpoint.rfid.GobizHandler.handleEvent(GobizHandler.java:38) ~[endpoint.exe:na]
>         at java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
>         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[na:na]
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[na:na]
>         at org.springframework.aop.framework.Interceptors$OptimizedReflectiveMethodInvocation.invokeJoinpoint(Interceptors.java:415) ~[na:na]
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[na:na]
>         at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[na:na]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
>         at java.lang.Thread.run(Thread.java:833) ~[na:na]
>         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596) ~[na:na]
>         at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138) ~[na:na]
> ```
> 
> cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC:
> 
> ```
> cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC
>         at cn.hutool.crypto.SecureUtil.createMessageDigest(SecureUtil.java:1037) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.init(Digester.java:92) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.<init>(Digester.java:78) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.<init>(Digester.java:56) ~[na:na]
>         at cn.hutool.crypto.digest.Digester.<init>(Digester.java:47) ~[na:na]
>         at cn.com.gobiz.model.AbstractModel.sign(AbstractModel.java:43) ~[endpoint.exe:na]
>         at cn.com.gobiz.ClientImpl.doRequest(ClientImpl.java:47) ~[na:na]
>         at cn.com.gobiz.ClientImpl.pushRfids(ClientImpl.java:90) ~[na:na]
>         at com.gracechain.orientaleagle.endpoint.rfid.GobizHandler.handleEvent(GobizHandler.java:38) ~[endpoint.exe:na]
>         at java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
>         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[na:na]
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[na:na]
>         at org.springframework.aop.framework.Interceptors$OptimizedReflectiveMethodInvocation.invokeJoinpoint(Interceptors.java:415) ~[na:na]
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[na:na]
>         at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[na:na]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
>         at java.lang.Thread.run(Thread.java:833) ~[na:na]
>         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596) ~[na:na]
>         at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138) ~[na:na]
> Caused by: java.security.NoSuchAlgorithmException: no such algorithm: SHA-256 for provider BC
>         at sun.security.jca.GetInstance.getService(GetInstance.java:101) ~[na:na]
>         at sun.security.jca.GetInstance.getInstance(GetInstance.java:218) ~[na:na]
>         at java.security.Security.getImpl(Security.java:730) ~[na:na]
>         at java.security.MessageDigest.getInstance(MessageDigest.java:300) ~[na:na]
>         at cn.hutool.crypto.SecureUtil.createMessageDigest(SecureUtil.java:1035) ~[na:na]
>         ... 18 common frames omitted
> ```

你好是因为版本冲突吗，我现在也遇到这个问题，且我确定我的 hutool 没有多版本引入

**Comment by looly** [comment]
@choubuzhaole 你使用的是JDK17，graalvm打包时可能会将不使用的模块去除，确保你import了所有需要的模块。
