### ISSUE TITLE
关于HttpUtil.get() 的接口默认行为

### ISSUE THREAD

**Issue by winlans** [looly/hutool#2262]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
HttpUtil.get("https://www.xxx.com?p1=中文");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
```plain
java.lang.IllegalArgumentException: Invalid character found in the request target [/pay/h5_pay?uid=85823115&pay_type=1&app_key=16000431&product_id=15&product_name=0xe70xbb0x880xe80xba0xab0xe40xbc0x9a0xe50x910x98&app_order_id=VIP16504276552733&pay_rmb=1&extra1=21dab8103e6ab4cf5674a4345be7acd4&extra2=PRO_ACTIVITY_ORDER:rxmn43m56l:15:1&app_name=0xe70xbb0x880xe80xba0xab0xe40xbc0x9a0xe50x910x98]. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:490)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

````

之前hutool版本是5.7.18 升级到5.7.22 之后在请求接口的时候发生了400错误，解决问题之后是发现hutool在22版本，更改了`HttpUtil.get()`方法的默认行为， 这里的`decodeUrl`默认为`false`, 因此之前charset是默认`UTF-8` 现在变成了`null` 这种是不是不太合适。
![image](https://user-images.githubusercontent.com/16457089/164175160-7e6fd099-dc56-4d0b-ae11-86a891254f5a.png)

**Comment by looly** [comment]
这个是为了解决URL中编码字符和未编码字符混合的问题。

而且这个参数只会影响解码，可能你碰到bug了。

升级到5.8.0.M3试下，因该是解决了发送请求编码的问题。

见：http://hutool.cn/docs/#/CHANGELOG?id=%f0%9f%90%9ebug%e4%bf%ae%e5%a4%8d
