### ISSUE TITLE
bug BeanUtil遇到枚举就出bug

### ISSUE THREAD

**Issue by zhouxiaofu** [looly/hutool#2281]
### 版本情况

早两年用的时候BeanUtil遇到枚举就有bug，然后现在还有！！！

[两年前提的issue](https://github.com/dromara/hutool/issues/1327)
这两年一直用的springframework的BeanUtils

属性转换不了能不能不抛异常
用springframework或者Apache的BeanUtils都从来没报过错

每次用hutoo的BeanUtil有枚举的时候都要测一下，因为怕不能自动转换，然后再手动进行转换

JDK版本：    jdk1.8
hutool版本： 5.7.22 / 5.8.0.M3

项目用的5.7.22，下面代码用的5.8.0.M3进行测试

```java

import cn.hutool.core.bean.BeanUtil;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;

public class HutoolBug {

    public static void main(String[] args) {

        User user = new User();
        {
            user.setId(1L);
            user.setName("hutool");
            user.setStatus(UserStatus.INACTIVE.getCode());
        }
        UserResponse userResponse = BeanUtil.copyProperties(user,UserResponse.class);
        userResponse.setStatus(UserStatus.valueOf(user.getStatus()));
        System.out.println(userResponse);
    }


    @Data
    private static class User{
        private Long id;
        private String name;
        private Integer status;
    }

    @Data
    private static class UserResponse{
        private Long id;
        private String name;
        private UserStatus status;
    }

    @Getter
    @AllArgsConstructor
    private enum UserStatus {
        ACTIVE(1),
        INACTIVE(2),
        ;
        private final int code;

        public static UserStatus valueOf(int code) {
            for (UserStatus userStatus : values()) {
                if (userStatus.code == code) {
                    return userStatus;
                }
            }
            throw new IllegalArgumentException("UserStatus.valueOf code not found,code=" + code);
        }
    }

}

```

报错信息:
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant cn.com.hndyzy.yun.auth.test.bean.HutoolBug.UserStatus.2
	at java.lang.Enum.valueOf(Enum.java:238)
	at cn.hutool.core.convert.impl.EnumConverter.convertInternal(EnumConverter.java:46)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convertSpecial(ConverterRegistry.java:358)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:272)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:298)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:746)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:74)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:327)
	at cn.hutool.core.bean.copier.BeanToBeanCopier.lambda$copy$0(BeanToBeanCopier.java:78)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at cn.hutool.core.bean.copier.BeanToBeanCopier.copy(BeanToBeanCopier.java:50)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:89)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:741)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:705)
	at cn.com.hndyzy.yun.auth.test.bean.HutoolBug.main(HutoolBug.java:18)

**Comment by zhouxiaofu** [comment]
我自己在项目framework中继承hutool beanUtil，然后重写，完美解决

```java

import cn.hutool.core.bean.copier.CopyOptions;
import cn.hutool.core.util.ReflectUtil;
import java.util.Collection;
import java.util.List;

public class BeanUtil extends cn.hutool.core.bean.BeanUtil {

    public static <T> T copyProperties(Object source, Class<T> tClass, String... ignoreProperties) {
        T target = ReflectUtil.newInstanceIfPossible(tClass);
        copyProperties(source, target, CopyOptions.create().setIgnoreProperties(ignoreProperties).setIgnoreError(true));
        return target;
    }

    public static <T> List<T> copyToList(Collection<?> collection, Class<T> targetType, String... ignoreProperties) {
        return copyToList(collection, targetType,
            CopyOptions.create().setIgnoreError(true).setIgnoreProperties(ignoreProperties));
    }
}

```

**Comment by looly** [comment]
你直接使用`BeanUtil.copyProperties(source, target, CopyOptions.create().setIgnoreProperties(ignoreProperties).setIgnoreError(true));`不就行了？

默认规则修改会导致向下兼容问题，所以保持默认规则。
