### ISSUE TITLE
在循环向文件中写入1亿条数据的时候，会报错误：

### ISSUE THREAD

**Issue by weipengfei0508** [looly/hutool#2293]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在循环向文件中写入1亿条数据的时候，会报错误：
```java
Exception in thread "main" cn.hutool.core.io.IORuntimeException: FileNotFoundException: d:\0428.txt (另一个程序正在使用 此文件，进程无法访问。)
        at cn.hutool.core.io.file.FileWriter.getWriter(FileWriter.java:370)
        at cn.hutool.core.io.file.FileWriter.getPrintWriter(FileWriter.java:382)
        at cn.hutool.core.io.file.FileWriter.writeLines(FileWriter.java:209)
        at cn.hutool.core.io.file.FileWriter.writeLines(FileWriter.java:194)
        at cn.hutool.core.io.FileUtil.writeLines(FileUtil.java:2946)
        at cn.hutool.core.io.FileUtil.writeLines(FileUtil.java:2916)
        at cn.hutool.core.io.FileUtil.appendLines(FileUtil.java:2871)
        at cn.hutool.core.io.FileUtil.appendUtf8Lines(FileUtil.java:2828)
        at Main.main(Main.java:27)
Caused by: java.io.FileNotFoundException: d:\0428.txt (另一个程序正在使用此文件，进程无法访问。)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at cn.hutool.core.io.file.FileWriter.getWriter(FileWriter.java:368)
        ... 8 more
```
1. 代码如下

```java
 public static void main(String[] args) {
        // write your code here

        Scanner scanner = new Scanner(System.in);
        System.out.println("请输入生成文件路径：");
        String filePath = scanner.next();
        System.out.println("文件生成路径是=>" + filePath);
        System.out.println("请输入生成记录条数：");
        int recordCount = scanner.nextInt();
        System.out.println("生成记录条数是=>" + recordCount);
        File file = new File(filePath);
        for (int i = 0; i < recordCount; i++) {
            String uuid = getUuid();
            String recordStr = "{\"id\":\"%s\",\"userId\":\"w.local\",\"operationTime\":\"2022-04-06 18:18:31\",\"logType\":\"文件日志\",\"active\":\"创建\",\"targetProgram\":\"360ZIP\",\"sourceFileName\":\"C:\\\\LOGSTASH-6.3.2\\\\VENDOR\\\\BUNDLE\\\\JRUBY\\\\2.3.0\\\\GEMS\\\\RUBYZIP-1.2.1\\\\TEST\\\\DATA\\\\TEST.XLS\",\"purposeFileName\":\"\",\"clientIp\":\"192.168.1.214\",\"logLevel\":\"4\",\"description\":\"\",\"logHashCode\":\"-101964198\",\"operaTime\":\"2022-04-06 18:18:31\"}";
            List<String> lines = new ArrayList<>(1);
            lines.add(String.format(recordStr, uuid));
            FileUtil.appendUtf8Lines(lines, file);
        }
    }
```

![企业微信截图_16511376303781](https://user-images.githubusercontent.com/63090347/165721011-29936699-0bd2-42e7-9e78-79d3250a1d9f.png)

**Comment by looly** [comment]
首先我这边测试没有问题：
![image](https://user-images.githubusercontent.com/1432613/165728792-6c54158b-f4d0-44d3-aae7-d0df5b182392.png)

请检查Hutool是否为最新版本。

2是你的代码效率很低，因为`FileUtil.appendUtf8Lines(lines, file);`每次都要打开和关闭，你应该在循环外创建FileWriter，然后循环写出。

3是因为每次打开和关闭文件，导致文件锁可能被其他应用占用，可能导致你报这个错误。
