### ISSUE TITLE
Freemarker ResourceMode=STRING TemplateNotFoundException

### ISSUE THREAD

**Issue by friedwm** [looly/hutool#231]
版本：**4.3.2**, freemarker: **2.3.28**。
由于项目中已经在用freemarker了，不想再引入其他模板引擎。
因为要动态传入模板，所以使用默认Configuration: 

```java
    Engine engine = TemplateUtil.createEngine();
    Template template = engine.getTemplate("你好,${uname}");
    String render = template.render(Dict.create().set("uname", "中国"));
    System.out.println(render);
```

结果是报异常模板找不到：
```
Exception in thread "main" cn.hutool.core.io.IORuntimeException: TemplateNotFoundException: Template not found for name "你好,${uname}".
The name was interpreted by this TemplateLoader: StringTemplateLoader(Map { }).
	at cn.hutool.extra.template.engine.freemarker.FreemarkerEngine.getTemplate(FreemarkerEngine.java:58)
	at xyz.quxiao.play.lab.tmp.Tmp.main(Tmp.java:19)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "你好,${uname}".
The name was interpreted by this TemplateLoader: StringTemplateLoader(Map { }).
	at freemarker.template.Configuration.getTemplate(Configuration.java:2797)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2599)
	at cn.hutool.extra.template.engine.freemarker.FreemarkerEngine.getTemplate(FreemarkerEngine.java:56)
	... 1 more
```

======
PS: 如果引入了Beetle则不会报错

**Comment by looly** [comment]
之前没有对Freemarker的字符串模板形式做实现。

4.3.3添加此功能。感谢。
