### ISSUE TITLE
使用Convert类型转换工具异常

### ISSUE THREAD

**Issue by zhangzhiyong-ay** [looly/hutool#2341]
### 版本情况

JDK版本：    openjdk version "1.8.0_302"
hutool版本： 5.8.1
### 问题描述（包括截图）
使用类型转换工具 cn.hutool.core.convert.Convert  将 java.time.LocalDateTime 转换为  java.time.LocalDate 时出现异常，异常信息：Exception in thread "main" java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.time.LocalDate

1. 复现代码

```java
public static void main(String[] args) {
        LocalDateTime localDateTime = LocalDateTime.now();
        LocalDate convert = Convert.convert(LocalDate.class, localDateTime);
        System.out.println(convert.getClass());
    }
```
控制台输出信息：
```java
Exception in thread "main" java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.time.LocalDate
	at ConvertTest.main(ConvertTest.java:12)
```

**Comment by CherryRum** [comment]
您应该这样获取
```java
LocalDateTime now = LocalDateTime.now();
LocalDate nowDate = now.toLocalDate();
```

**Comment by zhangzhiyong-ay** [comment]
演示只是简写了，实际业务上并不是固定要转为LocalDate.class 的，是根据反射获取Field的类型后转换的。
看简化后的业务代码吧。
```java
package com.cn;

import cn.hutool.core.convert.Convert;
import cn.hutool.core.util.ReflectUtil;

import java.lang.reflect.Field;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class ConvertTest {

    public static void main(String[] args) {
        // 时间值是第三方返回的数据，不同业务下，时间格式也不一样。
        // 可能是yyyy-MM，可能是yyyy-MM-dd，也可能是yyyy-MM-dd HH:mm:ss
        // 封装同一将返回的值先格式化为 localDateTime，然后根据不同的业务去转换该值。
        LocalDateTime now = LocalDateTime.now();

        // 简化后的业务
        // 第三方返回的时间字段，不同的业务使用不同类型来接收时间

        // 业务2 需要的是localDateTime
        Entity2 entity2 = convert(now, Entity2.class);
        System.out.println(entity2);

        // 业务1需要的是localDate
        Entity1 entity1 = convert(now, Entity1.class);
        System.out.println(entity1);


    }
    
    public static <T> T convert(LocalDateTime localDateTime, Class<T> tClass) {
        T entity = ReflectUtil.newInstance(tClass);
        Field[] fields = ReflectUtil.getFields(tClass);

        for (Field field : fields) {
            Object convertValue = Convert.convert(field.getType(), localDateTime);
            ReflectUtil.setFieldValue(entity, field, convertValue);
        }
        return entity;
    }

    public static class Entity1 {
        private LocalDate localDate;

        public LocalDate getLocalDate() {
            return localDate;
        }

        public Entity1 setLocalDate(LocalDate localDate) {
            this.localDate = localDate;
            return this;
        }

        @Override
        public String toString() {
            return "Entity1{" +
                    "localDate=" + localDate +
                    '}';
        }
    }

    public static class Entity2 {
        private LocalDateTime localDateTime;

        public LocalDateTime getLocalDateTime() {
            return localDateTime;
        }

        public Entity2 setLocalDateTime(LocalDateTime localDateTime) {
            this.localDateTime = localDateTime;
            return this;
        }

        @Override
        public String toString() {
            return "Entity2{" +
                    "localDateTime=" + localDateTime +
                    '}';
        }
    }
}

```
控制台输出结果：
```java
Entity2{localDateTime=2022-05-20T09:10:20.995}
Exception in thread "main" java.lang.IllegalArgumentException: Can not set java.time.LocalDate field com.cn.ConvertTest$Entity1.localDate to java.time.LocalDateTime
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at cn.hutool.core.util.ReflectUtil.setFieldValue(ReflectUtil.java:346)
	at com.cn.ConvertTest.convert(ConvertTest.java:38)
	at com.cn.ConvertTest.main(ConvertTest.java:26)

进程已结束,退出代码1

```

**Comment by zhangzhiyong-ay** [comment]
看源码是在 cn.hutool.core.convert.AbstractConverter类中 的 cn.hutool.core.convert.AbstractConverter#convert  方法导致的：
``` java
@Override
	@SuppressWarnings("unchecked")
	public T convert(Object value, T defaultValue) {
		Class<T> targetType = getTargetType();
		if (null == targetType && null == defaultValue) {
			throw new NullPointerException(StrUtil.format("[type] and [defaultValue] are both null for Converter [{}], we can not know what type to convert !", this.getClass().getName()));
		}
		if (null == targetType) {
			// 目标类型不确定时使用默认值的类型
			targetType = (Class<T>) defaultValue.getClass();
		}
		if (null == value) {
			return defaultValue;
		}

		if (null == defaultValue || targetType.isInstance(defaultValue)) {
			if (targetType.isInstance(value) && false == Map.class.isAssignableFrom(targetType)) {
				// 除Map外，已经是目标类型，不需要转换（Map类型涉及参数类型，需要单独转换）
				return targetType.cast(value);
			}
			T result = convertInternal(value);
			return ((null == result) ? defaultValue : result);
		} else {
			throw new IllegalArgumentException(
					StrUtil.format("Default value [{}]({}) is not the instance of [{}]", defaultValue, defaultValue.getClass(), targetType));
		}
	}
```
方法第一行 Class<T> targetType = getTargetType(); 返回的targetType类型是  java.time.temporal.TemporalAccessor。

**Comment by looly** [comment]
确实。

子类没有重写getType方法导致的，5.8.2修复。
