### ISSUE TITLE
NumberUtil无法判空

### ISSUE THREAD

**Issue by 2271659017** [looly/hutool#2350]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 57.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
public static void main(String[] args) {
    boolean b = NumberUtil.isDouble(null);
    System.out.println(b);
}
报错了：
Exception in thread "main" java.lang.NullPointerException
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at cn.hutool.core.util.NumberUtil.isDouble(NumberUtil.java:1274)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.2修复此问题，感谢。
