### ISSUE TITLE
HttpUtil如何设置忽略证书

### ISSUE THREAD

**Issue by oh-Aerox** [looly/hutool#2353]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.6

### 问题描述

1. 复现代码

```java
HttpUtil.get("https://localhost:80/manage
```

2. 堆栈信息
Unexpected error occurred in scheduled task
 cn.hutool.core.io.IORuntimeException: SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at cn.hutool.http.HttpRequest.send(HttpRequest.java:1164)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:969)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
        at cn.hutool.http.HttpUtil.get(HttpUtil.java:132)
        at cn.hutool.http.HttpUtil.get(HttpUtil.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

4. 测试涉及到的文件

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
升级到最新版本，默认忽略证书验证。
