### ISSUE TITLE
JSONUtil对byte[]转换问题

### ISSUE THREAD

**Issue by hdwang123** [looly/hutool#2365]
### 版本情况

JDK版本：    jdk-8u271-windows-x64.exe
hutool版本： 5.8.2

### 问题描述（包括截图）
包含byte[]类型的对象转换成json字符串后，无法再转换回来！希望能够默认将byte[]数组转换成数组字符串而不是Base64字符串。

1. 复现代码

```
@Data
public class FileInfo {

    private String fileName;

    private byte[] fileBytes;

}

File src = new File("001.txt");
byte[] fileBytes = FileUtil.readBytes(src);
FileInfo fileInfo = new FileInfo();
fileInfo.setFileBytes(fileBytes);
fileInfo.setFileName(src.getName());

String str = JSONUtil.toJsonStr(fileInfo);
JSONUtil.toBean(str, FileInfo.class, false);
```

2. 堆栈信息
java.lang.NumberFormatException: Unparseable number: "MDAx"
	at cn.hutool.core.util.NumberUtil.parseNumber(NumberUtil.java:2547)
	at cn.hutool.core.convert.impl.NumberConverter.convert(NumberConverter.java:119)
	at cn.hutool.core.convert.impl.PrimitiveConverter.convert(PrimitiveConverter.java:73)
	at cn.hutool.core.convert.impl.PrimitiveConverter.convertInternal(PrimitiveConverter.java:49)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:258)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:298)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:746)
	at cn.hutool.core.convert.impl.ArrayConverter.convertComponentType(ArrayConverter.java:198)
	at cn.hutool.core.convert.impl.ArrayConverter.convertArrayToArray(ArrayConverter.java:110)
	at cn.hutool.core.convert.impl.ArrayConverter.convertObjectToArray(ArrayConverter.java:129)
	at cn.hutool.core.convert.impl.ArrayConverter.convertInternal(ArrayConverter.java:72)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convertSpecial(ConverterRegistry.java:364)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:272)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:298)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:746)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:74)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:327)
	at cn.hutool.core.bean.copier.MapToBeanCopier.lambda$copy$0(MapToBeanCopier.java:86)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at cn.hutool.core.map.MapWrapper.forEach(MapWrapper.java:160)
	at cn.hutool.core.bean.copier.MapToBeanCopier.copy(MapToBeanCopier.java:60)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
	at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:78)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.Converter.convertWithCheck(Converter.java:35)
	at cn.hutool.json.JSONConverter.jsonToBean(JSONConverter.java:129)
	at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:95)
	at cn.hutool.json.JSON.toBean(JSON.java:185)
	at cn.hutool.json.JSONObject.toBean(JSONObject.java:289)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:477)

3. 测试涉及到的文件（注意脱密）

**Comment by hdwang123** [comment]
fastjson也有同样的问题，但是有解决办法，不知道你们是否有办法转成数组字符串？
![BT`8V)V1@KK~}K@H(U4OCXR](https://user-images.githubusercontent.com/19482651/172054405-62726128-da44-495f-8773-f4947ea8bd39.png)
如果实在不行，我用Base64字符串传输吧，byte[]好像好多问题。

**Comment by hdwang123** [comment]
经测试老版本byte[]转换是好的
![image](https://user-images.githubusercontent.com/19482651/172059621-e47962dd-646c-4771-bafa-043a9af9067f.png)

**Comment by hdwang123** [comment]
hutool: byte[]->base64->报错
fastjson:byte[]->数组->byte[]
jackson:byte[]->base64->byte[]

**Comment by looly** [comment]
5.8.2针对byte[]转换做的修改中，没有考虑Bean中字段的问题。

5.8.3修复此问题。

关联issue可以看：https://gitee.com/dromara/hutool/issues/I59LW4
