### ISSUE TITLE
SimpleCache get With NullPointerException

### ISSUE THREAD

**Issue by zhaomoran** [looly/hutool#2376]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Sftp sftp = new Sftp(host, port, user, password);
```

2. 堆栈信息
```
Exception in thread "main" java.lang.NullPointerException
	at cn.hutool.core.lang.SimpleCache.get(SimpleCache.java:99)
	at cn.hutool.extra.ssh.JschSessionPool.getSession(JschSessionPool.java:45)
	at cn.hutool.extra.ssh.JschUtil.getSession(JschUtil.java:55)
	at cn.hutool.extra.ssh.Sftp.init(Sftp.java:127)
	at cn.hutool.extra.ssh.Sftp.init(Sftp.java:146)
	at cn.hutool.extra.ssh.Sftp.<init>(Sftp.java:81)
	at cn.hutool.extra.ssh.Sftp.<init>(Sftp.java:70)
	at cn.hutool.extra.ssh.Sftp.<init>(Sftp.java:56)
```
3. 问题排查
https://github.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/lang/SimpleCache.java#L99
````
public V get(K key, Predicate<V> validPredicate, Func0<V> supplier) {
		V v = get(key);
                // 此处第一次访问时，v为null，调用validPredicate.test(v)时会报空指针异常
		if((null != validPredicate && false == validPredicate.test(v))){
			v = null;
		}
		................
		return v;
	}
````

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.3修复，重复issue，见：https://gitee.com/dromara/hutool/issues/I5BK4D
