### ISSUE TITLE
byte[]类型序列化方式最好统一一下

### ISSUE THREAD

**Issue by hdwang123** [looly/hutool#2377]
### 版本情况

JDK版本：     jdk-8u271-windows-x64.exe
hutool版本： 5.8.3

### 问题描述（包括截图）

1. 复现代码

```java
Object[] paramArray = new Object[]{ 1,new byte[]{10,11}, "报表.xlsx"};
        String paramsStr = JSONUtil.toJsonStr(paramArray);
        List<Object> paramList = JSONUtil.toList(paramsStr, Object.class);
        String paramBytesStr = JSONUtil.toJsonStr(paramList.get(1));
        byte[] paramBytes = JSONUtil.toBean(paramBytesStr, byte[].class, false);
        System.out.println(paramBytes);
```

2. 堆栈信息
Exception in thread "main" cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
	at cn.hutool.json.JSONParser.parseTo(JSONParser.java:51)
	at cn.hutool.json.ObjectMapper.mapFromTokener(ObjectMapper.java:239)
	at cn.hutool.json.ObjectMapper.mapFromStr(ObjectMapper.java:215)
	at cn.hutool.json.ObjectMapper.map(ObjectMapper.java:98)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:211)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:188)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:114)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:229)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:477)
	at com.hdwang.test.ObjectConvertTest.main(ObjectConvertTest.java:80)
Disconnected from the target VM, address: '127.0.0.1:62126', transport: 'socket'

Process finished with exit code 1

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这里其实没有问题。

你在`JSONUtil.toJsonStr(paramList.get(1));`方法调用时，将bytes转换为了字符串，但是使用`JSONUtil.toBean(paramBytesStr, byte[].class, false);`时，`paramBytesStr`必须是一个JSON字符串，因此这里报错很正常。

你要想对普通字符串或者普通值转换，可以使用

```java
final byte[] convert = Convert.convert(byte[].class, paramBytesStr);
```

不只是byte[]，任何单独的值，通过`JSONUtil.toJsonStr`都无法完成转换！

**Comment by hdwang123** [comment]
byte[]序列化不一，感觉怪怪的虽然有其它方式解决。最好还是能统一。目前单独的byte[]转成json数组，而bean里的byte[]却是base64字符串。这就有歧义了！这个byte[]类型转成字符串出现了两种形式。让用户无法准确知道到底转换成了什么？反序列化的时候就一脸懵逼了。我觉得byte[]类型默认全部转成数组的好，base64可以作为备选方案。

**Comment by looly** [comment]
5.8.4修改规则，感谢。
