### ISSUE TITLE
BigExcelWriter 百万条数据 写入单sheet报错

### ISSUE THREAD

**Issue by dnslin** [looly/hutool#2378]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 最新

### 问题描述（包括截图）
**总数据量 2821776 条 写入单sheet报错**
![image.png](https://img.dnslv.com/images/2022/06/13/image.png)
使用的是`xlsx`
1. 复现代码
```java
    String fileName = "C:\\Users\\dnslin\\Downloads\\Video\\sfurl.txt";
    Path path = Paths.get(fileName);
    byte[] bytes = Files.readAllBytes(path);
    List<String> allLines = Files.readAllLines(path, StandardCharsets.UTF_8);
    System.out.println(allLines.size());
    List<List<String>> rows = CollUtil.newArrayList(Collections.singleton(allLines));
    BigExcelWriter writer = ExcelUtil.getBigWriter("C:\\Users\\dnslin\\Downloads\\Video\\sfurl.xlsx");
    writer.write(rows);
    writer.close();
```

```java
 Invalid column index (16384).  Allowable column range for EXCEL2007 is (0..16383) or ('A'..'XFD')
```

2. 堆栈信息
```java
Exception in thread "main" java.lang.IllegalArgumentException: Invalid column index (16384).  Allowable column range for EXCEL2007 is (0..16383) or ('A'..'XFD')
	at org.apache.poi.xssf.streaming.SXSSFRow.checkBounds(SXSSFRow.java:156)
	at org.apache.poi.xssf.streaming.SXSSFRow.createCell(SXSSFRow.java:141)
	at org.apache.poi.xssf.streaming.SXSSFRow.createCell(SXSSFRow.java:124)
	at org.apache.poi.xssf.streaming.SXSSFRow.createCell(SXSSFRow.java:39)
	at cn.hutool.poi.excel.RowUtil.writeRow(RowUtil.java:110)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:1090)
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:1016)
	at cn.hutool.poi.excel.ExcelWriter.write(ExcelWriter.java:819)
	at cn.hutool.poi.excel.ExcelWriter.write(ExcelWriter.java:793)
	at com.dnslin.TestSpringBoot.spider.SpiderTwo.main(SpiderTwo.java:25)
```

**Comment by looly** [comment]
提示很明确，单个sheet数据量不能太多，这个是Excel文件的限制。
