### ISSUE TITLE
CellUtil依赖apache的poiBUG

### ISSUE THREAD

**Issue by 92daxia** [looly/hutool#2381]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
CellUtil 工具类中调用apache的poi类、方法，但是这个已经在很老的版本废弃了，apache的poi版本稍高一点就完蛋。依赖的第3方框架版本需要及时更新下新版本。
![image](https://user-images.githubusercontent.com/49838034/173722760-e6c8c9f9-a55b-4f1c-8cad-034e789eb035.png)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息
Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellType()Lorg/apache/poi/ss/usermodel/CellType;
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:190) ~[hutool-poi-5.7.16.jar:?]
	at cn.hutool.poi.excel.cell.CellUtil.setCellValue(CellUtil.java:151) ~[hutool-poi-5.7.16.jar:?]
	at cn.hutool.poi.excel.ExcelWriter.writeHeadRow(ExcelWriter.java:878) ~[hutool-poi-5.7.16.jar:?]
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:984) ~[hutool-poi-5.7.16.jar:?]
	at cn.hutool.poi.excel.ExcelWriter.writeRow(ExcelWriter.java:963) ~[hutool-poi-5.7.16.jar:?]
	at cn.hutool.poi.excel.ExcelWriter.write(ExcelWriter.java:817) ~[hutool-poi-5.7.16.jar:?]

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
![image](https://user-images.githubusercontent.com/49838034/173721921-bd17bd7c-b764-47ed-9865-c4fb92fa3480.png)

**Comment by looly** [comment]
你使用的POI版本太低了

文档有说明,需要最低4.12
