### ISSUE TITLE
extract文件后压缩文件的句柄并未释放，导致删除文件失败

### ISSUE THREAD

**Issue by SleepyOcean** [looly/hutool#2384]
### 版本情况

JDK版本：    zulujdk_8_201
hutool版本： 5.3.2

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/17136535/173985658-e09a0e16-26b7-486c-96e6-391ba1e20dd9.png)

在extract类型为7z的压缩包后，句柄并未释放，导致文件无法删除。确认流应该关闭了，但资源并未释放是什么原因呢？

1. 复现代码

```java
Extractor extractor = CompressUtil.createExtractor(
                CharsetUtil.defaultCharset(),
                FileUtil.file(compressFileName));
extractor.extract(FileUtil.file(extractDir));
FileUtil.del(compressFileName)
```

**Comment by looly** [comment]
你这缺少close方法调用吧？

```java
Extractor extractor = CompressUtil.createExtractor(
                CharsetUtil.defaultCharset(),
                FileUtil.file(compressFileName));
extractor.extract(FileUtil.file(extractDir));

extractor.close();

FileUtil.del(compressFileName);
```

**Comment by SleepyOcean** [comment]
no, extract中的finally里是有关闭操作，但是有其他的流貌似没有关闭。看了createExtractor中的操作，new StreamExtractor()这里会抛异常，但里面有个FileUtil.getInputStream(file)的操作，不太确定是不是这里的流没有关闭造成的？我这边再进去看看
![image](https://user-images.githubusercontent.com/17136535/173987209-c111d5f2-7e64-4f91-8e41-64c8549a9508.png)

**Comment by looly** [comment]
好像确实有一处没有关闭流。

**Comment by looly** [comment]
啊，绕了半天，这里确实可能存在流未关闭的问题！

5.8.4我在catch里增加关闭流的操作。

**Comment by SleepyOcean** [comment]
嗯嗯好的呀，辛苦~

**Comment by SleepyOcean** [comment]
By the way，在解压7z的文件时会需要这个依赖`org.tukaani.xz`，但文档中没有提到，没有引入的话会抛出`java.lang.NoClassDefFoundError: org/tukaani/xz/LZMA2Options`的异常，或许有空的话你们可以添加下^_^
```xml
         <dependency>
            <groupId>org.tukaani</groupId>
            <artifactId>xz</artifactId>
            <version>1.8</version>
        </dependency>
```

**Comment by looly** [comment]
@SleepyOcean 奇怪啊，我单元测试的时候并不需要这个包。你的commons-compress是`1.21`版本么？

**Comment by SleepyOcean** [comment]
是的，1.21
```xml
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.21</version>
        </dependency>
```

**Comment by SleepyOcean** [comment]
是不是本地有缓存的原因呢？[盲猜^_-]

**Comment by SleepyOcean** [comment]
或是其他依赖包中包含了`org.tukaani.xz`这个依赖😂

**Comment by looly** [comment]
@SleepyOcean 我检查了依赖树确实没有。

NoClassDefFoundError有堆栈么？我找找哪里 引用了。

**Comment by SleepyOcean** [comment]
sure，堆栈如下：
```java
Caused by: java.lang.NoClassDefFoundError: org/tukaani/xz/LZMA2Options
	at org.apache.commons.compress.archivers.sevenz.LZMADecoder.<init>(LZMADecoder.java:33)
	at org.apache.commons.compress.archivers.sevenz.Coders$1.<init>(Coders.java:52)
	at org.apache.commons.compress.archivers.sevenz.Coders.<clinit>(Coders.java:47)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.readEncodedHeader(SevenZFile.java:698)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.initializeArchive(SevenZFile.java:544)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.readHeaders(SevenZFile.java:474)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.<init>(SevenZFile.java:343)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.<init>(SevenZFile.java:135)
	at org.apache.commons.compress.archivers.sevenz.SevenZFile.<init>(SevenZFile.java:122)
	at cn.hutool.extra.compress.extractor.SevenZExtractor.<init>(SevenZExtractor.java:47)
	at cn.hutool.extra.compress.extractor.SevenZExtractor.<init>(SevenZExtractor.java:36)
	at cn.hutool.extra.compress.CompressUtil.createExtractor(CompressUtil.java:178)
	at cn.hutool.extra.compress.CompressUtil.createExtractor(CompressUtil.java:150)
```

**Comment by looly** [comment]
@SleepyOcean 确实引入了，Commons-compress没有说明，忽略了。

**Comment by SleepyOcean** [comment]
嗯嗯好的~
