### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by xiaoqiqiya** [looly/hutool#2417]
### 版本情况

JDK版本：    openjdk_8_333
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
HttpRequest.get(getTokenURL)
```

2. 堆栈信息
Exception in thread "main" cn.hutool.core.io.IORuntimeException: SSLHandshakeException: Received fatal alert: handshake_failure
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1258)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1123)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1012)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:988)
	at com.example.boottest.www.main(www.java:28)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:375)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1253)
	... 4 more

**Comment by looly** [comment]
见：https://hutool.cn/docs/#/http/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
