### ISSUE TITLE
Linux 环境中  httpUtil.downloanFile 报错。url 并非https

### ISSUE THREAD

**Issue by sunhai1988** [looly/hutool#244]
cn.hutool.http.HttpException: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:919)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:803)
	at cn.hutool.http.HttpRequest.executeAsync(HttpRequest.java:787)
	at cn.hutool.http.HttpUtil.downloadFile(HttpUtil.java:423)
	at cn.hutool.http.HttpUtil.downloadFile(HttpUtil.java:403)
	at cn.hutool.http.HttpUtil.downloadFile(HttpUtil.java:378)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:447)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:916)
	... 8 more
Caused by: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1117)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1043)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:985)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)

**Comment by looly** [comment]
看问题是触发了https请求，请检查你的url是否是https开头，还有升级jdk到最新的补丁版本，例如jdk8_191。

如果不行，请提供url我这边测试

**Comment by sunhai1988** [comment]
地址不是https  有可能服务器被强制走 了https
https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJaI8ZynPK4CTetexsW6esXLEeXWgHiaFuvq6iamcUiaq3d6hPoZS5TpTlt1HC3flvhrfN2n8ibKra54g/132
http://wx.qlogo.cn/mmopen/vKhlFcibVUtNBVDjcIowlg0X8aJfHXrTNCEFBukWVH9ta99pfEN88lU39MKspCUCOP3yrFBH3y2NbV7sYtIIlon8XxLwAEqv2/0
http://thirdwx.qlogo.cn/mmopen/vi_32/2NeT90z00wHzGercQTyfqKP849yz0qOebHfUaWG0eFt7LibNOU4HQmPZTJM78RR2s8bW3j7UPKngtsq0dJUicOQA/132

**Comment by sunhai1988** [comment]
尴尬了  有部分是https

**Comment by looly** [comment]
我本地测试正常，使用JDK版本为jdk7_79，代码如下：

```java
String url = "http://wx.qlogo.cn/mmopen/vKhlFcibVUtNBVDjcIowlg0X8aJfHXrTNCEFBukWVH9ta99pfEN88lU39MKspCUCOP3yrFBH3y2NbV7sYtIIlon8XxLwAEqv2/0";
HttpUtil.downloadFile(url, "e:/pic/t3.jpg");
```

再次确认下Hutool是否为最新版本，最新为4.4.0
