### ISSUE TITLE
randomInt报错

### ISSUE THREAD

**Issue by duhanmin** [looly/hutool#2502]
### 问题描述（包括截图）

1. 复现代码

```java
RandomUtil.randomInt(1, 1)
```

2. 堆栈信息
```
Exception in thread "main" java.lang.IllegalArgumentException: bound must be greater than origin
	at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:337)
	at cn.hutool.core.util.RandomUtil.randomInt(RandomUtil.java:184)```

**Comment by duhanmin** [comment]
场景:一个list中取值,
