### ISSUE TITLE
CompressUtil 解压报 IOException: Bad pathname

### ISSUE THREAD

**Issue by Mrqqqwww** [looly/hutool#2518]
### 版本情况

JDK版本：    11
hutool版本： 5.8.5
windows 11

### 问题描述（包括截图）

1. 复现代码

```java
public static boolean unCompressFile(File srcFile, String destDirPath) {
        try {
            Extractor extractor = CompressUtil.createExtractor(StandardCharsets.UTF_8, srcFile);
            File file = FileUtil.file("D:\\file\\img");
            extractor.extract(file);
   
        } catch (Exception e) {
            e.printStackTrace();
            log.error("解压文件失败：{}", e.getMessage());
            return false;
        }
        return true;
    }
```

2. 堆栈信息
```
Caused by: java.io.IOException: Bad pathname
	at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:438)
	at java.base/java.io.File.getCanonicalPath(File.java:620)
	at java.base/java.io.File.getCanonicalFile(File.java:645)
	at cn.hutool.core.io.FileUtil.getParent(FileUtil.java:3407)
	... 84 more
```
4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Mrqqqwww** [comment]
我知道是什么原因了，是StandardCharsets.UTF_8，中文文件会报错，改成CHARSET_ISO_8859_1就可以了

**Comment by Mrqqqwww** [comment]
改成CHARSET_ISO_8859_1后能解压，但是解压后的文件中文又乱码了

**Comment by looly** [comment]
@Mrqqqwww GBK呢？如果不行，麻烦提供下测试的zip。

**Comment by Mrqqqwww** [comment]
gbk可以，我现在的方式就是先判断文件名然后选择GBK或者UTF-8，这个hutool能不能直接判断选择CHARSET

**Comment by looly** [comment]
@Mrqqqwww 别说压缩包了，文本都没法判断编码类型。
