### ISSUE TITLE
TreeUtil 工具包setWeight()权重方法,无法使用Lambda表达式

### ISSUE THREAD

**Issue by zlz-alex** [looly/hutool#2554]
### 版本情况

JDK版本：    oraclejdk_1.8.0_202
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
TreeUtil 工具包setWeight()权重方法,无法使用Lambda表达式，使用
1. 复现代码

```java
@Service
public class AmsFolderServiceImpl extends ServiceImpl<AmsFolderMapper, AmsFolder> implements IAmsFolderService {
    @Autowired
    private IAmsAppService appService;

    @Override
    public List<AmsFolder> queryList(String appCode, UserModel userModel) {
        return list(new LambdaQueryWrapper<AmsFolder>()
                .eq(AmsFolder::getAppCode,appCode));
    }

    @Override
    public List<Tree<String>> queryTree(String appCode, UserModel userModel) {
        TreeNodeConfig treeNodeConfig = new TreeNodeConfig()
                        .setIdKey("id");
        return TreeUtil.build(queryList(appCode, userModel),"0",treeNodeConfig,(treeNode,tree)->{
            tree.setId(treeNode.getId())
                    .setId(treeNode.getId())
                    .setParentId(treeNode.getParentId())
                    .setName(treeNode.getName())
                    //设置权重,无法确定o的类型，这里对象o是AmsFolderServiceImpl
                    .setWeight((o)->((Integer)o).compareTo(treeNode.getSort()));
            tree.putExtra("appId",treeNode.getAppId());
            tree.putExtra("appCode",treeNode.getAppCode());
            tree.putExtra("appName",treeNode.getAppName());
            tree.putExtra("version",treeNode.getVersion());
            tree.putExtra("sort",treeNode.getSort());
        });
    }
}
```

2. 堆栈信息
```java
java.lang.ClassCastException: com.hangyi.service.ams.impl.AmsFolderServiceImpl$$Lambda$1038/671718469 cannot be cast to java.lang.Integer
	at com.hangyi.service.ams.impl.AmsFolderServiceImpl.lambda$null$0(AmsFolderServiceImpl.java:52) ~[classes/:na]
	at cn.hutool.core.comparator.CompareUtil.compare(CompareUtil.java:80) ~[hutool-all-5.8.5.jar:na]
	at cn.hutool.core.comparator.CompareUtil.compare(CompareUtil.java:59) ~[hutool-all-5.8.5.jar:na]
	at cn.hutool.core.lang.tree.Node.compareTo(Node.java:84) ~[hutool-all-5.8.5.jar:na]
	at cn.hutool.core.lang.tree.Node.compareTo(Node.java:14) ~[hutool-all-5.8.5.jar:na]
	at java.util.Map$Entry.lambda$comparingByValue$1065357e$1(Map.java:489) ~[na:1.8.0_202]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[na:1.8.0_202]
	at java.util.TimSort.sort(TimSort.java:220) ~[na:1.8.0_202]
	at java.util.Arrays.sort(Arrays.java:1512) ~[na:1.8.0_202]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_202]
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423) ~[na:1.8.0_202]
	at cn.hutool.core.map.MapUtil.sortByValue(MapUtil.java:857) ~[hutool-all-5.8.5.jar:na]
	at cn.hutool.core.lang.tree.TreeBuilder.buildFromMap(TreeBuilder.java:230) ~[hutool-all-5.8.5.jar:na]
	at cn.hutool.core.lang.tree.TreeBuilder.build(TreeBuilder.java:191) ~[hutool-all-5.8.5.jar:na]
	at cn.hutool.core.lang.tree.TreeUtil.buildSingle(TreeUtil.java:126) ~[hutool-all-5.8.5.jar:na]
	at cn.hutool.core.lang.tree.TreeUtil.build(TreeUtil.java:108) ~[hutool-all-5.8.5.jar:na]
	at com.hangyi.service.ams.impl.AmsFolderServiceImpl.queryTree(AmsFolderServiceImpl.java:46) ~[classes/:na]
	at com.hangyi.service.ams.impl.AmsFolderServiceImpl$$FastClassBySpringCGLIB$$afea23cf.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.hangyi.service.ams.impl.AmsFolderServiceImpl$$EnhancerBySpringCGLIB$$ffd978cf.queryTree(<generated>) ~[classes/:na]
	at com.hangyi.controller.ams.AmsFolderController.queryTree(AmsFolderController.java:50) ~[classes/:na]
	at com.hangyi.controller.ams.AmsFolderController$$FastClassBySpringCGLIB$$4d31b9b7.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.hangyi.common.aspect.WebLogAspect.around(WebLogAspect.java:51) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.hangyi.controller.ams.AmsFolderController$$EnhancerBySpringCGLIB$$44efde0b.queryTree(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84) ~[swagger-bootstrap-ui-1.9.6.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53) ~[swagger-bootstrap-ui-1.9.6.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) ~[druid-1.1.10.jar:1.1.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]

```
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

### 我是这样解决的
加了个类
```java
@Service
public class AmsFolderServiceImpl extends ServiceImpl<AmsFolderMapper, AmsFolder> implements IAmsFolderService {
    @Autowired
    private IAmsAppService appService;

    @Override
    public List<AmsFolder> queryList(String appCode, UserModel userModel) {
        return list(new LambdaQueryWrapper<AmsFolder>()
                .eq(AmsFolder::getAppCode,appCode));
    }
       /**
     * 加了这个类
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    class TreeComparable implements Comparable<TreeComparable>, Serializable {
        private static final long serialVersionUID = 1L;

        protected Integer sort;

        public TreeComparable(Integer sort) {
            this.sort = sort;
        }
        @Override
        public int compareTo(TreeComparable o) {
            return o.sort.compareTo(this.sort);
        }
    }

    @Override
    public List<Tree<String>> queryTree(String appCode, UserModel userModel) {
        TreeNodeConfig treeNodeConfig = new TreeNodeConfig()
                        .setIdKey("id");
        return TreeUtil.build(queryList(appCode, userModel),"0",treeNodeConfig,(treeNode,tree)->{
            tree.setId(treeNode.getId())
                    .setId(treeNode.getId())
                    .setParentId(treeNode.getParentId())
                    .setName(treeNode.getName())
                    //设置权重
                    .setWeight(new TreeComparable(treeNode.getSort()));
            tree.putExtra("appId",treeNode.getAppId());
            tree.putExtra("appCode",treeNode.getAppCode());
            tree.putExtra("appName",treeNode.getAppName());
            tree.putExtra("version",treeNode.getVersion());
            tree.putExtra("sort",treeNode.getSort());
        });
    }
}

```

**Comment by looly** [comment]
这里的weight其实是个自定义的比较器，节点的排序根据这个比较器比较，这个比较器由关联定义为weight的字段值，也就是说取决于你weight的对象类型。

这里你可以在lambda中判断o的类型，然后强转获取字段比较。
