### ISSUE TITLE
HttpUtil调用报cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by HuangZL-github** [looly/hutool#2560]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4

### 问题描述（包括截图）
Map<String, Object> paramMaps = new HashMap<>(4);
paramMaps.put("grant_type", "refresh_token");
paramMaps.put("client_id", "ZZZZ-CLIENT1");
paramMaps.put("client_secret", "!@#qwe");
paramMaps.put("refresh_token", "123456789QWER");
System.out.println(HttpUtil.get("http://202.205.188.198:9000/prod-api/api/web/collect/oauth2/refresh", paramMaps));

本地测试没问题，上服务器部署偶发性报下面这个错：
cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused (Connection refused)

**Comment by duhanmin** [comment]
堆栈发全一些

**Comment by HuangZL-github** [comment]
cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused (Connection refused)
at cn.hutool.http.HttpRequest.send(HttpRequest.java:1070)
at cn.hutool.http.HttpRequest.execute(HttpRequest.java:937)
at cn.hutool.http.HttpRequest.execute(HttpRequest.java:903)
at com.xxx.xxx.util.HttpUtil.post(HttpUtil.java:135)
at com.xxx.xxx.util.HttpUtil.request(HttpUtil.java:93)
at com.xxx.xxx.util.HttpUtil.send(HttpUtil.java:71)
at com.xxx.xxx.servlet.EventsServlet.service(EventsServlet.java:40)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocolConnectionHandler.process(AbstractProtocol.java:868)atorg.apache.tomcat.util.net.NioEndpointSocketProcessor.doRun(NioEndpoint.java:1590)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:624)atorg.apache.tomcat.util.threads.TaskThreadWrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
at sun.net.www.http.HttpClient.(HttpClient.java:242)
at sun.net.www.http.HttpClient.New(HttpClient.java:339)
at sun.net.www.http.HttpClient.New(HttpClient.java:357)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:450)
at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1088)
at cn.hutool.http.HttpRequest.send(HttpRequest.java:1060)
... 41 common frames omitted

**Comment by HuangZL-github** [comment]
> 堆栈发全一些

cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused (Connection refused)
at cn.hutool.http.HttpRequest.send(HttpRequest.java:1070)
at cn.hutool.http.HttpRequest.execute(HttpRequest.java:937)
at cn.hutool.http.HttpRequest.execute(HttpRequest.java:903)
at com.xxx.xxx.util.HttpUtil.post(HttpUtil.java:135)
at com.xxx.xxx.util.HttpUtil.request(HttpUtil.java:93)
at com.xxx.xxx.util.HttpUtil.send(HttpUtil.java:71)
at com.xxx.xxx.servlet.EventsServlet.service(EventsServlet.java:40)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocolConnectionHandler.process(AbstractProtocol.java:868)atorg.apache.tomcat.util.net.NioEndpointSocketProcessor.doRun(NioEndpoint.java:1590)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:624)atorg.apache.tomcat.util.threads.TaskThreadWrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
at sun.net.www.http.HttpClient.(HttpClient.java:242)
at sun.net.www.http.HttpClient.New(HttpClient.java:339)
at sun.net.www.http.HttpClient.New(HttpClient.java:357)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:450)
at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1088)
at cn.hutool.http.HttpRequest.send(HttpRequest.java:1060)
... 41 common frames omitted

**Comment by HuangZL-github** [comment]
> 堆栈发全一些

**Comment by HuangZL-github** [comment]
> 堆栈发全一些
我看到gitee上也有人提了issue，但是貌似没解决   --->

问题描述
大佬好，我使用HttpRequest.post请求第三方接口（我们自己的别的服务接口），然后就报cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused，单独请求第三方服务的接口是可以的，但唯独这个服务不行，重启这个服务会暂时解决，当过一段时间，就又会出现Connection refused。请求次数挺频繁的。

**Comment by looly** [comment]
那是你的服务端拒绝服务了把？请检查服务端接口或使用HttpClient尝试。

**Comment by fuyun2024** [comment]
我也遇到了这个问题，请问有解决方案么？

**Comment by HuangZL-github** [comment]
当时开发环境有这个问题，上了生产环境就没这个问题了，当时查了很多也没解决方案，但是好像对调接口没什么影响


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/hutool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 上午10:33
***@***.***&gt;;
抄送:&nbsp;"每    ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [dromara/hutool] HttpUtil调用报cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused (Connection refused) (Issue #2560)





 
我也遇到了这个问题，请问有解决方案么？

**Comment by jiegege8** [comment]
同样遇到了 怎么解决呢?
