### ISSUE TITLE
Json 序列化出现异常

### ISSUE THREAD

**Issue by pansong291** [looly/hutool#2572]
### 版本情况

JDK版本：    OpenJDK17U-jdk_x64_windows_hotspot_17.0.3_7
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
import cn.hutool.json.JSONObject;

import java.time.DayOfWeek;
import java.util.HashSet;
import java.util.Set;

public class Test {
    public static void main(String[] args) {
        Set<DayOfWeek> weeks = new HashSet<>();
        weeks.add(DayOfWeek.MONDAY);
        JSONObject obj = new JSONObject();
        obj.set("weeks", weeks);
        System.out.println(obj);
    }
}
```

2. 堆栈信息
Exception in thread "main" java.lang.ArithmeticException: long overflow
	at java.base/java.lang.Math.multiplyExact(Math.java:1004)
	at java.base/java.lang.Math.multiplyExact(Math.java:980)
	at java.base/java.time.Instant.toEpochMilli(Instant.java:1236)
	at cn.hutool.core.date.TemporalAccessorUtil.toEpochMilli(TemporalAccessorUtil.java:124)
	at cn.hutool.json.serialize.JSONWriter.formatDate(JSONWriter.java:387)
	at cn.hutool.json.serialize.JSONWriter.writeObjValue(JSONWriter.java:233)
	at cn.hutool.json.serialize.JSONWriter.writeValueDirect(JSONWriter.java:210)
	at cn.hutool.json.serialize.JSONWriter.writeValue(JSONWriter.java:155)
	at cn.hutool.json.JSONArray.lambda$write$97997a6d$1(JSONArray.java:571)
	at cn.hutool.core.collection.CollUtil.forEach(CollUtil.java:2622)
	at cn.hutool.core.collection.CollUtil.forEach(CollUtil.java:2606)
	at cn.hutool.json.JSONArray.write(JSONArray.java:568)
	at cn.hutool.json.JSONArray.write(JSONArray.java:549)
	at cn.hutool.json.serialize.JSONWriter.writeObjValue(JSONWriter.java:224)
	at cn.hutool.json.serialize.JSONWriter.writeValueDirect(JSONWriter.java:210)
	at cn.hutool.json.serialize.JSONWriter.writeField(JSONWriter.java:170)
	at cn.hutool.json.JSONObject.lambda$write$0(JSONObject.java:579)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at cn.hutool.core.map.MapWrapper.forEach(MapWrapper.java:160)
	at cn.hutool.json.JSONObject.write(JSONObject.java:571)
	at cn.hutool.json.JSONObject.write(JSONObject.java:553)
	at cn.hutool.json.JSON.toJSONString(JSON.java:112)
	at cn.hutool.json.JSONObject.toString(JSONObject.java:532)
	at java.base/java.lang.String.valueOf(String.java:4218)
	at java.base/java.io.PrintStream.println(PrintStream.java:1047)
	at Test.main(Test.java:17)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.6修复此问题，感谢！
