### ISSUE TITLE
java读取excel内存溢出

### ISSUE THREAD

**Issue by xhrwp** [looly/hutool#2595]
### 版本情况

JDK版本：    jdk1.8.0_231
hutool版本： 5.7.11

### 问题描述（包括截图）

1. 复现代码

        Workbook workbook;
        if (ExcelFileUtil.isXlsx(file)) {
            workbook = WorkbookUtil.createSXSSFBook(file);
        } else {
            workbook = WorkbookUtil.createBook(file);
        }

2. 堆栈信息

cn.hutool.poi.exceptions.POIException: IOException: GC overhead limit exceeded

	at cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:86)
	at cn.hutool.poi.excel.WorkbookUtil.createSXSSFBook(WorkbookUtil.java:166)
	at cn.hutool.poi.excel.WorkbookUtil.createSXSSFBook(WorkbookUtil.java:154)
	at com.ip.ExcelUtilsTest.getPhysicalRowCount(ExcelUtilsTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.io.IOException: GC overhead limit exceeded
	at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:351)
	at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:314)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:302)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:271)
	at cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:84)
	... 26 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at org.apache.xmlbeans.impl.values.NamespaceContext$NamespaceContextStack.push(NamespaceContext.java:81)
	at org.apache.xmlbeans.impl.values.NamespaceContext.push(NamespaceContext.java:110)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_dated(XmlObjectBase.java:1318)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.getStringValue(XmlObjectBase.java:1529)
	at org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTCellImpl.getR(Unknown Source)
	at org.apache.poi.xssf.usermodel.XSSFCell.<init>(XSSFCell.java:117)
	at org.apache.poi.xssf.usermodel.XSSFRow.<init>(XSSFRow.java:75)
	at org.apache.poi.xssf.usermodel.XSSFSheet.initRows(XSSFSheet.java:268)
	at org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:231)
	at org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java:218)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.parseSheet(XSSFWorkbook.java:448)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:413)
	at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:184)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:282)
	at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:88)
	at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:339)
	at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:314)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:302)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:271)
	at cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:84)
	at cn.hutool.poi.excel.WorkbookUtil.createSXSSFBook(WorkbookUtil.java:166)
	at cn.hutool.poi.excel.WorkbookUtil.createSXSSFBook(WorkbookUtil.java:154)

Process finished with exit code 255

4. 测试涉及到的文件（注意脱密）
测试的excel文件是100w行。大概30MB。压缩包形式上传
[ret0.xlsx.zip](https://github.com/dromara/hutool/files/9502288/ret0.xlsx.zip)

**Comment by looly** [comment]
你的Excel太大了，使用sax方式读取吧。
