### ISSUE TITLE
国密加密出现报错信息

### ISSUE THREAD

**Issue by AmazingLuck** [looly/hutool#2609]
### 版本情况

JDK版本：    jdk11

```xml
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.6</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bctls-jdk15to18</artifactId>
            <version>1.71</version>
        </dependency>
```

### 问题描述（包括截图）

国密算法工具 使用私钥D值签名 报错

![image](https://user-images.githubusercontent.com/42023817/190078992-c1f612d1-2f16-4cc9-b4b7-0fd87901ab44.png)
[](url)

```java
//指定的公钥
        String publicKeyHex = "04db9629dd33ba568e9507add5df6587a0998361a03d3321948b448c653c2c1b7056434884ab6f3d1c529501f166a336e86f045cea10dffe58aa82ea13d725363";
//需要加密的明文,得到明文对应的字节数组
        byte[] dataBytes = "我是一段测试aaaa".getBytes();
//签名值
        String signHex = "2881346e038d2ed706ccdd025f2b1dafa7377d5cf090134b98756fafe084dddbcdba0ab00b5348ed48025195af3f1dda29e819bb66aa9d4d088050ff148482a";

        final SM2 sm2 = new SM2(null, ECKeyUtil.toSm2PublicParams(publicKeyHex));
        sm2.usePlainEncoding();
// true
        boolean verify = sm2.verify(dataBytes, HexUtil.decodeHex(signHex));
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Incorrect length for infinity encoding
	at org.bouncycastle.math.ec.ECCurve.decodePoint(Unknown Source)
	at cn.hutool.crypto.ECKeyUtil.toPublicParams(ECKeyUtil.java:162)
	at cn.hutool.crypto.ECKeyUtil.toSm2PublicParams(ECKeyUtil.java:84)
	at cn.hjh.learn.common.GM.main(GM.java:64)
```

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你的测试公钥错了，你可能拷贝文档中的例子，正确的公钥是：

```
04db9629dd33ba568e9507add5df6587a0998361a03d3321948b448c653c2c1b7056434884ab6f3d1c529501f166a336e86f045cea10dffe58aa82ea13d7253763
```
