### ISSUE TITLE
DateUtil.parseUTC 不支持带减号的时区

### ISSUE THREAD

**Issue by pansong291** [looly/hutool#2612]
### 版本情况

JDK版本：    OpenJDK17U-jdk_x64_windows_hotspot_17.0.3_7
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
import cn.hutool.core.date.DateUtil;

public class Test {
    public static void main(String[] args) {
        System.out.println(DateUtil.parse("2022-09-14T23:59:00-08:00", DatePattern.UTC_WITH_XXX_OFFSET_FORMAT));
        System.out.println(DateUtil.parseUTC("2022-09-14T23:59:00-08:00"));
    }
}
```

2. 堆栈信息
```
Exception in thread "main" cn.hutool.core.date.DateException: No format fit for date String [2022-09-14T23:59:00-08:00] !
	at cn.hutool.core.date.DateUtil.parseUTC(DateUtil.java:880)
	at cn.hutool.core.date.DateUtil.parse(DateUtil.java:961)
```

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.7修复此问题，感谢！
