### ISSUE TITLE
AES加密算法中没有GCM模式

### ISSUE THREAD

**Issue by chenguosi** [looly/hutool#2613]
目前AES加密算法没有提供GCM模式的支持，有没有大佬能补上

**Comment by looly** [comment]
在使用bc库的情况下是支持的。

1. 引入bc库：

```
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bcpkix-jdk15to18</artifactId>
	<version>1.71</version>
</dependency>
```

```java
final AES aes = new AES("GCM", Padding.NoPadding.name(),
				"1234567890123456".getBytes(),
				"1234567890123456".getBytes());

// 加密
final String encryptHex = aes.encryptHex("123456");

// 解密
final String s = aes.decryptStr(encryptHex);
```

**Comment by chenguosi** [comment]
不能自定义填充类型，只能使用NoPadding模式，这个可以扩展吗？

**Comment by looly** [comment]
@chenguosi 可以吧，填充类型传字符串，只要bc库支持就可以传。

**Comment by chenguosi** [comment]
```
public static void main(String[] args) {
        String content = "123456";
        AES aes = new AES("GCM", Padding.PKCS5Padding.name(),
                // 密钥，可以自定义
                "12345678".getBytes(),
                // iv加盐，按照实际需求添加
                "12345678".getBytes());
        String encryptContent = aes.encryptBase64(content);
        System.out.println(encryptContent);
        String origin = aes.decryptStr(encryptContent);
        System.out.println(origin);

    }
```


执行报错：
Exception in thread "main" cn.hutool.crypto.CryptoException: NoSuchPaddingException: Only NoPadding can be used with AEAD modes.
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1034)
	at cn.hutool.crypto.CipherWrapper.<init>(CipherWrapper.java:39)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:150)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:127)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:190)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:165)
	at com.chen.demo.EncryptDemo.main(EncryptDemo.java:19)
Caused by: javax.crypto.NoSuchPaddingException: Only NoPadding can be used with AEAD modes.
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineSetPadding(Unknown Source)
	at javax.crypto.Cipher$Transform.setModePadding(Cipher.java:380)
	at javax.crypto.Cipher.getInstance(Cipher.java:673)
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1032)
	... 6 more

**Comment by looly** [comment]
@chenguosi 那就是bc库不支持……

**Comment by changhr2013** [comment]
GCM 扩展自 CTR 模式，本质上是用分组加密模拟流式加密，Padding 填充没有必要，都是 NoPadding 方式。

**Comment by wushuaiping** [comment]
什么时候能支持一下呢

**Comment by looly** [comment]
@wushuaiping 哈哈，我没有能力自己实现，如果BC库不支持，那就没办法了，你找下相关资料呗。
