### ISSUE TITLE
Linux 环境下 java17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 异常

### ISSUE THREAD

**Issue by FULaBUla** [looly/hutool#2631]
### 版本情况

JDK版本：    oracle java 17
hutool版本： 5.8.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
Linux 环境下 java17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 。
https://github.com/spring-projects/spring-boot/issues/28837 中有讨论过这个问题，在 2.7.2 及之前版本的springboot 有修复过这个问题，通过使用
```
bootJar {
    requiresUnpack '**/bcprov-jdk15on-*.jar'
}
```
可以解决问题，但是后来发现又会导致别的问题出现，所有修改被回归了。

在新的 2.7.3 和 2.74 版本依旧无法支持使用上面那个修改调用加解密库。

在议题中有另一个方式可以解决问题就是在调用  Bouncy Castle 前执行 `Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());`。

希望可以将这句话加到 hutool 调用   Bouncy Castle  的语句前，这样每次调用工具类的时候不需要在自己手动加了。

**Comment by CherryRum** [comment]
这个问题归根来说还是，jce中Security文件中缺少这个，而您说的方案是运行前临时假如环境变量，虽然是可行的，但是某些打包环境下，还是会出现问题，最好的办法还是部署时候加个环境变量，修改下Security文件

**Comment by looly** [comment]
嗯……虽然不能完全解决这个问题，5.8.8.会在全局引用BC时调用下这个方法，来解决部分环境问题。

**Comment by FULaBUla** [comment]
> 这个问题归根来说还是，jce中Security文件中缺少这个，而您说的方案是运行前临时假如环境变量，虽然是可行的，但是某些打包环境下，还是会出现问题，最好的办法还是部署时候加个环境变量，修改下Security文件

可惜 java17 没有 security 文件，之前确实想改来着

**Comment by CherryRum** [comment]
我的是有的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月26日(周一) 晚上7:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] Linux 环境下 java17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 异常 (Issue #2631)




  
这个问题归根来说还是，jce中Security文件中缺少这个，而您说的方案是运行前临时假如环境变量，虽然是可行的，但是某些打包环境下，还是会出现问题，最好的办法还是部署时候加个环境变量，修改下Security文件
  
可惜java17没有security文件，之前确实想改来着

**Comment by FULaBUla** [comment]
> 我的是有的？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月26日(周一) 晚上7:02 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [dromara/hutool] Linux 环境下 java17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 异常 (Issue #2631) 这个问题归根来说还是，jce中Security文件中缺少这个，而您说的方案是运行前临时假如环境变量，虽然是可行的，但是某些打包环境下，还是会出现问题，最好的办法还是部署时候加个环境变量，修改下Security文件 可惜java17没有security文件，之前确实想改来着 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你是用jdk生成的jre吗？我直接用的oracle jdk17，emmm

**Comment by CherryRum** [comment]
@FULaBUla 
看下这个地方
![image](https://user-images.githubusercontent.com/24296698/192465035-f9dce824-cfab-443a-b9a0-45762194e941.png)

**Comment by FULaBUla** [comment]
> @FULaBUla 看下这个地方 ![image](https://user-images.githubusercontent.com/24296698/192465035-f9dce824-cfab-443a-b9a0-45762194e941.png)

啊，![29500B87](https://user-images.githubusercontent.com/46469068/192520349-82e2161e-9e34-4ac4-9c0f-c6096bd154be.png)尴尬了，看来是之前找错地方了。谢谢啦

**Comment by FULaBUla** [comment]
> @FULaBUla 看下这个地方 ![image](https://user-images.githubusercontent.com/24296698/192465035-f9dce824-cfab-443a-b9a0-45762194e941.png)

我发现 jdk17 禁用了 ext，配置完了 security 文件后不知道应该把那个 jar 放在哪里，如果只配置不做别的操作，直接 springboot 打包运行还是会报错

**Comment by epca-job** [comment]
@FULaBUla What is the final solution?

**Comment by epca-job** [comment]
@CherryRum 咨询下oraclejdk17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 异常， 完整的解决方案有吗？

**Comment by CobraStarLE** [comment]
> @FULaBUla
> 看下这个地方
> ![image](https://user-images.githubusercontent.com/24296698/192465035-f9dce824-cfab-443a-b9a0-45762194e941.png)
具体配置哪个

**Comment by CobraStarLE** [comment]
> > @FULaBUla 看下这个地方 ![image](https://user-images.githubusercontent.com/24296698/192465035-f9dce824-cfab-443a-b9a0-45762194e941.png)
> 
> 啊，![29500B87](https://user-images.githubusercontent.com/46469068/192520349-82e2161e-9e34-4ac4-9c0f-c6096bd154be.png)尴尬了，看来是之前找错地方了。谢谢啦

改什么地方啊

**Comment by chenhongen** [comment]
所以怎么解决现在

**Comment by looly** [comment]
@chenhongen 不要打fatjar，bc库单独引入。

**Comment by ixqbar** [comment]
我也遇到了同样的问题  库单独引入测试无效

只能   SecureUtil.disableBouncyCastle();

**Comment by ixqbar** [comment]
```
Caused by: cn.hutool.crypto.CryptoException: SecurityException: JCE cannot authenticate the provider BC
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1034)
	at cn.hutool.crypto.CipherWrapper.<init>(CipherWrapper.java:39)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:150)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:127)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:190)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:165)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:94)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:81)
```

**Comment by CherryRum** [comment]
> @CherryRum 咨询下oraclejdk17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 异常， 完整的解决方案有吗？

只能打包时候不使用默认的打包，单独打包bc
建议openjdk吧，spring社区到现在都没解决

**Comment by rexlin600** [comment]
我是这解决的

private static final AES SINGLE_AES;

static {
        SecureUtil.disableBouncyCastle();
        SINGLE_AES = SecureUtil.aes(AES_KEY.getBytes(StandardCharsets.UTF_8));
    }

**Comment by CobraStarLE** [comment]
你用的是oracle的jdk吧，openjdk是不会出现这种问题的


| |
John
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月26日 11:01 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [dromara/hutool] Linux 环境下 java17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 异常 (Issue #2631) |

我是这解决的

private static final AES SINGLE_AES;

static {
SecureUtil.disableBouncyCastle();
SINGLE_AES = SecureUtil.aes(AES_KEY.getBytes(StandardCharsets.UTF_8));
}

**Comment by oniubi** [comment]
> > @FULaBUla 看下这个地方 ![image](https://user-images.githubusercontent.com/24296698/192465035-f9dce824-cfab-443a-b9a0-45762194e941.png)
> 
> 我发现 jdk17 禁用了 ext，配置完了 security 文件后不知道应该把那个 jar 放在哪里，如果只配置不做别的操作，直接 springboot 打包运行还是会报错

嗯，我也是发现这个jdk17禁用了ext，提示如下：
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.

**Comment by oniubi** [comment]
> 我也遇到了同样的问题 库单独引入测试无效
> 
> 只能 SecureUtil.disableBouncyCastle();

我也是，用了SecureUtil.disableBouncyCastle();才不报错，其他的改/lib/security/java.policy和conf/security/java.security，都没有解决。
1、security.provider.10=org.bouncycastle.jce.provider.BouncyCastleProvider
2、Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
以上两步我都试过了，没用。
但是在main中增加：
SecureUtil.disableBouncyCastle();
不报错了，要不要这样用，兄弟们自行斟酌！
我用的jdk是oracle的jdk-17.0.9。

**Comment by looly** [comment]
6.x做一些改造，抛弃JCE API，单独定义对象来封装BC库的方法，我想能绕过安全验证。

此issue暂时打开保留。

**Comment by oniubi** [comment]
> @chenhongen 不要打fatjar，bc库单独引入。

bc库单独引入好像没用，我用的jdk是oracle的jdk-17.0.9。

**Comment by looly** [comment]
@oniubi 后来我才发现，确实JDK新版中增加了对加密库的要求，就算是单独引入依旧存在这个问题。

因此打开此issue，6.x单独封装BC库了，跳过JCE。

**Comment by FULaBUla** [comment]
// https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
implementation 'org.bouncycastle:bcpkix-jdk18on:1.77'
可以试试这个版本 @looly @oniubi 应该是可以了

**Comment by lliyuu520** [comment]
> // https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on implementation 'org.bouncycastle:bcpkix-jdk18on:1.77' 可以试试这个版本 @looly @oniubi 应该是可以了

试了,不行,JDK版本oracle 17.0.6,用上面的SecureUtil.disableBouncyCastle()可以解决

**Comment by cxhello** [comment]
项目中需要使用SM4算法对配置文件解密，本地启动没问题，线上报`JCE cannot authenticate the provider BC`错误，最后将 Dockerfile 的基础镜像换成了 openjdk 解决了，感谢 @CherryRum 提供的思路。

**Comment by CherryRum** [comment]
嗯呢，没办法官方镜像非要验证签名



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月15日(周六) 中午1:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] Linux 环境下 java17 使用 Bouncy Castle 做加解密会出现 JCE cannot authenticate the provider BC 异常 (Issue #2631)




 
项目中需要使用SM4算法对配置文件解密，本地启动没问题，线上报JCE cannot authenticate the provider BC错误，最后将 Dockerfile 的基础镜像换成了 openjdk 解决了，感谢 @CherryRum 提供的思路。

**Comment by zeahoo** [comment]
今天也遇到同样的问题
电脑环境: m1 pro
JDK 版本： azul-23 aarch64 
Hutool 版本： 5.8.29
无论是否添加了bcpkix-jdk18on(1.77) 都会报错

**Comment by CherryRum** [comment]
@zeahoo @chenhongen @oniubi @lliyuu520 
麻烦尝试下最先
https://www.oracle.com/java/technologies/javase/17-0-10-relnotes.html

**Comment by running17** [comment]
> @zeahoo @chenhongen @oniubi @lliyuu520 麻烦尝试下最先 https://www.oracle.com/java/technologies/javase/17-0-10-relnotes.html
java version "17.0.11" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)
依然存在这个问题

**Comment by lgbisha** [comment]
java version "21.0.4" 2024-07-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.4+8.1 (build 21.0.4+8-LTS-jvmci-23.1-b41)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.4+8.1 (build 21.0.4+8-LTS-jvmci-23.1-b41, mixed mode, sharing)
虽然存在问题，但是SecureUtil.disableBouncyCastle(); 有效

**Comment by dddddkkkkk** [comment]
将jdk 升级到17.0.13 可以解决这个问题 [Adoptium JDK17](https://mirrors.tuna.tsinghua.edu.cn/Adoptium/17/jdk/x64/windows/)

**Comment by looly** [comment]
@dddddkkkkk 感谢提供的解决思路。貌似第三方的openJDK都没有这个校验。

**Comment by yyn0210** [comment]
验证过红帽和微软的也没问题

**Comment by CherryRum** [comment]
> 验证过红帽和微软的也没问题

不必验证openjdk,在openjdk没有证书验证这个环节.

**Comment by 709343767** [comment]
SecureUtil.disableBouncyCastle();   虽然不报错JCE cannot authenticate the provider BC，但是无法使用sm4等算法了

**Comment by 709343767** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CherryRum** [comment]
@looly
这个问题其实已经存在很久了，大概持续了两年左右。造成问题的原因并不唯一，涉及多个方面。目前 Oracle JDK 官方已经在新版本中修复了相关问题。

如果您必须使用 **Oracle JDK**，建议尝试 **JDK 17.0.10+** 版本（请注意，这个版本之后是 **付费版本**）。
相关参考链接：
👉 [[JDK-8313742 | JCE verification issue](https://bugs.java.com/bugdatabase/view_bug?bug_id=JDK-8313742)](https://bugs.java.com/bugdatabase/view_bug?bug_id=JDK-8313742)

另外，**OpenJDK** 暂时没有这个问题，因为它不需要验证 JCE 签名（**openjdk 不做 jce 签名校验**）。

如果仍然无法解决，建议您尝试以下方案（按优先级排序）：

1. **升级到 Spring Boot 3.2.2+**
2. **更换为 OpenJDK（推荐常用发行版，如 Temurin、Zulu 等）**

若由于历史原因无法升级更换 或 Spring Boot，您可以尝试一个「不太优雅」的临时方案：

```xml
<plugins>
  <plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
      <requiresUnpack>
        <dependency>
          <groupId>org.bouncycastle</groupId>
          <artifactId>bcprov-jdk15on</artifactId>
        </dependency>
      </requiresUnpack>
    </configuration>
  </plugin>
</plugins>
```
不过需要注意，这种方式在多上下文加载的场景下仍有可能出现问题，因此**并不推荐作为长期解决方案**。

还有,springboot修复的只是jar包问题,war的修复近期还没上**3.5.7**暂时还没有
https://github.com/spring-projects/spring-boot/issues/28837
https://github.com/spring-projects/spring-boot/pull/47284

**Comment by 709343767** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
