### ISSUE TITLE
dubbo接口返回值为Tree时报错：[ServiceDefinitionBuilder] Map type [cn.hutool.core.lang.tree.Tree<java.lang.Long>] with unexpected amount of arguments [[Ljava.lang.reflect.Type;@2a8e30e3].[class java.lang.Long]

### ISSUE THREAD

**Issue by ddfeiyu** [looly/hutool#2645]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5

### 问题描述（包括截图）

1. 复现代码

```java
     List<cn.hutool.core.lang.tree.Tree<Long>> getTree(boolean lazy, Long parentQuestionId);

```

2. 堆栈信息
```
java.lang.IllegalArgumentException: [ServiceDefinitionBuilder] Map type [cn.hutool.core.lang.tree.Tree<java.lang.Long>] with unexpected amount of arguments [[Ljava.lang.reflect.Type;@2a8e30e3].[class java.lang.Long]

	at org.apache.dubbo.metadata.definition.builder.MapTypeBuilder.build(MapTypeBuilder.java:56)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:50)
	at org.apache.dubbo.metadata.definition.builder.CollectionTypeBuilder.build(CollectionTypeBuilder.java:61)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:50)
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:76)
	at org.apache.dubbo.metadata.definition.ServiceDefinitionBuilder.build(ServiceDefinitionBuilder.java:89)
	at org.apache.dubbo.metadata.definition.ServiceDefinitionBuilder.build(ServiceDefinitionBuilder.java:45)
	at org.apache.dubbo.registry.client.metadata.store.InMemoryWritableMetadataService.publishServiceDefinition(InMemoryWritableMetadataService.java:174)
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.publishServiceDefinition(MetadataUtils.java:64)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:538)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:345)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:320)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:244)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportService(DubboBootstrap.java:1099)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$exportServices$14(DubboBootstrap.java:1086)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:1070)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:886)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:70)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:63)
	at com.alibaba.spring.context.OnceApplicationContextEventListener.onApplicationEvent(OnceApplicationContextEventListener.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:43)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by ddfeiyu** [comment]
一、背景：由于Tree继承了Map，就会使用MapTypeBuilder。
TypeBuilder默认有4个实现以及一个DefaultTypeBuilder

默认有4个实现:
```java
array=org.apache.dubbo.metadata.definition.builder.ArrayTypeBuilder
collection=org.apache.dubbo.metadata.definition.builder.CollectionTypeBuilder
map=org.apache.dubbo.metadata.definition.builder.MapTypeBuilder
enum=org.apache.dubbo.metadata.definition.builder.EnumTypeBuilder

```
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/104772676/194853005-b267b91b-8106-469e-afb0-62372b48dbb9.png">

二、报错原因：
如果是Map，必须有2个参数。
报错代码定位：
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/104772676/194853531-f16ec765-1b0c-4582-aea3-c14b163e95fc.png">


三、如何解决：
目前的解决方式是扩展TypeBuilder，新增一个针对Tree类型的HuToolTreeTypeBuilder。

①、新增文件 org.apache.dubbo.metadata.definition.builder.TypeBuilder
<img width="596" alt="image" src="https://user-images.githubusercontent.com/104772676/194852314-c9908512-6e2e-49a7-b6bc-f68c370f2f65.png">

文件内容：
cn.hutool.core.lang.tree.Tree=com.xxx.dubbo.metadata.definition.builder.HuToolTreeTypeBuilder

②、代码 HuToolTreeTypeBuilder 如下：
```java

import cn.hutool.core.lang.tree.Tree;
import org.apache.dubbo.metadata.definition.TypeDefinitionBuilder;
import org.apache.dubbo.metadata.definition.builder.TypeBuilder;
import org.apache.dubbo.metadata.definition.model.TypeDefinition;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.Map;

import static org.apache.dubbo.common.utils.TypeUtils.*;

public class HuToolTreeTypeBuilder implements TypeBuilder {

    @Override
    public boolean accept(Type type, Class<?> clazz) {
        if (clazz == null) {
            return false;
        }
        **// FIXME ①、只有Tree才应用HuToolTreeTypeBuilder**
        return Tree.class.isAssignableFrom(clazz);
    }

    @Override
    public TypeDefinition build(Type type, Class<?> clazz, Map<Class<?>, TypeDefinition> typeCache) {
        if (!(type instanceof ParameterizedType)) {
            return new TypeDefinition(clazz.getName());
        }

        ParameterizedType parameterizedType = (ParameterizedType) type;
        Type[] actualTypeArgs = parameterizedType.getActualTypeArguments();
        int actualTypeArgsLength = actualTypeArgs == null ? 0 : actualTypeArgs.length;

        String mapType = type.toString();

        TypeDefinition typeDefinition = new TypeDefinition(mapType);

        for (int i = 0; i < actualTypeArgsLength; i++) {
            Type actualType = actualTypeArgs[i];
            TypeDefinition item = null;
            Class<?> rawType = getRawClass(actualType);
            if (isParameterizedType(actualType)) {
                // Nested collection or map.
                item = TypeDefinitionBuilder.build(actualType, rawType, typeCache);
            } else if (isClass(actualType)) {
                item = TypeDefinitionBuilder.build(null, rawType, typeCache);
            }
            typeDefinition.getItems().add(item);
        }

        return typeDefinition;
    }
}

```

**Comment by looly** [comment]
Tree虽然继承自Map，但是map的泛型参数是指定ID的类型，导致的问题。

hutool这边没有办法创建dubbo的任何对象，所以在dubbo中或你的项目中单独定义HuToolTreeTypeBuilder是不错的选择。
