### ISSUE TITLE
aes解密失败，怀疑是不是数据太大导致解密失败

### ISSUE THREAD

**Issue by iceBurgz** [looly/hutool#2661]
### 版本情况

JDK版本：    JDK 1.8.0_202
hutool版本： 5.8.8

### 问题描述（包括截图）
大部分解密都是正常的，但是偶尔会解密失败，报cn.hutool.crypto.CryptoException: BadPaddingException: pad block corrupted，怀疑是不是数据量过大导致，求大神解答，（Google了好久没有找到类似解答）
1. 复现代码

```java
String key = "Pr0kS3abd8CYiIi6PDeU9g==";
        String offset = "4382822409223508";
        String message = "EY1vrW7YtYKD4kiha3GSLRZECnvIQSWz/JUkVq/TZXJ4MiA3sWI3/JZxthMghBl3N7ugngwexcaVeV1dZmiAf83EtUQhaXhKMJ/ZECkf2sdoWxQPia+a1g7jsn4jO4dHRcxsKYcHZcj7kdMKhjN24R4OA2h2rYU9zyu5Hn+iCHXdk1+Ya22BqxlV+9VexHwfDhjfNVsOfT53gVwOypRZxKd1l1ozoc79OXJOo6s7UnfxbkKuae+wI+0OC8ykvDJrVoTl2GimUvU27GSzGFhG1LjgX4CbTTQaVI/0CYffkjlURRWiLhfngqfVq/HBp/62IC8Jc7ZJgg9nQNbBr4uegiH2nkFO8ByusXX6MVJtgt+wbfqi/3CJj5KILQkpxxOnyhIUod5M7IdQXiXiOtUsnp24Qt7LmYvqUdqjpKqqoDqCLYHSZwV6M1YXn23f6TP0bXcoo2+D/N4q/ztbYMzyTkU1LME+vBUedBMHD5qKY3KHjh6JTEW0oGqCkGXp5r2rI2ZHFrQQQeyDWixee4zCK0kKFR1xScMhZbW6MrKhCFEbshBi4mjodv1c6RRaqTWPJfME5/eJSgyUAZlognVw9eK1DIirebNtOEN8jIgyZnY/x58eEpKusGv568QFvH5+JqFzuFcMkRW0gREkYJQnIWL+l4KI49Y7yg5ci8N7DIOsCGh+ADJ+3rmtKPCHtU13lrwjSavw5TceAh5up6iFlF7I/ozMqsE2Nxy2rmWDYDQAk21WoaHfq9i5J+ks46pOvJo1BvYRHEdGsd5Q67wacTBXgOANlQTNSKqZkd3MVZr57Fu6yd6CgjcKTEaI2VPDccuLqAHW73BqpiWts+R8riKSg2HSeaHVCTBLmRxfqOeRBVk8pSKS/FtDO99NG22kQTve8TkGNQDzWZzx/2qcoDQUEGRHvWApN2OncfneFPYwx3ECUjGi+Nt+4iLYgnrD6xEDtjZitAY+wB6rH0nayfLJVLAAxZJ0eoBGkfQ1OJ18D4EEfLjY232SUAu+WqDm/Uh1GDUXNCCAN6htY21jBy5tvBr6W73V9NQUEVjPnaGWGlLkdkTXmxTGgvzgozK1OK4fAko34rnVcivBomjOARI7fjyzZEI7EnHPP5qETr5tkZ1NwAl/kBfUj7Hk1B+95XTzMevlGN5REUrL+viKKZ0MdBmJTHImdYArUh/w8oCxCLzGkhs5xTVBb0gwD3u2gy+ZPLosjlEdn5jfnCWD3oP2IdooHYTsFkAleQbMgLfqZQhuXq0+8VRybaFVx6MVpqIOWkdXxkXy8vpHvHVolWcJYzbJEXh+r644ncbQpE1T40dx/Nbt2LP+FJeM4YiWZl0kvmPGLEVv3gaPWNsLcsto1poLL8VvMOZsvyHru40r43sYQMHSuUA7J36o3+DLmvSTmEtPBGR8vfDO/80uoIEqci2I3ybxHpLRVFFWCkmtngrMMGV2/VxN3KOx4RpZC4q16tXEMan7fIMwjWD88t4F2GH3rxMDVQ3eMx426wgsX3dghJI4JqlgR2OR4zbtA2eOqlwnSdcZrnCb9aInNhwo4TT+8hhjb9VEzSCjdChj5ViQJPfbAXwJ2XDCgy+uKXeIxEP9dVgdbfpYJQ8wj6VlQUzafLEmN7ZhFbhg/cnLo403WKuklOSUnstkIh1M18TOcwIjyfE39bRwgq8lj5kdA7rZXMLwahRgJXkp3pk7QNr/2hEuC+gdtlsRgw0JH/pspZmqZnS2yAu4Eo4x9kig+m0Ok8RKe1/pW0SqCcBN13GP6AQYBs9+i6zywuSI7F/vgfipx03aD3NNYXgZtLHO+feycIC5luQz1ujqbiU=";
AES aes = new AES(Mode.CBC, Padding.ISO10126Padding, key.getBytes(), offset.getBytes());
        System.out.print(aes.decryptStr(message, CharsetUtil.CHARSET_UTF_8));
```

2. 堆栈信息
cn.hutool.crypto.CryptoException: BadPaddingException: pad block corrupted
	at cn.hutool.crypto.symmetric.SymmetricCrypto.decrypt(SymmetricCrypto.java:388)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.decrypt(SymmetricCrypto.java:424)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.decryptStr(SymmetricCrypto.java:435)

**Comment by wangfanlan** [comment]
你的message是用aes.encryptBase64方法加密生成的吗

**Comment by iceBurgz** [comment]
> 
是前端加密的，后端解密，前端的加密方法如下
// 加密
  encrypt: (plaintext: string | object, key: string, iv) => {
    iv = Utf8.parse(iv) // 十六位十六进制数作为密钥偏移量
    if (plaintext instanceof Object) {
      // JSON.stringify
      plaintext = JSON.stringify(plaintext)
    }
    const srcs = Utf8.parse(plaintext)
    key = Utf8.parse(key)
    const encrypted = AES.encrypt(srcs, key, {
      mode: CBC,
      padding: Iso10126,
      iv
    })
    return encrypted.toString()
  },

**Comment by changhr2013** [comment]
@iceBurgz 前端用的 crypto-js?

**Comment by iceBurgz** [comment]
> @iceBurgz 前端用的 crypto-js?
@changhr2013 "crypto-es": "^1.2.7"

**Comment by changhr2013** [comment]
@iceBurgz 
Java 的错误堆栈报告的异常是说解 padding 时失败，说明解密后的原文不符合 padding 填充的规则。

大致看了下 crypto-es 和 crypto-js 的 API 函数几乎是一致的，我可以给你个 crypto-js 的版本试一下，目前看你这个生成的密文好像确实有点问题。

但是跟数据量大小应该是没什么关系，aes 是分组加密，每次运算只会运算 16 个字节，以下的例子我测试了个 4096 的长度也不会出什么问题。

使用 crypto-js 加密：

```js
const CryptoJS = require("crypto-js");

// 待加密的原文，使用 utf-8 编码处理
let message = CryptoJS.enc.Utf8.parse("hello world");

// 密钥的 base64
let key = CryptoJS.enc.Base64.parse("Pr0kS3abd8CYiIi6PDeU9g==");

// iv
let iv = CryptoJS.enc.Utf8.parse("4382822409223508");

// 加密
let encrypted = CryptoJS.AES.encrypt(
    message,
    key,
    {
        iv: iv,
        mode: CryptoJS.mode.CBC,
        padding: CryptoJS.pad.Iso10126
    }
);

// 密文，使用 base64 编码
let cipherTextBase64 = CryptoJS.enc.Base64.stringify(encrypted.ciphertext);

// 打印密文
console.log(cipherTextBase64);
```

Hutool 解密：

```java
@Test
public void testHutoolDecrypt() {
    // 密钥的 base64
    String keyBase64 = "Pr0kS3abd8CYiIi6PDeU9g==";
    // iv
    String iv = "4382822409223508";
    // 待解密的密文，base64 格式
    String message = "DAI5/h/c7jC/bTaliQULWw==";

    // 使用 hutool 解密
    cn.hutool.crypto.symmetric.AES aes = new cn.hutool.crypto.symmetric.AES(Mode.CBC, Padding.ISO10126Padding, Base64.getDecoder().decode(keyBase64), iv.getBytes());
    String decrypt = aes.decryptStr(Base64.getDecoder().decode(message), CharsetUtil.CHARSET_UTF_8);
    // 打印解密后的原文
    System.out.println(decrypt);
}
```

**Comment by iceBurgz** [comment]
> 

@changhr2013 我替换一下前端加密逻辑试一下，thx~

**Comment by looly** [comment]
@changhr2013 感谢解答~~
