### ISSUE TITLE
获取文件路径问题

### ISSUE THREAD

**Issue by cheng521521** [looly/hutool#2672]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在Mac系统中文件可以找见，部署到K8sPod中文件找不见了。解压pod jar包显示文件是在classes下面的。为什么处理过后的绝对路径
里面会有感叹号？
1. 复现代码

```java
FileReader fileReader = new FileReader("Deployment_Template.config");
```

2. 堆栈信息
 cn.hutool.core.io.IORuntimeException: File not exist: /project/xxxxjar!/BOOT-INF/classes!/Deployment_Template.config

 	at cn.hutool.core.io.file.FileReader.checkFile(FileReader.java:300)

 	at cn.hutool.core.io.file.FileReader.<init>(FileReader.java:57)

 	at cn.hutool.core.io.file.FileReader.<init>(FileReader.java:75)

 	at cn.hutool.core.io.file.FileReader.<init>(FileReader.java:102)

**Comment by cheng521521** [comment]
应该是和下面这段代码有关,我找了半天没找见问题出在哪里。
```
package cn.hutool.core.io;
	/**
	 * 获取绝对路径<br>
	 * 此方法不会判定给定路径是否有效（文件或目录存在）
	 *
	 * @param path      相对路径
	 * @param baseClass 相对路径所相对的类
	 * @return 绝对路径
	 */
	public static String getAbsolutePath(String path, Class<?> baseClass) {
		String normalPath;
		if (path == null) {
			normalPath = StrUtil.EMPTY;
		} else {
			normalPath = normalize(path);
			if (isAbsolutePath(normalPath)) {
				// 给定的路径已经是绝对路径了
				return normalPath;
			}
		}

		// 相对于ClassPath路径
		final URL url = ResourceUtil.getResource(normalPath, baseClass);
		if (null != url) {
			// 对于jar中文件包含file:前缀，需要去掉此类前缀，在此做标准化，since 3.0.8 解决中文或空格路径被编码的问题
			return FileUtil.normalize(URLUtil.getDecodedPath(url));
		}

		// 如果资源不存在，则返回一个拼接的资源绝对路径
		final String classPath = ClassUtil.getClassPath();
		if (null == classPath) {
			// throw new NullPointerException("ClassPath is null !");
			// 在jar运行模式中，ClassPath有可能获取不到，此时返回原始相对路径（此时获取的文件为相对工作目录）
			return path;
		}

		// 资源不存在的情况下使用标准化路径有问题，使用原始路径拼接后标准化路径
		return normalize(classPath.concat(Objects.requireNonNull(path)));
	}
```

**Comment by cheng521521** [comment]
找见原因了
