### ISSUE TITLE
BeanUtil.copyProperties  包含EnumSet ，类型转换异常 

### ISSUE THREAD

**Issue by lianyiwuming** [looly/hutool#2683]
### 版本情况

JDK版本：    1.8.0_73
hutool版本： 5.8.9（v5-master问题依旧）

### 问题描述（包括截图）
使用cn.hutool.core.bean.BeanUtil#copyProperties(java.lang.Object, java.lang.Class<T>, java.lang.String...) 功能，copy包含EnumSet集合的对象，出现异常。异常详情见下面堆栈信息。走测试用例beanWithEnumSetTest 复现。
1. 复现代码
走测试用例beanWithEnumSetTest 复现
```java
	enum Version {
		dev,
		prod
	}

	@Data
	public static class Vto {
		EnumSet<Version> versions;
	}


	@Test
	public void beanWithEnumSetTest() {
		Vto v1 = new Vto();
		v1.setVersions(EnumSet.allOf(Version.class));
		System.out.println(BeanUtil.copyProperties(v1, Vto.class));
	}
```

3. 堆栈信息

```java

java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')

	at cn.hutool.core.util.TypeUtil.getClass(TypeUtil.java:41)
	at cn.hutool.core.util.ClassUtil.getTypeArgument(ClassUtil.java:953)
	at cn.hutool.core.util.ClassUtil.getTypeArgument(ClassUtil.java:941)
	at cn.hutool.core.collection.CollUtil.create(CollUtil.java:1035)
	at cn.hutool.core.convert.impl.CollectionConverter.convertInternal(CollectionConverter.java:75)
	at cn.hutool.core.convert.impl.CollectionConverter.convert(CollectionConverter.java:64)
	at cn.hutool.core.convert.ConverterRegistry.convertSpecial(ConverterRegistry.java:352)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:276)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:308)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:765)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:86)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:342)
	at cn.hutool.core.bean.copier.BeanToBeanCopier.lambda$copy$0(BeanToBeanCopier.java:78)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at cn.hutool.core.bean.copier.BeanToBeanCopier.copy(BeanToBeanCopier.java:50)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:776)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:737)
	at cn.hutool.core.bean.BeanUtilTest.beanWithEnumSetTest(BeanUtilTest.java:658)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

```

**Comment by looly** [comment]
关联PR已合并。

**Comment by lianyiwuming** [comment]
ok ，thx&nbsp;


无名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden ***@***.***&gt;; 
发送时间: 2022年11月12日(星期六) 晚上7:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] BeanUtil.copyProperties  包含EnumSet ，类型转换异常  (Issue #2683)





 
关联PR已合并。
