### ISSUE TITLE
junit片状测试 in hutool-json

### ISSUE THREAD

**Issue by anantdahiya8** [looly/hutool#2709]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

我们使用该工具检测到 hutool-json 中存在 flaky test using [NonDex](https://github.com/TestingResearchIllinois/NonDex)
`mvn -pl hutool-json edu.illinois:nondex-maven-plugin:1.1.2:nondex`

Tests:
[INFO] cn.hutool.json.TransientTest#beanWithoutTransientTest
[INFO] cn.hutool.json.Issues1881Test#parseTest

```java
Console.log("报错了");
```

2. 堆栈信息

$ mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cn.hutool.json.TransientTest#beanWithoutTransientTest
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< cn.hutool:hutool-json >------------------------
[INFO] Building hutool-json 5.8.9
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> nondex-maven-plugin:1.1.2:nondex (default-cli) > test-compile @ hutool-json >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hutool-json ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hutool-json ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 32 source files to C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\target\classes
[WARNING] /C:/Users/admin/Desktop/CS527/PROJECT_FINAL/hutool/hutool-json/src/main/java/cn/hutool/json/JSONConverter.java:[119,68] unchecked cast
  required: T
  found:    capture#1 of ?
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hutool-json ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ hutool-json ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 74 source files to C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\target\test-classes
[INFO] /C:/Users/admin/Desktop/CS527/PROJECT_FINAL/hutool/hutool-json/src/test/java/cn/hutool/json/Issues1881Test.java: C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\src\test\java\cn\hutool\json\Issues1881Test.java uses or overrides a deprecated API.
[INFO] /C:/Users/admin/Desktop/CS527/PROJECT_FINAL/hutool/hutool-json/src/test/java/cn/hutool/json/Issues1881Test.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] <<< nondex-maven-plugin:1.1.2:nondex (default-cli) < test-compile @ hutool-json <<<
[INFO]
[INFO]
[INFO] --- nondex-maven-plugin:1.1.2:nondex (default-cli) @ hutool-json ---
INFO: The original argline is:
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex
nondexJarDir=.nondex
nondexExecid=clean_w6WMCbVa5vyRA8nwalSWuqtgRhW5zd0kbtgEQZDuqdU=
nondexLogging=CONFIG
test=
[INFO] Surefire report directory: C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex\clean_w6WMCbVa5vyRA8nwalSWuqtgRhW5zd0kbtgEQZDuqdU=

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running cn.hutool.json.TransientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.259 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

INFO: Adding excluded groups to newly created one
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex
nondexJarDir=C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex
nondexExecid=uJkeu1QQoQhygyX4yAUTw5NioiYhvjxrCLeINppyn10=
nondexLogging=CONFIG
test=
[INFO] Surefire report directory: C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex\uJkeu1QQoQhygyX4yAUTw5NioiYhvjxrCLeINppyn10=

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Concurrency config is parallel='none', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running cn.hutool.json.TransientTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.154 sec <<< FAILURE!
beanWithoutTransientTest(cn.hutool.json.TransientTest)  Time elapsed: 0.005 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"[id":"3243","bizNo":"bizNo]"}> but was:<{"[bizNo":"bizNo","id":"3243]"}>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at cn.hutool.json.TransientTest.beanWithoutTransientTest(TransientTest.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:62)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:139)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   beanWithoutTransientTest(cn.hutool.json.TransientTest): expected:<{"[id":"3243","bizNo":"bizNo]"}> but was:<{"[bizNo":"bizNo","id":"3243]"}>

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

INFO: Surefire failed when running tests for uJkeu1QQoQhygyX4yAUTw5NioiYhvjxrCLeINppyn10=
INFO: Adding excluded groups to newly created one
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=974622
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex
nondexJarDir=C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex
nondexExecid=PvqOTeyapXGeHqZt6z0kNqAsvywpE4ev6Ry1J4yVQ=
nondexLogging=CONFIG
test=
[INFO] Surefire report directory: C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex\PvqOTeyapXGeHqZt6z0kNqAsvywpE4ev6Ry1J4yVQ=

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Concurrency config is parallel='none', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running cn.hutool.json.TransientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.148 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

INFO: Adding excluded groups to newly created one
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=1016066
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex
nondexJarDir=C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex
nondexExecid=soBLS2savBiyCrUtPTyk0haTf192o9ZPBsc7yiRTeBM=
nondexLogging=CONFIG
test=
[INFO] Surefire report directory: C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex\soBLS2savBiyCrUtPTyk0haTf192o9ZPBsc7yiRTeBM=

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Concurrency config is parallel='none', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running cn.hutool.json.TransientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.151 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] NonDex SUMMARY:
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=933178 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex" -DnondexJarDir="C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex" -DnondexExecid=uJkeu1QQoQhygyX4yAUTw5NioiYhvjxrCLeINppyn10= -DnondexLogging=CONFIG
[WARNING] cn.hutool.json.TransientTest#beanWithoutTransientTest
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=974622 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex" -DnondexJarDir="C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex" -DnondexExecid=PvqOTeyapXGeHqZt6z0kNqAsvywpE4ev6Ry1J4yVQ= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=1016066 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex" -DnondexJarDir="C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex" -DnondexExecid=soBLS2savBiyCrUtPTyk0haTf192o9ZPBsc7yiRTeBM= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] Across all seeds:
[INFO] cn.hutool.json.TransientTest#beanWithoutTransientTest
[INFO] Test results can be found at:
[INFO] file://C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex\uJkeu1QQoQhygyX4yAUTw5NioiYhvjxrCLeINppyn10=\test_results.html
[INFO] [NonDex] The id of this run is: uJkeu1QQoQhygyX4yAUTw5NioiYhvjxrCLeINppyn10=
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.448 s
[INFO] Finished at: 2022-11-04T01:14:40-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal edu.illinois:nondex-maven-plugin:1.1.2:nondex (default-cli) on project hutool-json: Unable to execute mojo: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\admin\Desktop\CS527\PROJECT_FINAL\hutool\hutool-json\.nondex\uJkeu1QQoQhygyX4yAUTw5NioiYhvjxrCLeINppyn10= for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
单元测试问题吧？我没看懂。

**Comment by anantdahiya8** [comment]
cn.hutool.json.TransientTest#beanWithoutTransientTest
cn.hutool.json.Issues1881Test#parseTest

将对象转换为 JSON 时，元素的顺序是未定义的。测试应该能够处理所有这些情况，否则它们有时可能会失败。

Fix: https://github.com/dromara/hutool/pull/2713
