### ISSUE TITLE
httpRequest的patch请求出错

### ISSUE THREAD

**Issue by zzcabc** [looly/hutool#2710]
### 版本情况

JDK版本：    oraclejdk_8_281 和 oraclejdk_17.0.3
hutool版本： 5.8.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

使用httpClient没有问题

1. 复现代码
```java
HttpResponse execute = HttpRequest.patch("url")
                .header(Header.AUTHORIZATION, getSecret(secret))
                .body(json)
                .execute();
```

2. 堆栈信息
```
Exception in thread "main" java.lang.IllegalArgumentException: Field [modifiers] is not exist in [java.lang.reflect.Field]
	at cn.hutool.core.lang.Assert.lambda$notNull$3(Assert.java:217)
	at cn.hutool.core.lang.Assert.notNull(Assert.java:197)
	at cn.hutool.core.lang.Assert.notNull(Assert.java:217)
	at cn.hutool.core.util.ReflectUtil.setFieldValue(ReflectUtil.java:318)
	at cn.hutool.http.HttpGlobalConfig.allowPatch(HttpGlobalConfig.java:201)
	at cn.hutool.http.HttpConnection.setMethod(HttpConnection.java:123)
	at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1154)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1030)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1006)
```

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
JDK本身不支持patch，hutool使用注入方式hack了一下，可能存在不兼容性。考虑使用HttpClient吧。
