### ISSUE TITLE
默认的全局单例默认信任管理器报NullPointerException

### ISSUE THREAD

**Issue by aulang** [looly/hutool#2716]
### 版本情况

JDK版本：    openjdk_17.0.5
hutool版本： 5.8.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
默认信任管理器DefaultTrustManager的acceptedIssuers返回null报NullPointerException
1. 复现代码
```java
    @Bean
    public RestTemplate restTemplate() throws Exception {
        return new RestTemplate(clientHttpRequestFactory());
    }

    public ClientHttpRequestFactory clientHttpRequestFactory() throws Exception {
        return new OkHttp3ClientHttpRequestFactory(httpClient());
    }

    public OkHttpClient httpClient() throws Exception {
        return new OkHttpClient.Builder()
                .sslSocketFactory(sslSocketFactory(), DefaultTrustManager.INSTANCE)
                .hostnameVerifier(hostnameVerifier())
                .build();
    }

    public SSLSocketFactory sslSocketFactory() throws Exception {
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, new TrustManager[]{DefaultTrustManager.INSTANCE}, new SecureRandom());
        return sslContext.getSocketFactory();
    }

    public HostnameVerifier hostnameVerifier() {
        return (hostname, sslSession) -> true;
    }
```

2. 堆栈信息
Caused by: java.lang.NullPointerException: trustManager.acceptedIssuers must not be null
	at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:163)
	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:160)
	at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42)
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:811)
	at cn.aulang.oauth.config.RestTemplateConfiguration.httpClient(RestTemplateConfiguration.java:37)
	at cn.aulang.oauth.config.RestTemplateConfiguration.clientHttpRequestFactory(RestTemplateConfiguration.java:32)
	at cn.aulang.oauth.config.RestTemplateConfiguration.restTemplate(RestTemplateConfiguration.java:28)
	at cn.aulang.oauth.config.RestTemplateConfiguration$$EnhancerBySpringCGLIB$$b03415f7.CGLIB$restTemplate$4(<generated>)
	at cn.aulang.oauth.config.RestTemplateConfiguration$$EnhancerBySpringCGLIB$$b03415f7$$FastClassBySpringCGLIB$$9d04ce01.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at cn.aulang.oauth.config.RestTemplateConfiguration$$EnhancerBySpringCGLIB$$b03415f7.restTemplate(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 34 common frames omitted
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
默认`getAcceptedIssuers`返回确实是null，5.8.10修改为返回`new X509Certificate[0]`
