### ISSUE TITLE
String literals in formulas can't be bigger than 255 characters ASCII

### ISSUE THREAD

**Issue by ADolphin-02** [looly/hutool#2717]
### 版本情况

JDK版本：    openjdk_8_201
  hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
String literals in formulas can't be bigger than 255 characters ASCII
导出excel 下拉的选项太多 array 太长报错
1. 复现代码

```java
                    writer.addSelect(new CellRangeAddressList(2, 10002, z, z), array);

```

2. 堆栈信息
java.lang.IllegalArgumentException: String literals in formulas can't be bigger than 255 characters ASCII
	at org.apache.poi.ss.formula.ptg.StringPtg.<init>(StringPtg.java:61)
	at org.apache.poi.hssf.usermodel.DVConstraint.createListFormula(DVConstraint.java:419)
	at org.apache.poi.hssf.usermodel.DVConstraint.createFormulas(DVConstraint.java:391)
	at org.apache.poi.hssf.usermodel.HSSFDataValidation.createDVRecord(HSSFDataValidation.java:211)
	at org.apache.poi.hssf.usermodel.HSSFSheet.addValidationData(HSSFSheet.java:476)
	at cn.hutool.poi.excel.ExcelWriter.addValidationData(ExcelWriter.java:639)
	at cn.hutool.poi.excel.ExcelWriter.addSelect(ExcelWriter.java:628)
	at com.kakarote.core.utils.ExcelParseUtil.importExcel(ExcelParseUtil.java:167)

4. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/55866634/200219000-ac7a8697-f9d9-46cc-9499-c83422ac9723.png)

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
https://segmentfault.com/q/1010000009395339 参考

这个是poi的限制，数据超过255了
