### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by 203579397** [looly/hutool#2734]
07:02:47.139 [Hutool-socket-156] ERROR c.h.s.a.AcceptHandler - [failed,34] - Too many open files
java.io.IOException: Too many open files
	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.accept0(Native Method) 
	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.accept(UnixAsynchronousServerSocketChannelImpl.java:344)
	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.implAccept(UnixAsynchronousServerSocketChannelImpl.java:280)
	at sun.nio.ch.AsynchronousServerSocketChannelImpl.accept(AsynchronousServerSocketChannelImpl.java:135)
	at cn.hutool.socket.aio.AioServer.accept(AioServer.java:132)
	at cn.hutool.socket.aio.AcceptHandler.completed(AcceptHandler.java:20)
	at cn.hutool.socket.aio.AcceptHandler.completed(AcceptHandler.java:15)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
	at sun.nio.ch.Invoker.invoke(Invoker.java:185)
	at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.onEvent(UnixAsynchronousServerSocketChannelImpl.java:193)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by ZZemptypoint** [comment]
提供的信息太少了

**Comment by looly** [comment]
你是不创建的线程太多了，没有及时关闭？

有补充请再打开issue。
