### ISSUE TITLE
UnsupportedZipFeatureException: Unsupported feature data descriptor used in entry

### ISSUE THREAD

**Issue by zxuanhong** [looly/hutool#2736]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.8.9

### 问题描述（包括截图）
1. 解压文件异常，本地压缩工具解压正常。使用hutool解压提示：UnsupportedZipFeatureException: Unsupported feature data descriptor used in entry
2. 复现代码

```java
Extractor extractor = CompressUtil.createExtractor(
                    CharsetUtil.defaultCharset(),
                    file.getInputStream());
extractor.extract(FileUtil.file(saveDirectory));
```

3. 堆栈信息
```
cn.hutool.core.io.IORuntimeException: UnsupportedZipFeatureException: Unsupported feature data descriptor used in entry test/framework-rpc/.gitkeep
	at cn.hutool.extra.compress.extractor.StreamExtractor.extract(StreamExtractor.java:105)
	at cn.hutool.extra.compress.extractor.Extractor.extract(Extractor.java:23)
	at com.ktwlrj.javadoctools.module.service.impl.ConversionServiceImpl.swaggerToSpringDoc(ConversionServiceImpl.java:71)
	at com.ktwlrj.javadoctools.module.controller.ConversionController.storage(ConversionController.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.commons.compress.archivers.zip.UnsupportedZipFeatureException: Unsupported feature data descriptor used in entry test/framework-rpc/.gitkeep
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.read(ZipArchiveInputStream.java:517)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.skip(ZipArchiveInputStream.java:701)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.closeEntry(ZipArchiveInputStream.java:772)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:270)
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:475)
	at cn.hutool.extra.compress.extractor.StreamExtractor.extractInternal(StreamExtractor.java:123)
	at cn.hutool.extra.compress.extractor.StreamExtractor.extract(StreamExtractor.java:103)
```
4. 测试涉及到的文件（注意脱密）
[test.zip](https://github.com/dromara/hutool/files/10017326/test.zip)

**Comment by ZZemptypoint** [comment]
确实存在这个问题, 但是真正报错的是底层依赖的`apache`的`ZipArchiveInputStream`: 
> at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.read(ZipArchiveInputStream.java:517)

你的test.zip可能有点问题, 我用pc端解压软件解压, 然后再压缩后, hutool就可以正常解压所有文件了

**Comment by zxuanhong** [comment]
@ZZemptypoint 我确信是某个配置问题，我用apache自己实现的解压一切正常，代码如下:
```
public static void unzip(InputStream inputStream, String destDir) {
        ArchiveEntry zipEntry;
        try (BufferedInputStream bufferedInputStream = new BufferedInputStream(inputStream);
             ZipArchiveInputStream zipInputStream = new ZipArchiveInputStream(bufferedInputStream, CharsetUtil.defaultCharset().name(), false, true)) {
            while ((zipEntry = zipInputStream.getNextEntry()) != null) {
                File file = new File(destDir, zipEntry.getName());
                if (zipEntry.isDirectory()) {
                    boolean mkdirs = file.mkdirs();
                    if (!mkdirs) {
                        log.error("------------------创建目录失败--------->:\n{}", file.getAbsoluteFile());
                    }
                } else {
                    try (FileOutputStream outPut = new FileOutputStream(file);
                         BufferedOutputStream bufferedOutputStream = new BufferedOutputStream(outPut)) {
                        IOUtils.copy(zipInputStream, bufferedOutputStream, 8192);
                    } catch (IOException e) {
                        log.error("------------------解压文件异常--------->:\n{}", e.getMessage());
                    }
                }
            }
        } catch (IOException e) {
            throw new RuntimeException("解压失败", e);
        } finally {
            try {
                if (inputStream != null) {
                    inputStream.close();
                }
            } catch (IOException e) {
                log.error("------------------关闭流异常--------->:\n{}", e.getMessage());
            }
        }
    }
```
问题参考链接地址：
```
https://blog.csdn.net/weixin_30376163/article/details/97901246](https://stackoverflow.com/questions/15738312/how-to-fix-org-apache-commons-compress-archivers-zip-unsupportedzipfeatureexcept)
```
<img width="976" alt="image" src="https://user-images.githubusercontent.com/62740686/202163238-34bce4cb-396a-4975-9c2b-b4dd0f9f062e.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/62740686/202163424-8cac9ff7-7ef0-4104-9964-a9ec6bb862ca.png">

**Comment by ZZemptypoint** [comment]
@zxiaozhou 是的，你这个解决方法是可以的.
<p>
因为hutool内部调用的是 <strong>apache</strong> 的ArchiveStreamFactory.createArchiveInputStream()，它根据压缩文件类型提供不同的ArchiveInputStream对象，对于`ZIP`文档，它默认使用的构造方法是：
</p>

```java
public ZipArchiveInputStream(final InputStream inputStream, final String encoding);
```
感谢你的问题，暂时你只能用原生的ZipArchiveInputStream了，我们稍后会讨论该如何解决^_^

**Comment by looly** [comment]
@zxiaozhou 可以看下这个PR：https://github.com/apache/commons-compress/pull/137#issuecomment-690835644

有人给commons-compress提过相关的PR，但是被拒绝了。

因为`allowStoredEntriesWithDataDescriptor`这个选项会导致解压速度变慢和普通文件解压错误（如zip中包含zip文件）。

像是你这类特殊压缩包，考虑自行构造ZipArchiveInputStream。

补充一下，5.8.10会调整`StreamExtractor`构造，调整后可以通过构造此对象自定义。

**Comment by zxuanhong** [comment]
@ZZemptypoint @looly 但就是奇怪，没发现文件有啥子异常啊

**Comment by looly** [comment]
5.8.10可以：

```java
Extractor extractor = new StreamExtractor(CharsetUtil.defaultCharset(), new ZipArchiveInputStream(bufferedInputStream, CharsetUtil.defaultCharset().name(), false, true));
extractor.extract(FileUtil.file(saveDirectory));
```

**Comment by looly** [comment]
@zxiaozhou 忙猜你用的mac，把mac文件打包进去了。

**Comment by zxuanhong** [comment]
@looly 是的，用的就是mac.我已经升级版本了。非常感谢
