### ISSUE TITLE
最新版本解压utf-8格式的压缩包出错

### ISSUE THREAD

**Issue by Cultivators** [looly/hutool#2741]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10

### 问题描述（包括截图）

1. 复现代码
文件是mac平台下压缩的，编码是utf-8。
```java
ZipUtil.unzip(file.getInputStream(), targetFile, Charset.forName("GBK"));
```

2. 堆栈信息
java.lang.IllegalArgumentException: MALFORMED[1]
	at java.util.zip.ZipCoder.toString(ZipCoder.java:65)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at cn.hutool.core.compress.ZipReader.readFromStream(ZipReader.java:219)
	at cn.hutool.core.compress.ZipReader.read(ZipReader.java:184)
	at cn.hutool.core.compress.ZipReader.readTo(ZipReader.java:144)
	at cn.hutool.core.compress.ZipReader.readTo(ZipReader.java:131)
	at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:663)
	at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:648)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
3. 测试涉及到的文件（注意脱密）
无
比如报错的Excel文件，有问题的图片等。

**Comment by ZZemptypoint** [comment]
1. 用本地的解压软件是否能解压?
2. 为什么解压时不用`utf-8`编码?

**Comment by looly** [comment]
看报错是编码错误，请检查zip编码。

如果确认编码没问题，麻烦脱敏后上传我这边测试再打开issue。
