### ISSUE TITLE
FileAppender 追加写入时出错了

### ISSUE THREAD

**Issue by guicaiyue** [looly/hutool#2756]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/43875377/203781355-6b1bbd71-794e-4d83-95b0-f89a3814b466.png)

1. 复现代码

```java
我就是把一个目录下的文件扫描出来，把文件路径写道一个txt中，也就是 195322 个文件。报了很多次下面这个
```

2. 堆栈信息
多线程触发追加写入，锁不住
```java
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at cn.hutool.core.io.file.FileAppender.flush(FileAppender.java:114)
	at cn.hutool.core.io.file.FileAppender.append(FileAppender.java:93)
	at com.example.demo.util.WatchFileHandle.fileHandle(WatchFileHandle.java:77)
	at com.example.demo.util.WatchFileAbstract.asyncFileList(WatchFileAbstract.java:32)
	at com.example.demo.util.WatchFileAbstract.asyncFileList(WatchFileAbstract.java:27)
	at com.example.demo.util.WatchFileAbstract.asyncFileList(WatchFileAbstract.java:27)
	at com.example.demo.util.WatchFileAbstract.asyncFileList(WatchFileAbstract.java:27)
	at com.example.demo.util.WatchFileAbstract.asyncFileList(WatchFileAbstract.java:27)
	at com.example.demo.util.WatchFileAbstract.asyncFileList(WatchFileAbstract.java:27)
	at com.example.demo.util.WatchFileHandle.lambda$syncFileHandle$0(WatchFileHandle.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ZZemptypoint** [comment]
你构造FileAppender的时候是不是没有主动传Lock对象，你需要使用下面这个构造方法
![图片](https://user-images.githubusercontent.com/28431269/203785329-b61cc694-736c-44e0-bc6a-b2d29de1ad0d.png)

**Comment by guicaiyue** [comment]
好的，感谢
