### ISSUE TITLE
使用http上传文件失败

### ISSUE THREAD

**Issue by jdAction** [looly/hutool#2769]
### 版本情况

JDK版本：    jdk-11.0.12
hutool版本： 5.8.10

### 问题描述（包括截图）
上传失败,但是使用postman可以正常上传
![image](https://user-images.githubusercontent.com/87454525/204789354-0da1d2ad-8407-461e-9461-7a3257cfd6a3.png)
![image](https://user-images.githubusercontent.com/87454525/204789431-05ead94b-9bad-44b7-8922-003a6af72679.png)
![image](https://user-images.githubusercontent.com/87454525/204789499-d50c55f7-4261-458c-af63-30ea5337e347.png)

1. 复现代码

 Map<String, Object> hashMap = new HashMap<>(2);
        hashMap.put("file",file2);
        HttpUtil.createPost("http://192.168.43.132:5001/api/v0/add")
                .form(hashMap)
                .keepAlive(true)
                .execute();
        String post = HttpUtil.post("http://192.168.43.132:5001/api/v0/add", hashMap);

2. 堆栈信息
java.io.IOException: Error writing to server
	at java.base/sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:718) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:730) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1613) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:474) ~[hutool-all-5.8.10.jar:na]
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:528) ~[hutool-all-5.8.10.jar:na]
	at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:504) ~[hutool-all-5.8.10.jar:na]
	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:82) ~[hutool-all-5.8.10.jar:na]
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1163) ~[hutool-all-5.8.10.jar:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1030) ~[hutool-all-5.8.10.jar:na]
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1006) ~[hutool-all-5.8.10.jar:na]
	at com.cmbaas.ipfs_cluster.controller.IpfsController.add(IpfsController.java:58) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:696) ~[tomcat-embed-core-9.0.69.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.69.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
4. 测试涉及到的文件（注意脱密）
可以自己创建一个文件

比如报错的Excel文件，有问题的图片等。

**Comment by jdAction** [comment]
version: '3.4'
services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" 
      - "5001:5001" 
      - "8080:8080" 
    volumes:
      - ./compose/ipfs0:/data/ipfs

  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: k51qzi5uqu5djre5th2oarigenrhshkrwfx3o6ph16sdmkszd6npgaisq32rem
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
          - "9094:9094"
          - "9095:9095" # Cluster IPFS Proxy endpoint
          - "9096:9096" # Cluster swarm endpoint
    volumes:
      - ./compose/cluster0:/data/ipfs-cluster

上面的这个是我启动的测试环境,可以直接使用docker-compose 启动 然后直接使用postman请求

**Comment by looly** [comment]
当表单中有文件时，Hutool默认使用multipart/form-data上传。

检查你的服务端是否使用这种方式接收。

有问题补充再打开此issue。

**Comment by jdAction** [comment]
带不带都能上传
![image](https://user-images.githubusercontent.com/87454525/204792491-0796c825-200c-4f2a-971f-808cc4009518.png)
![image](https://user-images.githubusercontent.com/87454525/204793530-5dfbc523-6232-4ea0-83ed-c9a52be1bfee.png)

**Comment by jdAction** [comment]
> 当表单中有文件时，Hutool默认使用multipart/form-data上传。
> 
> 检查你的服务端是否使用这种方式接收。
> 
> 有问题补充再打开此issue。

我补充了,有条件的话你也测试下?

**Comment by looly** [comment]
我看你file是个id？不是一个文件File么？

**Comment by looly** [comment]
你可以看下自己的报文，请求到服务端应该是个JSON，而非multipart/form-data，此时你要使用body方法。

**Comment by jdAction** [comment]
![image](https://user-images.githubusercontent.com/87454525/204936628-bce8ccf8-df25-4da7-b486-0616466aa014.png)
不是JSON而是multipart/form-data,你看到的那个id就是文件名称.
![image](https://user-images.githubusercontent.com/87454525/204936699-5c16e437-9248-4752-84c7-5c8ab6a5f4d5.png)

**Comment by jdAction** [comment]
> 我看你file是个id？不是一个文件File么？

是一个文件
![image](https://user-images.githubusercontent.com/87454525/204936926-7a4d63bb-488d-43bc-9fdd-d70c8003862a.png)

**Comment by jdAction** [comment]
问题解决了,不过咱们目前有设置默认UA的参数吗
![image](https://user-images.githubusercontent.com/87454525/204939726-2fdc2f5c-059b-4e0b-ba45-640622d9685a.png)

**Comment by jdAction** [comment]
UA默认为空也可以,咱们就直接设置一个默认值即可,直接在源码中设置UA的header请求为空
![image](https://user-images.githubusercontent.com/87454525/204940519-128c32e0-1172-4dd2-8df2-33a526ef78ca.png)

**Comment by jdAction** [comment]
标红的部分能否直接是传文件名称,不确定有没有文件后缀,Fileutil.file就可以直接使用名称创建,看看能否新增工具类
![image](https://user-images.githubusercontent.com/87454525/204942823-bec33c9a-f919-4bc0-b768-2f94bc259e7a.png)

**Comment by jdAction** [comment]
> 你可以看下自己的报文，请求到服务端应该是个JSON，而非multipart/form-data，此时你要使用body方法。

是在修复吗?还是没看到这个问题

**Comment by looly** [comment]
@jdAction 奇怪了，UA为何会影响你的提交，那只能一种情况：hutool的UA被服务端封掉了。

Hutool默认的UA见：GlobalHeaders

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 Hutool`

**Comment by looly** [comment]
关于第二个临时文件创建的问题，使用这个方法：

![image](https://user-images.githubusercontent.com/1432613/205680500-a74b7874-8478-4674-b831-6439edbc16a8.png)

**Comment by jdAction** [comment]
> 

有问题可以自己验证下，我再自己的虚拟机验证的出现这个问题，希望能先验证再做判断。

**Comment by jdAction** [comment]
> 关于第二个临时文件创建的问题，使用这个方法：
> 
> ![image](https://user-images.githubusercontent.com/1432613/205680500-a74b7874-8478-4674-b831-6439edbc16a8.png)

我知道这个，这是后缀自己指定，前面的文件名称还是hutool，我想创建和传入文件名称一样的临时文件，这个目前是没有的，希望加一下。

**Comment by looly** [comment]
> > 
> 
> 有问题可以自己验证下，我再自己的虚拟机验证的出现这个问题，希望能先验证再做判断。

这个没看懂，如何验证呢？

**Comment by looly** [comment]
> > 关于第二个临时文件创建的问题，使用这个方法：
> > ![image](https://user-images.githubusercontent.com/1432613/205680500-a74b7874-8478-4674-b831-6439edbc16a8.png)
> 
> 我知道这个，这是后缀自己指定，前面的文件名称还是hutool，我想创建和传入文件名称一样的临时文件，这个目前是没有的，希望加一下。

事实上这个方法是`File.createTempFile`这方法的包装，只能指定前后缀，没法指定完整的文件名称。

**Comment by jdAction** [comment]
> version: '3.4' services: ipfs0: container_name: ipfs0 image: ipfs/go-ipfs:latest ports: - "4001:4001" - "5001:5001" - "8080:8080" volumes: - ./compose/ipfs0:/data/ipfs
> 
> cluster0: container_name: cluster0 image: ipfs/ipfs-cluster:latest depends_on: - ipfs0 environment: CLUSTER_PEERNAME: cluster0 CLUSTER_SECRET: k51qzi5uqu5djre5th2oarigenrhshkrwfx3o6ph16sdmkszd6npgaisq32rem CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001 CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery ports: - "9094:9094" - "9095:9095" # Cluster IPFS Proxy endpoint - "9096:9096" # Cluster swarm endpoint volumes: - ./compose/cluster0:/data/ipfs-cluster
> 
> 上面的这个是我启动的测试环境,可以直接使用docker-compose 启动 然后直接使用postman请求

version: '3.4'
services:
ipfs0:
container_name: ipfs0
image: ipfs/go-ipfs:latest
ports:
- "4001:4001"
- "5001:5001"
- "8080:8080"
volumes:
- ./compose/ipfs0:/data/ipfs

cluster0:
container_name: cluster0
image: ipfs/ipfs-cluster:latest
depends_on:
- ipfs0
environment:
CLUSTER_PEERNAME: cluster0
CLUSTER_SECRET: k51qzi5uqu5djre5th2oarigenrhshkrwfx3o6ph16sdmkszd6npgaisq32rem
CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
ports:
- "9094:9094"
- "9095:9095" # Cluster IPFS Proxy endpoint
- "9096:9096" # Cluster swarm endpoint
volumes:
- ./compose/cluster0:/data/ipfs-cluster

上面的这个是我启动的测试环境,可以直接使用docker-compose 启动 然后直接使用postman请求
