### ISSUE TITLE
未知原因导致StringConverter出现ClassNotFoundException异常

### ISSUE THREAD

**Issue by Qiaofanxing** [looly/hutool#2787]
### 版本情况

JDK版本：    openjdk_19_01
JavaFx版本：19
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

在Junit中测试时一切正常，直到结合JavaFX使用时，ConverterRegistry类中的defaultConverter方法中有一行
```java
defaultConverterMap.put(CharSequence.class, new StringConverter());
```
中的new StringConverter()出现异常。

![Snipaste_2022-12-08_16-28-45](https://user-images.githubusercontent.com/41269801/206397352-8cf3bd3e-ed22-4100-8444-167a30fa977f.png)

我最初在Excel07SaxReader的read方法中传入了字符串参数作为路径，由于方法自动调用Converter导致程序异常。我将传入参数改为 File 而非 String 以用来跳过Converter()，程序运行正常。我直接在方法中试图调用 new StringConverter() ，抛出同样异常，证实问题出现在StringConverter()。

由于Junit单元测试中没有出现问题，所以推测问题出现在与JavaFX结合使用。

1. 复现代码

```java
new StringConverter();
```

2. 堆栈信息

```
Caused by: java.lang.NoClassDefFoundError: java/sql/SQLException
	at hutool.all@5.8.10/cn.hutool.core.convert.ConverterRegistry.defaultConverter(ConverterRegistry.java:416)
	at hutool.all@5.8.10/cn.hutool.core.convert.ConverterRegistry.<init>(ConverterRegistry.java:133)
	at hutool.all@5.8.10/cn.hutool.core.convert.ConverterRegistry$SingletonHolder.<clinit>(ConverterRegistry.java:117)
	at hutool.all@5.8.10/cn.hutool.core.convert.ConverterRegistry.getInstance(ConverterRegistry.java:126)
	at hutool.all@5.8.10/cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:763)
	at hutool.all@5.8.10/cn.hutool.core.convert.Convert.convertQuietly(Convert.java:747)
	at hutool.all@5.8.10/cn.hutool.core.convert.Convert.toStr(Convert.java:49)
	at hutool.all@5.8.10/cn.hutool.core.convert.Convert.toStr(Convert.java:61)
	at hutool.all@5.8.10/cn.hutool.core.util.ObjectUtil.toString(ObjectUtil.java:698)
	at hutool.all@5.8.10/cn.hutool.core.text.StrJoiner.append(StrJoiner.java:215)
	at hutool.all@5.8.10/cn.hutool.core.text.StrJoiner.append(StrJoiner.java:244)
	at hutool.all@5.8.10/cn.hutool.core.collection.IterUtil.join(IterUtil.java:245)
	at hutool.all@5.8.10/cn.hutool.core.collection.CollUtil.join(CollUtil.java:569)
	at hutool.all@5.8.10/cn.hutool.core.io.FileUtil.normalize(FileUtil.java:1682)
	at hutool.all@5.8.10/cn.hutool.core.io.FileUtil.getAbsolutePath(FileUtil.java:1249)
	at hutool.all@5.8.10/cn.hutool.core.io.FileUtil.getAbsolutePath(FileUtil.java:1284)
	at hutool.all@5.8.10/cn.hutool.core.io.FileUtil.file(FileUtil.java:324)
	at hutool.all@5.8.10/cn.hutool.poi.excel.sax.ExcelSaxReader.read(ExcelSaxReader.java:51)
	at com.example.democl/com.example.democl.excel.ExcelService.excelIn(ExcelService.java:57)
	at com.example.democl/com.example.democl.UIController.OnCreateFilesAct(UIController.java:117)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 57 more
Caused by: java.lang.ClassNotFoundException: java.sql.SQLException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 78 more
与目标 VM 断开连接, 地址为: ''127.0.0.1:54583'，传输: '套接字''

进程已结束,退出代码130

```

3. 测试涉及到的文件（注意脱密）
如果需要，我可以提供更多信息。

**Comment by looly** [comment]
检查包冲突吧。
