### ISSUE TITLE
使用JSONUtil.toList方法出现大量线程阻塞

### ISSUE THREAD

**Issue by xuchengsheng** [looly/hutool#2812]
### 版本情况

JDK版本： openjdk11

hutool版本： 5.8.8

springboot版本：2.3.5.Release

### 问题描述（包括截图）

1、在springboot内嵌tomcat环境下，使用JSONUtil.toList方法出现大量线程阻塞
![image-20221217141428097](https://user-images.githubusercontent.com/30015049/208228590-29c20df9-03e0-4407-b639-cfa31452eef7.png)

2、经过排查发现在cn.hutool.core.convert.ConverterRegistry#convert方法中动态加载cn.hutool.json.BeanConverterForJSON类
![image-20221217141646327](https://user-images.githubusercontent.com/30015049/208228593-9da6bca4-ae6c-4592-a3af-0045c4ae0adf.png)

3、但是此类并不存在，发现在一个fix code过程中删除了BeanConverterForJSON类
![image-20221217141551247](https://user-images.githubusercontent.com/30015049/208228591-5c8e0097-56ea-4aa6-acdb-a63aca7caa60.png)

4、由于每次使用JSONUtil.toList方法都会加载BeanConverterForJSON类最终会被TomcatEmbeddedWebappClassLoader类加载器，此类加载器在加载类的过程中会对类进行上锁操作，导致线程阻塞
![微信截图_20221217142820](https://user-images.githubusercontent.com/30015049/208228790-1659c8d8-60c2-45b1-a85b-c4fc5e41385b.png)

堆栈信息
"http-nio-80-exec-33" Id=34550 cpuUsage=6.62% deltaTime=13ms time=11041ms BLOCKED on java.lang.Object@2b31178e owned by "http-nio-80-exec-48" Id=34624
    at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:68)
    -  blocked on java.lang.Object@2b31178e
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
    at java.base@11.0.5/java.lang.Class.forName0(Native Method)
    at java.base@11.0.5/java.lang.Class.forName(Class.java:398)
    at cn.hutool.core.util.ClassLoaderUtil.tryLoadInnerClass(ClassLoaderUtil.java:341)
    at cn.hutool.core.util.ClassLoaderUtil.doLoadClass(ClassLoaderUtil.java:317)
    at cn.hutool.core.util.ClassLoaderUtil.lambda$loadClass$1(ClassLoaderUtil.java:202)
    at cn.hutool.core.util.ClassLoaderUtil$$Lambda$1896/0x0000000101588c40.apply(Unknown Source)
    at cn.hutool.core.map.ReferenceConcurrentMap.lambda$computeIfAbsent$1(ReferenceConcurrentMap.java:137)
    at cn.hutool.core.map.ReferenceConcurrentMap$$Lambda$1777/0x00000001012dcc40.apply(Unknown Source)
    at cn.hutool.core.map.MapUtil.computeIfAbsent(MapUtil.java:1483)
    at cn.hutool.core.map.SafeConcurrentHashMap.computeIfAbsent(SafeConcurrentHashMap.java:72)
    at cn.hutool.core.map.ReferenceConcurrentMap.computeIfAbsent(ReferenceConcurrentMap.java:137)
    at cn.hutool.core.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:202)
    at cn.hutool.core.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:167)
    at cn.hutool.core.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:148)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:285)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:308)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:321)
    at cn.hutool.core.collection.CollUtil.addAll(CollUtil.java:2170)
    at cn.hutool.core.convert.impl.CollectionConverter.convertInternal(CollectionConverter.java:76)
    at cn.hutool.core.convert.impl.CollectionConverter.convert(CollectionConverter.java:64)
    at cn.hutool.core.convert.ConverterRegistry.convertSpecial(ConverterRegistry.java:352)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:276)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:308)
    at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:765)
    at cn.hutool.json.JSONConverter.jsonToBean(JSONConverter.java:133)
    at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:95)
    at cn.hutool.json.JSON.toBean(JSON.java:193)
    at cn.hutool.json.JSON.toBean(JSON.java:180)
    at java.base@11.0.5/java.lang.invoke.LambdaForm$DMH/0x000000010157f440.invokeSpecialIFC(LambdaForm$DMH)
    at java.base@11.0.5/java.lang.invoke.LambdaForm$MH/0x0000000101588840.invoke(LambdaForm$MH)
    at java.base@11.0.5/java.lang.invoke.LambdaForm$MH/0x0000000101588440.invoke(LambdaForm$MH)
    at java.base@11.0.5/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
    at java.base@11.0.5/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
    at cn.hutool.core.lang.reflect.MethodHandleUtil.invoke(MethodHandleUtil.java:222)
    at cn.hutool.core.lang.reflect.MethodHandleUtil.invokeSpecial(MethodHandleUtil.java:185)
    at cn.hutool.core.util.ReflectUtil.invokeRaw(ReflectUtil.java:1072)
    at cn.hutool.core.util.ReflectUtil.invoke(ReflectUtil.java:1008)
    at cn.hutool.core.util.ReflectUtil.invoke(ReflectUtil.java:1099)
    at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:83)
    at cn.hutool.core.bean.copier.CopyOptions$$Lambda$1769/0x00000001012dec40.convert(Unknown Source)
    at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:342)
    at cn.hutool.core.bean.copier.MapToBeanCopier.lambda$copy$0(MapToBeanCopier.java:86)
    at cn.hutool.core.bean.copier.MapToBeanCopier$$Lambda$1784/0x00000001012da840.accept(Unknown Source)
    at java.base@11.0.5/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
    at cn.hutool.core.map.MapWrapper.forEach(MapWrapper.java:160)
    at cn.hutool.core.bean.copier.MapToBeanCopier.copy(MapToBeanCopier.java:60)
    at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
    at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:78)
    at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:289)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:308)
    at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:321)
    at cn.hutool.core.collection.CollUtil.addAll(CollUtil.java:2170)
    at cn.hutool.core.convert.impl.CollectionConverter.convertInternal(CollectionConverter.java:76)
    at cn.hutool.core.convert.impl.CollectionConverter.convert(CollectionConverter.java:64)
    at cn.hutool.core.convert.Convert.toCollection(Convert.java:560)
    at cn.hutool.core.convert.Convert.toList(Convert.java:585)
    at cn.hutool.json.JSONConverter.toList(JSONConverter.java:57)
    at cn.hutool.json.JSONArray.toList(JSONArray.java:512)
    at cn.hutool.json.JSONUtil.toList(JSONUtil.java:532)
    at cn.hutool.json.JSONUtil.toList(JSONUtil.java:519)

**Comment by looly** [comment]
这里确实是遗留问题。

5.8.11去除这个问题。
