### ISSUE TITLE
Field [modifiers] is not exist in [java.lang.reflect.Field]

### ISSUE THREAD

**Issue by kings1990** [looly/hutool#2832]
### 版本情况

JDK版本：    jdk17
hutool版本： 5.8.5

### 问题描述（包括截图）
HttpRequest 使用Patch报错

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/8969637/210026575-660605b8-3040-4471-bb28-ae684d5a23f5.png">

1. 复现代码

```java

import cn.hutool.http.HttpRequest;
import cn.hutool.http.HttpUtil;
import cn.hutool.http.Method;

public class A {
    public static void main(String[] args) {
        HttpRequest request = HttpUtil.createRequest(Method.PATCH,"http://localhost:8081/test/patch");
        request.execute();
        System.out.println(1);
    }
}

```

2. 堆栈信息
```
java.lang.IllegalArgumentException: Field [modifiers] is not exist in [java.lang.reflect.Field]
 at cn.hutool.core.lang.Assert.lambda$notNull$3(Assert.java:217)
 at cn.hutool.core.lang.Assert.notNull(Assert.java:197)
 at cn.hutool.core.lang.Assert.notNull(Assert.java:217)
 at cn.hutool.core.util.ReflectUtil.setFieldValue(ReflectUtil.java:315)
 at cn.hutool.http.HttpGlobalConfig.allowPatch(HttpGlobalConfig.java:201)
 at cn.hutool.http.HttpConnection.setMethod(HttpConnection.java:123)
 at cn.hutool.http.HttpRequest.initConnection(HttpRequest.java:1172)
 at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1135)
 at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1013)
 at cn.hutool.http.HttpRequest.execute(HttpRequest.java:989)
```

**Comment by ZZemptypoint** [comment]
你的jdk版本太高了

**Comment by kings1990** [comment]
现在idea内置jdk版本17

**Comment by CherryRum** [comment]
需添加 open 模块，idea对于你的jdk不是内置的，他自己是使用jdk17了，您的亚马逊openjdk 应该是在idea中自己下载的

**Comment by kings1990** [comment]
这边截图只是一个demo，实际使用的是idea内置的jdk。现在2022默认使用了jdk17

**Comment by looly** [comment]
这个是Hutool对高版本JDK的兼容问题，此处应该忽略注入失败。

稍后处理。

**Comment by looly** [comment]
5.8.12做简单处理，调用失败忽略之。

**Comment by kings1990** [comment]
似乎jar包还没发布吧

**Comment by looly** [comment]
@kings1990 还没有，估计年前发布
