### ISSUE TITLE
FileUtil.move报错

### ISSUE THREAD

**Issue by kings1990** [looly/hutool#2893]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12

### 问题描述（包括截图）

1. 复现代码

```java
cn.hutool.core.io.FileUtil 方法void move(File src, File target, boolean isOverride)
如果target文件不存在报NoSuchFileException，5.8.5版本还是正常的
```

2. 堆栈信息
```
at cn.hutool.core.io.file.PathUtil.equals(PathUtil.java:557)
at cn.hutool.core.io.file.PathUtil.move(PathUtil.java:491)
at cn.hutool.core.io.FileUtil.move(FileUtil.java:1148)
```

**Comment by winlans** [comment]
@looly 由于判断是否同一文件导致的bug，我已修复，pr#2894

**Comment by kings1990** [comment]
hutool 的项目和人啥都快 😄

**Comment by looly** [comment]
ok，还有个类似问题，我一起看。


https://gitee.com/dromara/hutool/issues/I6ENDL

**Comment by looly** [comment]
关联：https://github.com/dromara/hutool/pull/2894
