### ISSUE TITLE
 zip END header not found

### ISSUE THREAD

**Issue by huliqin900** [looly/hutool#2939]
### 版本情况

JDK版本：    1.8
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

File unzip = ZipUtil.unzip("E:\\test\\附件管理0221.zip", "e:\\test", CharsetUtil.CHARSET_GBK);

2. 堆栈信息
Exception in thread "main" cn.hutool.core.io.IORuntimeException: ZipException: zip END header not found
	at cn.hutool.core.util.ZipUtil.toZipFile(ZipUtil.java:68)
	at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:542)
	at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:517)
	at zip.ZipTest.main(ZipTest.java:16)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1608)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1460)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1281)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1243)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:707)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:241)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:294)
	at cn.hutool.core.util.ZipUtil.toZipFile(ZipUtil.java:66)
	... 3 more

**Comment by looly** [comment]
检查下：

1. 你的Zip包是否被破坏了？
2. 编码设置是否正确。

如果确认都没问题，麻烦上传一下测试zip我这边测试。
