### ISSUE TITLE
导入 `hutool-crypto:5.8.15` 使用 AOT 编译成可执行程序运行报错

### ISSUE THREAD

**Issue by Deycoesr** [looly/hutool#2966]
### 版本情况

JDK版本：    openjdk-17.0.2
hutool版本： 5.8.15（最新版）

### 问题描述（包括截图）

打成可执行文件之后运行报错
```log
2023-03-09T18:40:31.587+08:00 ERROR * --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'accessCertAuthConfiguration': Unsatisfied dependency expressed through constructor parameter 2: Error creating bean with name 'aesSymmetricCrypto': Instantiation of supplied bean failed
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:351) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:271) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:206) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[*:6.0.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[*:6.0.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[*:6.0.6]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[*:6.0.6]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[*:6.0.6]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[*:3.0.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[*:3.0.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[*:3.0.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[*:3.0.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[*:3.0.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[*:3.0.4]
        at com.*.*.*.*Application.main(*Application.java:10) ~[*:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aesSymmetricCrypto': Instantiation of supplied bean failed
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1236) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[*:6.0.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[*:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[*:6.0.6]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[*:6.0.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405) ~[*:6.0.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[*:6.0.6]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:334) ~[na:na]
        ... 21 common frames omitted
Caused by: java.lang.NoSuchMethodError: cn.hutool.crypto.ProviderFactory.createBouncyCastleProvider()
        at cn.hutool.crypto.GlobalBouncyCastleProvider.<init>(GlobalBouncyCastleProvider.java:18) ~[*:na]
        at cn.hutool.crypto.GlobalBouncyCastleProvider.<clinit>(GlobalBouncyCastleProvider.java:11) ~[*:na]
        at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1028) ~[na:na]
        at cn.hutool.crypto.CipherWrapper.<init>(CipherWrapper.java:39) ~[na:na]
        at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:150) ~[*:na]
        at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:127) ~[*:na]
        at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:115) ~[*:na]
        at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:104) ~[*:na]
        at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:83) ~[*:na]
        at com.*.*.*.config.SymmetricCryptoConfiguration.aesSymmetricCrypto(SymmetricCryptoConfiguration.java:24) ~[*:na]
        at com.*.*.*.config.SymmetricCryptoConfiguration__BeanDefinitions.lambda$getAesSymmetricCryptoInstanceSupplier$1(SymmetricCryptoConfiguration__BeanDefinitions.java:38) ~[na:na]
        at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:63) ~[*:6.0.6]
        at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:51) ~[*:6.0.6]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$withGenerator$0(BeanInstanceSupplier.java:173) ~[na:na]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[*:6.0.6]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[*:6.0.6]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:208) ~[na:na]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[*:6.0.6]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[*:6.0.6]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:220) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:208) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[*:6.0.6]
        ... 33 common frames omitted
```
问题分析:
https://github.com/dromara/hutool/blob/9b81e5502daabe21ff7f71bcb420662c7d1c3b90/hutool-crypto/src/main/java/cn/hutool/crypto/ProviderFactory.java#L23-L25
由于这里没有没有依赖 `org.bouncycastle.jce.provider.BouncyCastleProvider` 这个类导致这个方法可能被处理掉了
https://github.com/dromara/hutool/blob/9b81e5502daabe21ff7f71bcb420662c7d1c3b90/hutool-crypto/src/main/java/cn/hutool/crypto/GlobalBouncyCastleProvider.java#L16-L22
然后这个抛出了 `java.lang.NoSuchMethodError` 这个异常然后这个只捕捉了 `java.lang.NoClassDefFoundError` 这个异常导致启动报错

<img width="791" alt="image" src="https://user-images.githubusercontent.com/33995808/224005793-089a3085-eace-4a69-8c98-bbeb1ba25caf.png">
我在本地改成这样就可以启动了

**Comment by looly** [comment]
5.8.16解决此问题。感谢。
