### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by actor007** [looly/hutool#2989]
### 版本情况

JDK版本：    1.8.0_341
hutool版本： 5.8.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用 HttpRequest.get 请求 https接口返回 Exception in thread "main" cn.hutool.core.io.IORuntimeException: SSLHandshakeException: The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]

1. 复现代码

```java
String url = "https://fpcy.liaoning.chinatax.gov.cn:443/NWebQuery/yzmQuery?fpdm=011001500389&fphm=72398295&r=0.47999423710325784&v=2.0.12_060&nowtime=1677749087009&area=&publickey=1677749087009&key9=430a931cdb8cabc2b03b4db6de8c208f&flwq39=KEU%2Bt7QYxBDELnJR7E%2B4UnYZ6h7m46aULD2v5dmhiVTKjudO1xeEGQ%2B1kllWdUK0CjDat4dj31v7YJMLuiXKsTZ72BJB8o9g0tbUxWjHyWKyKBWetIY9mUdnqZ%2BG3mKwE5I%2BbiYPTc6aswXEFwt5eZOuFAFIUWIWwk9%2BRkHTaS8%3D";
		HttpRequest.get(url).execute().body();
```

2. 堆栈信息
Exception in thread "main" cn.hutool.core.io.IORuntimeException: SSLHandshakeException: The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1272)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1137)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1013)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:989)
	at com.qixiangyun.keep.session.center.iproxy.IproxyJobHandler.main(IproxyJobHandler.java:897)
Caused by: javax.net.ssl.SSLHandshakeException: The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
	at sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(ServerHello.java:941)
	at sun.security.ssl.ServerHello$ServerHelloConsumer.consume(ServerHello.java:868)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:479)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:457)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:155)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1320)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1233)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:417)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:389)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:558)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:201)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:379)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1267)
	... 4 more

3. 测试涉及到的文件（注意脱密）
无
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你用浏览器访问也会报错：
![image](https://user-images.githubusercontent.com/1432613/225658316-41514d19-b74c-4d9c-8770-bcbcbeb289fc.png)

网站使用le了不受支持的SSL协议。
