### ISSUE TITLE
TextSimilarity内存空间优化

### ISSUE THREAD

**Issue by ryumiyax** [looly/hutool#3045]
TextSimilarity中使用到了dp计算公共子串，内部申请了一个dp[strA.length()][strB.length()]的矩阵

如果strA和strB均为较长字符串，例如长度为1024 * 1024的字符串(2M内存空间)
那么得到的矩阵即为2 ^ 40个int，也就是4T大小

看到知乎上面提到了[（知乎）编辑距离python实现及内存优化](https://zhuanlan.zhihu.com/p/164599274)
只申请正在使用的矩阵的2行即可将n^2的内存空间占用直接优化到2n

可以针对这个优化一下吗？

**Comment by ryumiyax** [comment]
我自己改了一版，~速度会比使用matrix慢一些，因为每次都需要重新分配int[strB.length()]的空间~直接行交换即可复用lastLine，不会读取本次循环未写入的列，第0列永远都是0
```java
    /**
     * 求公共子串，采用动态规划算法。 其不要求所求得的字符在所给的字符串中是连续的。
     * 2023-04-06 优化堆内存占用，此处不需要matrix[m][n]的完整矩阵，仅需右下角值
     *
     * @param strA 字符串1
     * @param strB 字符串2
     * @return 公共子串
     */
    public static int longestCommonSubstringLengthMod(String strA, String strB) {
        final int m = strA.length();
        final int n = strB.length();

        // 初始化矩阵数据,matrix[0][0]的值为0， 如果字符数组chars_strA和chars_strB的对应位相同，则matrix[i][j]的值为左上角的值加1，
        // 否则，matrix[i][j]的值等于左上方最近两个位置的较大值， 矩阵中其余各点的值为0.
        int[] lastLine = new int[n + 1], currLine = new int[n + 1], temp;
        for (int i = 1; i <= m; i++) {
            for (int j = 1; j <= n; j++) {
                if (strA.charAt(i - 1) == strB.charAt(j - 1)) {
                    currLine[j] = lastLine[j-1] + 1;
                } else {
                    currLine[j] = Math.max(currLine[j-1], lastLine[j]);
                }
            }
            temp = lastLine;
            lastLine = currLine;
            currLine = temp;
        }

        return lastLine[n];
    }
```

测试如下:
```java
    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        String strCommon = StringUtil.random(1024 * 32);

        String strA = StringUtil.random(1024 * 32) + strCommon;
        String strB = StringUtil.random(1024 * 32) + strCommon;

        System.out.println("textGenerated: " + (System.currentTimeMillis() - start) + "ms");
        System.out.println("textA: " + strA);
        System.out.println("textB: " + strB);

        start = System.currentTimeMillis();
        System.out.println(TextSimilarityMod.longestCommonSubstringLengthMod(strA, strB));
        System.out.println("textSimilarityMod: " + (System.currentTimeMillis() - start) + "ms");

        start = System.currentTimeMillis();
        System.out.println(TextSimilarityMod.longestCommonSubstringLength(strA, strB));
        System.out.println("textSimilarity: " + (System.currentTimeMillis() - start) + "ms");
    }
```

输出：
```java
textGenerated: 60ms
textA: k7qDqQ7QeRoXWAYNnOtRuHGsOSnhBEEDmdFHztRU9N...(后面省略，太长了)
textB: 1GZT0fqVF2fmOTcgMQVmsLFVnsRSNjseF9pFHc4Tni...(后面省略，太长了)
40110
textSimilarityMod: 17299ms
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.test.util.TextSimilarityMod.generateMatrix(TextSimilarityMod.java:134)
	at com.test.util.TextSimilarityMod.longestCommonSubstringLength(TextSimilarityMod.java:118)
	at com.test.Test.main(Test.java:41)
```

**Comment by ryumiyax** [comment]
理论上内存基本打不满了，只是会要比较久才能输出结果，但是需要大文本比对的应该也能接受吧 :P

**Comment by looly** [comment]
good job!

此优化在6.x中修改。

下次有解决办法可以直接提PR。
