### ISSUE TITLE
在android的xposed中使用

### ISSUE THREAD

**Issue by kigkrazy** [looly/hutool#307]
版本：4.3.2

错误信息：
```
I/art     (16658): Rejecting re-init on previously-failed class java.lang.Class<cn.hutool.core.convert.ConverterRegistry$SingletonHolder>
E/Xposed  (16658): java.lang.NoClassDefFoundError: cn.hutool.core.convert.ConverterRegistry$SingletonHolder
E/Xposed  (16658):      at cn.hutool.core.convert.ConverterRegistry.getInstance(ConverterRegistry.java:84)
E/Xposed  (16658):      at cn.hutool.core.convert.Convert.convert(Convert.java:610)
E/Xposed  (16658):      at cn.hutool.core.convert.Convert.convert(Convert.java:596)
E/Xposed  (16658):      at cn.hutool.core.convert.Convert.toStr(Convert.java:42)
E/Xposed  (16658):      at cn.hutool.core.getter.OptNullBasicTypeFromObjectGetter.getStr(OptNullBasicTypeFromObjectGetter.java:22)
E/Xposed  (16658):      at cn.hutool.json.JSONGetter.getStr(JSONGetter.java:26)
E/Xposed  (16658):      at cn.hutool.core.getter.OptNullBasicTypeGetter.getStr(OptNullBasicTypeGetter.java:30)
E/Xposed  (16658):      at com.xxx.xaxa.component.fake.xclazzext.ddd.xxx$1.beforeHookedMethod(xaxa.java:50)
E/Xposed  (16658):      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
E/Xposed  (16658):      at com.vvv.xxx.support.account.bean.BaseSecretRequest.toBody(<Xposed>)
E/Xposed  (16658):      at com.vvv.xxx.support.account.bean.BaseSecretRequest.onSetValue(:53)
E/Xposed  (16658):      at com.vvv.xxx.sdk.service.storekit.bean.RequestBean.genBody(:132)
E/Xposed  (16658):      at com.vvv.xxx.framework.bean.StoreRequestBean.genBody(:184)
E/Xposed  (16658):      at com.vvv.xxx.sdk.service.storekit.bean.RequestBean.genBody(:395)
E/Xposed  (16658):      at o.tt.ᐝ(:379)
E/Xposed  (16658):      at o.tt.ʽ(:194)
E/Xposed  (16658):      at o.tt.ॱˊ(:329)
E/Xposed  (16658):      at o.tt.doInBackground(:57)
E/Xposed  (16658):      at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/Xposed  (16658):      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Xposed  (16658):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Xposed  (16658):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Xposed  (16658):      at java.lang.Thread.run(Thread.java:818)
```

**Comment by looly** [comment]
安卓没有测试过，不过你要考虑是不是引入多个Hutool版本导致的冲突？

还有建议升级到4.5.2最新版。
