### ISSUE TITLE
HttpUtil.downloadBytes 链接被解码导致下载403

### ISSUE THREAD

**Issue by 15200933050** [looly/hutool#3079]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.8.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
原本文件下载没问题
```java
        String url = "http://xxxxxxx/xxx.pdf?download=xxx.pdf&Signature=CTRn%2BiwngoLsriTeEN&Expires=1682308718";
        byte[] bytes = HttpUtil.downloadBytes(url);
        FileUtil.writeBytes(bytes, new File("D:/1.pdf"));
```
后因为项目需求，同事修改了以下配置，导致Signature中的 `%2B` 被解码成 `+` ，致使文件下载403
```java
        HttpGlobalConfig.setDecodeUrl(true);
```

2. 堆栈信息

```
Exception in thread "main" cn.hutool.http.HttpException: Server response error with status code: [403]
	at cn.hutool.http.HttpDownloader.requestDownload(HttpDownloader.java:120)
	at cn.hutool.http.HttpDownloader.downloadBytes(HttpDownloader.java:40)
	at cn.hutool.http.HttpUtil.downloadBytes(HttpUtil.java:426)
	at com.example.demo.DemoApplicationTests.main(DemoApplicationTests.java:93)
```

3. 需求描述
`HttpUtil.downloadBytes` 方法是否考虑不受全局配置 `isDecodeUrl` 控制，或者提供参数选择，因为解码很容易破坏文件链接中的认证信息

**Comment by looly** [comment]
可以使用`HttpRequest.of(url, null)`，跳过。

**Comment by 15200933050** [comment]
我想使用的是 `HttpUtil.downloadBytes`， 想直接进行文件下载，我需要通过什么方法组合才能自行控制这个编码入参？ `HttpRequest.of(url, null)`

**Comment by looly** [comment]
直接封装的方法没有相关参数。
