### ISSUE TITLE
时间轮-使用SystemTimer构建时间轮，出现线程池无法关闭情况

### ISSUE THREAD

**Issue by 508284405** [looly/hutool#3090]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.15

### 问题描述（包括截图）

1. 复现代码

```java
    public static void main(String[] args) {
        SystemTimer timer = new SystemTimer();
        timer.setDelayQueueTimeout(1000);
        timer.start();
        timer.addTask(new TimerTask(() -> {
            System.out.println(1);
            System.out.println("任务已经完成");
        }, 1000));

        timer.stop();
        System.out.println("线程池已经关闭");
    }
```

2. 结果

19:35:35.528 [main] DEBUG cn.hutool.cron.timingwheel.TimingWheel - tickMs: 400 ------index: 1 ------expiration: 1683545736473
线程池已经关闭
19:35:36.409 [pool-1-thread-1] DEBUG cn.hutool.cron.timingwheel.TimingWheel - tickMs: 20 ------index: 3 ------expiration: 1683545736473
19:35:36.474 [pool-1-thread-1] DEBUG cn.hutool.cron.timingwheel.TimingWheel - tickMs: 1 ------index: 13 ------expiration: 1683545736473
1
任务已经完成

3. 堆栈信息
2023-05-08 19:36:40
Full thread dump OpenJDK 64-Bit Server VM (25.352-b08 mixed mode):

"DestroyJavaVM" #15 prio=5 os_prio=0 tid=0x0000019dace01000 nid=0x374 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-1-thread-1" #14 prio=5 os_prio=0 tid=0x0000019dccb56800 nid=0x1530 waiting on condition [0x0000005199ffe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000076d678c50> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.DelayQueue.poll(DelayQueue.java:259)
        at cn.hutool.cron.timingwheel.SystemTimer.poll(SystemTimer.java:115)
        at cn.hutool.cron.timingwheel.SystemTimer.advanceClock(SystemTimer.java:95)
        at cn.hutool.cron.timingwheel.SystemTimer.lambda$start$0(SystemTimer.java:61)
        at cn.hutool.cron.timingwheel.SystemTimer$$Lambda$2/159259014.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)

4. 描述
   程序任然处于挂起状态，线程池未关闭，初步判断是因为SystemTimer类中使用DelayQueue队列，其poll方法在拉取数据期间，若数据未到期，则会.LockSupport.parkNanos休眠，该函数在线程池调用shutdown(),即修改线程的Interrupted状态位，线程不会触发InterruptedException异常，SystemTimer的advanceClock就无法捕获该异常，也无法退出当前循环。

**Comment by looly** [comment]
5.8.19
6.0.0.M4

修复此问题。

修复方式为在`SystemTimer`中增加`isRunning`标识，用于标识运行状态。
