### ISSUE TITLE
FileUtil.getMimeType无法获取.webp格式类型

### ISSUE THREAD

**Issue by yixiaco** [looly/hutool#3092]
### 版本情况

JDK版本：    openjdk_17.0.1
hutool版本： 5.8.18（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
// 获取到为null
FileUtil.getMimeType("xxx.webp");
// 使用url会报错
FileUtil.getMimeType("https://xxx.oss-cn-hangzhou.aliyuncs.com/xxx.webp")
```

2. 堆栈信息
```java
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://ruoyi-xczl.oss-cn-hangzhou.aliyuncs.com/2023/04/26/481c54438b95456d835aac78ad7aa28c.webp
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at cn.hutool.core.io.FileUtil.getMimeType(FileUtil.java:3504)
	at org.dromara.system.service.impl.SysOssRuleServiceImpl.main(SysOssRuleServiceImpl.java:299)
```

**Comment by looly** [comment]
事实上JDK17（Oracle JDK17）是支持的。

5.8.19增加吧，兼容下低版本。
