### ISSUE TITLE
Android 荣耀平板6.0.6 Caused by: java.lang.NoClassDefFoundError: cn.hutool.core.lang.Assert$$ExternalSyntheticLambda12

### ISSUE THREAD

**Issue by zjianflys** [looly/hutool#3104]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.18.（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Caused by: java.lang.NoClassDefFoundError: cn.hutool.core.lang.Assert$$ExternalSyntheticLambda12
com.jszy.vi                          W  	at cn.hutool.core.lang.Assert.notNull(Assert.java:217)
com.jszy.vi                          W  	at cn.hutool.crypto.asymmetric.SM2.getCipherParameters(SM2.java:570)
com.jszy.vi                          W  	at cn.hutool.crypto.asymmetric.SM2.encrypt(SM2.java:224)
com.jszy.vi                          W  	at cn.hutool.crypto.asymmetric.AsymmetricEncryptor$-CC.$default$encrypt(AsymmetricEncryptor.java:92)
com.jszy.vi                          W  	at cn.hutool.crypto.asymmetric.AbstractAsymmetricCrypto.encrypt(AbstractAsymmetricCrypto.java)
com.jszy.vi                          W  	at cn.hutool.crypto.asymmetric.AsymmetricEncryptor$-CC.$default$encryptHex(AsymmetricEncryptor.java:104)
com.jszy.vi                          W  	at cn.hutool.crypto.asymmetric.AbstractAsymmetricCrypto.encryptHex(AbstractAsymmetricCrypto.java)
com.jszy.vi                          W  	at com.jszy.sm.Sm2Utils.encrypt(Sm2Utils.java:79)
com.jszy.vi                          W  	at com.jszy.sm.Sm2Utils.encrypt(Sm2Utils.java:54)
com.jszy.vi                          W  	at com.jszy.sm.Sm2Utils.encryptSM2Java(Sm2Utils.java:255)
com.jszy.vi                          W  	at com.xz.comm.utils.RSAUtil.encryptSM2Java(RSAUtil.java:445)
com.jszy.vi                          W  	at com.x.vi.net.StringBodyHelper.getInstance(StringBodyHelper.java:77)
com.jszy.vi                          W  	at com.x.vi.ui.login.LoginViewModel.lambda$getVerifycode$0(LoginViewModel.java:104)
com.jszy.vi                          W  	at com.x.vi.ui.login.LoginViewModel$$ExternalSyntheticLambda1.subscribe(D8$$SyntheticClass)
com.jszy.vi                          W  	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:41)
com.jszy.vi                          W  	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13176)
com.jszy.vi                          W  	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
com.jszy.vi                          W  	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
com.jszy.vi                          W  	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
com.jszy.vi                          W  	... 7 more
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

报找不到这个类？？？？

**Comment by zjianflys** [comment]
Android 系统 6.0.1

**Comment by looly** [comment]
安卓这个版本是不是不支持java8语法？

**Comment by Khaos116** [comment]
@looly 对，应该是不支持java8语法导致的，我在安卓6.0也出现了，
所以为了兼容安卓6.0，我把版本切换到了"cn.hutool:hutool-crypto:5.4.4"，从5.4.5版本开始，在安卓6.0就会闪退了

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcn/hutool/core/lang/Assert$$ExternalSyntheticLambda10;
       at cn.hutool.core.lang.Assert.notBlank(Assert.java:340)
       at cn.hutool.crypto.KeyUtil.generateKey(KeyUtil.java:161)
       at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:104)
       at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:45)
       at cn.hutool.crypto.SmUtil.sm4(SmUtil.java:205)
       at com.cv.impl.utils.SMUtils.deCodeSM4(SMUtils.kt:46)
