### ISSUE TITLE
XmlUtil.xmlToBean转换失败

### ISSUE THREAD

**Issue by Rain-Chen** [looly/hutool#3136]
在
https://github.com/dromara/hutool/issues/1663
该issues基础上进行测试
对BUG进行修改，修改两个模型为以下模型：
```
@Data
class SmsRes {
    /**
     * 状态码.
     */
    private String code;

    /**
    * 消息.
    */
    private Message message;
}

@Data
class Message {
    
    /**
     * 消息项.
     */
	private List<MessageItem> item = new ArrayList<>();
}

@Data
class MessageItem {

    /**
     * 手机号.
     */
    private String desmobile;
    /**
     * 消息id.
     */
    private String msgid;
}
```
使用相同测试用例
1、```String xmlStr = "<?xml version=\"1.0\" encoding=\"gbk\" ?><response><code>02</code></response>";``` 测试通过
2、```String xmlStr = "<?xml version=\"1.0\" encoding=\"gbk\" ?><response><code>02</code><message></message></response>"; ```异常
异常栈：
```
Exception in thread "main" cn.hutool.core.convert.ConvertException: Unsupported source type: class java.lang.String
	at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:84)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:228)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:247)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:753)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:92)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:349)
	at cn.hutool.core.bean.copier.MapToBeanCopier.lambda$copy$0(MapToBeanCopier.java:91)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at cn.hutool.core.bean.copier.MapToBeanCopier.copy(MapToBeanCopier.java:60)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
	at cn.hutool.core.bean.BeanUtil.copyProperties(BeanUtil.java:771)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:567)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:549)
	at cn.hutool.core.bean.BeanUtil.toBean(BeanUtil.java:505)
	at cn.hutool.core.util.XmlUtil.xmlToBean(XmlUtil.java:991)
```
使用5.8.19版本

_Originally posted by @Rain-Chen in https://github.com/dromara/hutool/issues/1663#issuecomment-1581862410_

**Comment by looly** [comment]
XmlUtil无法支持多层级转换，考虑使用JSON

**Comment by Rain-Chen** [comment]
个人感觉不支持多级转换可以接受，但是这个问题好像不是多级转换的问题，而是类型转换的问题
例如：
```
{
  "code": "02",
  "message": ""
}
```
```
@Data
class SmsRes {
    /**
     * 状态码.
     */
    private String code;

    /**
    * 消息列表.
    */
    private Message message;
}
```
即便是相同的JSON格式的数据转换也会是相同的报错，code的"02"转换到字符串型的值，message的字符串""值转换为Message类型这里正常的行为是否应该是当为Empty或Blank时映射为null，而不是将字符串直接通过类型转换器转换为我的自定义对象。是否应该考虑下空对象情况

**Comment by looly** [comment]
@Rain-Chen 这里就涉及到语义理解问题了。

我的理解是 当 message = null时可以，表示空对象，但是当message=""，表示有确切值，如果此处直接丢弃返回null，是否有问题呢？

**Comment by Rain-Chen** [comment]
我个人觉得这个语义没有问题，因为null表示空对象这个没有任何问题，但在处理xml或者json时（比如前端传递字段若无字段一定为空，若传递了字段但是内容为Empty也可以表示为空对象）。我觉得可以在处理自定义类型时做下兼容处理用来表示null对象（这里应该不会存在问题，因为empty不太可能转换为自定义对象其实完全同义为null），或者给个配置也可以。我暂时的做法是xml、json转换为map或JSON对象，然后判断value，最后BeanUtil转这样就规避了报错问题

**Comment by looly** [comment]
@Rain-Chen 我再仔细看下测试用例。看是否需要增加一个参数。issue暂时保留。

**Comment by looly** [comment]
@Rain-Chen 你说的非常有道理，XML中空节点读出来是""，此时理应理解为空节点。

5.8.20修复此问题！

**Comment by looly** [comment]
5.8.30此处变更规则：

Message为""时，转换为Bean为Message空对象，而非null。
