### ISSUE TITLE
使用ZipUtil解压4G左右文件失败

### ISSUE THREAD

**Issue by MouseSun846** [looly/hutool#3142]
### 版本情况

JDK版本：    openjdk:8-jdk-alpine
hutool版本： 5.8.19（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

解压zip文件大约4G，报错。但是linux执行unzip命令正常解压
```java
 public static List<File> unzipFile(String path) {
        log.info("path={}", path);
        List<File> list = null;
        if(ObjectUtils.isEmpty(path)) {
            log.error("path is empty.");
            return list;
        }
        // 获取解压目录
        File file = cn.hutool.core.io.FileUtil.file(path);
        String outPath = cn.hutool.core.io.FileUtil.file(file.getParentFile(), cn.hutool.core.io.FileUtil.mainName(file)).getAbsolutePath();
        outPath += ConstantEnum.SEPARATOR_LINE.getMessage();
        outPath += System.currentTimeMillis();
        ZipUtil.unzip(path, outPath);
        list = cn.hutool.core.io.FileUtil.loopFiles(outPath, filePath -> {
            return cn.hutool.core.io.FileUtil.isFile(filePath) && cn.hutool.core.io.FileUtil.getSuffix(filePath).toLowerCase().equals(ConstantEnum.TAR_SUFFIX.getMessage());
        });
        log.info("Upgrade file list = {}", list);
        return list;
    } public static List<File> unzipFile(String path) {
        log.info("path={}", path);
        List<File> list = null;
        if(ObjectUtils.isEmpty(path)) {
            log.error("path is empty.");
            return list;
        }
        // 获取解压目录
        File file = cn.hutool.core.io.FileUtil.file(path);
        String outPath = cn.hutool.core.io.FileUtil.file(file.getParentFile(), cn.hutool.core.io.FileUtil.mainName(file)).getAbsolutePath();
        outPath += ConstantEnum.SEPARATOR_LINE.getMessage();
        outPath += System.currentTimeMillis();
        ZipUtil.unzip(path, outPath);
        list = cn.hutool.core.io.FileUtil.loopFiles(outPath, filePath -> {
            return cn.hutool.core.io.FileUtil.isFile(filePath) && cn.hutool.core.io.FileUtil.getSuffix(filePath).toLowerCase().equals(ConstantEnum.TAR_SUFFIX.getMessage());
        });
        log.info("Upgrade file list = {}", list);
        return list;
    }

```

2. 堆栈信息
```
2023-06-11 21:12:54.699 [http-nio-9088-exec-2] ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] - log:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is cn.hutool.core.io.IORuntimeException: ZipException: invalid CEN header (bad signature)] with root cause
java.util.zip.ZipException: invalid CEN header (bad signature)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:279)
        at cn.hutool.core.util.ZipUtil.toZipFile(ZipUtil.java:66)
        at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:542)
        at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:517)
        at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:504)
```
3. 测试涉及到的文件（注意脱密）
![image](https://github.com/dromara/hutool/assets/46400044/80c402c0-7e03-409e-a086-70f1eb90fdc5)

比如报错的Excel文件，有问题的图片等

**Comment by looly** [comment]
目测`java.util.zip`不支持`Zip64`格式导致的。

尝试使用`Zip4j`或者CompressUtil试下。

**Comment by MouseSun846** [comment]
感谢回复，我取试试这两个库。
