### ISSUE TITLE
上传文件咨询

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#3179]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20

### 问题描述（包括截图）

1. 复现代码

```java
        List<File> downloadFileList = FileUtil.loopFiles(path);
        for (File file : downloadFileList) {
            logger.info("上传文件：{}", file.getPath());

            Map<String, Object> param = new LinkedHashMap<>();
            param.put("file", file);

            String returnData = HttpUtil.post(uploadIp, param);

            logger.info("上传文件返回：{}，{}", file.getPath(), returnData);
        }
```

用这个代码上传文件的时候，会报NoSuchFileException，好奇怪

cn.hutool.core.io.IORuntimeException: NoSuchFileException: xxx.jpg
	at cn.hutool.core.io.file.PathUtil.getMimeType(PathUtil.java:613)
	at cn.hutool.core.io.FileUtil.getMimeType(FileUtil.java:3313)
	at cn.hutool.http.HttpUtil.getMimeType(HttpUtil.java:802)
	at cn.hutool.http.HttpUtil.getMimeType(HttpUtil.java:791)
	at cn.hutool.http.body.MultipartBody.appendPart(MultipartBody.java:124)
	at cn.hutool.http.body.MultipartBody.writeForm(MultipartBody.java:94)
	at cn.hutool.http.body.MultipartBody.write(MultipartBody.java:80)
	at cn.hutool.http.HttpRequest.sendMultipart(HttpRequest.java:1211)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1155)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:957)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:928)
	at cn.hutool.http.HttpUtil.post(HttpUtil.java:192)
	at cn.hutool.http.HttpUtil.post(HttpUtil.java:179)

![image](https://github.com/dromara/hutool/assets/14087655/3bf691a8-f218-4ab4-8d14-76094f6d296d)
这里的fileName只有文件名而已，没有路径，这样不会读取不到文件吗？

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/00062ee7-0181-46e6-b39a-35aee60ec619)

很奇怪的问题，按理说文件不存在获取mime也是没有问题的。

猜测可能和OpenJDK的实现有关。这块我做下处理。

5.8.21 60.0-M5修复此问题。
