### ISSUE TITLE
java.net.SocketException: 打开的文件过多

### ISSUE THREAD

**Issue by Archer1003** [looly/hutool#3196]
### 版本情况

JDK版本：    jdk1.8.0_321
hutool版本： 5.8.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

定时任务，每分钟执行1次，3天左右出现。必现问题

1. 复现代码

String respJson = HttpRequest.post(systemConfig.getGraphqlUrl())

2. 堆栈信息
Caused by: java.net.SocketException: 打开的文件过多
	at java.net.Socket.createImpl(Socket.java:477)
	at java.net.Socket.connect(Socket.java:604)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:298)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:292)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1354)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1329)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:449)
	at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1281)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1250)
	... 10 more

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
1.确保及时关闭已打开的文件和网络连接：在您的代码中，确保在使用完文件和网络资源后，及时关闭相关的流、连接和套接字。使用`try-with-resources`或`finally`块来确保资源的正确关闭。
2.尝试以下修改系统限制
临时修改
```shell
ulimit -n 10240
ulimit -Hn 10240
```

**Comment by Archer1003** [comment]
调用这个吗？ 
 HttpRequest.closeCookie();

**Comment by CherryRum** [comment]
我的意思先看下你的链接为啥没关闭 
` HttpRequest.post`应该是执行了就关了，异步时候可能不会

第二个是系统改下打开文件限制

**Comment by looly** [comment]
@Archer1003 看样子是请求没有及时关闭。

考虑设置超时时长，这样就算遇到超长的连接，也会超时断开。

**Comment by Archer1003** [comment]
HttpResponse response = null;
        try {
            Map<String, String> query = new HashMap<>();
            query.put("query", queryStr);
            ObjectMapper mapper = new ObjectMapper();
            String strjson = mapper.writeValueAsString(query);
            log.info("graphapi strjson is:{}", strjson);
            response = HttpRequest.post(systemConfig.getGraphqlUrl())
                    .header("Content-type", "application/json;charset=UTF-8")
                    .header("Authorization", token)
                    .body(strjson).timeout(60000)
                    .execute();
            String respJson = response.body();
            if (respJson != null) {
                if (respJson.contains("errors")) {
                    log.info("graphapi respJson error is:{}", respJson);
                    return null;
                }
                return respJson;
            }
        } catch (Exception e) {
            log.error("GraphqlApi post fail:{}", e.getMessage(), e);
        } finally {
            if (response != null) {
                response.close();
            }
        }

**Comment by Archer1003** [comment]
问题已解决，不是hutool的问题，若有人遇到，可检查系统句柄数占用情况。逐步排查代码。
当句柄数占满时，请求无法建立连接，导致报错出现在http请求这里

**Comment by looly** [comment]
@Archer1003 感谢反馈的问题解决答案！
