### ISSUE TITLE
罕见的日期格式，转换时出现异常，无法直接使用字符串格式的dateFormat作为入参

### ISSUE THREAD

**Issue by weimo123** [looly/hutool#3213]
### 版本情况

JDK版本：    azul-1.8.0_332
hutool版本： 5.8.20

### 问题描述（包括截图）

1. 复现代码

```java
String dateString = "2020-08-02T16:32:47.046289Z";
String dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'";  // 输入日期的格式

// 原生正常
LocalDateTime dateTime = LocalDateTime.parse(dateString, DateTimeFormatter.ofPattern(dateFormat));
System.out.println("原生："+dateTime);
// 正常
DateTime parse1 = DateUtil.parse(dateString, DateTimeFormatter.ofPattern(dateFormat));
System.out.println("hutool01："+parse1);
// 异常
DateTime parse2 = DateUtil.parse(dateString, dateFormat);
System.out.println("hutool02："+parse2);
```

2. 堆栈信息
原生：2020-08-02T16:32:47.046289
hutool01：2020-08-02 16:32:47
Exception in thread "main" cn.hutool.core.date.DateException: Parse [2020-08-02T16:32:47.046289Z] with format [yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'] error!
	at cn.hutool.core.date.DateTime.parse(DateTime.java:1096)
	at cn.hutool.core.date.DateTime.<init>(DateTime.java:281)
	at cn.hutool.core.date.DateUtil.parse(DateUtil.java:731)
	at cc.weimo.mall.modules.tool.a.manageone.sc.service.MoScClientService.main(xxx.java:1172)
Caused by: java.text.ParseException: Unparseable date: "2020-08-02T16:32:47.046289Z"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at cn.hutool.core.date.DateTime.parse(DateTime.java:1088)
	... 3 more

3. 测试涉及到的文件（注意脱密）
<img width="1420" alt="image" src="https://github.com/dromara/hutool/assets/19280610/507a55b0-66cd-46b2-b8da-6d8c8fc15881">

**Comment by looly** [comment]
默认的，传入字符串格式使用`SimpleDateFormat`解析，默认使用严格模式：

```java
format.setLenient(false);
```

要想实现成功解析，需要：

```java
DateUtil.parse(dateString, new SimpleDateFormat(dateFormat));
```

但是解析出的结果是：

```java
2020-08-02 16:33:33
```

因此问题在于`SimpleDateFormat`对这种长毫秒的格式支持并不好，建议使用方式2。

**Comment by weimo123** [comment]
好的，感谢回复。只是想着用字符串方式用惯了，如果能底层自动去完成转换就最好了，丢失毫秒也没问题
