### ISSUE TITLE
`putByPath()`方法抛出OutOfMemory异常

### ISSUE THREAD

**Issue by ChangXiaoning** [looly/hutool#3285]
### 版本情况

JDK版本：    1.8.0_362
hutool版本： 5.8.21

### 问题描述（包括截图）

1. 复现代码

```java
import cn.hutool.json.JSONObject;

public class JSONObjectTest {

    public static void main(String[] args) {
        JSONObject jSONObject = new JSONObject();
        Object value = new Object();
        jSONObject.putByPath("...z.888888888", value);
    }
}

```

2. 堆栈信息

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:267)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
	at java.util.ArrayList.add(ArrayList.java:464)
	at cn.hutool.json.JSONArray.addRaw(JSONArray.java:594)
	at cn.hutool.json.JSONArray.add(JSONArray.java:352)
	at cn.hutool.core.collection.ListUtil.setOrPadding(ListUtil.java:435)
	at cn.hutool.core.collection.ListUtil.setOrPadding(ListUtil.java:414)
	at cn.hutool.core.bean.BeanUtil.setFieldValue(BeanUtil.java:312)
	at cn.hutool.core.bean.BeanPath.set(BeanPath.java:150)
	at cn.hutool.core.bean.BeanPath.set(BeanPath.java:115)
	at cn.hutool.json.JSONObject.putByPath(JSONObject.java:325)
	at JSONObjectTest.main(JSONObjectTest.java:39)
```

3. 测试涉及到的文件（注意脱密）
见复现代码。

**Comment by looly** [comment]
这个问题类似于：https://github.com/dromara/hutool/issues/3286

合并处理。
