### ISSUE TITLE
`JSONArray`的`add()`方法抛出OutOfMemory异常

### ISSUE THREAD

**Issue by ChangXiaoning** [looly/hutool#3286]
### 版本情况

JDK版本：    1.8.0_362
hutool版本： 5.8.21

### 问题描述（包括截图）

1. 复现代码

```java
import cn.hutool.json.JSONObject;

public class JSONObjectTest {

    public static void main(String[] args) {
        JSONArray jSONArray = new JSONArray();
        Object element = new Object();
        jSONArray.add(1247626122, element);
    }
}

```

2. 堆栈信息

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:267)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
	at java.util.ArrayList.add(ArrayList.java:464)
	at cn.hutool.json.JSONArray.addRaw(JSONArray.java:594)
	at cn.hutool.json.JSONArray.add(JSONArray.java:352)
	at cn.hutool.json.JSONArray.add(JSONArray.java:461)
	at JSONArrayFuzzerTest19.main(JSONArrayFuzzerTest19.java:37)
```

3. 测试涉及到的文件（注意脱密）
见复现代码。

4. 分析

`jsonArray.add(idx, [element)`会在指定索引`idx`添加一个元素`element`。如果`jsonArray`长度小于指定索引，[`jsonArray.add()`就会通过循环不断添加null，直到jsonArray的长度等于指定索引值](https://github.com/dromara/hutool/blob/5889435e0998a4159f4c219ac001a44d50070b8c/hutool-json/src/main/java/cn/hutool/json/JSONArray.java#L461C8-L461C8)。如果这个索引特别大，比如1247626122，就会报告一个OOM异常。

**Comment by looly** [comment]
确实存在这个安全隐患。

5.8.22 增加一个长度检查，允许当前(size+1) * 2

**Comment by lianyiwuming** [comment]
> 确实存在这个安全隐患。
> 
> 5.8.22 增加一个长度检查，允许当前(size+1) * 2

这个类实现自 List，个人认为，应保持List接口的定义逻辑，如果 index < 0 || index > size() 直接抛出异常。可参考java.util.List#add(int, E)  注释。
![image](https://github.com/dromara/hutool/assets/23331492/233d4cd6-940b-4b56-8924-c1fc13f9f3b6)
