### ISSUE TITLE
DateUtil.parse()无法在12小时制的服务器上格式化"00:01:00"格式的时间。

### ISSUE THREAD

**Issue by MoshiCoCo** [looly/hutool#3294]
### 版本情况

JDK版本：    jdk_8_172
hutool版本： 5.8.20

### 问题描述（包括截图）

无法格式化时间。

复现代码
```java
// start= "00:01:00"
DateUtil.parse(start, "HH:mm:ss");
```

使用01:00:00时正常，此问题只发生在特定服务器上（12小时制时间的服务器上）

堆栈信息
```log
cn.hutool.core.date.DateException: Parse [00:01:00] with format [HH:mm:ss] error!
        at cn.hutool.core.date.DateTime.parse(DateTime.java:1096)
        at cn.hutool.core.date.DateTime.<init>(DateTime.java:281)
        at cn.hutool.core.date.DateUtil.parse(DateUtil.java:731)
      
Caused by: java.text.ParseException: Unparseable date: "00:01:00"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at cn.hutool.core.date.DateTime.parse(DateTime.java:1088)
        ... 12 more
```

**Comment by CherryRum** [comment]
您尝试下
`DateUtil.parse(start, "II:mm:ss");`

**Comment by MoshiCoCo** [comment]
> "II:mm:ss"

这个格式在本地测试直接抛异常了。

```log
Exception in thread "main" java.lang.IllegalArgumentException: Illegal pattern character 'I'
	at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:826)
	at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:634)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:605)
	at cn.hutool.core.date.DateUtil.newSimpleFormat(DateUtil.java:2211)
	at cn.hutool.core.date.DateUtil.newSimpleFormat(DateUtil.java:2194)
	at cn.hutool.core.date.DateTime.<init>(DateTime.java:281)
	at cn.hutool.core.date.DateUtil.parse(DateUtil.java:731)
```


针对发生问题的服务器，执行date命令，时间格式为

```log
Tue Sep  5 03:54:15 AM CST 2023
```

在以下时间格式的机器上均能正常工作。

```
Tue Sep  5 03:54:21 CST 2023
Tue Sep  5 16:58:10 WIB 2023
Tue Sep  5 04:57:33 -05 2023
Tue Sep  5 06:57:48 -03 2023
```

**Comment by CherryRum** [comment]
那这个问题先开着吧，您有空发下`locale`

**Comment by MoshiCoCo** [comment]
> locale

墨西哥首都时间，`UTC -6 `，`America/Mexico_City`

**Comment by looly** [comment]
@MoshiCoCo 特定时区考虑自定义DateFormatter吧，而不是传入字符串。字符串默认是当地时区。
