### ISSUE TITLE
非对称加密SM2算法使用自定义密钥对加密或解密遇到问题

### ISSUE THREAD

**Issue by andglf** [looly/hutool#3327]
### 版本情况

JDK版本：    jdk_1.8.0_341
hutool版本： 5.8.22（请确保最新尝试是否还有问题）
Bouncy Castle版本：bcprov-jdk15on-1.62, bcprov-jdk15to18-1.69

### 问题描述（包括截图）

1. 复现代码(官方文档示例报错)
文档链接：https://doc.hutool.cn/pages/SmUtil/#%E9%9D%9E%E5%AF%B9%E7%A7%B0%E5%8A%A0%E5%AF%86sm2

```java
String text = "我是一段测试aaaa";

        KeyPair pair = SecureUtil.generateKeyPair("SM2");
        byte[] privateKey = pair.getPrivate().getEncoded();
        byte[] publicKey = pair.getPublic().getEncoded();

        SM2 sm2 = SmUtil.sm2(privateKey, publicKey);
        // 公钥加密，私钥解密
        String encryptStr = sm2.encryptBcd(text, KeyType.PublicKey);
        String decryptStr = StrUtil.utf8Str(sm2.decryptFromBcd(encryptStr, KeyType.PrivateKey));
```

3. 堆栈信息（报错代码为最后一行）
Exception in thread "main" cn.hutool.crypto.CryptoException: InvalidCipherTextException: invalid cipher text
	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:301)
	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:282)
	at cn.hutool.crypto.asymmetric.AsymmetricDecryptor.decryptFromBcd(AsymmetricDecryptor.java:112)
	at cn.hutool.crypto.asymmetric.AsymmetricDecryptor.decryptFromBcd(AsymmetricDecryptor.java:95)
	at com.zeewain.user.demo.SM2Demo.main(SM2Demo.java:43)
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: invalid cipher text
	at org.bouncycastle.crypto.engines.SM2Engine.decrypt(Unknown Source)
	at org.bouncycastle.crypto.engines.SM2Engine.processBlock(Unknown Source)
	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:299)
	... 4 more
4. 测试涉及到的文件（注意脱密）
![image](https://github.com/dromara/hutool/assets/46335954/513245f3-9306-4f7d-b764-acefdbd11cba)

比如报错的Excel文件，有问题的图片等。

5. 问题排查
debug到ECKeyUtil.decodePublicKeyParams方法中尝试Q值步骤抛出并捕获了异常，且进行如下调整后问题不再出现，所以怀疑是公钥解析导致的问题
![image](https://github.com/dromara/hutool/assets/46335954/8ace81f0-3941-4d9e-acd6-d37e096331ca)

**Comment by CherryRum** [comment]
我这边尝试没有报错，麻烦您检查下版本

**Comment by andglf** [comment]
嗯嗯，问题找到了，是bcprov-jdk15on-1.62版本导致的问题，我把bcprov-jdk15on-1.62换成bcprov-jdk15on-1.69之后问题就不再出现了，你如果想复现的话，可以将bcprov-jdk15to18-1.69去掉，只导入bcprov-jdk15on-1.62试试
