### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "java.util.Base64"

### ISSUE THREAD

**Issue by waylent** [looly/hutool#3339]
### 版本情况

Android版本：7.1.1
JDK版本：    8但可能定制过
hutool版本： 5.8.11（新版也有问题）

### 问题描述（包括截图）

1. 复现代码
由于Android在API26版本才引入java.util.Base64导致API26版本以下机型在调用hutool的base64编码工具后，全都报错闪退
希望可以提供兼容Android低版本的hutool

3. 堆栈信息
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@da5890c
versionCode=6006009
BOARD=sdm660
BOOTLOADER=unknown
TYPE=user
ID=NMF26X
TIME=1528460172000
BRAND=Xiaomi
TAG=Build
HARDWARE=qcom
SERIAL=4685dea6
SUPPORTED_ABIS=[Ljava.lang.String;@a853255
CPU_ABI=arm64-v8a
IS_DEBUGGABLE=false
RADIO=unknown
MANUFACTURER=Xiaomi
IS_EMULATOR=false
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@540bc3f
TAGS=release-keys
CPU_ABI2=
UNKNOWN=unknown
PERMISSIONS_REVIEW_REQUIRED=false
USER=builder
FINGERPRINT=Xiaomi/jason/jason:7.1.1/NMF26X/V9.6.1.0.NCHCNFD:user/release-keys
HOST=c3-miui-ota-bd67.bj
versionName=6.6.9
PRODUCT=jason
DISPLAY=NMF26X
MODEL=Mi Note 3
DEVICE=jason
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
	at cn.hutool.core.codec.Base64.encode(Base64.java:140)
	at cn.hutool.crypto.symmetric.SymmetricEncryptor$-CC.$default$encryptBase64(SymmetricEncryptor.java:129)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.encryptBase64(SymmetricCrypto.java)
        /****内部代码堆栈****/
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.smk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.smk-1/lib/arm64, /data/app/com.smk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 18 more
java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", dex file "/data/user/0/com.smk/.cache/stub.dex", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.smk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.smk-1/lib/arm64, /data/app/com.smk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at cn.hutool.core.codec.Base64.encode(Base64.java:140)
	at cn.hutool.crypto.symmetric.SymmetricEncryptor$-CC.$default$encryptBase64(SymmetricEncryptor.java:129)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.encryptBase64(SymmetricCrypto.java)
        /****内部代码堆栈****/
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

4. 测试涉及到的文件（注意脱密）
不涉及
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个没有办法……

Hutool基于JDK8开发，无法向下兼容。
