### ISSUE TITLE
SimpleServer在添加的HttpFilter中有获取请求参数时，具体处理方法中如再次获取请求参数，则会报错Stream is closed

### ISSUE THREAD

**Issue by jiubaK** [looly/hutool#3343]
### 版本情况

JDK版本：    1.8.0_181
hutool版本： 5.8.22

### 问题描述（包括截图）

1. 复现代码

```java
package testHutool;

import cn.hutool.core.date.DateUtil;
import cn.hutool.core.map.multi.ListValueMap;
import cn.hutool.http.HttpUtil;
import cn.hutool.http.server.HttpServerRequest;
import cn.hutool.http.server.HttpServerResponse;
import cn.hutool.http.server.SimpleServer;
import cn.hutool.http.server.filter.HttpFilter;
import cn.hutool.log.StaticLog;

public class Main {
	public static void main(String[] args) {
		StaticLog.info("准备运行...");
		int port = 9596;
		SimpleServer server = HttpUtil.createServer(port)
		.addFilter((HttpFilter) (req, res, chain) -> {
			try {
				String time = DateUtil.now();
				StaticLog.info(time + " got request: " + req.getPath());
				StaticLog.info(" >   from : " + req.getClientIP());
				// 过滤器中获取请求参数
				StaticLog.info(" > params : " + req.getParams());
				chain.doFilter(req.getHttpExchange());
			} catch (Exception e) {
				e.printStackTrace();
				throw new RuntimeException("执行错误", e);
			}
		});
		server.addAction("/", (request, response) -> {
			index(request, response);
		});
		server.start();
		StaticLog.info("已开始运行: " + port);
	}
	
	public static void index(HttpServerRequest request, HttpServerResponse response) {
		try {
			// 具体逻辑中再次获取请求参数
			ListValueMap<String, String> params = request.getParams();
			System.out.println("index params: " + params);
			response.getWriter().write("GOT: " + params);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(-1);
		}
	}
}
```

2. 堆栈信息

```java
[2023-10-19 15:29:08] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.
[2023-10-19 15:29:08] [INFO] testHutool.Main: 准备运行...
Hutool Simple Http Server listen on 【0:0:0:0:0:0:0:0:9596】
[2023-10-19 15:29:08] [INFO] testHutool.Main: 已开始运行: 9596
[2023-10-19 15:29:25] [INFO] testHutool.Main: 2023-10-19 15:29:25 got request: /
[2023-10-19 15:29:25] [INFO] testHutool.Main:  >   from : 0:0:0:0:0:0:0:1
[2023-10-19 15:29:25] [INFO] testHutool.Main:  > params : {name=[ICU]}
cn.hutool.core.io.IORuntimeException: IOException: Stream is closed
	at cn.hutool.core.io.copy.StreamCopier.copy(StreamCopier.java:71)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:162)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:146)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:132)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:119)
	at cn.hutool.core.io.IoUtil.read(IoUtil.java:408)
	at cn.hutool.core.io.IoUtil.readBytes(IoUtil.java:474)
	at cn.hutool.http.server.HttpServerRequest.getBodyBytes(HttpServerRequest.java:286)
	at cn.hutool.http.server.HttpServerRequest.getBody(HttpServerRequest.java:276)
	at cn.hutool.http.server.HttpServerRequest.getBody(HttpServerRequest.java:266)
	at cn.hutool.http.server.HttpServerRequest.getParams(HttpServerRequest.java:342)
	at testHutool.Main.index(Main.java:38)
	at testHutool.Main.lambda$1(Main.java:30)
	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:32)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at testHutool.Main.lambda$0(Main.java:23)
	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:129)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream is closed
	at sun.net.httpserver.LeftOverInputStream.read(LeftOverInputStream.java:97)
	at cn.hutool.core.io.copy.StreamCopier.doCopy(StreamCopier.java:97)
	at cn.hutool.core.io.copy.StreamCopier.copy(StreamCopier.java:68)
	... 25 more
```

3. 测试过程

```
发起请求
http://localhost:9596/?name=ICU
后台报错
```

**Comment by looly** [comment]
确认问题。

原因是filter时的req没有缓存导致的。

5.8.23 6.0.0-M8修复此问题。
