### ISSUE TITLE
toJsonStr反序列化产生StackOverflowError

### ISSUE THREAD

**Issue by wulangcode** [looly/hutool#3346]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.22

### 问题描述（包括截图）

1. 复现代码

```java
import io.undertow.servlet.spec.HttpServletResponseImpl;

@Data
public static class Test {
    String a;
    HttpServletResponseImpl httpServletResponse;
}
```

```java
JSONUtil.toJsonStr(Test)
```

2. 堆栈信息
```
Caused by: java.lang.StackOverflowError: null
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
	at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:765)
	at cn.hutool.json.JSONObject.set(JSONObject.java:377)
	at cn.hutool.json.JSONObject.put(JSONObject.java:355)
	at cn.hutool.json.JSONObject.put(JSONObject.java:43)
	at cn.hutool.core.bean.copier.BeanCopier.lambda$beanToMap$0(BeanCopier.java:197)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.hutool.core.bean.BeanUtil.descForEach(BeanUtil.java:180)
	at cn.hutool.core.bean.copier.BeanCopier.beanToMap(BeanCopier.java:164)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:106)
	at cn.hutool.json.JSONObject.populateMap(JSONObject.java:628)
	at cn.hutool.json.JSONObject.init(JSONObject.java:679)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:203)
......
```

能否设置一个默认的最大递归深度？防止程序崩溃，因为这是存在我们系统中一段打印日志的代码，不知道外面的程序传入什么对象，直接无脑`toJsonStr`了，不希望他影响程序的运行。

**Comment by CherryRum** [comment]
建议您把这种请求
`!(arg instanceof HttpServletRequest || arg instanceof HttpServletResponse)`
排除一下

**Comment by wulangcode** [comment]
> 建议您把这种请求 `!(arg instanceof HttpServletRequest || arg instanceof HttpServletResponse)` 排除一下

这可以解决当前的问题。但我不确定以后是否还有有其他的`StackOverflowError `。增加递归的深度，是否可以作为兜底呢？

**Comment by looly** [comment]
@wulangcode 经过测试，6.0.0-M7不存在递归问题。

**Comment by looly** [comment]
这里本质上是`NioSocketConduit`和`WorkerThread`两个对象存在互相引用的情况：

![image](https://github.com/dromara/hutool/assets/1432613/e1a8ed2e-97bb-4469-9be7-c59a6ad5d2b7)

![image](https://github.com/dromara/hutool/assets/1432613/ac6ff3e9-ff39-4683-bb45-babfe4214b5a)

最终导致JSON解析时循环调用导致的问题。

**Comment by looly** [comment]
我们简化这个场景：

```java
        @Test
	public void jsonWrapTest() {

		// 构建循环引用
		final TestBean1 testBean1 = new TestBean1();
		final TestBean2 testBean2 = new TestBean2();
		testBean1.testBean2 = testBean2;
		testBean2.testBean1 = testBean1;

		Console.log(InternalJSONUtil.wrap(testBean1, JSONConfig.of()));
	}

	@Data
	public class TestBean1{
		private TestBean2 testBean2;
	}

	@Data
	public class TestBean2{
		private TestBean1 testBean1;
	}
```

也就说，在Hutool的JSON中，没有处理循环引用的逻辑。

FastJSON中使用`$ref`来代替循环引用对象，Hutool并不支持这种模式。

考虑更换JSON库处理此类问题。
