### ISSUE TITLE
IllegalArgumentException: Invalid cookie name-value pair

### ISSUE THREAD

**Issue by mario1oreo** [looly/hutool#336]
httpResponse.init  方法获取httpConnection.headers(); 会有如下报错

尝试其他网站是正常的     但是模拟手机的请求  访问APP会有问题

Exception in thread "main" java.lang.IllegalArgumentException: Invalid cookie name-value pair
	at java.net.HttpCookie.parseInternal(HttpCookie.java:823)
	at java.net.HttpCookie.parse(HttpCookie.java:202)
	at java.net.HttpCookie.access$100(HttpCookie.java:58)
	at java.net.HttpCookie$12.parse(HttpCookie.java:977)
	at sun.net.www.protocol.http.HttpURLConnection.filterHeaderField(HttpURLConnection.java:2887)
	at sun.net.www.protocol.http.HttpURLConnection.getFilteredHeaderFields(HttpURLConnection.java:2924)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:2968)
	at cn.hutool.http.HttpConnection.headers(HttpConnection.java:346)
	at com.lightbend.akka.sample.HttpResponse.init(HttpResponse.java:322)
	at com.lightbend.akka.sample.HttpResponse.<init>(HttpResponse.java:53)
	at com.lightbend.akka.sample.HttpRequest.execute(HttpRequest.java:826)
	at com.lightbend.akka.sample.HttpRequest.execute(HttpRequest.java:793)

**Comment by mario1oreo** [comment]
private HttpResponse init() throws HttpException{
        try {
            this.status = httpConnection.responseCode();
//            this.headers = httpConnection.headers();
            final Charset charset = httpConnection.getCharset();
            this.charsetFromResponse = charset;
            if(null != charset) {
                this.charset = charset;
            }

            this.in = (this.status < HttpStatus.HTTP_BAD_REQUEST) ? httpConnection.getInputStream() : httpConnection.getErrorStream();
        } catch (IOException e) {
            if(e instanceof FileNotFoundException){
                //服务器无返回内容，忽略之
            }else{
                throw new HttpException(e);
            }
        }
        if(null == this.in) {
            //在一些情况下，返回的流为null，此时提供状态码说明
            this.in = new ByteArrayInputStream(StrUtil.format("Error request, response status: {}", this.status).getBytes());
        } else if(isGzip() && false == (in instanceof GZIPInputStream)){
            try {
                in = new GZIPInputStream(in);
            } catch (IOException e) {
                //在类似于Head等方法中无body返回，此时GZIPInputStream构造会出现错误，在此忽略此错误读取普通数据
                //ignore
            }
        }

        //同步情况下强制同步
        return this.isAsync ? this : forceSync();
    }



注释掉this.headers = httpConnection.headers();即可正常访问

**Comment by mario1oreo** [comment]
使用版本4.2.1   和最新版本都一样的问题



        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>4.2.1</version>
        </dependency>



        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>4.5.6</version>
        </dependency>

**Comment by looly** [comment]
应该是服务端Cookie格式不规范导致的。请检查。

4.5.7此处我会加一下try，跳过这个。

**Comment by mario1oreo** [comment]
> 应该是服务端Cookie格式不规范导致的。请检查。
> 
> 4.5.7此处我会加一下try，跳过这个。

谢谢
