### ISSUE TITLE
cn.hutool.json.JSONUtil的parse方法，传入map对象，会导致栈溢出

### ISSUE THREAD

**Issue by wanhonglei** [looly/hutool#3376]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4（最新版本依然有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Map<String,Object> map = new HashMap<>();
// map 中塞入以下JSON字符串的数据
// {"content-length":"749","receiver":13500001,"postman-token":"4edbff44-2209-4155-9b59-6d4739de7877","x5-uuid":"35123123132","messageId":2193983,"version":1,"content":"00340032003400340032006300330031003300300033003000330030003300300033003100330038003300330033003800330034003200630033003100330031003200630033003200330033003300300033003700330033003300300033003000330031003300300033003000320063003400630033003200350066003400330035003300350066003300310032006200330030003200650033003000320062003300300032006500330031003200620033003100320063003300300032006500330034003200610033003100330031","statics":{"empty":false},"accept":"*/*","messageType":7005,"sender":14492270,"requestid":"d879f329999f558153011b69fee9d8c8","host":"127.0.0.1:8080","content-type":"application/json","connection":"keep-alive","creationtime":"2023-07-30 00:57:39","cache-control":"no-cache","eagleeye-rpcid":"0.1","sendtime":"2023-07-29 16:57:39","accept-encoding":"gzip, deflate, br","user-agent":"PostmanRuntime/7.34.0"}

// 调用一下方法，会导致栈溢出
cn.hutool.json.JSON hutoolJson = cn.hutool.json.JSONUtil.parse(map);
```

2. 堆栈信息
java.lang.StackOverflowError
    at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:812)
    at cn.hutool.json.JSONObject.set(JSONObject.java:399)
    at cn.hutool.json.JSONObject.set(JSONObject.java:358)
    at cn.hutool.json.JSONObject.put(JSONObject.java:346)
    at cn.hutool.json.JSONObject.put(JSONObject.java:33)
    at cn.hutool.core.bean.copier.BeanToMapCopier.lambda$copy$0(BeanToMapCopier.java:77)
    at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
    at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:48)
    at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:16)
    at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
    at cn.hutool.core.bean.BeanUtil.beanToMap(BeanUtil.java:718)
    at cn.hutool.json.ObjectMapper.mapFromBean(ObjectMapper.java:260)
    at cn.hutool.json.ObjectMapper.map(ObjectMapper.java:114)
    at cn.hutool.json.JSONObject.<init>(JSONObject.java:211)
    at cn.hutool.json.JSONObject.<init>(JSONObject.java:188)
    at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:812)
    at cn.hutool.json.JSONObject.set(JSONObject.java:399)
    at cn.hutool.json.JSONObject.set(JSONObject.java:358)
    at cn.hutool.json.JSONObject.put(JSONObject.java:346)
    at cn.hutool.json.JSONObject.put(JSONObject.java:33)
    at cn.hutool.core.bean.copier.BeanToMapCopier.lambda$copy$0(BeanToMapCopier.java:77)
    at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
    at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:48)
    at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:16)
    at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
    at cn.hutool.core.bean.BeanUtil.beanToMap(BeanUtil.java:718)
    at cn.hutool.json.ObjectMapper.mapFromBean(ObjectMapper.java:260)
    at cn.hutool.json.ObjectMapper.map(ObjectMapper.java:114)
    at cn.hutool.json.JSONObject.<init>(JSONObject.java:211)
    at cn.hutool.json.JSONObject.<init>(JSONObject.java:188)
    at cn.hutool.json.JSONUtil.wrap(JSONUtil.java:812)
    at cn.hutool.json.JSONObject.set(JSONObject.java:399)
    at cn.hutool.json.JSONObject.set(JSONObject.java:358)
    at cn.hutool.json.JSONObject.put(JSONObject.java:346)
    at cn.hutool.json.JSONObject.put(JSONObject.java:33)
    at cn.hutool.core.bean.copier.BeanToMapCopier.lambda$copy$0(BeanToMapCopier.java:77)
    at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
    at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:48)
    at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:16)
    at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
    at cn.hutool.core.bean.BeanUtil.beanToMap(BeanUtil.java:718)
    at cn.hutool.json.ObjectMapper.mapFromBean(ObjectMapper.java:260)
    at cn.hutool.json.ObjectMapper.map(ObjectMapper.java:114)...

**Comment by ZZemptypoint** [comment]
没明白你的意思，你是指这样吗：
```java
        // map 中塞入以下JSON字符串的数据
        String str = "{\"content-length\":\"749\",\"receiver\":13500001,\"postman-token\":\"4edbff44-2209-4155-9b59-6d4739de7877\",\"x5-uuid\":\"35123123132\",\"messageId\":2193983,\"version\":1,\"content\":\"00340032003400340032006300330031003300300033003000330030003300300033003100330038003300330033003800330034003200630033003100330031003200630033003200330033003300300033003700330033003300300033003000330031003300300033003000320063003400630033003200350066003400330035003300350066003300310032006200330030003200650033003000320062003300300032006500330031003200620033003100320063003300300032006500330034003200610033003100330031\",\"statics\":{\"empty\":false},\"accept\":\"*/*\",\"messageType\":7005,\"sender\":14492270,\"requestid\":\"d879f329999f558153011b69fee9d8c8\",\"host\":\"127.0.0.1:8080\",\"content-type\":\"application/json\",\"connection\":\"keep-alive\",\"creationtime\":\"2023-07-30 00:57:39\",\"cache-control\":\"no-cache\",\"eagleeye-rpcid\":\"0.1\",\"sendtime\":\"2023-07-29 16:57:39\",\"accept-encoding\":\"gzip, deflate, br\",\"user-agent\":\"PostmanRuntime/7.34.0\"}";
        final JSONObject jsonObject = JSONUtil.parseObj(str);
        Map<String, Object> map = new HashMap<>(jsonObject);
        
        JSON hutoolJson = JSONUtil.parse(map);
```

**Comment by looly** [comment]
@wanhonglei  经过测试，未复现问题，麻烦升级到最新版本Hutool后尝试，如果复现请帖下完整测试用例再打开此issue。
