### ISSUE TITLE
JSONConfig.create().setIgnoreError(true)还会抛出异常

### ISSUE THREAD

**Issue by chauncy1** [looly/hutool#3379]
### 版本情况

JDK版本：    Oracle OpenJdk 1.8.0_144
hutool版本： 5.8.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
描述：解析json时设置了setIgnoreError(true)还会抛出异常

1. 复现代码

```java
String jsonStr = "{illegalFormal}";
JSONObject jsonObject = JSONUtil.parseObj(jsonStr, JSONConfig.create().setIgnoreError(true));
```

2. 堆栈信息
cn.hutool.json.JSONException: Expected a ':' after a key at 10 [character 11 line 1]

	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:450)
	at cn.hutool.json.JSONParser.parseTo(JSONParser.java:77)
	at cn.hutool.json.ObjectMapper.mapFromTokener(ObjectMapper.java:243)
	at cn.hutool.json.ObjectMapper.mapFromStr(ObjectMapper.java:219)
	at cn.hutool.json.ObjectMapper.map(ObjectMapper.java:98)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:210)
	at cn.hutool.json.JSONObject.<init>(JSONObject.java:187)
	at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:112)
	at com.snowball.fp.android.transitservice.SimpleTest.main1(SimpleTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

3. 测试涉及到的文件（注意脱密）
无
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这是语法错误异常，肯定得抛出啊。setIgnoreError只是过滤bean转JSON过程中的转换异常。
