### ISSUE TITLE
读取文件时偶现读取失败报错

### ISSUE THREAD

**Issue by hero-zhanghao** [looly/hutool#3395]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16

### 问题描述（包括截图）

1. 复现代码

```java
FileUtil.readString(file, CharsetUtil.CHARSET_UTF_8)
```

2. 堆栈信息
 cn.hutool.core.io.IORuntimeException: IOException: File length is [3436] but read [-1]!
	at cn.hutool.core.io.file.FileReader.readBytes(FileReader.java:129) ~[1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]
	at cn.hutool.core.io.file.FileReader.readString(FileReader.java:144) ~[1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1939) ~[-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]

3. 测试涉及到的文件（注意脱密）

文件为普通的txt文件，偶现了几次，请问下是什么原因呢

**Comment by looly** [comment]
@hero-zhanghao 几种情况：

1. 文件内容为空，或者文件不存在
2. 文件是否为占用？

贴下完整堆栈看下，再打开此issue。
