### ISSUE TITLE
BitMapBloomFilter OutOfMemoryError

### ISSUE THREAD

**Issue by section9-lab** [looly/hutool#3398]
### 版本情况

JDK版本：    openjdk_8_392
hutool版本： 5.8.23

### 问题描述（包括截图）

1. 复现代码

```java

package org.filter;

import cn.hutool.bloomfilter.BitMapBloomFilter;
import com.google.common.hash.BloomFilter;
import com.google.common.hash.Funnels;

import java.nio.charset.Charset;

public class Filter {
    public static void main(String[] args) {
        System.out.println("start");
        guava(1000_0000);
        huTool(1_0000);
    }

    public static void guava(int number){
        long start = System.currentTimeMillis();
        BloomFilter<CharSequence> bloomFilter = BloomFilter.create(Funnels.stringFunnel(Charset.defaultCharset()), number, 0.00001);

        for (int i = 0; i < number; i++) {
            bloomFilter.put("test_"+i);
        }
        System.out.println("guava init "+(System.currentTimeMillis() - start));

        for (int i = 0; i < number; i++) {
            boolean mightContain = bloomFilter.mightContain("test_" + i);
            if (!mightContain){
                System.out.println(mightContain);
            }
        }
        System.out.println("guava end "+(System.currentTimeMillis() - start));
    }

    public static void huTool(int number){
        long start = System.currentTimeMillis();
        BitMapBloomFilter bloomFilter = new BitMapBloomFilter(number);

        for (int i = 0; i < number; i++) {
            bloomFilter.add("test_"+i);
        }

        System.out.println("huTool init "+(System.currentTimeMillis() - start));
        for (int i = 0; i < number; i++) {
            boolean mightContain = bloomFilter.contains("test_" + i);
            if (!mightContain){
                System.out.println(mightContain);
            }
        }
        System.out.println("huTool end "+(System.currentTimeMillis() - start));
    }
}

```

2. 堆栈信息
```
start
guava init 22051
guava end 31191
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at cn.hutool.bloomfilter.bitMap.IntMap.<init>(IntMap.java:29)
	at cn.hutool.bloomfilter.filter.AbstractFilter.init(AbstractFilter.java:52)
	at cn.hutool.bloomfilter.filter.AbstractFilter.<init>(AbstractFilter.java:30)
	at cn.hutool.bloomfilter.filter.FuncFilter.<init>(FuncFilter.java:34)
	at cn.hutool.bloomfilter.filter.ELFFilter.<init>(ELFFilter.java:13)
	at cn.hutool.bloomfilter.filter.ELFFilter.<init>(ELFFilter.java:9)
	at cn.hutool.bloomfilter.BitMapBloomFilter.<init>(BitMapBloomFilter.java:33)
	at org.filter.Filter.huTool(Filter.java:36)
	at org.filter.Filter.main(Filter.java:13)

Process finished with exit code 1
```
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Hutool默认使用intMap构建，使用int[]存储，参数是数组长度，因此数字太大会导致溢出。
