### ISSUE TITLE
StrJoin当append内容后调用length()会出现空指针

### ISSUE THREAD

**Issue by zhangchaoxu** [looly/hutool#3444]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.24

### 问题描述（包括截图）

1. 复现代码

```java
 @Test
  void joinTest() {
      StrJoiner strJoinerEmpty = StrJoiner.of(",");
      Console.error("strJoinerEmpty.length={}", strJoinerEmpty.length());

      StrJoiner strJoinerWithContent = StrJoiner.of(",").append("haha");
      Console.error("strJoinerWithContent.length={}", strJoinerWithContent.length());
  }
```

2. 堆栈信息
strJoinerEmpty.length=0

java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.suffix" is null

	at cn.hutool.core.text.StrJoiner.length(StrJoiner.java:360)
	at com.xxx.NoEnvTest.joinTest(NoEnvTest.java:1959)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

4. 问题定位
StrJoiner的length方法，对suffix的操作未检查null

**Comment by looly** [comment]
感谢，未判空。

5.8.25 6.0.0-M10修复此问题。
