### ISSUE TITLE
JSONUtil.toJsonStr(Object obj) 数组下标越界

### ISSUE THREAD

**Issue by ageovb** [looly/hutool#3468]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.8.25

### 问题描述

1. 复现代码
实体类转 Json，数组下标越界，不知道其他 `toJsonStr()` 是否也有这个问题。

2. 堆栈信息
```java
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at cn.hutool.core.bean.copier.BeanToMapCopier.lambda$copy$0(BeanToMapCopier.java:75)
at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:48)
at cn.hutool.core.bean.copier.BeanToMapCopier.copy(BeanToMapCopier.java:16)
at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
at cn.hutool.json.JSONObject.populateMap(JSONObject.java:627)
at cn.hutool.json.JSONObject.init(JSONObject.java:670)
at cn.hutool.json.JSONObject.<init>(JSONObject.java:202)
at cn.hutool.json.JSONUtil.parse(JSONUtil.java:225)
at cn.hutool.json.JSONUtil.parse(JSONUtil.java:196)
at cn.hutool.json.JSONUtil.toJsonStr(JSONUtil.java:373)
```

**Comment by looly** [comment]
麻烦提供下测试的bean和测试数据。

**Comment by looly** [comment]
5.8.26 增加下标越界判断，感谢。
