### ISSUE TITLE
使用的是4.4.1的版本，想问下这个版本SimpleCache 是否存在死锁的场景

### ISSUE THREAD

**Issue by WXzhongwang** [looly/hutool#3471]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

我这边使用的是4.4.1的版本，想问下这个版本SimpleCache
是否存在死锁的场景？目前不太方便升级，辛苦帮解答下。

1. 复现代码

```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package cn.hutool.core.bean;

import cn.hutool.core.lang.SimpleCache;

public enum BeanDescCache {
    INSTANCE;

    private SimpleCache<Class<?>, BeanDesc> bdCache = new SimpleCache();

    private BeanDescCache() {
    }

    public BeanDesc getBeanDesc(Class<?> beanClass) {
        return (BeanDesc)this.bdCache.get(beanClass);
    }

    public void putBeanDesc(Class<?> beanClass, BeanDesc BeanDesc) {
        this.bdCache.put(beanClass, BeanDesc);
    }
}

```

2. 堆栈信息

$jstack 3218 | grep x'x'x'x'x -A 100
"xxxxx-0" #923646 prio=5 os_prio=0 tid=0x00007f136d4eb000 nid=0x3f932 waiting on condition [0x00007f134afed000]
   java.lang.Thread.State: WAITING (parking)
  at sun.misc.Unsafe.park0(Native Method)
  - parking to wait for  <0x00000006ff4a9978> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
  at sun.misc.Unsafe.park(Unsafe.java:1025)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:176)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:842)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:974)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1291)
  at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
  at xxxxx.cn.hutool.core.lang.SimpleCache.get(SimpleCache.java:32)
  at xxxx.cn.hutool.core.bean.BeanDescCache.getBeanDesc(BeanDescCache.java:22)

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
4.x不排除有bug。这个版本已经很久没有维护了。

如果发现有死锁问题，建议弃用。
