### ISSUE TITLE
Json 序列化错误

### ISSUE THREAD

**Issue by iszhangsc** [looly/hutool#3504]
### 版本情况

JDK版本：    zulu-17.jdk
hutool版本： 5.8.26（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
hutool json 序列化错误 、反序列化错误
jackson 可以序列化&&反序列化

1. 复现代码

```java
public class JsonTest {

    @Data
    public static class JsonBean {
        private String name;
        private Class<?>[] classes;
    }
    public static void main(String[] args) throws JsonProcessingException {
        JsonBean jsonBean = new JsonBean();
        jsonBean.setName("test");
        jsonBean.setClasses(new Class[]{String.class});
        String huToolJsonStr = JSONUtil.toJsonStr(jsonBean);
        System.out.println("hutool json str-------" + huToolJsonStr);

        // 需要导入jackson包依赖！！！
        ObjectMapper objectMapper = new ObjectMapper();
        String jacksonJsonStr = objectMapper.writeValueAsString(jsonBean);
        System.out.println("jackson json str-------" + jacksonJsonStr);

        // 可以反序列化
        JsonBean jacksonJsonBean = objectMapper.readValue(jacksonJsonStr, JsonBean.class);

        // error: 不能反序列
        JsonBean bean = JSONUtil.toBean(huToolJsonStr, JsonBean.class);
    }

}

```

2. 堆栈信息
 hutool json str-------{"name":"test","classes":["class java.lang.String"]}
jackson json str-------{"name":"test","classes":["java.lang.String"]}
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at cn.hutool.core.convert.ConverterRegistry.getDefaultConverter(ConverterRegistry.java:156)
	at cn.hutool.core.convert.ConverterRegistry.getConverter(ConverterRegistry.java:136)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:219)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:261)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:753)
	at cn.hutool.json.JSONConverter.jsonToBean(JSONConverter.java:138)
	at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:96)
	at cn.hutool.json.JSON.toBean(JSON.java:179)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:93)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:366)
	at cn.hutool.core.bean.copier.MapToBeanCopier.lambda$copy$0(MapToBeanCopier.java:91)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at cn.hutool.core.map.MapWrapper.forEach(MapWrapper.java:160)
	at cn.hutool.core.bean.copier.MapToBeanCopier.copy(MapToBeanCopier.java:60)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
	at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:89)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.Converter.convertWithCheck(Converter.java:35)
	at cn.hutool.json.JSONConverter.jsonToBean(JSONConverter.java:134)
	at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:96)
	at cn.hutool.json.JSON.toBean(JSON.java:179)
	at cn.hutool.json.JSON.toBean(JSON.java:155)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:447)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:420)
	at JsonTest.main(JsonTest.java:34)

**Comment by looly** [comment]
修复见：https://github.com/dromara/hutool/pull/3507
