### ISSUE TITLE
JSONUtil序列化和反序列化预期的结果不一致

### ISSUE THREAD

**Issue by misakacoder** [looly/hutool#3506]
### 版本情况

JDK版本：    oracle jdk 11.0.16.1
hutool版本： 5.8.26（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
当序列化的对象字段有class类型的时候，将序列化后的字符串再反序列化成这个对象会报错

1. 复现代码
```java
public class HutoolApplication {
    public static void main(String[] args) {
        Languages languages = new Languages();
        languages.setLanguageType(Java.class);

        System.out.println("============fastjson============");
        String fastJSONString = JSON.toJSONString(languages);
        System.out.println(fastJSONString);
        System.out.println(JSON.parseObject(fastJSONString, Languages.class));

        System.out.println("============hutool============");
        String hutoolJSONString = JSONUtil.toJsonStr(languages);
        System.out.println(hutoolJSONString);
        System.out.println(JSONUtil.toBean(hutoolJSONString, Languages.class));
    }

    public static class Languages {

        private Class<? extends Language> languageType;

        public Class<? extends Language> getLanguageType() {
            return languageType;
        }

        public void setLanguageType(Class<? extends Language> languageType) {
            this.languageType = languageType;
        }
    }

    public interface Language {}

    public static class Java implements Language {}
}
```

2. 堆栈信息
============fastjson============
{"languageType":"com.misaka.HutoolApplication$Java"}
com.misaka.HutoolApplication$Languages@7e0e6aa2
============hutool============
{"languageType":"class com.misaka.HutoolApplication$Java"}
Exception in thread "main" cn.hutool.core.exceptions.UtilException: ClassNotFoundException: class com.misaka.HutoolApplication$Java
	at cn.hutool.core.util.ClassLoaderUtil.doLoadClass(ClassLoaderUtil.java:314)
	at cn.hutool.core.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:197)
	at cn.hutool.core.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:164)
	at cn.hutool.core.convert.impl.ClassConverter.convertInternal(ClassConverter.java:36)
	at cn.hutool.core.convert.impl.ClassConverter.convertInternal(ClassConverter.java:12)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convertSpecial(ConverterRegistry.java:339)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:235)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:261)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:753)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:96)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:366)
	at cn.hutool.core.bean.copier.MapToBeanCopier.lambda$copy$0(MapToBeanCopier.java:91)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at cn.hutool.core.map.MapWrapper.forEach(MapWrapper.java:160)
	at cn.hutool.core.bean.copier.MapToBeanCopier.copy(MapToBeanCopier.java:60)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
	at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:89)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.Converter.convertWithCheck(Converter.java:35)
	at cn.hutool.json.JSONConverter.jsonToBean(JSONConverter.java:134)
	at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:96)
	at cn.hutool.json.JSON.toBean(JSON.java:179)
	at cn.hutool.json.JSON.toBean(JSON.java:155)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:447)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:420)
	at com.misaka.HutoolApplication.main(HutoolApplication.java:19)
Caused by: java.lang.ClassNotFoundException: class com.misaka.HutoolApplication$Java
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at cn.hutool.core.util.ClassLoaderUtil.doLoadClass(ClassLoaderUtil.java:309)
	... 26 more

**Comment by looly** [comment]
修复见：https://github.com/dromara/hutool/pull/3507
