### ISSUE TITLE
Cannot read the array length because "<local3>" is null

### ISSUE THREAD

**Issue by SkyLight1234** [looly/hutool#3576]
### 版本情况

JDK版本：    jdk21
hutool版本： 6.0.0-M12

### 问题描述（包括截图）

1. 复现代码

```java
java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
	at org.dromara.hutool.core.annotation.elements.CombinationAnnotatedElement.parseDeclared(CombinationAnnotatedElement.java:149)
	at org.dromara.hutool.core.annotation.elements.CombinationAnnotatedElement.parseDeclared(CombinationAnnotatedElement.java:158)
	at org.dromara.hutool.core.annotation.elements.CombinationAnnotatedElement.init(CombinationAnnotatedElement.java:130)
	at org.dromara.hutool.core.annotation.elements.CombinationAnnotatedElement.<init>(CombinationAnnotatedElement.java:95)
	at org.dromara.hutool.core.annotation.elements.CombinationAnnotatedElement.<init>(CombinationAnnotatedElement.java:83)
	at org.dromara.hutool.core.annotation.AnnotationUtil.toCombination(AnnotationUtil.java:76)
	at org.dromara.hutool.core.annotation.AnnotationUtil.getAnnotation(AnnotationUtil.java:162)
	at org.dromara.hutool.core.annotation.AnnotationUtil.hasAnnotation(AnnotationUtil.java:174)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
org.dromara.hutool.core.annotation.elements.CombinationAnnotatedElement#parseDeclared

**Comment by Createsequence** [comment]
这个问题似乎是递归解析注解的时候有一个注解数组为空导致的，可否有更具体的复现代码？

**Comment by looly** [comment]
@Createsequence 
![image](https://github.com/dromara/hutool/assets/1432613/8c71bc74-fbca-4f40-a474-36f3d50d6709)

是不是这个为null导致的？加个空判定？

**Comment by looly** [comment]
@Createsequence 我加了空判断返回。

@SkyLight1234 6.0.0-M13修复此问题~~

**Comment by SkyLight1234** [comment]
好的

**Comment by SkyLight1234** [comment]
还没提交maven么

**Comment by looly** [comment]
@SkyLight1234 定期提交的，不是每改一个bug就提交。

你可以把`v6-dev`pull下来本地install
