### ISSUE TITLE
读取文件超过3GB时报java.lang.NegativeArraySizeException: -221445712

### ISSUE THREAD

**Issue by zhiyuFeng** [looly/hutool#3577]
### 版本情况

JDK版本：    openjdk_11.0.16
hutool版本： 5.8.27（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
public static void main(String[] args) {
        String read = IoUtil.read(FileUtil.getInputStream("data.json"), StandardCharsets.UTF_8);
    }
```

2. 堆栈信息
```java
Exception in thread "main" java.lang.NegativeArraySizeException: -221445712
	at cn.hutool.core.io.FastByteBuffer.toArray(FastByteBuffer.java:210)
	at cn.hutool.core.io.FastByteArrayOutputStream.toByteArray(FastByteArrayOutputStream.java:93)
	at cn.hutool.core.io.IoUtil.readBytes(IoUtil.java:491)
	at cn.hutool.core.io.IoUtil.readBytes(IoUtil.java:457)
	at cn.hutool.core.io.IoUtil.read(IoUtil.java:368)
```
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你这个文件太大了，不能一次性读取（超过了byte[]最大容量）

见：https://stackoverflow.com/questions/816142/strings-maximum-length-in-java-calling-length-method

考虑其它读取方式。
