### ISSUE TITLE
org.dromara.hutool.http.HttpUtil#get(java.lang.String) 请求无法成功

### ISSUE THREAD

**Issue by SkyLight1234** [looly/hutool#3582]
### 版本情况

JDK版本：    org.dromara.hutool
hutool版本： 6.0.0-M12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
2024-05-13 13:11:27 XNIO-1 task-4 com.xingyuv.jushauth.log.Log(error:45) [ERROR] - Failed to login with oauth authorization.
java.lang.IllegalArgumentException: SSL context may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(SSLConnectionSocketFactory.java:273)
	at org.dromara.hutool.http.client.engine.httpclient4.HttpClient4Engine.buildSocketFactory(HttpClient4Engine.java:190)
	at org.dromara.hutool.http.client.engine.httpclient4.HttpClient4Engine.initEngine(HttpClient4Engine.java:116)
	at org.dromara.hutool.http.client.engine.httpclient4.HttpClient4Engine.send(HttpClient4Engine.java:80)
	at org.dromara.hutool.http.HttpUtil.get(HttpUtil.java:126)
	at org.dromara.hutool.http.HttpUtil.get(HttpUtil.java:111)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
6.0.0-M13修复此问题，感谢~~
