### ISSUE TITLE
SM2使用公钥加密报错

### ISSUE THREAD

**Issue by 77321660** [looly/hutool#359]
公钥pubicKey ： BF1D3283D27A5F2A53CF286609F9E213D7E55F38CEFA5C9E02C24F6B8576EFE312D701FD6CCE43A869181D122FFF0A35C4083A85C4973F213082C863FD7A06B4

sessionKey ： B1276F2620F484C5B19990D09D6B3067

SmUtil.sm2(null,HexUtil.decodeHex(pubicKey)).encryptBase64(HexUtil.decodeHex(sessionKey), KeyType.PublicKey);

报错如下：
cn.hutool.crypto.CryptoException: InvalidKeySpecException: encoded key spec not recognized: failed to construct sequence from byte[]: DER length more than 4 bytes: 28

	at cn.hutool.crypto.KeyUtil.generatePublicKey(KeyUtil.java:309)
	at cn.hutool.crypto.KeyUtil.generatePublicKey(KeyUtil.java:289)
	at cn.hutool.crypto.SecureUtil.generatePublicKey(SecureUtil.java:179)
	at cn.hutool.crypto.asymmetric.SM2.<init>(SM2.java:68)
	at cn.hutool.crypto.SmUtil.sm2(SmUtil.java:68)

**Comment by looly** [comment]
https://i.goto327.top/CryptTools/SM2.aspx?tdsourcetag=s_pctim_aiomsg

**Comment by looly** [comment]
按照长度来说，这个密钥肯定不对。

应该是公钥X、公钥Y和Id之类的组合一下。具体组合方式我这边也未知。请自行百度。

**Comment by 77321660** [comment]
国密规范SM2公钥明文长度是64字节，私钥长度是32字节
