### ISSUE TITLE
 RuntimeUtil.execForStr  执行pnpm命令报错

### ISSUE THREAD

**Issue by duzengjie** [looly/hutool#3622]
### 版本情况

JDK版本：    oracle 17
hutool版本： 5.8.28

### 问题描述（包括截图）

1. 复现代码

```java

        String path = System.getProperty("user.dir");
        System.out.println("Project path: " + path);

        String exec = "pnpm --prefix " + path + "\\front" + " run build";
        System.out.println(exec);
        String s = RuntimeUtil.execForStr(exec);
```

2. 堆栈信息
Exception in thread "main" cn.hutool.core.io.IORuntimeException: IOException: Cannot run program "pnpm": CreateProcess error=2, 系统找不到指定的文件。
	at cn.hutool.core.util.RuntimeUtil.exec(RuntimeUtil.java:86)
	at cn.hutool.core.util.RuntimeUtil.execForStr(RuntimeUtil.java:47)
	at cn.hutool.core.util.RuntimeUtil.execForStr(RuntimeUtil.java:34)
	at com.duzj.foodserver.FrontPackage.main(FrontPackage.java:17)
Caused by: java.io.IOException: Cannot run program "pnpm": CreateProcess error=2, 系统找不到指定的文件。
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at cn.hutool.core.util.RuntimeUtil.exec(RuntimeUtil.java:84)
	... 3 more
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 5 more

实际执行命令: pnpm --prefix E:\work\food-server\front run build
![image](https://github.com/dromara/hutool/assets/85781434/e7baa0fe-82ba-43de-90c2-02315708ea9a)

**Comment by looly** [comment]
因为在执行命令的时候没有获取系统环境变量，找不到pnmp的路径，两个办法：

1. 使用全路径
2. 使用`sh -c`

具体请自行搜索
