### ISSUE TITLE
cn.hutool.http.HttpException: Unexpected end of file from server

### ISSUE THREAD

**Issue by yangyang122** [looly/hutool#3647]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.25（请确保最新尝试是否还有问题）

post请求，偶现这个错误，调用示例：
HttpRequest httpRequest = new HttpRequest()
logger.info("request url:{},method:{}",httpRequest.getUrl(),httpRequest.getMethod());
HttpResponse httpResponse = httpRequest.execute();
String body = httpResponse.body();

```java
cn.hutool.http.HttpException: Unexpected end of file from server
        at cn.hutool.http.HttpResponse.init(HttpResponse.java:531)
        at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:504)
        at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:82)
        at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1195)
        at cn.hutool.http.HttpRequest.execute$original$yfpwKJOq(HttpRequest.java:1051)
        at cn.hutool.http.HttpRequest.execute$original$yfpwKJOq$accessor$xl1qSrtk(HttpRequest.java)
        at cn.hutool.http.HttpRequest$auxiliary$XwyZlb4o.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1027)
```
偶现的问题，项目中其他模块也用到HttpUtil, 但是单独了超时时间，比较长2分多，这个模块也用到了，是否之间有干扰?

**Comment by looly** [comment]
可能的原因：

请求成功了，但是读取响应的时候，服务端突然断开了连接，导致无法读取剩余响应内容，这个可以理解为无效请求或请求失败。
