### ISSUE TITLE
在Windows环境获取指定层级的父路径错误`FileUtil.getParent`

### ISSUE THREAD

**Issue by BruceMaa** [looly/hutool#3676]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.29

### 问题描述（包括截图）

背景：
在`Windows`环境运行服务，上传文件到`SFTP`服务。`SFTP`上没有对应路径，需要先创建。
创建路径后，上传文件失败。

1. 复现代码

```java
    /**
     * 上传文件到SFTP
     *
     * @param ftpConfig SFTP配置信息
     * @param destPath  目标目录
     * @param fileName  文件名称
     * @param tempFile  文件
     * @return 是否上传成功
     */
    public static synchronized boolean uploadSftpFile(FtpConfig ftpConfig, String destPath, String fileName, File tempFile) {
        try (Sftp sftp = new Sftp(ftpConfig)) {
            String fileFullName = StrUtil.addSuffixIfNot(destPath, StrUtil.SLASH) + StrUtil.removePrefix(fileName, StrUtil.SLASH);
            String fullPath = FileUtil.getParent(fileFullName, 1);
            if (!sftp.exist(fullPath)) {
                sftp.mkDirs(fullPath);
            }
            return sftp.upload(fileFullName, tempFile);
        }
    }
```

2. 堆栈信息

```
cn.hutool.extra.ssh.JschRuntimeException: SftpException: No such file
	at cn.hutool.extra.ssh.Sftp.put(Sftp.java:567)
	at cn.hutool.extra.ssh.Sftp.put(Sftp.java:550)
	at cn.hutool.extra.ssh.Sftp.put(Sftp.java:538)
	at cn.hutool.extra.ssh.Sftp.upload(Sftp.java:505)
```

3. debug后发现问题在于获取文件父路径方法 `FileUtil.getParent`，示例代码如下

```
String fileFullName = "/Uploads/20240601/aaaa.txt";
String parent = FileUtil.getParent(fileFullName, 1);
System.out.println("parent = " + parent);
```

打印信息为
```
parent = D:\Uploads\20240601
```

**Comment by looly** [comment]
FileUtil依赖于本地文件系统获取父路径，因此传入FTP中的路径是不可取的。

严格来说，FTP中的路径是URI路径，可以使用：

```java
String fileFullName = "/Uploads/20240601/aaaa.txt";
final URI uri = URLUtil.toURI(fileFullName);
// /Uploads/20240601/
final URI resolve = uri.resolve(".");
```
