### ISSUE TITLE
cron 错误 栈溢出

### ISSUE THREAD

**Issue by Colory** [looly/hutool#3685]
### 版本情况

JDK版本：    corretto-17.0.11
hutool版本： 5.8.29（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
CronPatternUtil.nextDateAfter(CronPattern.of(“0 0 * * MON”), new Date(), true);
```

2. 堆栈信息
```
Caused by: java.lang.StackOverflowError: null
	at java.base/sun.util.calendar.ZoneInfo.getOffsets(ZoneInfo.java:228)
	at java.base/java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2301)
	at java.base/java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2779)
	at java.base/java.util.Calendar.updateTime(Calendar.java:3411)
	at java.base/java.util.Calendar.complete(Calendar.java:2279)
	at java.base/java.util.Calendar.get(Calendar.java:1849)
	at cn.hutool.cron.pattern.PatternUtil.getFields(PatternUtil.java:46)
	at cn.hutool.cron.pattern.CronPattern.match(CronPattern.java:130)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:153)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
	at cn.hutool.cron.pattern.CronPattern.nextMatchAfter(CronPattern.java:163)
```

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
确认bug

5.8.30修复此问题，感谢~~

修复见：https://github.com/dromara/hutool/commit/4c00f6adb22a005cfa958c4d3c4e55ef70ec5f75
