### ISSUE TITLE
LRU Cache  并发get

### ISSUE THREAD

**Issue by 1471246901** [looly/hutool#3686]
hutool 版本 5.8.29  
 zulu-17

复现代码 不稳定复现,需要多次测试
```java
public static void main(String[] args) {


		LRUCache<Long, Integer> objects = CacheUtil.newLRUCache(20, TimeUnit.SECONDS.toMillis(30));
		List<Thread> list = new ArrayList<>();
		for (int i = 0; i < 10; i++) {
			Thread thread = new Thread(() -> {
				while (true) {
					for (int i1 = 0; i1 < 100; i1++) {
						int finalI = i1;
						objects.get((long) i1, () -> finalI);
					}
					ThreadUtil.sleep(500);
				}
			});
			list.add(thread);
		}
		for (Thread thread : list) {
			thread.start();
		}
	}
```

堆栈异常
Exception in thread "Thread-6" java.util.ConcurrentModificationException
线程“Thread-6”中的异常 java.util.ConcurrentModificationException
at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
在 java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
在 java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
at cn.hutool.cache.impl.LRUCache.pruneCache(LRUCache.java:69)
在 cn.hutool.cache.impl.LRUCache.pruneCache(LRUCache.java:69)
at cn.hutool.cache.impl.AbstractCache.putWithoutLock(AbstractCache.java:97)
在 cn.hutool.cache.impl.AbstractCache.putWithoutLock(AbstractCache.java:97)
at cn.hutool.cache.impl.ReentrantCache.put(ReentrantCache.java:28)
在 cn.hutool.cache.impl.ReentrantCache.put(ReentrantCache.java:28)
at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:142)
在 cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:142)
at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:121)
在 cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:121)
at cn.hutool.cache.Cache.get(Cache.java:78)
在 cn.hutool.cache.Cache.get(Cache.java:78)

好像是AbstractCache 中的 133 行 getWithoutLock 引起的, linkedHashMap  get 内部会对链表有操作, 应该是需要加一下锁

**Comment by looly** [comment]
感谢，已复现问题。

问题出在List的读写没有使用同一把锁。导致的并发问题。

5.8.30修复此问题~~
