### ISSUE TITLE
JSONUtil.toBean字符串转日期会报错

### ISSUE THREAD

**Issue by duxingxia081** [looly/hutool#3695]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.22

### 问题描述（包括截图）

1. 复现代码

```java
import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class DTO{

    @JsonFormat(pattern = "yyyy", timezone = "GMT+8")
    private Date reviewYear;
    public Date getReviewYear() {
        return this.reviewYear;
    }
    public void setReviewYear(Date reviewYear) {
        this.reviewYear = reviewYear;
    }
}

public class TestMain {
    public static void main(String[]args){
        try {
            DTO dt0 = JSONUtil.toBean("{\"reviewYear\":\"2024\"}",DTO.class);
            System.out.println(dt0.getReviewYear());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

2. 堆栈信息
cn.hutool.core.date.DateException: No format fit for date String [2024] !
	at cn.hutool.core.date.DateUtil.parse(DateUtil.java:1027)
	at cn.hutool.core.convert.impl.DateConverter.convertInternal(DateConverter.java:80)
	at cn.hutool.core.convert.impl.DateConverter.convertInternal(DateConverter.java:18)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:222)
	at cn.hutool.core.convert.ConverterRegistry.convert(ConverterRegistry.java:262)
	at cn.hutool.core.convert.Convert.convertWithCheck(Convert.java:753)
	at cn.hutool.core.bean.copier.CopyOptions.lambda$new$0(CopyOptions.java:90)
	at cn.hutool.core.bean.copier.CopyOptions.convertField(CopyOptions.java:347)
	at cn.hutool.core.bean.copier.MapToBeanCopier.lambda$copy$0(MapToBeanCopier.java:91)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at cn.hutool.core.map.MapWrapper.forEach(MapWrapper.java:160)
	at cn.hutool.core.bean.copier.MapToBeanCopier.copy(MapToBeanCopier.java:60)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:92)
	at cn.hutool.core.convert.impl.BeanConverter.convertInternal(BeanConverter.java:90)
	at cn.hutool.core.convert.AbstractConverter.convert(AbstractConverter.java:58)
	at cn.hutool.core.convert.Converter.convertWithCheck(Converter.java:35)
	at cn.hutool.json.JSONConverter.jsonToBean(JSONConverter.java:134)
	at cn.hutool.json.JSONConverter.jsonConvert(JSONConverter.java:96)
	at cn.hutool.json.JSON.toBean(JSON.java:179)
	at cn.hutool.json.JSON.toBean(JSON.java:155)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:447)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:420)
	at com.jf.TestMain.main(TestMain.java:9)

**Comment by looly** [comment]
Hutool的json不支持Jackson的注解。

考虑使用JSONConfig.setDateFormat.

但是解析并不支持，这个在6.x完整支持。
