### ISSUE TITLE
No such algorithm: SM4

### ISSUE THREAD

**Issue by LuciusChen** [looly/hutool#3711]
### 版本情况

JDK版本：    openjdk_8_301（本地无问题）/jdk1.8.0_192（测试服务器找不到 SM4算法）
hutool版本： 5.2.26（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
 SymmetricCrypto sm4 = SmUtil.sm4(SystemConfig.SM4_PRIVATE_KEY.getBytes());
```

2. 堆栈信息

```
2024-08-29 17:47:25,295 ERROR [com.sinocjh.batchjob.aop.LogAdvice] - cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: No such algorithm: SM4
2024-08-29 17:47:25,296 ERROR [org.quartz.core.JobRunShell] - Job DEFAULT.HazMatJob threw an unhandled Exception: 
cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: No such algorithm: SM4
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1037)
	at cn.hutool.crypto.CipherWrapper.<init>(CipherWrapper.java:39)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:150)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:127)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:115)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:104)
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:45)
	at cn.hutool.crypto.SmUtil.sm4(SmUtil.java:205)
	at com.sinocjh.batchjob.quartz.hazMatExample.service.impl.HazMatServiceImpl.insertProvincialDangerous(HazMatServiceImpl.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:42)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy3593.insertProvincialDangerous(Unknown Source)
	at com.sinocjh.batchjob.quartz.job.HazMatJob.execute(HazMatJob.java:39)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
Caused by: java.security.NoSuchAlgorithmException: No such algorithm: SM4
	at javax.crypto.Cipher.getInstance(Cipher.java:687)
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1035)
	... 28 more
Caused by: java.security.NoSuchAlgorithmException: class configured for Cipher (provider: BC) cannot be found.
	at java.security.Provider$Service.getImplClass(Provider.java:1649)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at javax.crypto.Cipher.getInstance(Cipher.java:668)
	... 29 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jcajce.provider.symmetric.SM4$ECB
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1858)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1709)
	at java.security.Provider$Service.getImplClass(Provider.java:1636)
	... 31 more
2024-08-29 17:47:25,301 DEBUG [org.quartz.utils.ExceptionHelper] - Detected JDK support for nested exceptions.
2024-08-29 17:47:25,302 ERROR [org.quartz.core.ErrorLogger] - Job (DEFAULT.HazMatJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: No such algorithm: SM4]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
Caused by: cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: No such algorithm: SM4
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1037)
	at cn.hutool.crypto.CipherWrapper.<init>(CipherWrapper.java:39)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:150)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:127)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:115)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:104)
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:45)
	at cn.hutool.crypto.SmUtil.sm4(SmUtil.java:205)
	at com.sinocjh.batchjob.quartz.hazMatExample.service.impl.HazMatServiceImpl.insertProvincialDangerous(HazMatServiceImpl.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:42)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy3593.insertProvincialDangerous(Unknown Source)
	at com.sinocjh.batchjob.quartz.job.HazMatJob.execute(HazMatJob.java:39)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: java.security.NoSuchAlgorithmException: No such algorithm: SM4
	at javax.crypto.Cipher.getInstance(Cipher.java:687)
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1035)
	... 28 more
Caused by: java.security.NoSuchAlgorithmException: class configured for Cipher (provider: BC) cannot be found.
	at java.security.Provider$Service.getImplClass(Provider.java:1649)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at javax.crypto.Cipher.getInstance(Cipher.java:668)
	... 29 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jcajce.provider.symmetric.SM4$ECB
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1858)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1709)
	at java.security.Provider$Service.getImplClass(Provider.java:1636)
	... 31 more
```

**Comment by looly** [comment]
升级你的BC库吧~~

见：https://doc.hutool.cn/pages/SmUtil/#%E5%BC%95%E5%85%A5bouncy-castle%E4%BE%9D%E8%B5%96

**Comment by LuciusChen** [comment]
> 升级你的 BC 库吧～～
> 
> 见：https://doc.hutool.cn/pages/SmUtil/#%E5%BC%95%E5%85%A5bouncy-castle%E4%BE%9D%E8%B5%96

升级到了最新，本地是没有问题的，到了测试服务器就报这个错误。

**Comment by LuciusChen** [comment]
服务器 lib 下面 jar 都有，就是找不到。。。

**Comment by looly** [comment]
@LuciusChen 看下版本是不太低了。

**Comment by LuciusChen** [comment]
> @LuciusChen 看下版本是不太低了。

```
<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpkix-jdk18on</artifactId>
			<version>1.78.1</version>
		</dependency>
		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-all</artifactId>
			<version>5.8.26</version>
		</dependency>
```
本地哪怕低版本都可以，就是到了测试服务器不行，不知道该如何定位了。

**Comment by looly** [comment]
@LuciusChen 那忙猜你服务端可能引入了多个版本BC库，或者lib并不在classpath中。

**Comment by LuciusChen** [comment]
> @LuciusChen 那忙猜你服务端可能引入了多个版本 BC 库，或者 lib 并不在 classpath 中。

<img width="418" alt="image" src="https://github.com/user-attachments/assets/db2591ba-e011-41fe-b717-6838416b847d">
服务器看了下，和本地一致，相关的 bc库就这三个，其他的包正常工作，就 bc 不行，感谢，我再找找原因。
