### ISSUE TITLE
请教下怎么重写响应体？

### ISSUE THREAD

**Issue by Mr-LiuDC** [looly/hutool#3723]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.28

### 问题描述
我想通过HttpFilter实现重写JSON响应体，折腾了很久没能实现，如下方式提示 `headers already sent`

1. 复现代码

```java
package org.example.filter;

import cn.hutool.core.util.IdUtil;
import cn.hutool.core.util.StrUtil;
import cn.hutool.http.ContentType;
import cn.hutool.http.server.HttpExchangeWrapper;
import cn.hutool.http.server.HttpServerRequest;
import cn.hutool.http.server.HttpServerResponse;
import cn.hutool.http.server.filter.HttpFilter;
import cn.hutool.json.JSONUtil;
import cn.hutool.log.Log;
import com.sun.net.httpserver.Filter;
import org.example.common.base.BaseResponse;
import org.slf4j.MDC;

import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

import static cn.hutool.http.Header.CONTENT_TYPE;
import static cn.hutool.http.HttpStatus.HTTP_INTERNAL_ERROR;

/**
 * @author LDC
 */
public class TraceIdFilter implements HttpFilter {

    private static final Log log = Log.get();

    @Override
    public void doFilter(HttpServerRequest req, HttpServerResponse res, Filter.Chain chain) {
        try {
            String requestId = IdUtil.fastSimpleUUID();
            MDC.put("requestId", requestId);
            req.getHttpExchange().setAttribute("requestId", requestId);
            req.getHttpExchange().getResponseHeaders().add("X-Request-Id", requestId);

            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            HttpExchangeWrapper httpExchangeWrapper = new HttpExchangeWrapper(req.getHttpExchange()) {
                @Override
                public OutputStream getResponseBody() {
                    return byteArrayOutputStream;
                }
            };
            chain.doFilter(httpExchangeWrapper);

            String contentType = res.getHeaders().getFirst(CONTENT_TYPE.getValue());
            if (StrUtil.isNotBlank(contentType) && contentType.startsWith("application/json")) {
                String originalBody = byteArrayOutputStream.toString(StandardCharsets.UTF_8.name());
                BaseResponse<?> baseResponse = JSONUtil.toBean(originalBody, BaseResponse.class);
                baseResponse.setRequestId(requestId);
                String modifiedBody = JSONUtil.toJsonStr(baseResponse);
                res.write(modifiedBody, ContentType.JSON.getValue()).send(baseResponse.getCode());
            }
        } catch (final Throwable e) {
            afterException(req, res, e);
        } finally {
            MDC.remove("requestId");
        }
    }

    /**
     * 异常之后的处理逻辑
     *
     * @param req {@link HttpServerRequest}
     * @param res {@link HttpServerResponse}
     * @param e   异常
     */
    public void afterException(final HttpServerRequest req, final HttpServerResponse res, final Throwable e) {
        String requestId = req.getHttpExchange().getAttribute("requestId").toString();
        BaseResponse<Object> result = BaseResponse.of(HTTP_INTERNAL_ERROR, e.getMessage(), null);
        result.setRequestId(requestId);
        log.error(e, "Exception occurred when processing request from {} to {}", req.getClientIP(), req.getPath());
        res.write(JSONUtil.toJsonStr(result), ContentType.JSON.getValue()).send(result.getCode());
    }
}

```

2. 堆栈信息
```
cn.hutool.core.io.IORuntimeException: IOException: headers already sent
	at cn.hutool.http.server.HttpServerResponse.send(HttpServerResponse.java:116) ~[hutool-all-5.8.28.jar:5.8.28]
	at cn.hutool.http.server.HttpServerResponse.sendOk(HttpServerResponse.java:75) ~[hutool-all-5.8.28.jar:5.8.28]
	at cn.hutool.http.server.HttpServerResponse.write(HttpServerResponse.java:353) ~[hutool-all-5.8.28.jar:5.8.28]
	at cn.hutool.http.server.HttpServerResponse.write(HttpServerResponse.java:305) ~[hutool-all-5.8.28.jar:5.8.28]
	at cn.hutool.http.server.HttpServerResponse.write(HttpServerResponse.java:282) ~[hutool-all-5.8.28.jar:5.8.28]
	at cn.hutool.http.server.HttpServerResponse.write(HttpServerResponse.java:271) ~[hutool-all-5.8.28.jar:5.8.28]
	at org.example.filter.TraceIdFilter.doFilter(TraceIdFilter.java:55) [classes/:?]
	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:130) [hutool-all-5.8.28.jar:5.8.28]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82) [?:1.8.0_351]
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:802) [?:1.8.0_351]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_351]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_351]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_351]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
Caused by: java.io.IOException: headers already sent
	at sun.net.httpserver.ExchangeImpl.sendResponseHeaders(ExchangeImpl.java:206) ~[?:1.8.0_351]
	at sun.net.httpserver.HttpExchangeImpl.sendResponseHeaders(HttpExchangeImpl.java:86) ~[?:1.8.0_351]
	at cn.hutool.http.server.HttpExchangeWrapper.sendResponseHeaders(HttpExchangeWrapper.java:105) ~[hutool-all-5.8.28.jar:5.8.28]
	at cn.hutool.http.server.HttpServerResponse.send(HttpServerResponse.java:114) ~[hutool-all-5.8.28.jar:5.8.28]
	... 17 more
```

**Comment by looly** [comment]
`chain.doFilter(httpExchangeWrapper);`这个应该在最后调用吧。

```java
public class Issue3723Test {
	public static void main(String[] args) {
		SimpleServer server = HttpUtil.createServer(8888);
		server.addFilter((req, res, chain) -> {
			String requestId = IdUtil.fastSimpleUUID();
			req.getHttpExchange().setAttribute("requestId", requestId);
			res.addHeader("X-Request-Id", requestId);

			res.write("new Content");

			chain.doFilter(req.getHttpExchange());
		});
		server.addAction("/", (req, res)-> res.write("Hello Hutool Server", ContentType.JSON.getValue()));
		server.start();
	}
}
```

**Comment by Mr-LiuDC** [comment]
> `chain.doFilter(httpExchangeWrapper);`这个应该在最后调用吧。
> 
> ```java
> public class Issue3723Test {
> 	public static void main(String[] args) {
> 		SimpleServer server = HttpUtil.createServer(8888);
> 		server.addFilter((req, res, chain) -> {
> 			String requestId = IdUtil.fastSimpleUUID();
> 			req.getHttpExchange().setAttribute("requestId", requestId);
> 			res.addHeader("X-Request-Id", requestId);
> 
> 			res.write("new Content");
> 
> 			chain.doFilter(req.getHttpExchange());
> 		});
> 		server.addAction("/", (req, res)-> res.write("Hello Hutool Server", ContentType.JSON.getValue()));
> 		server.start();
> 	}
> }
> ```

你这种比较简单可以修改后再doFilter，我的场景是要先根据Action的响应内容判断作何逻辑，要先 doFilter 后才能取到 Action 的响应内容。

**Comment by looly** [comment]
@Mr-LiuDC 那就不行了，doFilter貌似执行后就写出到客户端了，就没法修改了。
