### ISSUE TITLE
JWTSignerUtil.createSigner 不支持传入hutool所定义算法Id

### ISSUE THREAD

**Issue by BingChunMoLi** [looly/hutool#3733]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.32（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

涉及文档：https://doc.hutool.cn/pages/JWTSignerUtil/
如下两行代码行为不一致, 文档中未强调Id与算法实际名称的区分度并代码没有做一定的兼容
期望行为: 文档中清晰指明ID与算法名称的区别与用途，例如ID只是枚举的快捷别名。
或者 generateKeyPair 方法内自行调用AlgorithmUtil.getAlgorithm(algorithmId)以提供更好的兼容性

1. 复现代码
```java
   JWTSignerUtil.createSigner("RS256", KeyUtil.generateKeyPair(AlgorithmUtil.getAlgorithm("RS256"), 2048));
   JWTSignerUtil.createSigner("RS256", KeyUtil.generateKeyPair("RS256", 2048));
```
2. 堆栈信息
```java
Exception in thread "main" cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: RS256 KeyPairGenerator not available
	at cn.hutool.crypto.KeyUtil.getKeyPairGenerator(KeyUtil.java:534)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:482)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:447)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:386)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:367)
Caused by: java.security.NoSuchAlgorithmException: RS256 KeyPairGenerator not available
	at java.base/java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:236)
	at cn.hutool.crypto.KeyUtil.getKeyPairGenerator(KeyUtil.java:531)
	... 5 more
```

**Comment by looly** [comment]
JWT和crypto属于不同模块。

JWT中定义的算法简写和crypto中定义不相同，因此不能通用，也没做兼容。

后续将在文档中做标注，感谢。
