### ISSUE TITLE
不兼容bcprov-jdk15to18的1.79版本的ECIES

### ISSUE THREAD

**Issue by bai-xuan** [looly/hutool#3793]
### 版本情况

JDK版本：  openjdk  jdk-17.0.12+7
hutool版本： hutool-all-5.8.33.jar（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
最新版hutool使用bcprov-jdk15to18的1.66版本可以运行，但是无法在bcprov-jdk15to18的1.79运行
![image](https://github.com/user-attachments/assets/08c25424-30a2-40d1-8775-24097deaae20)

1. 复现代码
![image](https://github.com/user-attachments/assets/0ce44406-b5c4-4e93-a4d3-1d52c4bff24f)

```java
    public static void main(String[] args) {
        final ECIES ecies = new ECIES();
        String privateKeyBase64 = ecies.getPrivateKeyBase64();
        String publicKeyBase64 = ecies.getPublicKeyBase64();
        System.out.println(privateKeyBase64);
        System.out.println(publicKeyBase64);
        String textBase = "我是一段特别长的测试";
        StringBuilder text = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            text.append(textBase);
        }

        // 公钥加密，私钥解密
        String encryptStr = ecies.encryptBase64(text.toString(), KeyType.PublicKey);
        System.out.println(encryptStr);
        String decryptStr = StrUtil.utf8Str(ecies.decrypt(encryptStr, KeyType.PrivateKey));

        System.out.println(decryptStr);
    }
```

3. 堆栈信息

![image](https://github.com/user-attachments/assets/3965e217-3644-4212-b1d5-8c74164efa4c)
Exception in thread "main" cn.hutool.crypto.CryptoException: IllegalArgumentException: cannot handle supplied parameter spec: must be passed IES parameters
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.encrypt(AsymmetricCrypto.java:277)
	at cn.hutool.crypto.asymmetric.AsymmetricEncryptor.encrypt(AsymmetricEncryptor.java:92)
	at cn.hutool.crypto.asymmetric.AsymmetricEncryptor.encryptBase64(AsymmetricEncryptor.java:129)
	at org.example.TestECIES.main(TestECIES.java:28)
Caused by: java.lang.IllegalArgumentException: cannot handle supplied parameter spec: must be passed IES parameters
	at org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher.engineInit(Unknown Source)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1296)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1236)
	at cn.hutool.crypto.CipherWrapper.initMode(CipherWrapper.java:116)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.initMode(AsymmetricCrypto.java:392)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.encrypt(AsymmetricCrypto.java:265)
	... 3 more

4.提供问题参考解决办法
https://runnable.run/docs/backend/Java/fix-issues/yi-jie-jue-cannothandlesuppliedparameterspecmustbepassediesparameters/

**Comment by looly** [comment]
这块文档滞后了，新版本的BC库中，这么使用：

```java
ECIES ecies = new ECIES();
IESParameterSpec iesParameterSpec = new IESParameterSpec(null, null, 128);
ecies.setAlgorithmParameterSpec(iesParameterSpec);

....
```

后续我修改文档，感谢。
