### ISSUE TITLE
编译JS脚本出错

### ISSUE THREAD

**Issue by whyneh** [looly/hutool#3804]
### 版本情况

JDK版本：    openjdk_1.8.0_431
hutool版本：5.8.33

### 问题描述（包括截图）

我是用ScriptUtil编译JS脚本的时候出现了这个错误，报错信息指向这个computeIfAbsentForJdk8方法，排查半天不清楚什么原因导致的
![微信截图_20241202165303](https://github.com/user-attachments/assets/980416d5-b2f4-4e83-a913-3e75d9f65ffe)

1. 复现代码

`    public static void main(String[] args) {
        CompiledScript script = ScriptUtil.compile("print('Script test!');");
        try {
            script.eval();
        } catch (ScriptException e) {
            throw new ScriptRuntimeException(e);
        }
    }
`

2. 堆栈信息
Exception in thread "main" java.lang.NoSuchMethodError: cn.hutool.core.map.MapUtil.computeIfAbsentForJdk8(Ljava/util/Map;Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object;
	at cn.hutool.core.map.SafeConcurrentHashMap.computeIfAbsent(SafeConcurrentHashMap.java:75)
	at cn.hutool.core.map.ReferenceConcurrentMap.computeIfAbsent(ReferenceConcurrentMap.java:137)
	at cn.hutool.core.map.ReferenceConcurrentMap.computeIfAbsent(ReferenceConcurrentMap.java:154)
	at cn.hutool.script.ScriptUtil.getScript(ScriptUtil.java:32)
	at cn.hutool.script.ScriptUtil.getJsEngine(ScriptUtil.java:72)
	at cn.hutool.script.ScriptUtil.compile(ScriptUtil.java:260)
        at com.yw.test.core.tools.FillingUtil.main(FillingUtil.java:40)

**Comment by looly** [comment]
方法找不到，可能是包冲突了。

检查是否引入多个版本了。
