### ISSUE TITLE
DateUtil解析问题

### ISSUE THREAD

**Issue by 89333367** [looly/hutool#385]
我有一个英文格式的日期字符串信息
```
Tue Jun 4 16:25:15 +0800 2019
```
通过hutool工具类解析出错
```
 @Test
    public void t2() {
        String str = "Tue Jun 4 16:25:15 +0800 2019";
        DateUtil.parse(str, "yyyy-MM-dd HH:mm:ss E Z");
    }
```
```
cn.hutool.core.date.DateException: Parse [Tue Jun 4 16:25:15 +0800 2019] with format [yyyy-MM-dd HH:mm:ss E Z] error!

	at cn.hutool.core.date.DateTime.parse(DateTime.java:885)
	at cn.hutool.core.date.DateTime.<init>(DateTime.java:169)
	at cn.hutool.core.date.DateTime.<init>(DateTime.java:158)
	at cn.hutool.core.date.DateUtil.parse(DateUtil.java:622)
	at sunyu.demo.integration.bigdata.admin.Tests.t2(Tests.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.text.ParseException: Unparseable date: "Tue Jun 4 16:25:15 +0800 2019"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at cn.hutool.core.date.DateTime.parse(DateTime.java:877)
	... 26 more
```

后来发现，解析英文格式需要Locale.ENGLISH信息，我没有在DateUtil工具类里面找到类似参数。
现在解析方式如下：注意这里有第二个参数  Locale.ENGLISH
```
@Test
    public void t1() throws ParseException {
        String str = "Tue Jun 4 16:25:15 +0800 2019";
        SimpleDateFormat format = new SimpleDateFormat("EEE MMM dd hh:mm:ss Z yyyy", Locale.ENGLISH);
        Date dateTrans = format.parse(str);
        String s = DateUtil.format(dateTrans, "yyyy-MM-dd HH:mm:ss E Z");
        System.out.println(s);
    }
```

请大神，将英文格式的解析方式，添加到DateUtil中吧。毕竟英文格式的日期是标准格式，应该在parse方法中存在

**Comment by looly** [comment]
可以这么用：
```
String str = "Tue Jun 4 16:25:15 +0800 2019";
DateTime dateTime = DateUtil.parse(str, DatePattern.JDK_DATETIME_FORMAT);
Console.log(dateTime);
```

**Comment by looly** [comment]
4.5.12增加直接parse支持

**Comment by songxiaoxiao** [comment]
DateUtil.解析格式"2024-01-第1周", "yyyy-MM-第W周" 报错格式错误。第二周后就好了。这是对iso标准时间解析有误。请修复

**Comment by looly** [comment]
@songxiaoxiao 这种特殊格式无法自动解析，你需要传入自定义的format
