### ISSUE TITLE
Setting store() 并发修改异常

### ISSUE THREAD

**Issue by Bophie** [looly/hutool#399]
Setting实例，在开启autoLoad(true)自动加载的情况下，调用store()保存，有可能会引起并发异常：
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at cn.hutool.setting.SettingLoader.store(SettingLoader.java:181)
	at cn.hutool.setting.SettingLoader.store(SettingLoader.java:166)
	at cn.hutool.setting.Setting.store(Setting.java:319)

建议内部对加载和保存的方法加锁

**Comment by looly** [comment]
4.5.13修复此问题，感谢。
