### ISSUE TITLE
生成图形验证码报空指针异常

### ISSUE THREAD

**Issue by ObamaX** [looly/hutool#420]
版本：4.5.16
CaptchaUtil.createShearCaptcha(200, 100, 4, 4);
创建图形验证码时报空指针异常：
java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.access$000(Font.java:224)
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
	at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:670)
	at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:831)
	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:50)
	at sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2926)
	at cn.hutool.core.img.GraphicsUtil.drawString(GraphicsUtil.java:111)
	at cn.hutool.core.img.GraphicsUtil.drawStringColourful(GraphicsUtil.java:71)
	at cn.hutool.captcha.ShearCaptcha.drawString(ShearCaptcha.java:81)
	at cn.hutool.captcha.ShearCaptcha.createImage(ShearCaptcha.java:63)
	at cn.hutool.captcha.AbstractCaptcha.createCode(AbstractCaptcha.java:84)
	at cn.hutool.captcha.AbstractCaptcha.<init>(AbstractCaptcha.java:76)
	at cn.hutool.captcha.AbstractCaptcha.<init>(AbstractCaptcha.java:58)
	at cn.hutool.captcha.ShearCaptcha.<init>(ShearCaptcha.java:54)
	at cn.hutool.captcha.CaptchaUtil.createShearCaptcha(CaptchaUtil.java:84)

**Comment by ObamaX** [comment]
在本地windows环境不会报错，在docker容器里的应用服务，生成验证码的时候报错怎么解决？

**Comment by looly** [comment]
默认字体不存在造成的。群里应该回复了。我记得你的做法是导入字体。

**Comment by looly** [comment]
```
yum install fontconfig
fc-cache --force
```

见这篇文章：

https://blog.csdn.net/crystonesc/article/details/86305466

**Comment by AlawnCN** [comment]
合理的做法应该是可以选择字体才对吧

**Comment by looly** [comment]
可以选择字体，有setFont方法。

**Comment by vnobo** [comment]
> 可以选择字体，有setFont方法。

我设置了字体,验证码不出来了

**Comment by looly** [comment]
看下系统有哪些字体，然后选择合适字体。
