### ISSUE TITLE
throw  java.nio.file.ClosedWatchServiceException when WatchMonitor closed

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#427]
JDK10.0.2

测试代码:

```
	WatchMonitor watchMonitor = WatchUtil.createModify("D:\\xxx", new SimpleWatcher() {

		@Override
		public void onModify(WatchEvent<?> event, Path currentPath) {
			Console.log(currentPath);
		}
	});
	watchMonitor.start();

	ThreadUtil.sleep(2000);
		
	watchMonitor.close();
```

关闭之后出现ClosedWatchServiceException,

```

Exception in thread "Thread-0" java.nio.file.ClosedWatchServiceException
	at java.base/sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80)
	at java.base/sun.nio.fs.AbstractWatchService.checkKey(AbstractWatchService.java:92)
	at java.base/sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:119)
	at cn.hutool.core.io.watch.WatchMonitor.watch(WatchMonitor.java:379)
	at cn.hutool.core.io.watch.WatchMonitor.watch(WatchMonitor.java:361)
	at cn.hutool.core.io.watch.WatchMonitor.run(WatchMonitor.java:354)
```

是不是在这个地方catch ClosedWatchServiceException更好
> cn.hutool.core.io.watch.WatchMonitor.watch(Watcher)

![12222](https://user-images.githubusercontent.com/18179821/61171650-10207a80-a5ad-11e9-9361-7a264c329436.jpg)

**Comment by looly** [comment]
4.5.17增加catch，感谢。
