### ISSUE TITLE
get the last empty collection causes [java.lang.IndexOutOfBoundsException]

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#436]
4.5.17

测试代码
```

List<String> test = CollUtil.newArrayList();
System.out.println(CollUtil.getLast(test));
```

应该是返回null,而不是抛出IndexOutOfBoundsException
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -1 out-of-bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at cn.hutool.core.collection.CollUtil.get(CollUtil.java:1872)
	at cn.hutool.core.collection.CollUtil.getLast(CollUtil.java:1955)
```

**Comment by looly** [comment]
4.5.18修复此问题，十分感谢。
