### ISSUE TITLE
HttpUtil发起http请求时报错Unexpected end of file from server

### ISSUE THREAD

**Issue by VanMesure** [looly/hutool#444]
http://img01.fs.yiban.cn/mobile/2D0Y71 这个链接，使用浏览器、postman、okhttp框架都是可以正常请求到的。

` String url = "http://img01.fs.yiban.cn/mobile/2D0Y71";

        HttpRequest request = new HttpRequest(url);

        request.header("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,image/jpeg,*/*;q=0.8");

        request.header("Accept-Encoding", "gzip, deflate");

        request.header("Accept-Language", "zh-CN,zh;q=0.9");

        request.header("Host", "img01.fs.yiban.cn");

        request.header("Upgrade-Insecure-Requests", "1");

        request.header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3704.400 QQBrowser/10.4.3587.400");

        request.execute();`

错误信息如下：

`Exception in thread "main" cn.hutool.http.HttpException: Unexpected end of file from server
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:338)
	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:64)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:882)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:845)
	at Entry.main(Entry.java:19)
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:448)
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:325)
	... 4 more`

**Comment by looly** [comment]
由于在get请求中错误的请求头设置导致的。4.6.0修复此问题，如果着急用，请clone v4-dev分支代码，编译使用。

十分感谢。

**Comment by qq253498229** [comment]
我也遇到这个问题了，可版本是5.8.9啊

**Comment by looly** [comment]
@qq253498229 请求的地址公开么？

**Comment by zeasly** [comment]
我5.5.7也有这个问题
`
14:07:07.725 [http-nio-8080-exec-3] ERROR c.s.c.c.RequestController - [loansQuery,92] - 2.2.7.借款结果查询接口  try errorUnexpected end of file from server
cn.hutool.http.HttpException: Unexpected end of file from server
        at cn.hutool.http.HttpResponse.init(HttpResponse.java:406)
        at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:379)
        at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:76)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:976)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
        at com.spman.cmpay.util.credit.CreditHttpUtils.doRequest(CreditHttpUtils.java:73)
        at com.spman.cmpay.util.credit.CreditHttpUtils.requestWithVerify(CreditHttpUtils.java:44)
        at com.spman.cmpay.util.credit.CreditHttpUtils.request(CreditHttpUtils.java:35)
        at com.spman.cmpay.service.impl.CmpayRequestServiceImpl.requestCreditCmapy(CmpayRequestServiceImpl.java:127)
        at com.spman.cmpay.service.impl.CmpayRequestServiceImpl$$FastClassBySpringCGLIB$$36dcd91d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at com.spman.cmpay.service.impl.CmpayRequestServiceImpl$$EnhancerBySpringCGLIB$$b5d7463a.requestCreditCmapy(<generated>)
        at com.spman.cmpay.service.impl.CreditCmpayServiceImpl.getSignUrl(CreditCmpayServiceImpl.java:118)
        at com.spman.cmpay.service.impl.CreditCmpayServiceImpl$$FastClassBySpringCGLIB$$1900bd77.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.spman.cmpay.service.impl.CreditCmpayServiceImpl$$EnhancerBySpringCGLIB$$b47f7b88.getSignUrl(<generated>)
        at com.spman.cmpay.service.impl.RequestServiceImpl.loansQuery(RequestServiceImpl.java:754)
        at com.spman.cmpay.service.impl.RequestServiceImpl$$FastClassBySpringCGLIB$$97dca8ad.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
`

**Comment by looly** [comment]
@zeasly 麻烦提供下请求URL我这边测试。（你也可以升级到最新版本hutool尝试）

**Comment by panther125** [comment]
post请求5.8.8也出现问题，本地没问题，但是上传服务器就报错了，
cn.hutool.http.HttpException: Unexpected end of file from server
        at cn.hutool.http.HttpResponse.init(HttpResponse.java:511) ~[hutool-all-5.8.8.jar!/:na]
        at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:484) ~[hutool-all-5.8.8.jar!/:na]
        at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:81) ~[hutool-all-5.8.8.jar!/:na]
        at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1146) ~[hutool-all-5.8.8.jar!/:na]
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1013) ~[hutool-all-5.8.8.jar!/:na]
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:989) ~[hutool-all-5.8.8.jar!/:na]
        at com.yupi.yucongming.dev.client.YuCongMingClient.doChat(YuCongMingClient.java:49) ~[yucongming-java-sdk-0.0.2.jar!/:0.0.2]

**Comment by looly** [comment]
@panther125 麻烦升级到5.8.21试下。

**Comment by panther125** [comment]
> @panther125 麻烦升级到5.8.21试下。

已更新到最新版本，我甚至加大了服务器的带宽，结果还是一样。
cn.hutool.http.HttpException: Unexpected end of file from server
        at cn.hutool.http.HttpResponse.init(HttpResponse.java:531) ~[hutool-all-5.8.21.jar!/:5.8.21]
        at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:504) ~[hutool-all-5.8.21.jar!/:5.8.21]
        at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:82) ~[hutool-all-5.8.21.jar!/:5.8.21]
        at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1196) ~[hutool-all-5.8.21.jar!/:5.8.21]
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1052) ~[hutool-all-5.8.21.jar!/:5.8.21]
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1028) ~[hutool-all-5.8.21.jar!/:5.8.21]

**Comment by looly** [comment]
@panther125 你链接可否提供下？

**Comment by liuhulu** [comment]
这个问题并没有解决。

**Comment by looly** [comment]
@liuhulu 有测试链接么？

**Comment by liuhulu** [comment]
@looly httprequest post请求，HttpUtil.createServer创建接口服务，并在action中抛出异常。

**Comment by looly** [comment]
@liuhulu 确实。这个是server的问题。

1. 浏览器访问显示：
![image](https://github.com/dromara/hutool/assets/1432613/ed6adf9b-6dda-4902-b587-7f428102df65)

2. HttpClient报错：

![image](https://github.com/dromara/hutool/assets/1432613/f3a28c9b-1bcf-4678-a812-ce6c5d676ae4)

3. OkHttp报错：

![image](https://github.com/dromara/hutool/assets/1432613/78cff120-5309-4c79-98a4-7b892f6c01db)

4. JDK报错：

![image](https://github.com/dromara/hutool/assets/1432613/6f64804e-97cf-4b61-a6b7-4bdfa8197eed)


客户端这边没啥问题，问题在于SimpleServer没有统一处理异常而已，抛出异常后没有返回到客户端数据导致的。

**Comment by endlessfantasy0** [comment]
我也遇到了这个问题，很费解，换了好几种方式都一样，最后仔细检查发现是有一个参数名没写对

**Comment by yangyang122** [comment]
这个问题修复了吗？5.8.25还存在此问题

**Comment by yangyang122** [comment]
post请求，偶现这个错误，调用示例：
HttpRequest httpRequest = new HttpRequest()
logger.info("request url:{},method:{}",httpRequest.getUrl(),httpRequest.getMethod());
HttpResponse httpResponse = httpRequest.execute();
String body = httpResponse.body();

**Comment by looly** [comment]
@yangyang122 这个issue列出问题是一直有问题，你的是偶发性问题，已经回复了。

**Comment by wangyuanchen** [comment]
![image](https://github.com/user-attachments/assets/776a9aca-8c9f-4615-8078-e7aa905df980)

我现在碰到的不是偶发现象，而且奇怪的是测试环境没有问题，部署到生产环境之后一直报这个错误
![image](https://github.com/user-attachments/assets/884ba5ae-3427-412b-aa0a-cb98a7cc53fb)  
我使用curl进行访问都是正常，比较奇怪，请求是get请求

**Comment by looly** [comment]
@wangyuanchen JDK不一致么？

**Comment by wtus** [comment]
一样的问题，最新版本，感觉跟服务的某个配置有关系。用python实现请求和postman都可以正常请求。

**Comment by looly** [comment]
@wtus Hutool最新版本么？

**Comment by CIdea-art** [comment]
> @wtus Hutool最新版本么？

5.8.32也一样

**Comment by looly** [comment]
@1010995846 可以提供一个测试的可供请求的地址么，我这边没法复现排查问题。

**Comment by Mxgxg** [comment]
> @1010995846 可以提供一个测试的可供请求的地址么，我这边没法复现排查问题。
5.8.24版本出现的问题，http请求好像没问题
这是个下载地址
https://lowcode.cloudos.svolt.cn/attach/attachment/fcny2/20240920/ce9b4c960ac0471db04709b085fe22df/到货计划表1.xls

**Comment by Vl1nn** [comment]
Caused by: cn.hutool.core.io.IORuntimeException: SocketException: Unexpected end of file from server
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1350)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1188)
	at cn.hutool.http.HttpRequest.$sw$original$execute$d66v271(HttpRequest.java:1051)
	at cn.hutool.http.HttpRequest.$sw$original$execute$d66v271$accessor$$sw$7k1hdn1(HttpRequest.java)
	at cn.hutool.http.HttpRequest$$sw$auxiliary$behmh13.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1027)
	开发环境好的，一上服务器就报这个错

**Comment by looly** [comment]
@Vl1nn 是不是服务器被对方禁了？

尝试关闭Cookie自动记录试下。

看下这篇：https://flynx.dev/post/unexpected-end-of-file-from-server/
