### ISSUE TITLE
文件上传问题(javax.crypto.AEADBadTagException: Tag mismatch!)

### ISSUE THREAD

**Issue by superpipo** [looly/hutool#464]
版本：4.5.16
https下载文件报错：
2019-11-10 16:36:02.425 [ERROR] [DubboServerHandler-10.0.0.9:17199-thread-31] - com.lls.doc.provider.ZipProvider-80 cn.hutool.core.io.IORuntimeException: SSLException: Tag mismatch!
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:283)
	at cn.hutool.core.io.IoUtil.copyByNIO(IoUtil.java:202)
	at cn.hutool.http.HttpResponse.writeBody(HttpResponse.java:242)
	at cn.hutool.http.HttpResponse.writeBody(HttpResponse.java:280)
	at cn.hutool.http.HttpUtil.downloadFile(HttpUtil.java:315)
...
Caused by: javax.net.ssl.SSLException: Tag mismatch!
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1020)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:274)
	... 56 more
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:571)
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1046)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:983)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
	at javax.crypto.Cipher.doFinal(Cipher.java:2377)
	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1015)

**Comment by looly** [comment]
这个是http？
