### ISSUE TITLE
BigExcelWriter使用autoSizeColumnAll报错

### ISSUE THREAD

**Issue by ltylty** [looly/hutool#478]
4.6.1版本
ExcelWriter writer= ExcelUtil.getBigWriter();
writer.write(rows);
writer.autoSizeColumnAll();
会报错，异常如下
java.lang.IllegalStateException: Could not auto-size column. Make sure the column was tracked prior to auto-sizing the column.
	at org.apache.poi.xssf.streaming.SXSSFSheet.autoSizeColumn(SXSSFSheet.java:1591)
	at org.apache.poi.xssf.streaming.SXSSFSheet.autoSizeColumn(SXSSFSheet.java:1545)
	at cn.hutool.poi.excel.ExcelWriter.autoSizeColumn(ExcelWriter.java:242)
	at cn.hutool.poi.excel.ExcelWriter.autoSizeColumnAll(ExcelWriter.java:228)

**Comment by looly** [comment]
https://www.cnblogs.com/Yiran583/p/6739187.html
