### ISSUE TITLE
com.xiaoleilu.hutool.util.RuntimeUtil#exec 执行 which 异常

### ISSUE THREAD

**Issue by aristotll** [looly/hutool#50]
```java 
import static com.xiaoleilu.hutool.util.RuntimeUtil.exec;        
final List<String> exec = exec("which java");
```
异常

```
Exception in thread "main" com.xiaoleilu.hutool.io.IORuntimeException: IOException: Cannot run program "which java": error=2, No such file or directory
	at com.xiaoleilu.hutool.util.RuntimeUtil.exec(RuntimeUtil.java:32)
	at nio.files.SymbolicLinksDemo.main(SymbolicLinksDemo.java:15)
Caused by: java.io.IOException: Cannot run program "which java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.xiaoleilu.hutool.util.RuntimeUtil.exec(RuntimeUtil.java:30)
	... 1 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more
```

**Comment by aristotll** [comment]
确定`which java` 肯定是有正确的结果的

**Comment by looly** [comment]
这是由于which这个命令并非独立运行的，需要配合sh，考虑这样运行：exec("sh which java");
