### ISSUE TITLE
AES加解密问题，如何正确创建一个CBC加密模式+填充类型+指定偏移量的AES类

### ISSUE THREAD

**Issue by CharleyXu** [looly/hutool#55]
代码实例	
	//随机生成密钥
		byte[] key = SecureUtil.generateKey(SymmetricAlgorithm.AES.getValue()).getEncoded();
		AES aes = new AES(Mode.CBC, Padding.NoPadding, key);
		aes.setIv(new IvParameterSpec("0102030405060708".getBytes()));
		//加密
		byte[] encrypt = aes.encrypt(content);

报错如下：

com.xiaoleilu.hutool.crypto.CryptoException: InvalidKeyException: Wrong algorithm: AES or Rijndael required

	at com.xiaoleilu.hutool.crypto.symmetric.SymmetricCrypto.encrypt(SymmetricCrypto.java:132)
	at com.xiaoleilu.hutool.crypto.symmetric.SymmetricCrypto.encrypt(SymmetricCrypto.java:174)
	at com.xu.spider4j.encrypt.SymmetricTest.aesTest3(SymmetricTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.security.InvalidKeyException: Wrong algorithm: AES or Rijndael required
	at com.sun.crypto.provider.AESCrypt.init(AESCrypt.java:83)
	at com.sun.crypto.provider.CipherBlockChaining.init(CipherBlockChaining.java:93)
	at com.sun.crypto.provider.CipherCore.init(CipherCore.java:591)
	at com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:346)
	at javax.crypto.Cipher.implInit(Cipher.java:806)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at com.xiaoleilu.hutool.crypto.symmetric.SymmetricCrypto.encrypt(SymmetricCrypto.java:128)
	... 24 more

**Comment by looly** [comment]
AES属于对称加密，特殊要求的加密模式请使用SymmetricCrypto传入字符串的算法。前提是JDK支持。可以看下这部分文档：http://hutool.mydoc.io/?t=233546

**Comment by CharleyXu** [comment]
自己用Cipher类实现了，这部分文档就没有涉及到我问的问题

**Comment by looly** [comment]
Hutool本质上是封装了Cipher。如果方便，欢迎提供Cipher实现的代码。我看Hutool如何实现，我会补充到文档。谢谢~

**Comment by CharleyXu** [comment]
好的，我是参考了中文文档 http://www.matools.com/manual/1000和
在线测试http://tool.chacuo.net/cryptaes ，希望有所帮助

具体如下：
	/**
	 * ASE-128-CBC加密
	 * @param src	加密内容
	 * @param key	密钥	16位
	 * @param iv	偏移量	16
	 * @return
	 * @throws Exception
	 */
	public static String aesEncrypt(String src, String key,String iv) throws Exception {
		String encodingFormat = "UTF-8";
		Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
		byte[] raw = key.getBytes();
		SecretKeySpec secretKeySpec = new SecretKeySpec(raw, "AES");
		IvParameterSpec ivParameterSpec = new IvParameterSpec(iv.getBytes());
		// 使用CBC模式，需要一个向量vi，增加加密算法强度
		cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec, ivParameterSpec);
		byte[] encrypted = cipher.doFinal(src.getBytes(encodingFormat));
		return new BASE64Encoder().encode(encrypted);

	}

	public static void main(String[] args) {
		String result = null;
		try {
			result = aesEncrypt("123", "0CoJUm6Qyw8W8jud", "0102030405060708");
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println(result);
	}

**Comment by looly** [comment]
Sorry关于这个问题这么久回复。经过排查已经找到问题，3.3.0中会修复此问题。

新版可以直接这么使用：

```java
DES des = new DES(Mode.CBC, Padding.PKCS5Padding, "0CoJUm6Qyw8W8jud".getBytes(), "01020304".getBytes());
```

**Comment by MrSummer33** [comment]
@looly  请问java 支持AES 256位偏移量嘛

**Comment by planwk** [comment]
请问下，如果要实现AES256位加密，是否生成的密钥是256位即可？也就是长度是32个字节

**Comment by changhr2013** [comment]
@planwk 是的，jce 实现的内部会根据传入密钥的 size 自动计算轮数。
