### ISSUE TITLE
cn.hutool.http.HttpException: Too many open files

### ISSUE THREAD

**Issue by wuuJiawei** [looly/hutool#621]
在Quartz定时任务中执行如下代码：
```
 HttpResponse response = null;
        try {
            response = HttpRequest.post(createUrl(MSG)).body(JSONUtil.parse(params)).execute();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (response != null) {
                response.close();
            }
        }
```
执行几小时后出现异常：
```
[DefaultQuartzScheduler_Worker-7] ERROR org.quartz.core.ErrorLogger - Job (SendGroup.SendJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
cn.hutool.http.HttpException: Too many open files
        at cn.hutool.http.HttpRequest.send(HttpRequest.java:1008)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:879)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:849)
        at com.beike.utils.tencent.im.QueryState.query(QueryState.java:45)
        at com.beike.utils.tencent.im.QueryState.isOnline(QueryState.java:30)
        at com.beike.module.robot.quartz.SendJob.execute(SendJob.java:84)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketException: Too many open files
        at java.net.Socket.createImpl(Socket.java:478)
        at java.net.Socket.connect(Socket.java:605)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
        at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:453)
        at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1026)
        at cn.hutool.http.HttpRequest.send(HttpRequest.java:998)
        ... 7 more

```
运行环境是Centos 7.5.1804 (Core)
大概每秒钟发送10-130次网络请求

**Comment by wuuJiawei** [comment]
hutool版本：`4.6.1`

**Comment by looly** [comment]
检查几个问题：

1、定时任务执行后是不是因为网络阻塞导致http处于等待状态，后边的http请求又启动了。
2、检查Linux句柄是不是过小`vim /etc/security/limits.conf `

**Comment by Archer1003** [comment]
cn.hutool.core.io.IORuntimeException: SocketException: 打开的文件过多
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1258)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1123)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1012)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:988)
	at com.hollysys.collector.graphql.CGraphql.GraphqlApi(CGraphql.java:232)
	at com.hollysys.collector.graphql.CGraphql.GraphqlGetSnmpParam(CGraphql.java:122)
	at com.hollysys.collector.graphql.CGraphql.getDevInfo(CGraphql.java:104)
	at com.hollysys.collector.core.SnmpGetTask.start(SnmpGetTask.java:49)
	at com.hollysys.collector.job.SnmpGetDevStatuJob.execute(SnmpGetDevStatuJob.java:37)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketException: 打开的文件过多
	at java.net.Socket.createImpl(Socket.java:477)
	at java.net.Socket.connect(Socket.java:604)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:298)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:292)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1354)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1329)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:449)
	at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1281)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1250)
	... 10 more

**Comment by Archer1003** [comment]
此问题在5.8.0 中依然存在

cn.hutool.core.io.IORuntimeException: SocketException: 打开的文件过多
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1258)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1123)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1012)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:988)
	at com.hollysys.collector.graphql.CGraphql.GraphqlApi(CGraphql.java:232)
	at com.hollysys.collector.graphql.CGraphql.GraphqlGetSnmpParam(CGraphql.java:122)
	at com.hollysys.collector.graphql.CGraphql.getDevInfo(CGraphql.java:104)
	at com.hollysys.collector.core.SnmpGetTask.start(SnmpGetTask.java:49)
	at com.hollysys.collector.job.SnmpGetDevStatuJob.execute(SnmpGetDevStatuJob.java:37)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketException: 打开的文件过多
	at java.net.Socket.createImpl(Socket.java:477)
	at java.net.Socket.connect(Socket.java:604)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:298)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:292)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1354)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1329)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:449)
	at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1281)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1250)
	... 10 more
