### ISSUE TITLE
IPV6地址使用HttpUtil.post方法报错

### ISSUE THREAD

**Issue by zuxingyu** [looly/hutool#651]
带端口的IPV6的URL地址（例：http://[2008::232]:1234）使用HttpUtil.post方法将URL中"[]"转义导致jdk中URLStreamHandler.java:185无法判断host是否为ipv6地址。
    报错信息如下：

    Exception in thread "main" cn.hutool.core.exceptions.UtilException: MalformedURLException: For input string: ":207%5D:3030"

	at cn.hutool.core.util.URLUtil.toUrlForHttp(URLUtil.java:126)
	at cn.hutool.http.HttpRequest.initConnecton(HttpRequest.java:976)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:934)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:903)
	at cn.hutool.http.HttpUtil.post(HttpUtil.java:161)
	at cn.hutool.http.HttpUtil.post(HttpUtil.java:148)
	at com.example.demo.Demo.main(Demo.java:77)

另：get方法也存在相同问题。

**Comment by looly** [comment]
感谢：https://github.com/looly/hutool/pull/654
