### ISSUE TITLE
hutool-all 5.0.7 国密算法

### ISSUE THREAD

**Issue by ghost** [looly/hutool#652]
项目引入 

```
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>5.0.7</version>
</dependency>
```

使用代码 

```
SymmetricCrypto sm4 = new SM4(Mode.ECB, Padding.PKCS5Padding, "keykeyke".getBytes());
```

出现下面错误

```
Caused by: cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: Cannot find any provider supporting SM4/ECB/PKCS5Padding
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:987) ~[hutool-all-5.0.7.jar:na]
	at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:154) ~[hutool-all-5.0.7.jar:na]
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:124) ~[hutool-all-5.0.7.jar:na]
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:163) ~[hutool-all-5.0.7.jar:na]
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:138) ~[hutool-all-5.0.7.jar:na]
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:70) ~[hutool-all-5.0.7.jar:na]
	at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:58) ~[hutool-all-5.0.7.jar:na]
```

Java 1.8.0_221  x64

**Comment by ghost** [comment]
我将key 换成 ```b51df7646a762f18``` 同样不好使

**Comment by sc-ik** [comment]
这问题 多久回复 啊?  还不如 换 jar 快呢

**Comment by ghost** [comment]
呵呵, 无语  我的 钛合金 大眼睛 丢了 

```
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>${bouncycastle.version}</version>
</dependency>
```

**Comment by looly** [comment]
哈哈，hutool依赖bc库实现sm4。

**Comment by minesunny** [comment]
> 

既然这样hutool还有什么意义,竟是用别人的代码

**Comment by VampireAchao** [comment]
> > 
> 
> 既然这样hutool还有什么意义,竟是用别人的代码

hutool的宗旨是为了降低学习成本，提升开发效率，避免网上各种参差不齐的代码复制过来不敢用，不好用

**Comment by Createsequence** [comment]
> > 
> 
> 既然这样hutool还有什么意义,竟是用别人的代码

老实说，你这话说的让人不知道怎么回你。

我猜你没上官网看过 hutool 的简介，所以我专门再复制过来让你看看 hutool 是干嘛的：

> Hutool是一个小而全的Java工具类库，通过静态方法封装，降低相关API的学习成本，提高工作效率，使Java拥有函数式语言般的优雅，让Java语言也可以“甜甜的”。
>
> Hutool中的工具方法来自每个用户的精雕细琢，它涵盖了Java开发底层代码中的方方面面，它既是大型项目开发中解决小问题的利器，也是小型项目中的效率担当；
>
> Hutool是项目中“util”包友好的替代，它节省了开发人员对项目中公用类和公用工具方法的封装时间，使开发专注于业务，同时可以最大限度的避免封装不完善带来的bug。

hutool 是个工具类，是常用功能的封装，**目的是为了降低程序员日常寻找工具类的额外时间成本，提高开发效率，而不是把所有的轮子都自己再造一遍**。
