### ISSUE TITLE
JavaBean转换成JSONObject时对Date类型的属性转换出现负数，然后通过toBean方法无法再从String转换成JavaBean

### ISSUE THREAD

**Issue by Jalone5186** [looly/hutool#677]
伪代码：
//auditResultDto对象中有Date类型的字段，Date的值为：1969-12-15
JSONObject jsonObject = JSONUtil.parseObj(auditResultDto);
String objString = jsonObject.toString();
AuditResultDto auditResultDto = JSONUtil.toBean(objString , AuditResultDto.class);//执行这行代码报错
Caused by: cn.hutool.core.convert.ConvertException: Can not convert [-1497600000] to type [java.sql.Date]
	at cn.hutool.json.InternalJSONUtil.jsonConvert(InternalJSONUtil.java:327)
	at cn.hutool.json.InternalJSONUtil$1.value(InternalJSONUtil.java:235)
	at cn.hutool.json.InternalJSONUtil$1.value(InternalJSONUtil.java:226)
	at cn.hutool.core.bean.copier.BeanCopier.valueProviderToBean(BeanCopier.java:140)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:64)
	at cn.hutool.core.bean.BeanUtil.fillBean(BeanUtil.java:419)
	at cn.hutool.json.InternalJSONUtil.toBean(InternalJSONUtil.java:226)
	at cn.hutool.json.JSONObject.toBean(JSONObject.java:325)
	at cn.hutool.json.JSONObject.toBean(JSONObject.java:302)
	at cn.hutool.json.InternalJSONUtil.jsonConvert(InternalJSONUtil.java:299)
	at cn.hutool.json.InternalJSONUtil$1.value(InternalJSONUtil.java:235)
	at cn.hutool.json.InternalJSONUtil$1.value(InternalJSONUtil.java:226)
	at cn.hutool.core.bean.copier.BeanCopier.valueProviderToBean(BeanCopier.java:140)
	at cn.hutool.core.bean.copier.BeanCopier.copy(BeanCopier.java:64)
	at cn.hutool.core.bean.BeanUtil.fillBean(BeanUtil.java:419)
	at cn.hutool.json.InternalJSONUtil.toBean(InternalJSONUtil.java:226)
	at cn.hutool.json.JSONObject.toBean(JSONObject.java:325)
	at cn.hutool.json.JSONObject.toBean(JSONObject.java:269)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:330)
	at cn.hutool.json.JSONUtil.toBean(JSONUtil.java:305)
	at com.jalone.misc.application.controller.MainController.listenMessage(MainController.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)
	... 10 common frames omitted

**Comment by looly** [comment]
int类型转换日期错误导致的，之前我只考虑了long类型。5.1.0修复此问题。
