### ISSUE TITLE
ZipException: incorrect header check

### ISSUE THREAD

**Issue by zhzhlit** [looly/hutool#694]
老版本（4.3.2）压缩的数据，新版本（5.1.0）读取的时候报错：
`cn.hutool.core.io.IORuntimeException: ZipException: incorrect header check
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:183)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:148)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:135)
	at cn.hutool.core.util.ZipUtil.inflater(ZipUtil.java:1042)
	at cn.hutool.core.util.ZipUtil.unZlib(ZipUtil.java:823)
	at cn.hutool.core.util.ZipUtil.unZlib(ZipUtil.java:799)
	at cn.hutool.core.util.ZipUtil.unZlib(ZipUtil.java:788)
`

压缩方法：
ZipUtil.zlib(String 原始数据, Charsets.UTF_8.name(), 9)
解压方法:
ZipUtil.unZlib(byte[] 压缩后数据, Charsets.UTF_8.name());

**Comment by looly** [comment]
旧版此处存在bug，zlib部分做了修改导致的。请以新版为准。
