### ISSUE TITLE
springboot打成jar包后获取配置文件报错

### ISSUE THREAD

**Issue by yxiaozhou** [looly/hutool#725]
private Props getConfig() {
        Props props = new Props("generator.properties");
        props.autoLoad(true);
        return props;
    }
使用该代码获取resource目录下的配置文件在项目打成jar包后报错，ide中调试没有问题。
报错内容如下：
2020-01-15 16:14:06.388  INFO 11896 --- [  XNIO-2 task-5] com.zaxxer.hikari.Hika
riDataSource       : HikariPool-6 - Start completed.
2020-01-15 16:14:06.396  INFO 11896 --- [  XNIO-2 task-5] com.zaxxer.hikari.Hika
riDataSource       : HikariPool-6 - Shutdown initiated...
2020-01-15 16:14:06.398  INFO 11896 --- [  XNIO-2 task-5] com.zaxxer.hikari.Hika
riDataSource       : HikariPool-6 - Shutdown completed.
2020-01-15 16:14:06.402 ERROR 11896 --- [  XNIO-2 task-5] io.undertow.request
                   : UT005023: Exception handling request to /demo/generator

org.springframework.web.util.NestedServletException: Request processing failed;
nested exception is java.nio.file.FileSystemNotFoundException
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:1006) ~[spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServ
let.java:901) ~[spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.
servlet-api-4.0.1.jar!/:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:875) ~[spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.
servlet-api-4.0.1.jar!/:4.0.1]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHand
ler.java:74) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(F
ilterHandler.java:129) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(
RequestContextFilter.java:99) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61
) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(F
ilterHandler.java:131) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(For
mContentFilter.java:92) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61
) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(F
ilterHandler.java:131) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInterna
l(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE
]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61
) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(F
ilterHandler.java:131) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern
al(CharacterEncodingFilter.java:200) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELE
ASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61
) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(F
ilterHandler.java:131) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandle
r.java:84) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.hand
leRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.0.14.Final.ja
r!/:2.0.14.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChai
n.java:68) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(
ServletDispatchingHandler.java:36) ~[undertow-servlet-2.0.14.Final.jar!/:2.0.14.
Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandle
r.handleRequest(SSLInformationAssociationHandler.java:132) ~[undertow-servlet-2.
0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandle
r.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.0
.14.Final.jar!/:2.0.14.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateH
andler.java:43) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRe
quest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.0.14.Final.jar!/
:2.0.14.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstrain
tHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undert
ow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleR
equest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.0.14.Final.jar
!/:2.0.14.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandl
er.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2
.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandl
er.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-c
ore-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateH
andler.java:43) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateH
andler.java:43) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest
(ServletInitialHandler.java:292) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Fin
al]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(Servlet
InitialHandler.java:81) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInit
ialHandler.java:138) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInit
ialHandler.java:135) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.cal
l(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.14.Final
.jar!/:2.0.14.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(Context
ClassLoaderSetupAction.java:43) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Fina
l]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(Se
rvletInitialHandler.java:272) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]

        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(Servlet
InitialHandler.java:81) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(Se
rvletInitialHandler.java:104) [undertow-servlet-2.0.14.Final.jar!/:2.0.14.Final]

        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
 [undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:8
30) [undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_191]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_191]
Caused by: java.nio.file.FileSystemNotFoundException: null
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemPr
ovider.java:171) ~[zipfs.jar:1.8.0_191]
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider
.java:157) ~[zipfs.jar:1.8.0_191]
        at java.nio.file.Paths.get(Unknown Source) ~[na:1.8.0_191]
        at cn.hutool.core.io.watch.WatchUtil.createModify(WatchUtil.java:301) ~[
hutool-all-5.0.0.jar!/:na]
        at cn.hutool.core.io.watch.WatchUtil.createModify(WatchUtil.java:276) ~[
hutool-all-5.0.0.jar!/:na]
        at cn.hutool.core.io.watch.WatchUtil.createModify(WatchUtil.java:263) ~[
hutool-all-5.0.0.jar!/:na]
        at cn.hutool.setting.dialect.Props.autoLoad(Props.java:282) ~[hutool-all
-5.0.0.jar!/:na]
        at com.xkcoding.codegen.utils.CodeGenUtil.getConfig(CodeGenUtil.java:218
) ~[classes!/:na]
        at com.xkcoding.codegen.utils.CodeGenUtil.generatorCode(CodeGenUtil.java
:72) ~[classes!/:na]
        at com.xkcoding.codegen.service.impl.CodeGenServiceImpl.generatorCode(Co
deGenServiceImpl.java:103) ~[classes!/:na]
        at com.xkcoding.codegen.controller.CodeGenController.generatorCode(CodeG
enController.java:51) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.
0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.
0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:
1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvok
e(InvocableHandlerMethod.java:215) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.2.RELEAS
E]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeF
orRequest(InvocableHandlerMethod.java:142) ~[spring-web-5.1.2.RELEASE.jar!/:5.1.
2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-
webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[sprin
g-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-web
mvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.2.RELEASE.ja
r!/:5.1.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:1038) ~[spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:942) ~[spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:998) ~[spring-webmvc-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        ... 50 common frames omitted

**Comment by yxiaozhou** [comment]
搜索后是WatchUtil 301行 Paths.get(uri)这里获取文件时需要兼容下

**Comment by looly** [comment]
jar包内的配置文件不支持autoLoad，所以不要加这个即可。
