### ISSUE TITLE
excel导出问题

### ISSUE THREAD

**Issue by amyema** [looly/hutool#730]
在maven中央仓库中引用了 hutool-all 5.1.1 以及 poi-ooxml 4.1.1，jdk版本1.8，使用 ExcelUtil.getBigWriter(fileName) 方法从数据库中分页查询，每页查询 40000 条数据导出一个 excel，该方法会抛出异常 ：
Exception in thread "main" org.apache.poi.ooxml.POIXMLException: java.io.EOFException: Unexpected end of ZLIB input stream
	at org.apache.poi.ooxml.POIXMLDocument.getProperties(POIXMLDocument.java:147)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:240)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:953)
	at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:971)
	at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:945)
	at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:931)
	at cn.hutool.poi.excel.BigExcelWriter.close(BigExcelWriter.java:122)
无法导出

**Comment by amyema** [comment]
没有问题

**Comment by 8debug** [comment]
请问如何解决的呀？

**Comment by 8debug** [comment]
> 在maven中央仓库中引用了 hutool-all 5.1.1 以及 poi-ooxml 4.1.1，jdk版本1.8，使用 ExcelUtil.getBigWriter(fileName) 方法从数据库中分页查询，每页查询 40000 条数据导出一个 excel，该方法会抛出异常 ：
> Exception in thread "main" org.apache.poi.ooxml.POIXMLException: java.io.EOFException: Unexpected end of ZLIB input stream
> at org.apache.poi.ooxml.POIXMLDocument.getProperties(POIXMLDocument.java:147)
> at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:240)
> at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:953)
> at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:971)
> at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:945)
> at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:931)
> at cn.hutool.poi.excel.BigExcelWriter.close(BigExcelWriter.java:122)
> 无法导出

请问如何解决的呀
