### ISSUE TITLE
CharsetUtil 在类加载时访问了GBK字符编码，在不支持GBK的系统中运行报错 指定字符集无法避免类加载错误

### ISSUE THREAD

**Issue by Dustone-JavaWeb** [looly/hutool#731]
Jan 17, 2020 6:55:18 AM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.lang.ExceptionInInitializerError
        at cn.hutool.core.util.ZipUtil.<clinit>(ZipUtil.java:45)
        at com.advantech.deviceon.commbridge.util.CommonUtil.makeZip(CommonUtil.java:201)
        at com.advantech.deviceon.commbridge.component.SystemContext.backupCommbridgeInfo(SystemContext.java:585)
        at com.advantech.deviceon.commbridge.Application.backupConfigs(Application.java:372)
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:219)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:120)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:231)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:211)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:74)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:417)
        at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:483)
        at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:457)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:714)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:622)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.charset.UnsupportedCharsetException: GBK
        at java.nio.charset.Charset.forName(Unknown Source)
        at cn.hutool.core.util.CharsetUtil.<clinit>(CharsetUtil.java:29)
        ... 45 more

![image](https://user-images.githubusercontent.com/35624201/72591204-8629e380-393a-11ea-89bf-de6df11d21be.png)

**Comment by looly** [comment]
看报错是GBK不被支持但是你用了GBK编码，经过查看源码，ZipUtil默认编码是平台默认设置的编码，即`Charset.defaultCharset()`，说明你在系统中或者jdk中设置了默认编码为GBK，请检查系统配置文件。

**Comment by Dustone-JavaWeb** [comment]
> 看报错是GBK不被支持但是你用了GBK编码，经过查看源码，ZipUtil默认编码是平台默认设置的编码，即`Charset.defaultCharset()`，说明你在系统中或者jdk中设置了默认编码为GBK，请检查系统配置文件。

我没有使用GBK方法  JDK中设置的默认编码为UTF -8  是yocto上ARM版本的JDK，我这里说的是Charset.forName(“GBK”) 这个方法会抛出异常，因为系统不支持GBK编码，而在加载CharsetUtil这个类时并没有对这个异常进行处理导致类加载失败。

**Comment by looly** [comment]
明白了，5.1.3修复此问题。
