### ISSUE TITLE
Word生成-Word07Writer 出现错误

### ISSUE THREAD

**Issue by WangYekun** [looly/hutool#737]
个人代码如下===============>>>>使用的poi-ooxml版本为3.9 xercesImpl版本为 2.12.0 
package wang.utils.word;

import cn.hutool.core.io.FileUtil;
import cn.hutool.log.StaticLog;
import cn.hutool.poi.word.Word07Writer;

import java.awt.*;

/**
 * @author Mark
 * @version 1.0
 * @date 2020/1/20 16:10
 * @description word工具类
 */
public class WordUtils {
    public static void main(String[] args) {
        Word07Writer writer = new Word07Writer();
        // 添加段落（标题）
        writer.addText(new Font("方正小标宋简体", Font.PLAIN, 22), "我是第一部分", "我是第二部分");
        // 添加段落（正文）
        writer.addText(new Font("宋体", Font.PLAIN, 22), "我是正文第一部分", "我是正文第二部分");
        // 写出到文件
        writer.flush(FileUtil.file("d:/wordWrite.docx"));
        // 打印输出成功
        StaticLog.info("#####################输出成功########################");
        // 关闭流
        writer.close();
    }
}
<<<<<<<<控制台输出异常代码如下>>>>>>>>>>>>>>>>>>>>
[2020-01-20 16:26:08] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.
[2020-01-20 16:26:08] [INFO] wang.utils.word.WordUtils: #####################输出成功########################
Exception in thread "main" java.lang.IncompatibleClassChangeError
	at cn.hutool.core.io.IoUtil.close(IoUtil.java:992)
	at cn.hutool.poi.word.Word07Writer.closeWithoutFlush(Word07Writer.java:217)
	at cn.hutool.poi.word.Word07Writer.close(Word07Writer.java:210)
	at wang.utils.word.WordUtils.main(WordUtils.java:27)
<<<<<<<<===进行源码时这个方法报错了===>>>>>>>>>>>>>>>>>>
	/**
	 * 关闭Word文档但是不写出
	 */
	protected void closeWithoutFlush() {
		IoUtil.close(this.doc);
		this.isClosed = true;
	}
<<<<========= 个人认为是不是因为我引入的包太新，出现了问题========>>>>>>>>>

**Comment by WangYekun** [comment]
说明 poi-ooxml 版本需高于 3.17（别问我3.8版本为啥不行，因为3.17 > 3.8 ） xercesImpl版本高于2.11.0
故==>>>>>使用的poi-ooxml版本为3.9 xercesImpl版本为 2.12.0

**Comment by looly** [comment]
hutool基于poi-3.17封装，你的3.9不是太新，而是太旧了。
