### ISSUE TITLE
sax 模式读取excel2003时报数组越界

### ISSUE THREAD

**Issue by xinjirufen** [looly/hutool#750]
[读取的文件.zip](https://github.com/looly/hutool/files/4209609/default.zip)

执行代码：ExcelUtil.read03BySax();

报错信息：
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 14, Size: 12
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at cn.hutool.poi.excel.sax.Excel03SaxReader.processRecord(Excel03SaxReader.java:197)

hutool版本：4.6.8

**Comment by xinjirufen** [comment]
我查了下，如果excel中单元格添加了批注，就会报这个错误

**Comment by looly** [comment]
可否提供下测试用的excel？

**Comment by xinjirufen** [comment]
> 可否提供下测试用的excel？

在问题内容中已经有了“读取的文件.zip”，我这边在传一次
[读取的文件.zip](https://github.com/looly/hutool/files/4222521/default.zip)

**Comment by looly** [comment]
好的，谢谢。稍后测试。

**Comment by looly** [comment]
5.1.4修复此问题，感谢。
