### ISSUE TITLE
[BUG] 5.2.1 TemplateUtil BUG

### ISSUE THREAD

**Issue by xkcoding** [looly/hutool#785]
### 版本情况

JDK版本：    1.8.0_162
hutool版本： 5.2.1

### 问题描述（包括截图）

1. 复现代码

```java
@UtilityClass
public class Func {
    private final static TemplateEngine ENGINE = TemplateUtil.createEngine(new TemplateConfig("templates", TemplateConfig.ResourceMode.CLASSPATH));

    public String buildSql(SqlModelDTO sqlModel) {
        final Template template = ENGINE.getTemplate("sql/sql.template");
        return template.render(BeanUtil.beanToMap(sqlModel));
    }
}

// 测试类，测试 buildSql ，出错
```

2. 堆栈信息

```java
Caused by: cn.hutool.extra.template.TemplateException: No template found ! Please add one of template jar to your project !
	at cn.hutool.extra.template.engine.TemplateFactory.doCreate(TemplateFactory.java:50)
	at cn.hutool.extra.template.engine.TemplateFactory.create(TemplateFactory.java:26)
	at cn.hutool.extra.template.TemplateUtil.createEngine(TemplateUtil.java:32)
	at com.mchz.bigdata.quality.util.Func.<clinit>(Func.java:42)
	... 61 common frames omitted
```

3. 测试涉及到的文件
pom 文件已经添加依赖
```xml
   <dependency>
      <groupId>cn.hutool</groupId>
      <artifactId>hutool-all</artifactId>
      <version>5.2.1</version>
    </dependency>
<!--模板引擎-->
    <dependency>
      <groupId>com.jfinal</groupId>
      <artifactId>enjoy</artifactId>
      <version>4.8</version>
    </dependency>
```

> 备注：使用 `5.1.0` 测试可用，`5.2.0` 以及 `5.2.1` 均不可用，具体从哪个版本开始出现，暂不知道，需要小磊找找了。

**Comment by looly** [comment]
5.2.3解决了此问题，请升级。

**Comment by xkcoding** [comment]
感谢！
