### ISSUE TITLE
空指针了哟~

### ISSUE THREAD

**Issue by pkaq** [looly/hutool#827]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.3.0

### 问题描述（包括截图）

1. 复现代码
cookie没拿到东西  空指针了哟
```java
java.lang.NullPointerException: null
	at java.base/java.lang.reflect.Array.getLength(Native Method) ~[na:na]
	at cn.hutool.core.collection.ArrayIter.<init>(ArrayIter.java:57) ~[hutool-all-5.3.0.jar:na]
	at cn.hutool.core.collection.ArrayIter.<init>(ArrayIter.java:45) ~[hutool-all-5.3.0.jar:na]
	at cn.hutool.core.collection.ArrayIter.<init>(ArrayIter.java:34) ~[hutool-all-5.3.0.jar:na]
	at cn.hutool.extra.servlet.ServletUtil.readCookieMap(ServletUtil.java:422) ~[hutool-all-5.3.0.jar:na]
```

**Comment by looly** [comment]
5.3.1修复此问题，感谢。
