### ISSUE TITLE
CollectionUtil.isNotEmpty(null)报错

### ISSUE THREAD

**Issue by gebilaoman** [looly/hutool#841]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.4|5.3.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
package com.test
import cn.hutool.core.collection.CollUtil
import cn.hutool.core.collection.CollectionUtil
import cn.hutool.core.map.MapUtil

class test {
    public static void main(String[] args) {
        CollectionUtil.isNotEmpty(null) // 报错
        CollUtil.isNotEmpty(null)// 报错
        MapUtil.isNotEmpty(null)// 正常
    }
}

```

2. 堆栈信息
```
Connected to the target VM, address: '127.0.0.1:63150', transport: 'socket'
Exception in thread "main" groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method cn.hutool.core.collection.CollectionUtil#isNotEmpty.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[interface java.lang.Iterable]
	[interface java.util.Collection]
	[interface java.util.Enumeration]
	[interface java.util.Iterator]
	[interface java.util.Map]
	at groovy.lang.MetaClassImpl.doChooseMostSpecificParams(MetaClassImpl.java:3251)
	at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:3228)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3217)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3160)
	at groovy.lang.MetaClassImpl.pickStaticMethod(MetaClassImpl.java:1528)
	at groovy.lang.MetaClassImpl.retrieveStaticMethod(MetaClassImpl.java:1424)
	at groovy.lang.MetaClassImpl.createStaticSite(MetaClassImpl.java:3419)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:76)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.forceclouds.tq.test.main(test.groovy:35)
Disconnected from the target VM, address: '127.0.0.1:63150', transport: 'socket'

Process finished with exit code 1

```

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
```java
CollUtil.isNotEmpty((Collection<?>) null);
```

CollUtil.isNotEmpty涉及到多种对象的重载，直接传null也没有意义。
