### ISSUE TITLE
HttpRequest 请求报错

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#842]
hutool-all 4.2.1版本
      
  String result = HttpRequest.post(postUrl)
                .header("accessToken", ACCESS_TOKEN)
                .header("Content-Type", "application/json")
                .body(JSONObject.toJSONString(updateApplyDataRequest))
                .execute().body();

$$java.lang.NoSuchMethodError: cn.hutool.core.lang.Assert.notBlank(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
        at cn.hutool.http.HttpRequest.<init>(HttpRequest.java:126)
        at cn.hutool.http.HttpRequest.post(HttpRequest.java:140)
        at com.caidanmao.pos.client.QingLiuClient.addContractApplyDataRequest(QingLiuClient.java:137)
        at com.caidanmao.service.shop.server.service.base.ContractQingLiuUtilService.lambda$handleOrderDataToQingLiu$4(ContractQingLiuUtilService.java:280)
        at java.lang.Thread.run(Thread.java:748)

**Comment by looly** [comment]
升级Hutool后需要重新编译项目。
