### ISSUE TITLE
cn.hutool.extra.ftp.AbstractFtp#exist 方法增强

### ISSUE THREAD

**Issue by xingguang2013** [looly/hutool#844]
### 版本情况

JDK版本：    openjdk_8_172
hutool版本： 5.2.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Sftp sftp = new Sftp('x.x.x.x', 22, 'username', 'passowrd');
sftp.exist("/a/b/c/test.txt");
```

2. 堆栈信息
```java
cn.hutool.extra.ssh.JschRuntimeException: SftpException: No such file
	at cn.hutool.extra.ssh.Sftp.ls(Sftp.java:241) ~[hutool-all-5.2.4.jar!/:?]
	at cn.hutool.extra.ssh.Sftp.lsFiles(Sftp.java:217) ~[hutool-all-5.2.4.jar!/:?]
```

3. 测试涉及到的文件（注意脱密）
目前判断文件是否存在只支持在 sftp 服务器上存在该文件的目录时，才可以，否则会报上述错误，是否可以增强支持文件的上层某个目录不存在时，也是可以判断出来的，而不是报错( No such file)。

**Comment by looly** [comment]
5.3.2处理此异常。

**Comment by looly** [comment]
5.3.2处理此异常。
