### ISSUE TITLE
h2数据库大小写问题

### ISSUE THREAD

**Issue by TFlay** [looly/hutool#847]
### 版本情况

JDK版本：    java version 1.8.0_191
hutool版本： 5.3.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

**h2数据库查询时报错**
**在添加 IGNORECASE=TRUE 属性后 Db.use().find(Entity) 报错，Db.use().query("sql") 正常**
**h2的版本号为 h2-1.4.200**
**h2中的表名，字段名为大写**

----

**1. 复现代码**

**java代码**
```java
      Entity entity = new Entity("tb_user");
        try {
            // 使用Db.use().find(Entity) 报错
            // List<Entity> entities = Db.use().find(entity);
            // 使用Db.use().query("sql") 正常
            List<Entity> query = Db.use().query("select * from tb_user");
            System.out.println(query);
            // System.out.println(entities);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
```
**setting配置**
```shell
## 基本配置信息
# url添加IGNORECASE=TRUE属性不区分大小写
url = jdbc:h2:~/demo;IGNORECASE=TRUE
username = sa
password = sa
driver = org.h2.Driver

## 连接池配置项
# 自动提交
autoCommit = true
# 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
connectionTimeout = 30000
# 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
idleTimeout = 600000
# 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
maxLifetime = 1800000
# 获取连接前的测试SQL
connectionTestQuery = SELECT 1
# 最小闲置连接数
minimumIdle = 10
# 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
maximumPoolSize = 10
# 连接只读数据库时配置为true， 保证安全
readOnly =false
```

**2. 堆栈信息**
```shell
Caused by: java.lang.NullPointerException
	at cn.hutool.db.DbUtil.close(DbUtil.java:158)
	at cn.hutool.db.SqlConnRunner.find(SqlConnRunner.java:317)
	at cn.hutool.db.SqlConnRunner.find(SqlConnRunner.java:336)
	at cn.hutool.db.AbstractDb.find(AbstractDb.java:455)
	at cn.hutool.db.AbstractDb.find(AbstractDb.java:521)
```

**Comment by looly** [comment]
5.3.2修改增加null的判断。
