### ISSUE TITLE
发送httpRequest请求socket一直阻塞

### ISSUE THREAD

**Issue by carl-don-it** [looly/hutool#862]
### 版本情况

JDK版本：   jre1.8.0_241
hutool版本： 4.5.7

### 问题描述（包括截图）
对方接收到了我发送的信息并且已经写入了数据库，但是我这边还是不断开连接，一直在读数据阻塞，是socket的问题吗？怎么解决？谢谢。

1. 复现代码

```java
            String result = HttpRequest.post(url)
                    .contentType("application/json")
                    .body(log)
                    .execute()
                    .body();
```

2. 堆栈信息
```
"pool-1-thread-19" #11341 prio=5 os_prio=0 tid=0x0000000056e67000 nid=0x18a4 runnable [0x000000005e39e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	- locked <0x00000000eb0e9b60> (a java.io.BufferedInputStream)
	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.readAhead(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
	- locked <0x00000000eb0ecdd8> (a sun.net.www.http.ChunkedInputStream)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:173)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:147)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:134)
	at cn.hutool.http.HttpResponse.readBody(HttpResponse.java:401)
	at cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:428)
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:383)
	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:66)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:882)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:845)
	....//自己代码
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by looly** [comment]
设置下超时，setTimeout。应该是读取服务端返回内容时候，服务端始终不返回（比如未关闭流）导致的。
