### ISSUE TITLE
使用EC算法进行非对称加密报错

### ISSUE THREAD

**Issue by bjpo** [looly/hutool#887]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.5

### 问题描述（包括截图）

1. 复现代码

AsymmetricCrypto asymmetricCrypto = new AsymmetricCrypto(AsymmetricAlgorithm.EC);

2. 堆栈信息
Exception in thread "main" cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: No such algorithm: EC
	at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:987)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.initCipher(AsymmetricCrypto.java:266)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.init(AsymmetricCrypto.java:183)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.init(AsymmetricCrypto.java:31)
	at cn.hutool.crypto.asymmetric.BaseAsymmetric.<init>(BaseAsymmetric.java:54)
	at cn.hutool.crypto.asymmetric.AbstractAsymmetricCrypto.<init>(AbstractAsymmetricCrypto.java:38)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.<init>(AsymmetricCrypto.java:140)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.<init>(AsymmetricCrypto.java:122)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.<init>(AsymmetricCrypto.java:59)
	at com.hytera.hdc.admin.core.utils.TestECC.main(TestECC.java:38)
3. 测试涉及到的文件（注意脱密）
  详见堆栈信息

4.注意
   另外，使用MAVEN引入pom，jar包，bcprov-jdk15on类不加载，使用代码生成
KeyPair pair = SecureUtil.generateKeyPair("EC");可以生成，但是明显不正确，私钥比公钥还短。如果显示的把bcprov-jdk15on的jar包引入进来，则声称的key是正确的。

**Comment by looly** [comment]
EC只支持生成密钥对。不是加密解密算法。

**Comment by looly** [comment]
5.3.6去除。
