### ISSUE TITLE
BigExcelWrite与try-with-resource兼容性不够好

### ISSUE THREAD

**Issue by magical-l** [looly/hutool#920]
### 版本情况

JDK版本： 
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
hutool版本： 5.3.7

### 问题描述（包括截图）

1. 复现代码

```java
final Map<String, ?> map1 = Map.of("id", "123456");
final Map<String, ?> map2 = Map.of("id", "123457");
final List<?> data = Arrays.asList(map1, map2);
final var destFilePath = "";//略
try (final var writer = ExcelUtil.getBigWriter(destFilePath).write(data).flush()) {
}
```

2. 堆栈信息
```
Exception in thread "main" cn.hutool.core.io.IORuntimeException: IOException: Stream closed
	at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:1057)
	at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:1028)
	at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:1014)
	at cn.hutool.poi.excel.BigExcelWriter.close(BigExcelWriter.java:122)
	at trial.poi.HutoolPoiTrial.main(HutoolPoiTrial.java:18)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedWriter.ensureOpen(BufferedWriter.java:107)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:117)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:256)
	at org.apache.poi.xssf.streaming.SheetDataWriter.close(SheetDataWriter.java:128)
	at org.apache.poi.xssf.streaming.SXSSFSheet.getWorksheetXMLInputStream(SXSSFSheet.java:98)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:408)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:959)
	at cn.hutool.poi.excel.ExcelWriter.flush(ExcelWriter.java:1054)
	... 4 more
```

在close()方法中也会调用flush()。所以若先主动调用flush()，然后java的“try-with-resource”自动关闭流时调用close()，close()调用flush()时就会发生此错误。
建议：close()-flush()时判断状态，若已flush，则直接返回。

**Comment by looly** [comment]
5.3.8修复此问题。感谢！
