### ISSUE TITLE
Excel07SaxReader 读取包含公式的Excel异常

### ISSUE THREAD

**Issue by chris-peng** [looly/hutool#931]
### 版本情况

JDK版本：    openjdk_8_241
hutool版本： 5.3.6

### 问题描述（包括截图）

1. 复现代码

2. 堆栈信息
Exception in thread "Thread-15" java.lang.NumberFormatException: For input string: "SUBTOTAL(5,K6:K199975)2"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at cn.hutool.poi.excel.sax.ExcelSaxUtil.getNumberValue(ExcelSaxUtil.java:202)
	at cn.hutool.poi.excel.sax.ExcelSaxUtil.getDataValue(ExcelSaxUtil.java:76)
	at cn.hutool.poi.excel.sax.Excel07SaxReader.endCell(Excel07SaxReader.java:282)
	at cn.hutool.poi.excel.sax.Excel07SaxReader.endElement(Excel07SaxReader.java:182)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at cn.hutool.poi.excel.sax.ExcelSaxUtil.readFrom(ExcelSaxUtil.java:160)
	at cn.hutool.poi.excel.sax.Excel07SaxReader.read(Excel07SaxReader.java:149)
	at cn.hutool.poi.excel.sax.Excel07SaxReader.read(Excel07SaxReader.java:105)
	at cn.hutool.poi.excel.sax.Excel07SaxReader.read(Excel07SaxReader.java:31)
	at cn.hutool.poi.excel.sax.AbstractExcelSaxReader.read(AbstractExcelSaxReader.java:31)
	at com.hpa.dmt.vibranium.bpo.springbatch.reader.common.excel.HutoolExcelStreamer$1.run(HutoolExcelStreamer.java:52)
3. 测试涉及到的文件
[fomula_test.xlsx](https://github.com/looly/hutool/files/4801993/fomula_test.xlsx)

**Comment by looly** [comment]
5.3.9解决此问题，感谢。
