### ISSUE TITLE
在依赖低版本POI(例如我项目里的POI版本为3.9)的项目里出现方法未找到的异常,急需要兼容低版本POI

### ISSUE THREAD

**Issue by Kavin-Cao** [looly/hutool#938]
### 版本情况

JDK版本：    oraclejdk_8_144
hutool版本： 5.3.1 到 5.3.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
由于本项目使用了低版本POI(也不算太低,版本3.9), 使用ExcelUtil.getReader的时候提示方法不存在
1. 复现代码

```java
 List<JSONObject> rows = ExcelUtil.getReader(excel.getInputStream()).readAll(JSONObject.class)
                .stream()
                .map(r -> {
                    r.put(HEADER_SKU_ID, StrUtil.trim(r.getString(HEADER_SKU_ID)));
                    r.put(HEADER_CHANNEL_PRICE, Optional.ofNullable(r.getBigDecimal(HEADER_CHANNEL_PRICE))
                            .orElse(BigDecimal.ZERO).setScale(2,BigDecimal.ROUND_HALF_DOWN));
                    return r;
                })
                .collect(Collectors.toList());
```

2. 堆栈信息
Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.WorkbookFactory.create(Ljava/io/InputStream;Ljava/lang/String;)Lorg/apache/poi/ss/usermodel/Workbook;
	at cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:113)
	at cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:99)
	at cn.hutool.poi.excel.ExcelReader.<init>(ExcelReader.java:92)
	at cn.hutool.poi.excel.ExcelUtil.getReader(ExcelUtil.java:309)
	at cn.hutool.poi.excel.ExcelUtil.getReader(ExcelUtil.java:262)
	at com.dlifva.jdopen.controller.JdGoodsConvertController.batchImportSkus(JdGoodsConvertController.java:244)
	at com.dlifva.jdopen.controller.JdGoodsConvertController$$FastClassBySpringCGLIB$$83a6430c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.dlifva.common.aspect.WebLogAspect.doAround(WebLogAspect.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor$1.proceed(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:82)
	at org.apache.shiro.authz.aop.AuthorizingMethodInterceptor.invoke(AuthorizingMethodInterceptor.java:39)
	at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor.invoke(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.dlifva.jdopen.controller.JdGoodsConvertController$$EnhancerBySpringCGLIB$$227a5ce8.batchImportSkus(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	... 60 common frames omitted
3. 测试涉及到的文件（注意脱密）
任意excel文件
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
不考虑兼容低版本。
