### ISSUE TITLE
StrUtil.format 调用发出 java.lang.ExceptionInInitializerError 错误

### ISSUE THREAD

**Issue by Coneboy-k** [looly/hutool#96]
我是Android发生的这个问题。
我的代码

```
String finalULR = StrUtil.format("{}{}", serverBaseURL, urlTmp);
```
堆栈
```
04-05 02:06:10.469 E/CrashReport(28741): # CRASH STACK:
04-05 02:06:10.469 E/CrashReport(28741): java.lang.ExceptionInInitializerError
04-05 02:06:10.469 E/CrashReport(28741): 	at com.xiaoleilu.hutool.util.StrUtil.utf8Str(StrUtil.java:1278)
04-05 02:06:10.469 E/CrashReport(28741): 	at com.xiaoleilu.hutool.lang.StrFormatter.format(StrFormatter.java:61)
04-05 02:06:10.469 E/CrashReport(28741): 	at com.xiaoleilu.hutool.util.StrUtil.format(StrUtil.java:1181)
04-05 02:06:10.469 E/CrashReport(28741): 	at com.xzutils.anewhttp.XZAbsHTTPRequestBuilder.addRequestURL(XZAbsHTTPRequestBuilder.java:51)
```
偶现出现，但是随机出现的。
我这边查询资料，这边查是因为 在StrUtil.utf8Str 初始化之前被  StrUtil.format 调用了，导致ExceptionInInitializerError 异常。

hutool版本

com.xiaoleilu:hutool-all:3.0.7

**Comment by looly** [comment]
Sorry，Hutool并未在Android平台上测试，可能存在不兼容状况。

还有Hutool最新已经更新至4.0.9，详情访问 hutool.cn
