### ISSUE TITLE
下载附件报错（地址存在空格的情况）

### ISSUE THREAD

**Issue by lucky-CCC** [looly/hutool#971]
### 版本情况

JDK版本：    openjdk_8_21
hutool版本： 5.3.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
String uri = "http://www.xxxxx/x xxx.png";
File file = xxx ;
cn.hutool.http.HttpUtil.downloadFile(uri, file, 1000 * 60 * 5);
```

2. 堆栈信息
```
Exception in thread "main" cn.hutool.http.HttpException: Server response error with status code: [404]
	at cn.hutool.http.HttpUtil.downloadFile(HttpUtil.java:314)
	at cn.hutool.http.HttpUtil.downloadFile(HttpUtil.java:280)
```

3. 原因
```
流程分析：
调用downloadFile之后的代码跟踪如下
-downloadFile:280, HttpUtil
	-downloadFile:312, HttpUtil
		-executeAsync:924, HttpRequest
			-execute:937, HttpRequest
				-initConnection:997, HttpRequest
					-toURL:452, UrlBuilder
						-getPathStr:275, UrlBuilder
							-build:126, UrlPath
结果：
跟踪到最后UrlPath类的第126行的URLUtil.encodeAll方法（底层用java.net.URLEncoder.encode(String,String)）时。
jdk自带的URL编码工具类 URLEncoder 在对字符串进行URI编码的时候，会把空格编码为 + 号。
由于uri中存在空格，最终变成(http://www.xxxxx/x+xxx.png)导致访问404。
```

**Comment by lucky-CCC** [comment]
正确的结果是：http://www.xxxxx/x%20xxx.png

**Comment by looly** [comment]
升级到5.3.9解决了这个问题。

见：https://gitee.com/loolly/hutool/issues/I1NGW4?from=project-issue
