### ISSUE TITLE
国密算法依赖bcprov-jdk15on的1.54版本加密异常问题

### ISSUE THREAD

**Issue by wenit** [looly/hutool#980]
### 版本情况

JDK版本：    1.8.0_191-b12
hutool版本： 5.3.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

在使用国密SM2算法时报错，依赖的bcprov-jdk15on版本为1.54，使用bcprov-jdk15on的1.65版本正常，因项目中已经引用了bcprov-jdk15on的1.54版本，如果改成1.65版本会导致老的功能冲突，请问有什么好的解决办法

1. 复现代码

```xml
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bcprov-jdk15on</artifactId>
	<version>1.54</version>
</dependency>
```

``` java
		String text = "我是一段测试aaaa";

		KeyPair pair = SecureUtil.generateKeyPair("SM2");
		byte[] privateKey = pair.getPrivate().getEncoded();
		byte[] publicKey = pair.getPublic().getEncoded();

		SM2 sm2 = SmUtil.sm2(privateKey, publicKey);
		// 公钥加密，私钥解密
		String encryptStr = sm2.encryptBcd(text, KeyType.PublicKey);
		String decryptStr = StrUtil.utf8Str(sm2.decryptFromBcd(encryptStr, KeyType.PrivateKey));
		
```

2. 堆栈信息

``` java
cn.hutool.crypto.CryptoException: InvalidAlgorithmParameterException: unknown curve name: sm2p256v1
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:501)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:437)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:373)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:357)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:345)
	at cn.hutool.crypto.SecureUtil.generateKeyPair(SecureUtil.java:202)
	at cn.com.yitong.ares.api.utils.sign.SM2SignUtilTest.test(SM2SignUtilTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.security.InvalidAlgorithmParameterException: unknown curve name: sm2p256v1
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.createNamedCurveSpec(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.initializeNamedCurve(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.initialize(Unknown Source)
	at cn.hutool.crypto.KeyUtil.generateKeyPair(KeyUtil.java:496)
	... 29 more

```

3. 测试涉及到的文件（注意脱密）

**Comment by looly** [comment]
这个没办法。Hutool封装是基于最新版本的，旧版少很多算法。

**Comment by Jiiiiiin** [comment]
@looly 使用者本地是否可以将依赖升级到 bcprov-jdk18on ，目前测试编译没有啥问题，针对 和当前文档依赖的版本的区别在于：
![image](https://github.com/dromara/hutool/assets/8840636/f289f8a6-01d5-496c-a490-42c232fd4b03)

**Comment by looly** [comment]
@Jiiiiiin 嗯，亲测可用。实际上已经更新了依赖并做了测试（Hutool是可选依赖，你自己引入jdk18on即可。）

**Comment by agoodcoolman** [comment]
我用的1.65版本  还是有问题。
static {
        Security.addProvider(new BouncyCastleProvider());
    }

在代码中加了这个正常了

**Comment by looly** [comment]
@agoodcoolman 这是全局设定Provider。

不生效的原因可能是你使用中未指定Provider。
