### ISSUE TITLE
升级hutool版本后，因为用了树结构TreeUtil，与dubbo2.7.6冲突，导致项目启动不起来

### ISSUE THREAD

**Issue by guoguo66** [looly/hutool#981]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.9

### 问题描述（包括截图）

1. 复现代码
            List<Tree<String>> treeList = TreeUtil.build(nodeList, "0");

```java
Console.log("报错了");
```

2. 堆栈信息
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logisticsServiceImpl': Injection of @Reference dependencies is failed; nested exception is java.lang.IllegalArgumentException: [ServiceDefinitionBuilder] Map type [cn.hutool.core.lang.tree.Tree<java.lang.String>] with unexpected amount of arguments [[Ljava.lang.reflect.Type;@465a121d].[class java.lang.String]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:146) ~[spring-context-support-1.0.6.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1383) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: [ServiceDefinitionBuilder] Map type [cn.hutool.core.lang.tree.Tree<java.lang.String>] with unexpected amount of arguments [[Ljava.lang.reflect.Type;@465a121d].[class java.lang.String]
	at org.apache.dubbo.metadata.definition.builder.MapTypeBuilder.build(MapTypeBuilder.java:57) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:54) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.builder.CollectionTypeBuilder.build(CollectionTypeBuilder.java:61) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:54) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.builder.DefaultTypeBuilder.build(DefaultTypeBuilder.java:60) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:57) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.TypeDefinitionBuilder.build(TypeDefinitionBuilder.java:83) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.ServiceDefinitionBuilder.build(ServiceDefinitionBuilder.java:77) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.definition.ServiceDefinitionBuilder.build(ServiceDefinitionBuilder.java:44) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.store.InMemoryWritableMetadataService.publishServiceDefinition(InMemoryWritableMetadataService.java:140) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.metadata.store.RemoteWritableMetadataServiceDelegate.publishServiceDefinition(RemoteWritableMetadataServiceDelegate.java:73) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:362) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:258) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.getOrCreateProxy(ReferenceAnnotationBeanPostProcessor.java:274) ~[dubbo-2.7.6.jar:2.7.6]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:143) ~[dubbo-2.7.6.jar:2.7.6]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:359) ~[spring-context-support-1.0.6.jar:na]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:539) ~[spring-context-support-1.0.6.jar:na]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:142) ~[spring-context-support-1.0.6.jar:na]
	... 30 common frames omitted
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
![image](https://user-images.githubusercontent.com/29192570/88353034-9c53a900-cd8e-11ea-90ef-1f77a6be83c4.png)

**Comment by looly** [comment]
看报错信息是Tree类被当作Map类处理了，然后获取泛型参数个数不对导致的问题。

dubbo的源码：https://github.com/apache/dubbo/blob/master/dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/builder/MapTypeBuilder.java

可以看到：
![image](https://user-images.githubusercontent.com/1432613/88356900-fdce4480-cd9b-11ea-9bfd-11ed42b60980.png)


dubbo要求Map的子类泛型参数必须为2个，Tree只有一个，所以报错。


不知道你怎么用的，不过建议不要将Tree对象直接作为rpc参数或者传输用，考虑转为JSON字符串用String吧。

**Comment by JKTerrific** [comment]
可以升级到dubbo-2.7.8
Supporting TypeBuilder sorting
