### ISSUE TITLE
IncompatibleClassChangeError: cn/hutool/json/JSONObject

### ISSUE THREAD

**Issue by jipfqf** [looly/hutool#996]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.3.10

### 问题描述（包括截图）

1. 复现代码
只要是json相关的代码都会出现 Caused by: java.lang.IncompatibleClassChangeError: Implementing class
```
Map<String,String> o=new HashMap<>();
    o.put("A", "1");
    o.put("B", "1");
    o.put("C", "1");
return JSONUtil.toJsonStr(o);

```
2. 堆栈信息
```
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:225)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:196)
	at cn.hutool.json.JSONUtil.toJsonStr(JSONUtil.java:373)
	at cn.px.*.test(*.java:97)

```
我看了下只有基础pom文件里面引入了下面，版本号也是统一配置
```
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>${hutool.version}</version>
</dependency>
```
其它包都好好的，像什么StrUtil,BeanUtil都可以用，就这个json一用就报错，也不知道是为什么

**Comment by jipfqf** [comment]
![image](https://user-images.githubusercontent.com/22951659/89243789-6ab4ca80-d637-11ea-9152-99687948dcde.png)
打包后看到多个hutool包，不知道是为啥

**Comment by looly** [comment]
这个是多版本包引入冲突导致的。

考虑其它库关联依赖了Hutool。
